### ISSUE TITLE
here we go again

### ISSUE THREAD

**Issue by copenhaus** [MicrosoftDocs/OfficeDocs-DeployOffice#100]
here we go again...new software, new methods...who is the genius at MS that decides the old tools is no good any more and needs new instructions for the new stuff....you know what this will cause?  Searching for documentation for the right version...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [Deploy Office 2019 (for IT Pros)](https://docs.microsoft.com/en-us/DeployOffice/office2019/deploy#edit-the-configurationxml)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by deucalion** [comment]
Don't get your hopes up - this bug report will most probably be deleted without further information.

C2R is here to stay without any alternative. What we crave for (a truly customizable installer like we were used to with "setup.exe /admin myconfig.msp") has been purposely ignored... at least that's all I can surmise from the lack of documentation and and transition information (2016 to 2019).

I'd truly appreciate a public statement ("no more customizable installer, live with it") instead of the "use ODT"... because ODT doesn't even remotely cover what you were able to do with the Office Customization Tool / OCT.

**Comment by YanWah2012** [comment]
<Configuration>
<Add OfficeClientEdition="32" >
    <Product ID="VisioPro2019Volume">
      <Language ID="zh-TW" />
      <ExcludeApp ID="OneDrive" />
    </Product>
</Add>
<Display Level="Full" AcceptEULA="TRUE" />
<Updates Enabled="TRUE"  />
</Configuration>


I tried to download the offline files for visio pro 2019, however when install, it gives me error 
"Invalid product VisioPro2019Volume specified. ‬‪Error configuring products!‬"

**Comment by YanWah2012** [comment]
<Configuration>
<Add OfficeClientEdition="32" >
    <Product ID="VisioPro2019Volume">
      <Language ID="zh-TW" />
      <ExcludeApp ID="OneDrive" />
    </Product>
</Add>
<Display Level="Full" AcceptEULA="TRUE" />
<Updates Enabled="TRUE"  />
</Configuration>

here is my XML file

**Comment by YanWah2012** [comment]
Configuration
Add OfficeClientEdition="32" 
    Product ID="VisioPro2019Volume"
      Language ID="zh-TW" /
      ExcludeApp ID="OneDrive" /
    /Product
/Add
Display Level="Full" AcceptEULA="TRUE" /
Updates Enabled="TRUE"  /
/Configuration

(Removed the arrow)

**Comment by DHB-MSFT** [comment]
@YanWah2012 -- I used your xml file and was able to download, install, and open VIsio. When did you get the error message? I briefly saw a notification appear in the bottom right of my screen at the end of the install, but it disappeared before I could look at it more closely. And it was in zh-tw so couldn't immediately tell what it said at a glance.

**Comment by PerkTech** [comment]
I was able to download but not install Visio Pro 19, but it didn't throw an error or anything. Acted normally. Any ideas?

**Comment by msft-bcorob** [comment]
> I'd truly appreciate a public statement ("no more customizable installer, live with it") instead of the "use ODT"... because ODT doesn't even remotely cover what you were able to do with the Office Customization Tool / OCT.

Although some of the methods used for customization differ in C2R, we have worked hard to ensure that the supported deployment scenarios in MSI and the OCT are still possible in C2R using the ODT.

The ODT natively supports customization of products to install, UI level, architecture, and upgrades, and licensing information.  We have also recently added the capability to customize thousands of Office application preferences at deployment time.  You can try this out today at https://config.office.com/

If there is a specific capability that you are looking for in the ODT that is not present or possible today, please do let us know so we can consider improvements in the future.

**Comment by YanWah2012** [comment]
> @YanWah2012 -- I used your xml file and was able to download, install, and open VIsio. When did you get the error message? I briefly saw a notification appear in the bottom right of my screen at the end of the install, but it disappeared before I could look at it more closely. And it was in zh-tw so couldn't immediately tell what it said at a glance.

issue resolved. it should the office CDN temp unavailable

**Comment by DHB-MSFT** [comment]
@YanWah2012 -- glad to hear your issue was resolved.
