### ISSUE TITLE
wheres the opt-out???

### ISSUE THREAD

**Issue by fastrack86** [MicrosoftDocs/OfficeDocs-DeployOffice#1003]
all of this info is great and all but whats the point of it being "optional" without there being any clear indication of how to opt out of these optional privacy controls...otherwise all of your blah blah info is just empty appearances of amelioratory nothingness...and we dont want that do we?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d14345a-d55e-f7ed-4a0a-a8fe97e442ff
* Version Independent ID: 409d6b69-b142-29e8-86cc-0df365e73b30
* Content: [Required diagnostic data for Office - Deploy Office](https://docs.microsoft.com/en-us/DeployOffice/privacy/required-diagnostic-data)
* Content Source: [DeployOffice/privacy/required-diagnostic-data.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/required-diagnostic-data.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Information about diagnostic data controls (on Windows) for organizations can be found here: [Policy setting for diagnostic data](https://learn.microsoft.com/deployoffice/privacy/manage-privacy-controls#policy-setting-for-diagnostic-data). There is similar info for other platforms, such as macOS. See the Table of Contents on the left hand side of the page.
