### ISSUE TITLE
Contradiction assigning device based licenses

### ISSUE THREAD

**Issue by chris2k** [MicrosoftDocs/OfficeDocs-DeployOffice#1004]
[Enter feedback here]

This document indicates that device-based licenses must be assigned to a device's Group, from the Microsoft 365 Admin Center and not from the Azure AD Portal.
However, the option to assign licenses in the Microsoft 365 admin center is just for users, not groups. The Assign Licenses option explicitly says:
"Manage and view licenses and apps for your users. Manage group-based licenses in the Azure portal"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e52eb9c1-1755-bec5-4ad8-6df59779e041
* Version Independent ID: 10e4cf5d-ea61-806e-f226-1e14265eabe1
* Content: [Device-based licensing for Microsoft 365 Apps for enterprise - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/device-based-licensing)
* Content Source: [DeployOffice/device-based-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/device-based-licensing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@chris2k  Thanks for pointing this out. We're checking with the product team that's responsible for that area.

**Comment by MJP-MSFT** [comment]
@chris2k  Thanks for reaching out! Sorry the process is a two step. First you need to create and add devices to an Azure AD group and then sign into the M365 admin center to assign the license to the group. 

Under M365 admin center:
 Licenses node > Find Device license and select > Click on + Assign license > on the fly out search for your group from AAD. 
 
 Please let me know if you have any other questions or concerns.

**Comment by chris2k** [comment]
Hi Matt,

Yes, that’s exactly the point, that’s not correct. Under M365 admin center it is not possible to assign licenses to Groups, just Users:
***@***.***
Regards,
/Christian

**Comment by DHB-MSFT** [comment]
@chris2k Are you selecting "Microsoft 365 Apps for Education (device)" or "Microsoft 365 Apps for enterprise (device)"  [depending on which subscription you have] when you're on the Billing > Licenses > Subscriptions page in the Microsoft 365 admin center?

**Comment by chris2k** [comment]
Daniel,

That’s another issue, that license does not exist in our CSP marketplace, and our distributor (Intcomex) is not aware about a “Microsoft 365 Apps for enterprise (device)”.

It’s a Microsoft 365 E3 which already includes Microsoft 365 Apps.

So I see where the problem is, thank you for the clarification.

Regards,
/Christian

**Comment by 010265mohamadazat** [comment]
@DHB-MSFT

**Comment by 010265mohamadazat** [comment]
السلام عليكم ورحمة الله وبركاته انا جديد في الفريق

**Comment by 010265mohamadazat** [comment]
انا فى الشعبة الأدبية
