### ISSUE TITLE
Not working on Server 2016 for Office 2021

### ISSUE THREAD

**Issue by dark73horse** [MicrosoftDocs/OfficeDocs-DeployOffice#1008]
This is not working for Office 2021 on Server 2016.
Step 3 says....
Run the Office Volume License Pack executable file. Running the executable file will install the Office Volume License Pack on the KMS host computer and then opens the Volume Activation Tools wizard.
The Volume Activation Tools wizard never opens or runs.  How do you enter the KMS key?
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dffd0c18-e6ff-d0df-771d-8082d6473fbe
* Version Independent ID: 3b0adc2b-464e-bf01-9a4f-6098301d57c4
* Content: [Configure a KMS host computer to activate volume licensed versions of Office - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/vlactivation/configure-a-kms-host-computer-for-office#feedback)
* Content Source: [DeployOffice/vlactivation/configure-a-kms-host-computer-for-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/vlactivation/configure-a-kms-host-computer-for-office.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@dark73horse   Not sure what's causing your specific problem. I was able to run the Office LTSC 2021 Volume License Pack on a Windows Server 2016 Standard virtual machine. The Volume Activation Tools wizard started and got me to the screen where I could enter a KMS host key.

Probably best for you to contact Microsoft Support to get assistance with this problem.
