### ISSUE TITLE
Office 2019 and SCCM

### ISSUE THREAD

**Issue by Daxis9** [MicrosoftDocs/OfficeDocs-DeployOffice#101]
We're running SCCM 1806 and [this page](https://docs.microsoft.com/en-us/DeployOffice/office2019/deploy#install-office-2019-by-using-system-center-configuration-manager) says you can deploy Office 2019 through the Office 365 Client Installation wizard. I'm not seeing an Office 2019 option anywhere. I see O365ProPlus and Business but nothing for Office 2019. Is there some prereq I'm missing or is the option actually called O365ProPlus?

**Comment by DHB-MSFT** [comment]
I'm checking with the product team about why the choice isn't showing up. Will get back to you when I find out more. Thanks for the comment/feedback.

**Comment by FreelanceX** [comment]
Any update on this? Would like to start testing deployment. Manually installed it on one client and SCCM doesn't recognise the channel or version.

**Comment by DHB-MSFT** [comment]
Sorry, there was a misunderstanding on my part and Office 2019 isn't currently supported in the Office 365 Client Installation wizard. I'll update the article today. The product team is expecting for that capability to be available before the end of this year. In the meantime, you can manual create the xml file and then create an application and a deployment type to distribute & deploy Office 2019. Sorry for the error.

**Comment by DHB-MSFT** [comment]
The article has been updated. Sorry for the error. Thanks for your comment/feedback.
