### ISSUE TITLE
We can't install Error

### ISSUE THREAD

**Issue by plecomp** [MicrosoftDocs/OfficeDocs-DeployOffice#102]
Fresh install of Windows, no office installed and when I run setup.exe /configure I get the following:

We can't install
The following product(s) can't be installed at the same time:

ProPlus2019Retail

Not having office installed already, not sure how to proceed from this.
![capture](https://user-images.githubusercontent.com/41418738/46054169-b8796580-c178-11e8-87fa-c9b0ba1c91ea.PNG)

**Comment by Simoncusonnet** [comment]
Cannot even download the files 👍 
![image](https://user-images.githubusercontent.com/22100267/46085695-e2498100-c1a6-11e8-8d74-edd1867bcdcc.png)

**Comment by DHB-MSFT** [comment]
@plecomp -- I'm checking with the product team to see if they know why you might be seeing this error. There are no other Office apps on the computer, such as Project or Visio?  Thanks.

**Comment by plecomp** [comment]
@DHB-MSFT Nope. Fresh copy of windows, only office related thing on a fresh install is the get office app which I removed and also ran the office removal tool to see if that alleviated resolved the problem but same error each time unfortunately

**Comment by Simoncusonnet** [comment]
@DHB-MSFT here is my xml: let me know if you see sth wrong, and I did put the whole name.
<Configuration>
  <Add SourcePath="D:\temp\2019" OfficeClientEdition="32" Channel="PerpetualVL2019">
      <Product ID="ProPlus2019Volume"  
         <Language ID="en-us" />
		 <Language ID="fr-fr" />
      </Product>
      <Product ID="ProofingTools">
        <Language ID="de-de" />
        <Language ID="en-us" />
		<Language ID="fr-fr" />
      </Product>
  </Add>
   <Display Level="Full" />  
</Configuration>

I ran from an admin command line: setup.exe /download config.xml

**Comment by plecomp** [comment]
@Simoncusonnet Is that all that is inside your xml? If so, it is incomplete. There is an example over here: https://docs.microsoft.com/en-us/deployoffice/office2019/deploy

Though that does add a lot in that may not be necessary. Simplest xml file I have seen looks like this:

-<Configuration>
<Add Channel="Monthly" OfficeClientEdition="32">
<Product ID="**YOUROFFICEIDHERE**">
<Language ID="en-us"/>
</Product>
</Add>
</Configuration>

You can also use this tool to help create config files: https://officedev.github.io/Office-IT-Pro-Deployment-Scripts/XmlEditor.html

@DHB-MSFT - correct me if I am wrong here.

**Comment by Simoncusonnet** [comment]
As you can see, my xml file i not that different than the exemple of MS on https://docs.microsoft.com/en-us/deployoffice/office2019/deploy#sample-configurationxml-file-to-use-with-the-office-deployment-tool

And Yes, I have office 2016 installed (word/excel/ppt/outlook) but I only want to download the installation files, so that I can put them on a server for company-wide distribution. The same way I did with the old version, and then I created the MSP 
Why did MS change something that was working well with another stuff with problems ?

**Comment by DHB-MSFT** [comment]
@Simoncusonnet -- I think there must be some hidden invalid character in your xml file because I can't open/view your xml in Edge, but all my xml files (including one I created that looked like yours and which did the download just fine) can be viewed in Edge.  And yes, you can just download the files with the Office Deployment Tool and put them on a share. But you'll need to then create xml files that the ODT can use to install from that network share. Hope that helps.

**Comment by DHB-MSFT** [comment]
@plecomp -- The Product ID for Office Professional Plus 2019 (available through volume licensing) is ProPlus2019**Volume**.  Only volume licensed versions of Office 2019 are currently available.

**Comment by Simoncusonnet** [comment]
Hello, thank you all, I finally found out what was wrong in the xml file, I missed one ">" at the end of the product line :-( ans there were also some extra spaces at the end of some lines, now I can open the files in edge ;-) I don't have the error message anymore, and I have a "Data" flder in my 2019 folder, but it's totally empty... I'll let it run a little, and we'll see if something in it ...

**Comment by plecomp** [comment]
@DHB-MSFT Thank you for the info. What I was trying to achieve is installing office to our windows 10 images with the option to try, buy, or activate. Ready for its release. Is Is there a particular way this should be done? As previously I had run a batch file which flagged the first run status for office when the system was put into OOBE.

**Comment by DHB-MSFT** [comment]
For troubleshooting questions, you might consider posting them to the [Answers forum](https://answers.microsoft.com) or the [Tech Community](https://techcommunity.microsoft.com/). Probably more people are on those sites (than reading this article) and you might get a faster response/answer.

**Comment by DHB-MSFT** [comment]
@plecomp -- There might be an OPK (OEM/Office Preinstallation Kit)  available on the [Device Partner Center](https://devicepartner.microsoft.com/en-US/) that might be able to help with your Try/Buy/Activate scenario.

**Comment by pgw3000** [comment]
So blooded helpful!!

Any ideas what the problem is?

<img width="960" alt="CantInstall" src="https://user-images.githubusercontent.com/32594328/59378495-52eff800-8d4c-11e9-87d1-13d1868f679e.png">
