### ISSUE TITLE
M365 Apps are not supported on Windows LTSC

### ISSUE THREAD

**Issue by fabrizob** [MicrosoftDocs/OfficeDocs-DeployOffice#1020]
[According to https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2OqRI, M365 Apps are not supported on Windows 10 LTSC 2019, why in this article instead it's stated that it is supported?]
![image](https://user-images.githubusercontent.com/41018953/137507716-ce33ea27-5456-40c3-aeb9-fb2c0fe76f46.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e52eb9c1-1755-bec5-4ad8-6df59779e041
* Version Independent ID: 10e4cf5d-ea61-806e-f226-1e14265eabe1
* Content: [Device-based licensing for Microsoft 365 Apps for enterprise - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/device-based-licensing)
* Content Source: [DeployOffice/device-based-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/device-based-licensing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by fabrizob** [comment]
![image](https://user-images.githubusercontent.com/41018953/137507966-b688290d-8728-4c02-bc68-969bbc6be3d8.png)

**Comment by DHB-MSFT** [comment]
@fabrizob Thanks for bringing this to our attention. We've removed the reference to Windows 10 LTSC 2019 from the device-based licensing article.
