### ISSUE TITLE
Remove Element

### ISSUE THREAD

**Issue by jonpaulday** [MicrosoftDocs/OfficeDocs-DeployOffice#103]
Can I add the remove element to the setup/ configure xml or does it have to be in a separate xml file? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a0b1ff-0498-505a-6024-b813980d310f
* Version Independent ID: b8057930-b4bd-1304-17ce-5561f837e901
* Content: [Configuration options for the Office Deployment Tool](https://docs.microsoft.com/en-us/deployoffice/configuration-options-for-the-office-2016-deployment-tool)
* Content Source: [DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by jwhit-MSFT** [comment]
We recommend creating a dedicated configuration file for it--details are [here](https://docs.microsoft.com/en-us/deployoffice/overview-of-the-office-2016-deployment-tool#exclude-or-remove-office-365-proplus-products-from-client-computers). Will that work for you?
