### ISSUE TITLE
msupdate no longer uses Apple Events as of version 4.35

### ISSUE THREAD

**Issue by joshlawton** [MicrosoftDocs/OfficeDocs-DeployOffice#1031]
The second paragraph of this page states:

> msupdate works by **sending Apple Events** to the MAU daemon.

As of [Microsoft AutoUpdate 4.35](https://docs.microsoft.com/en-us/officeupdates/release-history-microsoft-autoupdate#may-2021-release), **xpc** is used to control the MAU daemon:

> Command Line Interface (CLI) **now uses native xpc** to communicate with Microsoft Update Assistant **instead of Apple Events**.

Proposed change:

> msupdate works by using native XPC to communicate with the MAU daemon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59e840a0-92ac-3ba4-75b3-01a154d67899
* Version Independent ID: 8f7fd243-8f3a-7d32-8433-03b8167aee6f
* Content: [Update Microsoft applications for Mac by using msupdate - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/mac/update-office-for-mac-using-msupdate)
* Content Source: [DeployOffice/mac/update-office-for-mac-using-msupdate.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/mac/update-office-for-mac-using-msupdate.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @pbowden-msft
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@joshlawton Thanks for pointing that out. We've updated the article based on your suggestion.
