### ISSUE TITLE
Incorrect beginning date?

### ISSUE THREAD

**Issue by feeked** [MicrosoftDocs/OfficeDocs-DeployOffice#1034]
I'm assuming that November 8, 20**22** is a typo, and is supposed to be November 8, 20**21**? Or do I just not understand why the beginning would be after the automatic migration in January 2022?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b877205a-ffdf-2f5e-4f69-73d8088b4f39
* Version Independent ID: b877205a-ffdf-2f5e-4f69-73d8088b4f39
* Content: [Migrate security policies from Security Policy Advisor to the Office cloud policy service - Deploy Office](https://docs.microsoft.com/en-us/DeployOffice/admincenter/migrate-security-policies-from-spa-to-ocps)
* Content Source: [DeployOffice/admincenter/migrate-security-policies-from-spa-to-ocps.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/admincenter/migrate-security-policies-from-spa-to-ocps.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by DHB-MSFT** [comment]
@feeked Thanks for catching that error. We're in the process of fixing it. Article will be updated shortly.

**Comment by DHB-MSFT** [comment]
@feeked  Fixed. Thanks again for letting us know.
