### ISSUE TITLE
Export Inventory

### ISSUE THREAD

**Issue by clissdo** [MicrosoftDocs/OfficeDocs-DeployOffice#1038]
The article suggests that we can export the Inventory from the "Microsoft 365 Apps admin center". I can find a way to filter but not export. Has this feature been removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e28f21c4-9bdb-00cc-f18f-053f89dc4702
* Version Independent ID: 0f9e593e-f4d2-4d3a-6bc3-a436d3f615d2
* Content: [Overview of inventory in the Microsoft 365 Apps admin center - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/admincenter/inventory)
* Content Source: [DeployOffice/admincenter/inventory.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/admincenter/inventory.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DarrenDMSFT
* Microsoft Alias: **darrend**

**Comment by DarrenDMSFT** [comment]
Hi, thanks for your message. I can confirm we have not removed this feature. I'd like to help resolve this for you and as I'll need some details, can you contact me via darren.doyle@microsoft.com and we can investigate.

**Comment by 010265mohamadazat** [comment]
السلام عليكم ورحمة الله وبركاته انا جديد في الفريق
