### ISSUE TITLE
 no Teams Public Preview features in Teams

### ISSUE THREAD

**Issue by mathewlowry** [MicrosoftDocs/OfficeDocs-DeployOffice#1047]
I have followed the instructions  - see screenshot -but they are wrong.

I am the only user of my organisation.
I am in Office Current Channel (Preview) - see screenshot.
I have an update policy of Follow Office Preview (default)  - see screenshot.

But I see no Teams Public Preview features in Teams (eg Loop components).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cd85e3b-e780-457e-9502-856bc6315bca
* Version Independent ID: 416e351f-13c5-e951-ea81-1650910a7c25
* Content: [Overview of update channels for Microsoft 365 Apps - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/overview-update-channels)
* Content Source: [DeployOffice/overview-update-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-update-channels.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown*
![1](https://user-images.githubusercontent.com/19875849/149511872-2abdd2ab-8162-4a99-a229-1590b355aba9.png)
![2](https://user-images.githubusercontent.com/19875849/149511980-8a5c6278-6afb-40e7-9e74-131810bafee3.png)
![3](https://user-images.githubusercontent.com/19875849/149511986-a8985893-2722-4a53-aa89-537968c5baf8.png)
*

**Comment by DHB-MSFT** [comment]
We suggest you leave this comment/question on the [Microsoft Teams Public Preview](https://docs.microsoft.com/MicrosoftTeams/public-preview-doc-updates) article. Scroll to the end of that article to the **Feedback** section and choose **This page** and then enter your comment/question. The writers of that article are more likely to be able to help you. We're not experts on the Teams Public Preview.
