### ISSUE TITLE
Inventory not syncing

### ISSUE THREAD

**Issue by agerm-lb** [MicrosoftDocs/OfficeDocs-DeployOffice#1049]
Hi,

How do I force the inventory to sync with a specific machine? I have a machine reporting X86 office when I know I have updated to X64. The last contact says 12 Jan (it is 17 Jan at the point of writing this comment). Intune shows the device sync'd today (17 Jan) but I am not sure the intune sync and the inventory sync are the same thing.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e28f21c4-9bdb-00cc-f18f-053f89dc4702
* Version Independent ID: 0f9e593e-f4d2-4d3a-6bc3-a436d3f615d2
* Content: [Overview of inventory in the Microsoft 365 Apps admin center - Deploy Office](https://docs.microsoft.com/en-gb/deployoffice/admincenter/inventory)
* Content Source: [DeployOffice/admincenter/inventory.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/admincenter/inventory.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DarrenDMSFT
* Microsoft Alias: **darrend**

**Comment by manoth-msft** [comment]
The sync is triggered in the device itself for each device individually. By default, the inventory checks for changes every 90 minutes. So, make sure that the device is online for this period (e.g. when it is a lab/test device) and open any Office application at least once on the device. This will allow the device to acquire the required tokens and start the sync cycle. Allow the backend a few minutes to process the update. 

So action plan: Boot device, log in, launch any Office app (e.g. Word) once, let machine run, check inventory after 120 minutes. Device should show as online and with latest inventory data.
