### ISSUE TITLE
Enterprise versus Business 

### ISSUE THREAD

**Issue by melissabrownblaeuer** [MicrosoftDocs/OfficeDocs-DeployOffice#1057]
As an Office for Business subscriber, I received an email notification to read this macro security update.  Well into the article, I read the policy settings are only available for Enterprise. Can a link be added to cross-reference the security settings and options for Business subscribers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc5b380c-87db-3823-711d-6c8809392795
* Version Independent ID: cc5b380c-87db-3823-711d-6c8809392795
* Content: [Macros from the internet are blocked by default in Office  - Deploy Office](https://docs.microsoft.com/en-us/DeployOffice/security/internet-macros-blocked)
* Content Source: [DeployOffice/security/internet-macros-blocked.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/internet-macros-blocked.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@melissabrownblaeuer  There are no registry keys available that are equivalent to the policy settings mentioned in the article. A benefit of this upcoming change to the default behavior is that it should help improve security in versions of Office that don't have access to policy settings. For versions of Office without access to policy settings, settings are available in the Office apps under **File** > **Options** > **Trust Center** > **Trust Center Settings...** > **Macro Settings**.

Available choices for **Macro Settings** are listed in the article. Here's a screen shot of that part of the article:

![image](https://user-images.githubusercontent.com/32883970/153680998-0aaa2e6d-e1cd-4028-b146-56cede1b24a8.png)
