### ISSUE TITLE
What about on a Mac?

### ISSUE THREAD

**Issue by linx-collin** [MicrosoftDocs/OfficeDocs-DeployOffice#1058]
Hi,

It would be nice to see some information around how one would check the "Unblock" check box on a Mac since there is no Windows Explorer. To be fare, I've not seen if the Mac "Get Info" dialogue has a similar check box but either way it would be nice if this page mentioned it.

Thanks
Collin

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc5b380c-87db-3823-711d-6c8809392795
* Version Independent ID: cc5b380c-87db-3823-711d-6c8809392795
* Content: [Macros from the internet are blocked by default in Office  - Deploy Office](https://docs.microsoft.com/en-gb/DeployOffice/security/internet-macros-blocked)
* Content Source: [DeployOffice/security/internet-macros-blocked.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/internet-macros-blocked.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by kellieei** [comment]
The default change for blocking macros in files from the internet applies to Office on Windows only. The Mac platform does not support Mark of the Web, and therefore does not have the ability to only block macros from the internet. There are macro security preferences for Office on Mac described in this [article](https://docs.microsoft.com/en-us/deployoffice/mac/set-preference-macro-security-office-for-mac). By default, it is set to “Disable all macros with notification” which allows end users to enable macros in the message bar. To further restrict macros, you can set the preference to “Disable all macros without notification” removing the ability for users to run macros at all.
