### ISSUE TITLE
Broad Channel Setting?

### ISSUE THREAD

**Issue by danbu** [MicrosoftDocs/OfficeDocs-DeployOffice#106]
What channel setting is "Broad"?  The chart shows the "Monthly Channel", "Semi-Annual Channel", and "Semi-Annual Channel (Targeted)".  I assume the "Broad" channel is the "Semi-Annual Channel" but that is not made clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cd85e3b-e780-457e-9502-856bc6315bca
* Version Independent ID: 416e351f-13c5-e951-ea81-1650910a7c25
* Content: [Overview of update channels for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/overview-of-update-channels-for-office-365-proplus)
* Content Source: [DeployOffice/overview-of-update-channels-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-update-channels-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Yes, Broad = Semi-Annual Channel. I'll try to make that clearer. Thanks for your comment/feedback.

**Comment by danbu** [comment]
Thanks

**Comment by michaelblumenthal** [comment]
I have a related Channel question: Does "Targeted" give you early access to the Semi-Annual or Monthly release?  Per https://docs.microsoft.com/en-us/DeployOffice/overview-of-update-channels-for-office-365-proplus, there are Targetted channels for both, not just for Semi-Annual.

**Comment by DHB-MSFT** [comment]
Targeted gives you Semi-Annual Channel (Targeted). To get Monthly Channel (Targeted) you'd use "Insiders" as documented [here](https://support.office.com/article/4dd8ba40-73c0-4468-b778-c7b744d03ead), Hope that helps.

**Comment by DHB-MSFT** [comment]
@danbu and @michaelblumenthal   FYI, I updated several articles to make it clearer that Broad = Semi-Annual Channel and Targeted = Semi-Annual Channel (Targeted).  Appreciate the feedback to help make this content better.
