### ISSUE TITLE
Outlook for macOS "Archive" Button & Folder

### ISSUE THREAD

**Issue by reuven-cohen** [MicrosoftDocs/OfficeDocs-DeployOffice#1060]
How do we disable or redirect the "Archive" button. We have another integrated archive function that is used in outlook, and the built in "Archive" button is a huge issue and creating confusion with the users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee85c2aa-f4df-d3b9-1491-76b662cc748a
* Version Independent ID: eadbcd7e-16f3-0ead-3e6a-530bfd999e1b
* Content: [Set preferences for Outlook for Mac - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/mac/preferences-outlook)
* Content Source: [DeployOffice/mac/preferences-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/mac/preferences-outlook.md)
* Service: **o365-proplus-itpro**
* Sub-service: **office-mac**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@pbowden-msft  Do you know if there is a way to disable or redirect the Archive button?

**Comment by pbowden-msft** [comment]
@DHB-MSFT the presence of the archive button is based on the mailbox settings. If the IT admin disables the archive mailbox through PowerShell, Outlook for Mac will no longer show the archive button. See https://learn.microsoft.com/en-us/microsoft-365/compliance/enable-archive-mailboxes?view=o365-worldwide#disable-archive-mailboxes
