### ISSUE TITLE
Please document how to change the assigned group, from the GUI I cannot find a way.

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/OfficeDocs-DeployOffice#1063]
Please document how to change the assigned group, from the GUI I cannot find a way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa63a94-daaa-9491-213e-f0329f6299b1
* Version Independent ID: 47fe5a3a-ee7c-a7f7-b913-ca0ac3c063e0
* Content: [Overview of the Office cloud policy service for Microsoft 365 Apps for enterprise - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/admincenter/overview-office-cloud-policy-service#requirements-for-using-the-office-cloud-policy-service)
* Content Source: [DeployOffice/admincenter/overview-office-cloud-policy-service.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/admincenter/overview-office-cloud-policy-service.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
Currently there is no way to change the assigned group. A workaround is to specify a group which you use to then nest other groups into it. So e.g. a policy targetes a group called "OCPS Policy XYZ assignments", then add groups with the desired users to this groups (e.g. "IT department", "finance", ...). If you need to change the assignments, just add/remove groups from the "OCPS Policy XYZ assignments" group.
