### ISSUE TITLE
Channel Options

### ISSUE THREAD

**Issue by danbu** [MicrosoftDocs/OfficeDocs-DeployOffice#107]
What are the valid values for the "Channel" Parameter?  The Example shows "PerpetualVL2019" but the link to the Channels shows Targeted and Monthly.  If you have an option the documentation should show what valid parameters for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [Deploy Office 2019 (for IT Pros)](https://docs.microsoft.com/en-us/deployoffice/office2019/deploy)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
In the table about editing the configuration.xml file, there is a row for channel, which links out to this -- [Update channel for Office 2019](https://docs.microsoft.com/en-us/deployoffice/office2019/update#update-channel-for-office-2019). But I do need to also update the main configuration.xml article to mention the perpetual channel. Thanks for the comment/feedback.

**Comment by danbu** [comment]
Great that is clear.
