### ISSUE TITLE
mis-spelt the product name, oops  :)

### ISSUE THREAD

**Issue by DonPick** [MicrosoftDocs/OfficeDocs-DeployOffice#1079]
Hi, mis-spelt "Configuration Manger" in the 'Important Note" just after this anchor https://docs.microsoft.com/en-us/deployoffice/change-update-channels#change-the-update-channel-with-configuration-manager

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d23ac821-9cb8-8855-598f-d1327df04fac
* Version Independent ID: 78f2127a-0c6b-d236-a415-6215c582ce8b
* Content: [Change the Microsoft 365 Apps update channel for devices in your organization - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/change-update-channels?source=docs#change-the-update-channel-with-configuration-manager)
* Content Source: [DeployOffice/change-update-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/change-update-channels.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@DonPick Thanks for pointing that out. It's been fixed. We also checked the rest of our "Deploy Office" content to make sure we didn't have any other instances of "Manger" (we didn't).
