### ISSUE TITLE
Registry path incorrect?

### ISSUE THREAD

**Issue by HarjitSi** [MicrosoftDocs/OfficeDocs-DeployOffice#1080]
When I looked in the registry, there was no such hive as: HKEY_CURRENT_USER\Software\Policies\Microsoft\office\16.0\common\privacy

but there was: HKEY_CURRENT_USER\Software\Microsoft\office\common\clienttelemetry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef4debee-6a1e-53c7-7bec-2dbd208f4f2d
* Version Independent ID: b93ad6a2-0976-6f5f-7aae-1756079bdc1d
* Content: [Use policy settings to manage privacy controls for Microsoft 365 Apps for enterprise - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/privacy/manage-privacy-controls)
* Content Source: [DeployOffice/privacy/manage-privacy-controls.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/manage-privacy-controls.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@HarjitSi  Those registry locations don't appear by default. They only appear if you've configured one of the policy settings.
