### ISSUE TITLE
Printing from word

### ISSUE THREAD

**Issue by ironargonaut** [MicrosoftDocs/OfficeDocs-DeployOffice#1081]
Office refuses to print a word document. Error says I need to enable some service, link to info about services has no information on what service to implement. Rather confused as to why I can't print an emailed word document from MS word on Android phone.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9f215c4-d995-2d6c-0693-bca19f66fe2f
* Version Independent ID: a9aa816b-f30d-3bbe-8fdc-204777b25dfe
* Content: [Connected experiences in Office - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/privacy/connected-experiences)
* Content Source: [DeployOffice/privacy/connected-experiences.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/connected-experiences.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@ironargonaut We suggest you either [contact support](https://support.microsoft.com/contactus) or post your issue on https://answers.microsoft.com/ and someone there might be able to help you.

**Comment by ironargonaut** [comment]
Perhaps, I am wording this wrong. I get error "To enable this experience change your privacy settings" with a link that says "learn more", I click link. Link takes me to article on "Connected experiences in office" which has no mention of printing.  Page contains link to submit feedback for "This page".  So, I click link and am submitting feedback that the page has no "experience" for printing.  Is this not the place to submit feedback on the page? By the way tried the "support" link DHB-MSFT placed got zero relevant hits in search.

**Comment by DHB-MSFT** [comment]
@ironargonaut  We're not sure which connected experience in that article is causing the issue, but the following steps are likely to resolve the issue.  

*(These steps are for Word on a Windows device. If you're on an Android device, to get to your privacy settings, you might need to select your account picture in the upper left corner, and select **Privacy Settings**.)*

1. In Word, go to **File** > **Account**. 
2. Under the **Account Privacy** heading, select **Manage Settings**.
3. In the **Privacy Settings** dialog, scroll down to the **Connected experiences** section. 
4. Make sure all 3 of these check boxes are selected:

- Turn on experiences that analyze your content
- Turn on experiences that download online content
- Turn on all connected experiences

Hope that helps.
