### ISSUE TITLE
Disable Junk Mail Email Delete Confirmation

### ISSUE THREAD

**Issue by davisbr1** [MicrosoftDocs/OfficeDocs-DeployOffice#1084]
When deleting Junk Mail, the message "Are you sure you want to permanently delete the selected message?" pops up and requires confirmation. I'm not sure if a preference even exists to disable this message, but it would be great if there were!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee85c2aa-f4df-d3b9-1491-76b662cc748a
* Version Independent ID: eadbcd7e-16f3-0ead-3e6a-530bfd999e1b
* Content: [Set preferences for Outlook for Mac - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/mac/preferences-outlook)
* Content Source: [DeployOffice/mac/preferences-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/mac/preferences-outlook.md)
* Service: **o365-proplus-itpro**
* Sub-service: **office-mac**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@pbowden-msft  Is there a way to disable this confirmation message?

**Comment by pbowden-msft** [comment]
@DHB-MSFT legacy Outlook had a preference to disable the dialog. However, Phoenix doesn't appear to honor this preference. I've opened bug 7437553
