### ISSUE TITLE
Please clarify what deployment channels this apply to / does not apply to?

### ISSUE THREAD

**Issue by tomrune** [MicrosoftDocs/OfficeDocs-DeployOffice#1085]
I would like to see the article comment on:
* Devices where Office is managed by MEM Configuration Manager. Does MC362760 / this article _not apply_ to customers with Office updates managed that way? The tenant where we got this message does not use ConfigMgr, whereas a tenant we have with MEM did not get the message. Ideally the criteria for getting the message should be explained (same applies to the MC post)

* How a business should deal with devices where Semi-Annual is used should be discussed. The article makes it unclear how or if M365 apps deployed through Company Portal with a specified update channel of semi-annual or custom xml is affected. Are they?

* What happens to Office clients deployed with semi-annual channel deployed after this change takes effect? The MC/article says new Office installations will have Monthly Enterprise, but does that apply to Office installations from office.com or are you retiring custom channel configs? This is not very clear now...

While we generally prefer monthly, we have specific device needs for semi-annual. As long as SAC is an offering, we would like to use it, or get an explanation of what happens to it. I won't argue with Microsofts findings in their research (and generally agree with it), but this was sudden. 

Finally - a day less than a month headsup warning about such a change is unfortunate. This should have a longer action window.

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: 570282bb-a7c8-48c6-36df-c58f960f3739
* Version Independent ID: 570282bb-a7c8-48c6-36df-c58f960f3739
* Content: [Microsoft 365 Apps will be updated to Monthly Enterprise Channel on all your Office devices - Deploy Office](https://docs.microsoft.com/nb-no/DeployOffice/other/devices-updating-monthly-enterprise-channel?source=docs#how-to-opt-out-of-changing-devices-to-monthly-enterprise-channel)
* Content Source: [DeployOffice/other/devices-updating-monthly-enterprise-channel.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/other/devices-updating-monthly-enterprise-channel.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@tomrune Thanks for taking time to provide feedback. We've sent it on to the team implementing this change.

Some info based on your feedback/questions:

- The management tool in use (for example, Configuration Manager or Intune) is not a factor in which tenants received Message Center post MC362760.

- The change applies to new and existing installations, regardless of how Office was or will be installed. For example, any new installs from office.com will get Monthly Enterprise Channel.

- If you still have devices that need to be on Semi-Annual Enterprise Channel, you should opt out. If you do opt out, the team implementing this change would appreciate you leaving feedback on the reasons for your decision. You'll be prompted to provide feedback as part of the opt out process. That team is monitoring the feedback submitted through that process.

We recently updated the article and the Message Center post to make some of this information more clear.
