### ISSUE TITLE
2021 Volume version of Visio has "LTSC" in it's name but Project doesn't have it. 

### ISSUE THREAD

**Issue by WindowsAddict** [MicrosoftDocs/OfficeDocs-DeployOffice#1086]
https://config.office.com/deploymentsettings

On this site, if I select O365 Enterprise + Visio LTSC Pro 2021 (Volume) + Project Pro 2021 (Volume)

LTSC term is not included for Project in the mentioned site and neither when product installation is finished.

So why is it that when Visio and Project both belong to the same license and update channel?

Is there some valid reason or did developers just forget to add LTSC term with Project?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d40c96f3-1c97-b538-ef82-ffbf0eef204d
* Version Independent ID: 2d6883b5-1b5c-dc16-9999-17d0652bfa48
* Content: [Supported scenarios for installing different versions of Office, Project, and Visio on the same computer - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/install-different-office-visio-and-project-versions-on-the-same-computer)
* Content Source: [DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@WindowsAddict   The Project team decided not to use the LTSC naming convention for their 2021 version/release.
