### ISSUE TITLE
Just no

### ISSUE THREAD

**Issue by PJ0222** [MicrosoftDocs/OfficeDocs-DeployOffice#1089]
What gives you the idea that we didn't understand our choices?

NEVER ALTER A CUSTOMER'S CHOICE LIKE THIS!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 570282bb-a7c8-48c6-36df-c58f960f3739
* Version Independent ID: 570282bb-a7c8-48c6-36df-c58f960f3739
* Content: [Microsoft 365 Apps will be updated to Monthly Enterprise Channel on all your Office devices - Deploy Office](https://docs.microsoft.com/en-us/DeployOffice/other/devices-updating-monthly-enterprise-channel)
* Content Source: [DeployOffice/other/devices-updating-monthly-enterprise-channel.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/other/devices-updating-monthly-enterprise-channel.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@PJ0222  We'll pass on your feedback to the team implementing this change. You can also provide feedback when you opt out, as described at the end of the article. That team is monitoring all feedback submitted through that process.
