### ISSUE TITLE
Some Outlook versions are blocked

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/OfficeDocs-DeployOffice#1094]
Modify note accordingly:
https://techcommunity.microsoft.com/t5/microsoft-365-blog/new-minimum-outlook-for-windows-version-requirements-for/ba-p/2684142

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e86f8d4f-3eb1-6763-0f10-a0b637f3035c
* Version Independent ID: a6642647-dc4d-30a9-e962-76f7cd1f5089
* Content: [Office versions and connectivity to Microsoft 365 services - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/endofsupport/microsoft-365-services-connectivity)
* Content Source: [DeployOffice/endofsupport/microsoft-365-services-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/endofsupport/microsoft-365-services-connectivity.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@trudolf-msft We updated that section of the article to just point to the blog post, since the blog post is being updated with the latest information.

**Comment by trudolf-msft** [comment]
See https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/1156
