### ISSUE TITLE
Registry setting

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/OfficeDocs-DeployOffice#11]
For application deployment admins using sccm, it would make more sense to use a registry-based configuration baseline.  You may want to suggest to them that they can use a registry setting to change the update channel and provide the registry setting and values associated with each channel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd18fe4f-5a0e-22cd-61b8-242419c6b18a
* Version Independent ID: d6f7ce9e-09f8-87fb-f05e-07e1a8d0ee01
* [Content](https://docs.microsoft.com/en-us/DeployOffice/overview-of-update-channels-for-office-365-proplus?ui=en-US&rs=en-US&ad=US)
* [Content Source](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-update-channels-for-office-365-proplus.md)
* Service: o365-administration

**Comment by DHB-MSFT** [comment]
Thanks for your feedback. We don't usually recommend editing the registry manually or via scripting, especially in cases where there are other methods that can achieve the same results. In this case, there is a Group Policy setting to do that. If using Group Policy isn't an option, you can run the Office Deployment Tool (with a configuration.xml specifying the new channel) on the user's computer. Also, keep in mind that changing the update channel for a user shouldn't be a common occurrence.
