### ISSUE TITLE
Issue with vNextDiag.ps1 (vNext license query script)

### ISSUE THREAD

**Issue by WindowsAddict** [MicrosoftDocs/OfficeDocs-DeployOffice#1100]
Apparently, it has an error if a lifetime vNext license for Homestudent2021 is found.

It's taken from,
`"C:\Program Files\Microsoft Office\Office16\vNextDiag.ps1"`

![Screenshot 2022-06-16 023201](https://user-images.githubusercontent.com/40813939/173929779-cf38aaa3-4df0-46c9-980f-b0883b8791e1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 89f157e6-7034-f723-1d4c-e49ee521ab0d
* Version Independent ID: 89f157e6-7034-f723-1d4c-e49ee521ab0d
* Content: [Check the license and activation status for Microsoft 365 Apps - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/licensing-activation/vnextdiag)
* Content Source: [DeployOffice/licensing-activation/vnextdiag.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/licensing-activation/vnextdiag.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @nicholasswhite
* Microsoft Alias: **nwhite**

**Comment by WindowsAddict** [comment]
https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/1270 
new raised here

**Comment by DHB-MSFT** [comment]
@MJP-MSFT   Can you check with the product team about this? Even though vnextdiag.ps1 isn't intended to be used with perpetual SKUs, it probably should do a better job of error handling in this case?
