### ISSUE TITLE
You're screwing me over here

### ISSUE THREAD

**Issue by SrDirko** [MicrosoftDocs/OfficeDocs-DeployOffice#1101]
This just affected documents I've been using at my work for over a year with no issue. I have macro-enabled excel documents that I emailed myself over a year ago. I've been using them without issue until this month. They are saved in my OneDrive. I've enabled the macros before. I've tried adding the location as a trusted location with no effect. This is blatantly false:

2. If the file is from a Trusted Location, the file is opened with the macros enabled. If the file isn't from a Trusted Location, the evaluation continues.

6. If the user had previously opened the file, before this change in default behavior, and had selected Enable content from the Trust Bar, then the macros are enabled because the file is considered trusted.

I tried following the Learn More button in the notification. [These instructions](https://support.microsoft.com/en-us/topic/a-potentially-dangerous-macro-has-been-blocked-0952faa0-37e7-4316-b61d-5b5ed6024216) are also useless:

If you’re sure the file is safe and want to unblock macros

1. Save the file to a local hard drive, network share, or cloud share like OneDrive.
2. Open Windows File Explorer and go to the folder where you saved the file.
3.  Right-click the file and choose Properties from the context menu.
4. At the bottom of the General tab select the Unblock checkbox and select OK.

There is no Unblock checkbox on my file. 

So now the only way I can use my own macro-enabled file is to enable macros for all files. This change has only made things less secure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc5b380c-87db-3823-711d-6c8809392795
* Version Independent ID: cc5b380c-87db-3823-711d-6c8809392795
* Content: [Macros from the internet are blocked by default in Office  - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/security/internet-macros-blocked?source=docs)
* Content Source: [DeployOffice/security/internet-macros-blocked.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/internet-macros-blocked.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by SrDirko** [comment]
Update. Even worse. Even if I check the radio button in Macro Settings, "Enable VBA macros (not recommended; potentially dangerous code can run), I get the same behavior. You've essentially killed my macros. Thanks.

**Comment by DHB-MSFT** [comment]
@SrDirko  We recommend that you contact [Microsoft Support](https://support.microsoft.com/contactus) to help you with your issue. Support is in regular contact with the product team responsible for this change. And both Support and the product team will let us know if there is additional information that needs to be included in the documentation, based on issues that customers are encountering.
