### ISSUE TITLE
"As part of the installation process" doesn't quite make sense without additional context

### ISSUE THREAD

**Issue by TiJohn0108** [MicrosoftDocs/OfficeDocs-DeployOffice#1103]
Unless you choose to add some context or clarity, "As part of the installation process" in the sentence below doesn't make sense at least when you are installing using the Office Deployment Tool (ODT) as I wouldn't expect to have any user information at that point during an install through ODT. It might be cleaner to drop "As part of the installation process" at this point. Perhaps if installing from the Office Portal, perhaps it might apply then, but haven't tested it. 

Currently:
"As part of the installation process, Microsoft 365 Apps communicates with the Office Licensing Service and the Activation and Validation Service to obtain and activate a product key. " 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3c236da-c63a-f789-f1b6-7aeb41f16c1f
* Version Independent ID: 35319bac-d94f-832c-ce79-41bffe5c8d25
* Content: [Overview of licensing and activation in Microsoft 365 Apps - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/overview-licensing-activation-microsoft-365-apps#activating-office-365-proplus)
* Content Source: [DeployOffice/overview-licensing-activation-microsoft-365-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-licensing-activation-microsoft-365-apps.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @MJP-MSFT
* Microsoft Alias: **mattphil**

**Comment by DHB-MSFT** [comment]
@TiJohn0108   Thanks for the feedback. Initial impression is that we can just get rid of that phrase, but will look more closely.
