### ISSUE TITLE
Group Policy path for setting Microsoft Office preview channel is different from shown on Windows Build 25145

### ISSUE THREAD

**Issue by dutch55** [MicrosoftDocs/OfficeDocs-DeployOffice#1105]
The path in the instructions to you Group Policy editor doesn't seem to work for the Windows 11 Dev Channel.
The instructions show: 
Computer Configuration\Policies\Administrative Templates\Microsoft Office 2016 (Machine)\Updates

But on Build 25145 under Computer Configuration there is no Policies entry. The tp ones are Software Settings, Windows Settings, and Administrative Settings. Under All settings, there are entries for Office 2016, but none for (Machine).

FYI, I download the Preview channel Office 365 using the .xml file method, but it reverts to standard Channel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e89daf60-7ec1-5ca4-5969-8050cdc42d72
* Version Independent ID: e89daf60-7ec1-5ca4-5969-8050cdc42d72
* Content: [Use Group Policy to install Office Insider on Windows devices - Office Insider](https://docs.microsoft.com/en-us/deployoffice/office-insider/deploy/group-policy)
* Content Source: [DeployOffice/office-insider/deploy/group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office-insider/deploy/group-policy.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@dutch55   Have you downloaded the Office policy files from https://www.microsoft.com/en-us/download/details.aspx?id=49030? 

The **Policies** node shows up if you're using the Group Policy Management ***Console***, which is a Windows Server admin tool. If you're just using the Group Policy ***Editor***, which comes on Windows client, then you won't see the **Policies** node.

In either tool, with the Office policy files installed, you should see an entry for **Microsoft Office 2016 (Machine)** under **Administrative Templates**, similar to this screenshot.
![gpeditor_machine_node](https://user-images.githubusercontent.com/32883970/175988130-154a950c-bc8e-42e5-bb8e-a5ef28d12dc1.png)

**Comment by dutch55** [comment]
Thanks for answering. I am not a Windows systems admin, and I just manage my own two desktops, and I wasn't paying attention to the distinction. I modified the registry using the other method described on that page.  Since the screen layout on my Windows desktop looks like the desktop MMC that's been around forever, I didn't appreciate there was a difference.
