### ISSUE TITLE
Langauge support for en-gb for Visio and Project 2021

### ISSUE THREAD

**Issue by Marilena-Neaga** [MicrosoftDocs/OfficeDocs-DeployOffice#1108]
Hello team,

During testing we noticed that Visio and Project 2021 can't be installed in the newly added languages (en-gb, fr-ca, es-mx).  I wanted to suggest if it would be possible to mention that in the article. A customer pointed out that from the documentation, they understand that both Visio and Project 2021 are supporting the languages, so a statement would bring more clarity. 

Thank you! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8f67f86-10d5-8dd2-3d29-c2112522b11b
* Version Independent ID: 14036bbd-22f5-6528-97c9-00c5d0f2fe9f
* Content: [Overview of Office LTSC 2021 - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/ltsc2021/overview)
* Content Source: [DeployOffice/ltsc2021/overview.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/ltsc2021/overview.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@Marilena-Neaga   Thanks for bringing this to our attention. We're following up with the Languages team to confirm this is expected. If it is, we'll update the article to clarify the matter.

**Comment by DHB-MSFT** [comment]
@Marilena-Neaga   The Languages team has confirmed that those 3 languages aren't available for Project & Visio 2021. We've updated the "Language support" section of the article to clarify that. Thanks again for bringing that to our attention.
