### ISSUE TITLE
Reactivate office on every single computer??? You gotta be kidding me

### ISSUE THREAD

**Issue by zignzag12** [MicrosoftDocs/OfficeDocs-DeployOffice#111]
Just tested installing 16.17 update and it's prompting to reactivate?

**Comment by pbowden-msft** [comment]
Hi there,

16.17 is the first build of the '2019 generation' client which uses a different activation scheme from the '2016 generation'.

Based on your symptoms, it sounds like you're using a 2016 perpetual license (e.g. Volume License), in which case you need to stick to the 16.16.x series of builds (the latest of which is 16.16.2). You can check https://macadmins.software for the list of packages.

Builds 16.17 and later can only be used with Office 365 and 2019 license types.

Hope this helps.

Paul.
