### ISSUE TITLE
ODT can no longer deploy Office 2019 - .cab files unavailable

### ISSUE THREAD

**Issue by SBMcath** [MicrosoftDocs/OfficeDocs-DeployOffice#1111]
Hi folks,

As of July 2022 these instructions fail with **error code 30125-39 (400)** when the ODT tries to retrieve the first files for Office Professional Plus 2019. The exact file it fails to retrieve is **http://officecdn.microsoft.com/pr/f2e724c1-748f-4b47-8fb8-8e0d210e9208/Office/Data/16.0.10387.20023/s642057.cab**
or for 32bit installs: **http://officecdn.microsoft.com.edgesuite.net/db/f2e724c1-748f-4b47-8fb8-8e0d210e9208/Office/Data/16.0.10387.20023/s322057.cab** but I presume more will fail once it gets past that one.

I know this isn't the right place to report technical faults but I've spent 2 weeks trying to communicate this issue with microsoft support and all I have to show for it is a lot of frustration..

**If you browse to the above urls or try the deploy process yourself you should be able to replicate the issue and see these instructions do not currently work** (they did a few months ago, and they do if you load a config xml for o365 instead). Maybe whoever reads this can navigate the microsoft support system better than me and get that resolved. Otherwise just delete this feedback as me whining and we'll leave it broken.

Have a nice day.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [Deploy Office 2019 (for IT Pros) - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/office2019/deploy)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@SBMcath   We'll pass this on to some other teams to see if they know what might be going on. We just did a quick test and were able to install Office Professional Plus 2019 (16.0.10387.20023) without getting an error.

**Comment by SBMcath** [comment]
@DHB-MSFT Thank you **very much** for your time checking that. Twenty minutes after reading that I was able to successfully deploy Office 2019 using the sample xml in the documentation.

For posterity, the ultimate cause was that I was using config.office.com to generate xmls and **setting the primary language to English (United Kingdom)** in all of my config files. I can replicate this by changing the sample xml  line `Language ID="en-us"` to `Language ID="en-gb"` which allows me to download but not install office. I'm going to assume this is actually just an invalid configuration option and not actually a missing file so **I don't believe any further investigation is required.**

It's also a moot point because en-us lets me use English (Australia) as proofing language which is my only requirement, so I can now push this out to the laptops that have been waiting for the past fortnight.

My sincerest thanks for taking the time to check this and getting back to me. All of my attempts on different networks, devices, tethered through my phone, on my home PC and even sending to former colleagues at different businesses had all been hitting the same wall as I was always changing the primary language in the xml file. Your response confirmed it had to be between the keyboard and the chair which led to the solution in under an hour.

Thanks again and have a lovely day

**Comment by DHB-MSFT** [comment]
@SBMcath  We're glad to hear you were able to figure out the issue. Just as an FYI, en-gb is not a supported language for Office 2019. It's available for Office LTSC 2021 and Microsoft 365 Apps, starting with Version 2108. However, en-gb isn't available for any version of Project and Visio.
