### ISSUE TITLE
Japanese translation typo.

### ISSUE THREAD

**Issue by okumura-pico** [MicrosoftDocs/OfficeDocs-DeployOffice#1115]
[Enter feedback here]

At the first sentence, "shared computer activation" translated to "強要コンピューターのライセンス認証".
It should be "共有コンピューターのライセンス認証".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6da18a8b-9e96-0155-7b30-9c211070d793
* Version Independent ID: 5a7e610a-bfcb-d9cc-03f7-589d970128d9
* Content: [Deploy Microsoft 365 Apps by using Remote Desktop Services - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/deploy-microsoft-365-apps-remote-desktop-services)
* Content Source: [DeployOffice/deploy-microsoft-365-apps-remote-desktop-services.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-microsoft-365-apps-remote-desktop-services.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@okumura-pico  Thank you for bringing this to our attention. We've sent your feedback to our Localization team to review and take action as needed.

**Comment by DHB-MSFT** [comment]
@okumura-pico   Our Localization team has fixed this issue and the article has been updated. Thanks again for bringing this issue to our attention.
