### ISSUE TITLE
Wrong Registry Key Location

### ISSUE THREAD

**Issue by OfficeCloudKey** [MicrosoftDocs/OfficeDocs-DeployOffice#1116]
We are migrating away from SCCM and will be using Office to auto update itself.  
Some of our machines still say "managed by your system administrator" and when I investigated these devices, I found this registry key:

hkey_local_machine\software\wow6432node\Policies\Microsoft\cloud\office\16.0\common\officeupdates

The devices having issues have this key location, and the ones that don't do not.  I can't find any documentation on why this key exists under the "cloud\office\" location as microsofts documentation doesn't even outline this.  Under this location, the registry key "OfficeMgmtCOM" is set to 1, and if I set it to 0 everything works great.  However, this eventually updates itself back to 1.

SCCM has Office 365 workloads transferred to Intune, and Client Settings are set to "disabled" for Office management for SCCM.

The machines that are working have their keys located here:
hkey_local_machine\software\policies\microsoft\office\16.0\common\officeupdates
And officemgmtCOM is set to 0 here, which is great.

Why are keys being created on some devices under the "cloud" location?

I logged into config.office.com and there are no policies created here, aside from a servicing profile that justs adds devices to receive updates.

**Comment by DHB-MSFT** [comment]
@manoth-msft   Is this something you can help with?  Thanks.

**Comment by manoth-msft** [comment]
The key you mentioned is created by the Servicing Profile. So, for devices which are in-scope for the Profile (listed on the devices tab at https://config.office.com/officeSettings/serviceprofile), this is expected. Also, the message "managed by your admin" is expected for these devices, as not the user, but the admin is in control of updates. 

We have a deep-dive video on Servicing Profiles and what happens on an in-scope device here: https://youtu.be/YO6a3iNVXXI

**Comment by manoth-msft** [comment]
You have basically two options now:

- Increase the coverage of Servicing Profile to all devices (go with 'all devices' and all update channel checkboxes ticked). Those device will auto-update from the OfficeCDN and you have increased control and reporting. It automatically overrules the SCCM settings (for Office updates only!), so there nothing else to configure. I would recommend this approach.
- If you want to go "auto-update" without management, enforcement and reporting, add an empty AzureAD group to the Servicing Profile and it will release the control of all devices within a few hours.

Benefits of using Profiles: https://docs.microsoft.com/en-us/deployoffice/fieldnotes/adopt-servicing-profiles#benefits-of-using-a-servicing-profile
