### ISSUE TITLE
Servicing Profile: Office 365 won't update

### ISSUE THREAD

**Issue by OfficeCloudKey** [MicrosoftDocs/OfficeDocs-DeployOffice#1118]
I have had this ticket in with Microsoft for a full week and have not heard back.  I am hoping this can get looked at as we would like to eventually roll this out everywhere.  Are there any logs I can look at? Is there anyone that can assist?

I have 15 devices enrolled in servicing profile for the past 3 weeks.  Of the 15 devices, 7 of them have completed their updates and the remaining 8 are stuck at "Not started".  We have a 1 day deadline for updates and have selected not to use waves for rollouts.

3 of these 7 devices have moved to "In progress" and within 1-3 days will revert back to "Not started".  

I have seen these same 3 devices show up with "Failure" once in awhile too that usually lasts about an hour on the dashboard before disappearing and reverting back to "not started".  Usually the failure will NOT show any error code under issues.  However the one this morning shows this error code:

Error 30088, unknown click to run issue under "Download" deployment stage"

This was a machine that just booted up this morning.

Why did only half the machines update and the remaining half seem to be having problems? Makes me nervous wanting to roll this out to the company.

**Comment by DHB-MSFT** [comment]
@manoth-msft  Any thoughts on what might be happening here?  Thanks.

**Comment by manoth-msft** [comment]
@OfficeCloudKey Can you share more details regarding the "ticket with Microsoft"? Have you submitted feedback through the feedback button in the APps Admin Center, or do you have a RAVE case open with support?

Github is not the intended/best way for troubleshooting support, so I'm happy to work off a feedback item or rave case.

**Comment by OfficeCloudKey** [comment]
@manoth-msft My apologies, yes I did submit feedback through the feedback button on the Apps Admin Center.  I  received a response that day that they received my feedback and would look into it, and that was the first and only response I've received.

The feedback does not have a ticket # so I don't have any details to provide for you to look it up.

when I look at the servicing profile this morning, I see that there are #'s under "projected waves" but clicking on the "Devices" button shows nothing there.  I'm guessing it's probably loading up for the next update of 365 as today is release build 2206.

Do you have an email I can reach out to and we can troubleshoot further off the feedback item?

**Comment by OfficeCloudKey** [comment]
@manoth-msft We are still experiencing this issue.  Half the devices have still not updated, or 1 or 2 devices will show "failure" upon booting up at the "download" stage.  Have yet to hear anything back from Microsoft from my feedback case submitted last Monday.

**Comment by OfficeCloudKey** [comment]
@manoth-msft Updating that this issue is still present monday morning.  Channel 2205 build 20370 is still flipping between "In progress" to "not started" on devices.  Issue has been present for several weeks.  I followed up on my feedback ticket and still no response from anyone.

**Comment by manoth-msft** [comment]
I've nudged engineering to respond to your feedback item. This GitHub repo is focused on the maintenance of the documentation, not troubleshooting cases. Can we please continue the conversation on TechCommunity (there is a thread regarding your issue already,

**Comment by OfficeCloudKey** [comment]
@manoth-msft Thank you, I appreciate the nudge.  Hoping I'll hear from someone soon.  I will shift and update that thread on TechCommunity shortly.

**Comment by DHB-MSFT** [comment]
@manoth-msft   Thanks for your assistance. 

Closing this as further discussion will take place in TechCommunity.
