### ISSUE TITLE
No troubleshooting information

### ISSUE THREAD

**Issue by spalmstr** [MicrosoftDocs/OfficeDocs-DeployOffice#112]
We tried installing Office Standard 2019 volume licensed using an updated configuration file.  It ran for a short time but gave no error message.  We did not have a SourcePath as we wanted to get the software from the CDN. This article doesn't point to any troubleshooting or diagnostic guides.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [Deploy Office 2019 (for IT Pros)](https://docs.microsoft.com/en-gb/DeployOffice/office2019/deploy)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by PerkTech** [comment]
I have been trying to install Visio Pro 2019. Instead I keep getting Project 2019. Thoughts?

**Comment by DHB-MSFT** [comment]
First step would be to double-check that the Product ID in your xml is either VisioPro2019Volume or VisioStd2019Volume, depending on what you're licensed for.

**Comment by PerkTech** [comment]
<Product ID="VisioPro2019Volume"

**Comment by crazychef** [comment]
I have the same problem like #spalmstr
ODT is downloading, fine
ODT configure is running for ~1sec and just stops
This is my *.xml

<Configuration>
  <Add OfficeClientEdition="64" Channel="PerpetualVL2019">
    <Product ID="Standard2019Volume" PIDKEY="XXXXX-XXXXX-XXXXX-XXXXX-XXXXX">
      <Language ID="de-de" />
    </Product>
    <Product ID="ProofingTools">
      <Language ID="de-de" />
    </Product>
  </Add>
  <RemoveMSI All="True" />
  <Display Level="None" AcceptEULA="TRUE" />
  <Property Name="AUTOACTIVATE" Value="1" />
</Configuration>

**Comment by crazychef** [comment]
<Configuration>
  <Add OfficeClientEdition="64" Channel="PerpetualVL2019">
    <Product ID="Standard2019Volume" PIDKEY="XXXXX-XXXXX-XXXXX-XXXXX-XXXXX">
      <Language ID="de-de" />
    </Product>
    <Product ID="ProofingTools">
      <Language ID="de-de" />
    </Product>
  </Add>
  <RemoveMSI All="True" />
  <Display Level="None" AcceptEULA="TRUE" />
  <Property Name="AUTOACTIVATE" Value="1" />
</Configuration>

**Comment by DHB-MSFT** [comment]
@spalmstr -- hmm...hard to diagnose without an error message. Might have been a temporary connectivity issue with the Office Content Delivery Network (CDN). Have you re-tried installing?  Often setup will provide an error dialog with an error code and link to more info. Here's a list of some of those errors and links to associated content -- [Error messages when installing Office](https://support.office.com/article/35ff2def-e0b2-4dac-9784-4cf212c1f6c2#bkmk_buserrormessages). Hope that helps.

**Comment by DHB-MSFT** [comment]
@PerkTech -- I used this simple xml file and got Visio installed.

<Configuration>
  <Add OfficeClientEdition="32" Channel="PerpetualVL2019">
    <Product ID="VisioPro2019Volume">
      <Language ID="en-us" />
    </Product>
  </Add>
</Configuration>

**Comment by PerkTech** [comment]
Yeah I have tried and every time I try I get Project instead and I get no errors. I think I know what to do, but I kind of moved on and installed the 2016 version because I needed to accomplish another task.

I think the issue was I did accidentally, copy the wrong thing the first time and I got Project. But fixing the config and blowing away the downloaded directory didn't fix the issue. I need to uninstall it all and then blow it away and then try again. If that doesn't work, I will have to try the remove MSI command, which I do not want to do because I do not want to uninstall the old Office just for this one new product. But if that doesn't work, then I may have found a bug.

**Comment by spalmstr** [comment]
@DHB-MSFT There were no error messages, but then the display level was None.  Setting it to Full showed what was going on, for example that something needed to be removed first.

**Comment by crazychef** [comment]
Solved.
It didn't download the full package, even if I tried it multiple time, was always ~2gig
On a "clean" internet connection it downloaded ~5gig, then installation worked

**Comment by DHB-MSFT** [comment]
@spalmstr  and @crazychef  -- glad things got worked out for you.
