### ISSUE TITLE
Does the Remove Element Still work with the latest ODT?

### ISSUE THREAD

**Issue by klwzo** [MicrosoftDocs/OfficeDocs-DeployOffice#1120]
My xml file for uninstalling 365 apps quit working with the latest ODT, and have tried many different versions. All works with an old copy of ODT, is this a bug, is there new syntax,  or has this feature been removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a0b1ff-0498-505a-6024-b813980d310f
* Version Independent ID: b8057930-b4bd-1304-17ce-5561f837e901
* Content: [Configuration options for the Office Deployment Tool - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/office-deployment-tool-configuration-options#remove-element)
* Content Source: [DeployOffice/office-deployment-tool-configuration-options.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office-deployment-tool-configuration-options.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@klwzo  The ODT team is aware of this issue in the July 12 version of the ODT. They are working on a fix. Once fixed, a new version of the ODT will be posted to the Download Center.

For now, if you need the "remove" functionality, you can use an earlier version of the ODT.

**Comment by DHB-MSFT** [comment]
@klwzo  An updated version of the Office Deployment Tool was released this afternoon (Tuesday 16 August 2022, PDT). This version should fix the issue with using the "remove" functionality. 

You can download the updated ODT from here: [https://www.microsoft.com/download/details.aspx?id=49117](https://www.microsoft.com/download/details.aspx?id=49117)

It's Version 16.0.15427.20220 (setup.exe version 16.0.15427.20220).

Hope that helps.

**Comment by klwzo** [comment]
All is working now, thanks!
