### ISSUE TITLE
Rollout for Semi-Annual Enterprise Channel

### ISSUE THREAD

**Issue by PPMS-QA** [MicrosoftDocs/OfficeDocs-DeployOffice#1121]
Just wondering why the rollout date for the macro blocking update in the Semi-Annual Enterprise Channel is now "To be determined" and if it's possible to get an estimated rollout date. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc5b380c-87db-3823-711d-6c8809392795
* Version Independent ID: cc5b380c-87db-3823-711d-6c8809392795
* Content: [Macros from the internet are blocked by default in Office  - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/security/internet-macros-blocked)
* Content Source: [DeployOffice/security/internet-macros-blocked.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/internet-macros-blocked.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@PPMS-QA   We won't know a more definite date for Semi-Annual Enterprise Channel until the update is available in Semi-Annual Enterprise Channel *_(Preview)_*. But the update probably won't be available in Semi-Annual Enterprise Channel until January 2023, which is the next scheduled version update for that channel. 

As soon as we have more information, we'll update the table in the article. Until then the table will remain as "to be determined" and any suggested dates (like the one above) are "unofficial" and are subject to change. Hope that helps.
