### ISSUE TITLE
Help clarify policy

### ISSUE THREAD

**Issue by FullStackEngN** [MicrosoftDocs/OfficeDocs-DeployOffice#1122]
From the chart flow, could you help confirm following questions?
1) Clarify which policy is in used in step 4a/4b?

I'm asking because there are two policies regarding Excel application here, which one should be used in step 4a/4b? Thanks.
a. "Block macros from running in Office files from the Internet policy"
b. "VBA Macro notification settings".

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc5b380c-87db-3823-711d-6c8809392795
* Version Independent ID: cc5b380c-87db-3823-711d-6c8809392795
* Content: [Macros from the internet are blocked by default in Office  - Deploy Office](https://docs.microsoft.com/en-gb/DeployOffice/security/internet-macros-blocked#vba-macro-notification-settings)
* Content Source: [DeployOffice/security/internet-macros-blocked.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/internet-macros-blocked.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
It checks for both policies, as both influence the outcome of this check.
