### ISSUE TITLE
Thank you for providing both "Go Beta" and "Roll back to Current" with one easy registry script to paste

### ISSUE THREAD

**Issue by Mardurolla** [MicrosoftDocs/OfficeDocs-DeployOffice#1123]
[Enter feedback here]
Thank you for this quick and easy solution. I've been an admin for decades and never knew why solutions were not provided with a quick cmd Registry hack. Instead, the go-to has always been the "Advance" Tab then "Options" button, do you really want to do this, only to find that, after clicking [Yes] the "Operation Failed" where the only option is to click the [OK] button. So thank you for providing a script for going Beta AND for rolling back to Current, without any patronizing or endless clicking steps. I hope this helps you for continuing this type of good work. You just saved me days and a lot of frustration.   

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3437d6c-4600-9ba3-4214-37d45f304e4c
* Version Independent ID: f3437d6c-4600-9ba3-4214-37d45f304e4c
* Content: [Use a registry command to install Office Insider on Windows devices - Office Insider](https://docs.microsoft.com/en-gb/DeployOffice/office-insider/deploy/registry)
* Content Source: [DeployOffice/office-insider/deploy/registry.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office-insider/deploy/registry.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@Mardurolla   Thanks for taking time to provide this feedback about our documentation. We're glad the article helped you.
