### ISSUE TITLE
Release frequency1 for Semi-Annual Enterprise Channel should be 'second Tuesday of the month in January and July'?

### ISSUE THREAD

**Issue by jrdtechnologies** [MicrosoftDocs/OfficeDocs-DeployOffice#1124]
Table : "Comparison of the update channels for Microsoft 365 Apps" 
Column : "Semi-Annual Enterprise Channel" 
Row Header: Release frequency1
The  "Once a month, on the second Tuesday of the month" is not correct?
Shouldn't the Release frequency1 be "Released on the second Tuesday of the month in January and July."
or is Row Header: Release frequency1 for Security Updates?

Thanks 
Jason

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cd85e3b-e780-457e-9502-856bc6315bca
* Version Independent ID: 416e351f-13c5-e951-ea81-1650910a7c25
* Content: [Overview of update channels for Microsoft 365 Apps - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/overview-update-channels#feedback)
* Content Source: [DeployOffice/overview-update-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-update-channels.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
The Semi-Annual Enterprise Channel receives monthly security updates. That's why the statement in the table is correct, there is a new release every month (even so it does not include feature updates every month). But there is a release you should deploy to your devices on a monthly base to keep them secure.
