### ISSUE TITLE
Clear statement regarding Mac support of M365 Apps Device licenses

### ISSUE THREAD

**Issue by mcnaugha** [MicrosoftDocs/OfficeDocs-DeployOffice#1125]
Could you please add a note to this page to advise on whether or not the Mac version of M365 Apps supports device licenses? It is not addressed at all.

I have assigned M365 Apps device licenses to our Macs but it looks like they don't support it.

Is support coming for this? It's a real problem for us because we work with multiple tenants and I can't separate my Mac users from the Windows users and do not want to see Windows clients preference user licensing over the device licensing I have provided.

We are a large Education environment with a few hundred Macs but 25,000 Windows clients.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c517dca4-9d87-72b1-9789-68fbcd1e56af
* Version Independent ID: 0535d6c1-d5eb-7b30-73f9-c12a45f7049f
* Content: [Overview of activation for Office for Mac - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/mac/overview-of-activation-for-office-for-mac)
* Content Source: [DeployOffice/mac/overview-of-activation-for-office-for-mac.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/mac/overview-of-activation-for-office-for-mac.md)
* Service: **o365-proplus-itpro**
* Sub-service: **office-mac**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@pbowden-msft   Can you answer this question?  Thanks.

**Comment by pbowden-msft** [comment]
@mcnaugha Unfortunately, Office for Mac doesn't support device-based licenses. It is something that we've looked at, but there are some large technical challenges. While I understand it's not ideal, the current recommendation would be to use the Office 2021 VL Serializer to activate shared Macs.
