### ISSUE TITLE
Servicing profiles stop GPOs / Intune

### ISSUE THREAD

**Issue by AndytheIT** [MicrosoftDocs/OfficeDocs-DeployOffice#1127]
Hi does setting up Servicing profiles stop other office GPOs / Intune polices applying or is it controlling the updating of Office?

Thanks

Andy

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89082997-601e-1b5b-ffa5-9316bef898e8
* Version Independent ID: 7b50b5b7-2e0c-15e7-b64a-1492697c997c
* Content: [Overview of servicing profile in the Microsoft 365 Apps admin center - Deploy Office](https://docs.microsoft.com/en-gb/DeployOffice/admincenter/servicing-profile)
* Content Source: [DeployOffice/admincenter/servicing-profile.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/admincenter/servicing-profile.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @dhirendra-bhupati
* Microsoft Alias: **dhirenb**

**Comment by manoth-msft** [comment]
(Might be a duplicate): Servicing Profile will overrule only GPO/Intune policies which are relevant for the Office Update Engine. E.g. automatic updates, deadline, update channel, target version and such. Settings which do not deal with the updates (VBA settings; ruler on/off; ...) are not overruled and will still apply.

Or in other words: Servicing Profiles does not disable policy settings in general, it only overrules a few settings which are related to the update experience.

**Comment by AndytheIT** [comment]
Hi Thanks for getting back to me that's great

Andy
