### ISSUE TITLE
No display level information

### ISSUE THREAD

**Issue by spalmstr** [MicrosoftDocs/OfficeDocs-DeployOffice#113]
There is no information about the Display Level options.  That would have been useful for troubleshooting purposes.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [Deploy Office 2019 (for IT Pros)](https://docs.microsoft.com/en-gb/DeployOffice/office2019/deploy)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Display level info can be found here -- [Display element](https://docs.microsoft.com/en-us/DeployOffice/configuration-options-for-the-office-2016-deployment-tool#display-element). Hope that helps.

**Comment by spalmstr** [comment]
It does indeed, but it would have been helpful if the document in question had that information.

**Comment by DHB-MSFT** [comment]
There is a link to that article after the table about editing the configuration.xml file. That table is intended to cover settings that might require specific settings for Office 2019 or for settings admin should be aware of that are different than how they previously deployed Office. Didn't see a need to duplicate more generic settings, like Display Level that are covered elsewhere. I could try to make it clearer there are other options to consider than just those in the table, and those settings are documented in the article.

**Comment by spalmstr** [comment]
Thanks - I think I missed that link on the first read through.
