### ISSUE TITLE
Office 365 Plus => Office 365 ProPlus

### ISSUE THREAD

**Issue by takeakitake** [MicrosoftDocs/OfficeDocs-DeployOffice#1134]
Please revise product name from Office 365 Plus to Office 365 ProPlus in this sentence. Correct name is Office 365 ProPlus.
-----------
Any plan that includes Microsoft 365 Apps for enterprise (previously named Office 365 Plus). For example, Office 365 E3 or Microsoft 365 E5.
-----------

This is reference.

Name change for Office 365 ProPlus
https://docs.microsoft.com/en-us/deployoffice/name-change

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ab31873-7ad3-afde-3c72-8a7fb4f2e551
* Version Independent ID: 19f7f483-9f53-f577-1cd4-d360c0b234fc
* Content: [Overview of shared computer activation for Microsoft 365 Apps - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/overview-shared-computer-activation)
* Content Source: [DeployOffice/overview-shared-computer-activation.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-shared-computer-activation.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@takeakitake  Thanks for noticing that and letting us know. It's been fixed. We also checked to make sure that same error didn't appear in other articles in the "deploy Office" content.
