### ISSUE TITLE
Blocked macros in multiple copies of Word

### ISSUE THREAD

**Issue by linguistrick** [MicrosoftDocs/OfficeDocs-DeployOffice#1136]
[Enter feedback here]
I understand the new policy on macros in files from the Internet, but your new policies have created a new problem for me: for many years now I have been running multiple copies of Word, and running macros in each one, to save time, since some of the macros run in the background over long time periods. With your new policies, the macros still run, but only in the first copy of Word. In the second copy they are blocked, and nothing I can find to do will unblock them. This problem only started in the last week or two.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc5b380c-87db-3823-711d-6c8809392795
* Version Independent ID: cc5b380c-87db-3823-711d-6c8809392795
* Content: [Macros from the internet are blocked by default in Office  - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/security/internet-macros-blocked)
* Content Source: [DeployOffice/security/internet-macros-blocked.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/internet-macros-blocked.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@linguistrick  We recommend that you contact [Microsoft Support](https://support.microsoft.com/contactus) to help you with your issue. Support is in regular contact with the product team responsible for this change. And both Support and the product team will let us know if there is information that needs to be changed in or added to the documentation, based on issues that customers are encountering.

**Comment by linguistrick** [comment]
Dan,

 

I don’t understand! No one responded to my serious concern, and now you say it is closed as completed. It is not completed, because I still have no solution. Is there one?

 

Rick Aschmann

**Comment by DHB-MSFT** [comment]
You need to contact support. Their role is to help customers troubleshoot and resolve issues such as this. 

Based on what support/product team determine is the underlying issue & resolution, they'll let us know if the article needs to be updated.

This issue isn't designed to track the progress of your support issue and the possibility of any future documentation update. Which is why we closed it.

**Comment by linguistrick** [comment]
Yes, sorry, I read your second email first. I am doing that.
