### ISSUE TITLE
It's kills all the word automation

### ISSUE THREAD

**Issue by LeonPr** [MicrosoftDocs/OfficeDocs-DeployOffice#1137]
We using word automation to crate documents.
    If AcctionNeeded = OpenExtDoc Then
        Set wordobj = GetObject(, "Word.Application")
        If Err.number <> 0 Then
            WordWasOpen = False
            Set wordobj = CreateObject("Word.Application")
        Else
            WordWasOpen = True
        End If
        Err.Clear   ' Clear Err object in case error occurred.
    Else
        Set wordobj = CreateObject("Word.Application")
    End If
The new security fires every time command CreateObject("Word.Application") used if word object opened.
Peoples spend years and a lot of money to create macro based templates and now Microsoft just trash all the work done.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc5b380c-87db-3823-711d-6c8809392795
* Version Independent ID: cc5b380c-87db-3823-711d-6c8809392795
* Content: [Macros from the internet are blocked by default in Office  - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/security/internet-macros-blocked)
* Content Source: [DeployOffice/security/internet-macros-blocked.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/internet-macros-blocked.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@LeonPr  We recommend that you contact [Microsoft Support](https://support.microsoft.com/contactus) to help you with your issue. Support is in regular contact with the product team responsible for this change. And both Support and the product team will let us know if there is information that needs to be changed in or added to the documentation, based on issues that customers are encountering.
