### ISSUE TITLE
Clarity on number of supported methods

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/OfficeDocs-DeployOffice#1138]
[Enter feedback here]
This pages sates

> _Group Policy and the ODT are the only supported methods to change update channels....._

But lists or talk about 4 methods; Group Policy, ODT, Configuration Manager and Intune. Somewhat confusing 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d23ac821-9cb8-8855-598f-d1327df04fac
* Version Independent ID: 78f2127a-0c6b-d236-a415-6215c582ce8b
* Content: [Change the Microsoft 365 Apps update channel for devices in your organization - Deploy Office](https://docs.microsoft.com/en-gb/deployoffice/change-update-channels#feedback)
* Content Source: [DeployOffice/change-update-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/change-update-channels.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
We have removed the statement to reduce confusion.
