### ISSUE TITLE
Deploy ProjectPro2019Volume???

### ISSUE THREAD

**Issue by niceguy0815** [MicrosoftDocs/OfficeDocs-DeployOffice#114]
Hi I want to deploy Project but nothing happend when i test the download.
My XML:
```
<Configuration>
   <Add SourcePath="C:\Office\" OfficeClientEdition="32" Channel="PerpetualVL2019">
      <Product ID="ProjectPro2019Volume">
         <Language ID="de-de" />
      </Product>
	       <Product ID="ProofingTools">
        <Language ID="de-de" />
		<Language ID="en-us" />
      </Product>
       </Add>
  <Display Level="None" AcceptEULA="TRUE" />  
  <Property Name="AUTOACTIVATE" Value="1" />
</Configuration>
```

With Office 2019 Pro plus it has worked!

Do i need other Parameters for Project and Visio 2019
an Example config would be nice!

**Comment by DHB-MSFT** [comment]
I used your xml and the download worked fine for me.  FYI, there is a sample here -- [Sample configuration.xml file to use with the Office Deployment Tool](https://docs.microsoft.com/en-us/deployoffice/office2019/deploy#sample-configurationxml-file-to-use-with-the-office-deployment-tool).  Also, when you do a download (for example, 32-bit Office Professional Plus 2019), the download also includes 32-bit versions of Visio 2019 and Project 2019. They're all included in the stream.x86.x-none.dat file. So you only have to do one download (per bitness).  Hope that helps.

**Comment by niceguy0815** [comment]
Yes I got it now too :)
The Problem was the hardware Firwall from my company.
After switching out LAN Cable and conect my notebook to LTE the download wokrs fine :)

**Comment by DHB-MSFT** [comment]
@niceguy0815  -- glad to hear your issue was resolved.
