### ISSUE TITLE
Article "Configure update settings for Microsoft 365 Apps" is unlinked in the TOC

### ISSUE THREAD

**Issue by AlexJerabek** [MicrosoftDocs/OfficeDocs-DeployOffice#1140]
This article isn't linked in the table of contents. It should either be added to the repo's toc.yml or deleted.

![image](https://user-images.githubusercontent.com/38896772/190492045-3bcbc93a-e76f-49f4-a5ef-b3d912a1461c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 601039de-64e0-6f70-a5c6-f569f7d0cf87
* Version Independent ID: 861e9906-f260-fdcd-9bba-eb86056e51bd
* Content: [Configure update settings for Microsoft 365 Apps - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/configure-update-settings-microsoft-365-apps?redirectSourcePath=%252fen-us%252farticle%252fConfigure-update-settings-for-Office-365-ProPlus-a073ea21-62ed-40ef-8405-fd287f7d0b11#use-group-policy-to-configure-update-settings-for-microsoft-365-apps)
* Content Source: [DeployOffice/configure-update-settings-microsoft-365-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/configure-update-settings-microsoft-365-apps.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Yes, we're aware of that. We have plans to consolidate multiple update articles (including this one) into one article, which will appear in the TOC.
