### ISSUE TITLE
Unclear (incorrect) information in article

### ISSUE THREAD

**Issue by cawiesla** [MicrosoftDocs/OfficeDocs-DeployOffice#115]
I have a Customer that created a case regarding an Issue with SCA. They got the answer from support technicians that the mode they use for SCA is not supported and they also got reffered to this article. 

The support team interpret the article as SCA is only supported in RDS/VDI Environment... but that is not the case it seems. To start with, the article sais "it is most common in RDS" but that is not the same as "not supported outside RDS".

Customer got it confirmed from Product group that the way they use SCA is supported.

Can you please get this confirmed from Product group and then clarify this in the article to avoid more misunderstandings from support technicians in the future? 

Thanks in advance!

BR
Catrine Wieslander, SDM Microsoft Sweden

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ab31873-7ad3-afde-3c72-8a7fb4f2e551
* Version Independent ID: 19f7f483-9f53-f577-1cd4-d360c0b234fc
* Content: [Overview of shared computer activation for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/overview-of-shared-computer-activation-for-office-365-proplus)
* Content Source: [DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Have replied to Catrine offline.

**Comment by SCS-sysadmin** [comment]
I would also like to see this clarified. There are many use cases around SCA and I would like some guidance on when to use it and when not:

RDS/VDI
Computers where many users may be entering info/logging in throughout the day (e.g. on a plant floor)
Desktop machines where the users change daily (e.g. part-time receptionists)
Desktops used occasionally to run presentations over a projector.

Thanks!

**Comment by DHB-MSFT** [comment]
@cawiesla and @SCS-sysadmin I've updated the introduction of the article to make it clearer (hopefully) what are supported shared computer activation scenarios.  See the bullet points. Hope that helps. Thanks for the comment/feedback.
