### ISSUE TITLE
Inaccurate instructions

### ISSUE THREAD

**Issue by donfaison** [MicrosoftDocs/OfficeDocs-DeployOffice#1150]
"•	If you're not using digital signatures, you can save the template file to a [Trusted Location](https://learn.microsoft.com/en-us/deployoffice/security/trusted-locations) and have users get the template file from that location."  It IS in a trusted location, and ALL files created with that template are blocked.   Windows 10 ver 21H1, build 19043.2006; Word 365 apps for business, ver 2208; build 15601.20148
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc5b380c-87db-3823-711d-6c8809392795
* Version Independent ID: cc5b380c-87db-3823-711d-6c8809392795
* Content: [Macros from the internet are blocked by default in Office  - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/security/internet-macros-blocked)
* Content Source: [DeployOffice/security/internet-macros-blocked.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/internet-macros-blocked.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@donfaison We recommend that you contact [Microsoft Support](https://support.microsoft.com/contactus) to help you with your issue. Support is in regular contact with the product team responsible for this change. And both Support and the product team will let us know if there is information that needs to be changed in or added to the documentation, based on issues that customers are encountering.
