### ISSUE TITLE
Office 2019 App Icons showing in Searchbar when migrating to O365 Apps for Enterprise

### ISSUE THREAD

**Issue by debalti** [MicrosoftDocs/OfficeDocs-DeployOffice#1152]
We upgraded from Office 2019 to Office 365 using the Office Deployment Tool. After the installation the Apps work just fine but in the Searchbar the App Icons are still Office 2019. We tried deleting every cache we could find. Yet it does not seem to help. It reindexes them wrong.

**Comment by DHB-MSFT** [comment]
@debalti For troubleshooting questions such as these, we recommend doing one of the following:

- Contact [Microsoft Support](https://support.microsoft.com/contactus)
- Post on [Microsoft Answers](https://answers.microsoft.com/msoffice/forum)
- Post on [Microsoft Tech Community](https://techcommunity.microsoft.com/t5/microsoft-365-apps-for/bd-p/Microsoft365Apps)

FYI, we did reach out to the product team for this area, but they hadn't encountered this issue before. It's possible someone on Answers or Tech Community might have encountered this problem before and/or have a suggestion.
