### ISSUE TITLE
Still hate you guys for this.

### ISSUE THREAD

**Issue by SrDirko** [MicrosoftDocs/OfficeDocs-DeployOffice#1155]
I submitted feedback for this article before your rollback and I'm doing it again now.

This is a hair-brained implementation. Macros cannot be unblocked by any of the methods in your article. We don't have any policies set up to block them. I've tried adding trusted locations. I've tried unblocking the file (it's not blocked). I've tried allowing all VBA macros. Nothing. Nothing works. 

Fire the team that made this change. They didn't get it right on the first or second attempt. I can't open the macros I've written myself. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc5b380c-87db-3823-711d-6c8809392795
* Version Independent ID: cc5b380c-87db-3823-711d-6c8809392795
* Content: [Macros from the internet are blocked by default in Office  - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/security/internet-macros-blocked#files-on-onedrive-or-sharepoint)
* Content Source: [DeployOffice/security/internet-macros-blocked.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/internet-macros-blocked.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by SrDirko** [comment]
https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/1101

**Comment by DHB-MSFT** [comment]
@SrDirko  We recommend that you contact [Microsoft Support](https://support.microsoft.com/contactus) to help you with your issue. Support is in regular contact with the product team responsible for this change. And both Support and the product team will let us know if there is additional information that needs to be included in the documentation, based on issues that customers are encountering.

**Comment by SrDirko** [comment]
I would do that if you provided a means. There is no option to contact support on Microsoft Documentation any longer.

**Comment by DHB-MSFT** [comment]
@SrDirko   We provided a link in our response.  https://support.microsoft.com/contactus

**Comment by SrDirko** [comment]
I found a solution to my specific problem, maybe that can influence you to update your documentation. When it comes to OneDrive for Business files, even if you are syncing and have a local copy of a file, you cannot use the path on your computer when adding to trusted sites. You have to add the URL to the folder in OneDrive online. For this you need to go to the Classic OneDrive Experience to find the URL of an item or folder. You then have to check the box marked "Allow Trusted Locations on my network (not recommended)".
