### ISSUE TITLE
Unsupported Outlook versions are actively blocked

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/OfficeDocs-DeployOffice#1156]
Please modify this article and add this note.

****The block will start rolling out for Outlook 2016 MSI users (on versions earlier than 16.0.4600.1000) & Outlook for Microsoft 365 users (on versions earlier than 16.0.8321.1000) on March 28, 2022 and will proceed in a phased rollout.

https://techcommunity.microsoft.com/t5/microsoft-365-blog/new-minimum-outlook-for-windows-version-requirements-for/ba-p/2684142

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e86f8d4f-3eb1-6763-0f10-a0b637f3035c
* Version Independent ID: a6642647-dc4d-30a9-e962-76f7cd1f5089
* Content: [Office versions and connectivity to Microsoft 365 services - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/endofsupport/microsoft-365-services-connectivity)
* Content Source: [DeployOffice/endofsupport/microsoft-365-services-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/endofsupport/microsoft-365-services-connectivity.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@trudolf-msft  That information is in the Tech Community blog post. We link to that blog post from our article ("Office versions and connectivity....").  We aren't going to repeat the same info in our article.

**Comment by trudolf-msft** [comment]
Hi Dan,

I am confused about first Statement in the article.

We won’t take any active measures to block older Office versions from connecting to Microsoft 365 services

This is wrong!!!

Thanks,
Thomas
________________________________

**Comment by DHB-MSFT** [comment]
@trudolf-msft  Let's discuss offline. I've sent you an email about this. Thanks.
