### ISSUE TITLE
Will a 'Microsoft 365 Apps for business' license and SCA work with this method?

### ISSUE THREAD

**Issue by Dustrega** [MicrosoftDocs/OfficeDocs-DeployOffice#1159]
Apologies if this was answered in a different pull req. I honestly hope I'm just missing something crucial, but I am investigating an ongoing issue with SCA that was previously implemented as "working", though I have found no evidence to that claim. The document [here](https://learn.microsoft.com/en-us/deployoffice/overview-shared-computer-activation#how-to-enable-shared-computer-activation-for-microsoft-365-apps), as of 10/24/2022, states the following for license requirements:

![image](https://user-images.githubusercontent.com/29438865/197637761-545994cb-7b80-4b6c-92ca-1f8f956b48c8.png)

Where I lose the plot is that after assigning a **Microsoft 365 Apps for business** license
![image](https://user-images.githubusercontent.com/29438865/197639504-ebb26727-acba-437c-8c4c-3b517b5425f4.png)

Implementing the Reg_SZ key of 'SharedComputerLicensing' at the location 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration', after a fresh install of Office (now M365), and logging in with the credentials of the account with the mentioned license, I receive a message that states the following in some effect:

![chrome_cHCi7NIHxY](https://user-images.githubusercontent.com/29438865/197638656-d94f5b5f-acb6-475d-897f-f1c9d63cbf80.png)

Note: Removal of the key and a restart of Office has this message not appear, but Shared Licensing is then not enacted (which should not be the case according to the doc). This would seem to indicate that the flag/key is being read, but the licensing is noted of being at issue. If I log in with my E3 enabled license, Shared Activation is shown without problems in the About section of any Office app.

The chief question would be, does the lone license of **Microsoft 365 Apps for business** work with SCA?

I would really appreciate the clarification/confirmation and thank you for the time in advance.

**Comment by DHB-MSFT** [comment]
@MJP-MSFT   Can you help with this?  Thanks.

**Comment by MJP-MSFT** [comment]
@Dustrega   Which plan do you have enabled?  Just underneath the content you shared there's a note calling out support for SCA only with Business Premium SKU's 

NOTE:
The Microsoft 365 Business Premium plan is the only business plan that includes support for shared computer activation. There are other business plans, such as Microsoft 365 Business Standard, that include Microsoft 365 Apps for business, but, those business plans don't include support for shared computer activation.

**Comment by Dustrega** [comment]
@MJP-MSFT When we run into the issue of SCA not being allowed, we are using the **Microsoft 365 Apps for business** standalone license (not Microsoft 365 Business Premium; picture below).

![image](https://user-images.githubusercontent.com/29438865/197809968-b4a8de23-e5c3-4729-9c21-d87614883cc3.png)

If my guess is correct, based on your explanation and that of the documentation, only the following work with SCA:

Easily understood:
- Office 365 E3 and E5 licensing (tried and tested)
- Project Plan 3 or Visio Plan 2

Semi-ambiguous:
- The Microsoft 365 Business Premium plan, which includes Microsoft 365 Apps for business. (Does this mean the standalone license is included or excluded; According to the note below the license requirements, it is plain to me that a standalone Microsoft 365 Apps for business license alone will not cut it.)

![image](https://user-images.githubusercontent.com/29438865/197812462-211eb380-2fef-432a-94f5-c16bbbb65db6.png)

Will absolutely not work with SCA:
- Microsoft 365 Basic or Standard (fairly obvious)
- Microsoft 365 Apps for business license (need confirmation/clarification)

I appreciate your diligence and please let me know of any further information required.

**Comment by MJP-MSFT** [comment]
@Dustrega 

It is my understanding that it is tied to the plan. Even through the Premium plan includes the bits for Microsoft 365 Apps for Business it does not allow the capability of using SCA.  In order to use SCA you would need to move the users over to the premium plan.

**Comment by Dustrega** [comment]
@MJP-MSFT - Masterful! Thank you, once again, for all your time and diligence.
