### ISSUE TITLE
Missing channel "Monthly Channel (Targeted)"

### ISSUE THREAD

**Issue by bramdejager** [MicrosoftDocs/OfficeDocs-DeployOffice#116]
Based on this article (https://docs.microsoft.com/en-us/sccm/sum/deploy-use/manage-office-365-proplus-updates#change-the-update-channel-after-you-enable-office-365-clients-to-receive-updates-from-configuration-manager) there are four channels which can be used to retrieve updates from. 

* Monthly Channel (Targeted)
* Monthly Channel 
* Semi-Annual Channel (Targeted) 
* Semi-Annual Channel

Where did the "Monthly Channel (Targeted)" go, it seems it is missing from this page. And my machine is set to this channel, but it looks it is ignoring it. As a result I'm set to the "Monthly Channel"!? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cd85e3b-e780-457e-9502-856bc6315bca
* Version Independent ID: 416e351f-13c5-e951-ea81-1650910a7c25
* Content: [Overview of update channels for Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/overview-of-update-channels-for-office-365-proplus?ui=en-US&rs=en-US&ad=US%3E)
* Content Source: [DeployOffice/overview-of-update-channels-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-update-channels-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Monthly Channel (Targeted) is mentioned in a note at the end of the [Monthly Channel section](https://docs.microsoft.com/en-us/DeployOffice/overview-of-update-channels-for-office-365-proplus#monthly-channel-for-office-365-proplus). This article is primarily targeted at IT Pros/admins deploying Office 365 ProPlus in the enterprise, and we don't usually recommend deploying Monthly Channel (Targeted) to end users in an enterprise.  Hope that helps.
