### ISSUE TITLE
If Protected is Disable, the icon becomes x

### ISSUE THREAD

**Issue by TomoharuMisawa** [MicrosoftDocs/OfficeDocs-DeployOffice#1166]
Allow specified hosts to show Basic Authentication prompts to Office
the third icon is weird

![image](https://user-images.githubusercontent.com/41832013/199794484-a90c2d7a-1a54-4c20-9e23-4c7c2ab32b88.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 861173eb-69e2-109a-bfea-3a22440f5854
* Version Independent ID: 861173eb-69e2-109a-bfea-3a22440f5854
* Content: [Basic authentication sign-in prompts are blocked by default in Microsoft 365 Apps - Deploy Office](https://learn.microsoft.com/en-us/DeployOffice/security/basic-authentication-prompts-blocked?WT.mc_id=M365-MVP-5002496#use-policies-to-manage-basic-authentication-prompts)
* Content Source: [DeployOffice/security/basic-authentication-prompts-blocked.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/basic-authentication-prompts-blocked.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@TomoharuMisawa   Can you clarify what you mean by "the third icon is weird"?  Thanks.

**Comment by DHB-MSFT** [comment]
@TomoharuMisawa  We're using the green check mark to indicate that you're"protected" if you choose the option in that row, which is the case for the 3rd row (when you set the policy to Disabled).  The x icon is used to indicate that you're not "protected" if you choose the option in the row.  Does that explanation help?
