### ISSUE TITLE
Version number has not updated

### ISSUE THREAD

**Issue by rysuz** [MicrosoftDocs/OfficeDocs-DeployOffice#1169]
[Enter feedback here]
The effective versions of Office has not updated yet. From internal information, currently the effective version is 2209. The page shows old information 2208 so far.

<html>
<body>

Update channel | Version | Date
-- | -- | --
Current Channel (Preview) | Version 2208 | August 2022
Current Channel | Version 2208 | To be determined
Monthly Enterprise Channel | To be determined | To be determined
Semi-Annual Enterprise Channel (Preview) | To be determined | To be determined
Semi-Annual Enterprise Channel | To be determined | To be determined

</body>
</html>
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 861173eb-69e2-109a-bfea-3a22440f5854
* Version Independent ID: 861173eb-69e2-109a-bfea-3a22440f5854
* Content: [Basic authentication sign-in prompts are blocked by default in Microsoft 365 Apps - Deploy Office](https://learn.microsoft.com/en-us/DeployOffice/security/basic-authentication-prompts-blocked)
* Content Source: [DeployOffice/security/basic-authentication-prompts-blocked.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/basic-authentication-prompts-blocked.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@rysuz   Yes, we're aware of that. We're in the process of updating that (as well as making some other updates to the article).

**Comment by rysuz** [comment]
Thank you, @DHB-MSFT !

**Comment by DHB-MSFT** [comment]
@rysuz  The version info in the article has been updated.
