### ISSUE TITLE
Spelling Mistake 

### ISSUE THREAD

**Issue by nkas0512** [MicrosoftDocs/OfficeDocs-DeployOffice#1173]
Under Note section, we have a small spelling mistake which needs attention. 

**Instead of same it is written saem** 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8cfd7df-f070-3665-7546-c49227e89dbd
* Version Independent ID: 5f3bd903-656a-85a3-2f80-c0a1b006523d
* Content: [Choose how to deliver updates for Microsoft 365 Apps for enterprise - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/fieldnotes/choose-how-to-deliver-updates)
* Content Source: [DeployOffice/fieldnotes/choose-how-to-deliver-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/fieldnotes/choose-how-to-deliver-updates.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @manoth-msft
* Microsoft Alias: **manoth**

**Comment by DHB-MSFT** [comment]
@nkas0512   Thanks for pointing that out. It's been fixed.
