### ISSUE TITLE
The key OLDisableJunkOptionsPrefKey in macOS configuration profiles does not actually work

### ISSUE THREAD

**Issue by ianhoopes** [MicrosoftDocs/OfficeDocs-DeployOffice#1177]
In the latest version (16.55) of the Outlook preferences deployed via Configuration Profile, the OLDisableJunkOptionsPrefKey does not work. The Junk options are visible whether the key is applied as true or false in the New Outlook experience. Tested by deploying from Jamf Pro and installing the profile manually; in both cases the button is still visible.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ee85c2aa-f4df-d3b9-1491-76b662cc748a
* Version Independent ID: eadbcd7e-16f3-0ead-3e6a-530bfd999e1b
* Content: [Set preferences for Outlook for Mac - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/mac/preferences-outlook#disable-junk-settings)
* Content Source: [DeployOffice/mac/preferences-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/mac/preferences-outlook.md)
* Service: **o365-proplus-itpro**
* Sub-service: **office-mac**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@pbowden-msft   Do you know anything about this? Thanks.

**Comment by pbowden-msft** [comment]
@DHB-MSFT I checked the sources as the key doesn't have the 'OL' prefix, so the op is correct. I created a pull request for the updated key name.

**Comment by DHB-MSFT** [comment]
@ianhoopes  Looks like we had an error in the key name. Should be DisableJunkOptionsPrefKey  (no OL at the beginning). We've updated the article. Thanks for bringing this issue to our attention.

**Comment by ianhoopes** [comment]
Working as expected now with the updated preference key. Thanks folks! Now here's hoping Jamf updates their built-in repository in the near future.

**Comment by pbowden-msft** [comment]
@ianhoopes thanks for confirming! I've spoken to Jamf, and the built-in repo will be updated by the end of this week.
Thanks for reporting!
