### ISSUE TITLE
No mention of config.office.com?

### ISSUE THREAD

**Issue by bmilbauer** [MicrosoftDocs/OfficeDocs-DeployOffice#118]
There are people at Microsoft who have put countless hours into developing config.office.com, a tremendously helpful tool, and yet on the main landing page for deploying Office 2019 which will heavily influence the experience of IT professionals deploying this product, you make no mention of it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da0ced28-ffb1-1924-6fc7-24265bc95c42
* Version Independent ID: b261a792-c076-2221-65f0-1d2ac52fef7a
* Content: [Overview of Office 2019 (for IT Pros)](https://docs.microsoft.com/en-us/deployoffice/office2019/overview)
* Content Source: [DeployOffice/office2019/overview.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/overview.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Config.office.com is currently still in Preview and at this time doesn't support Office 2019. Support for Office 2019 is expected by the end of this year.  Hope that helps.
