### ISSUE TITLE
Registry Setting

### ISSUE THREAD

**Issue by OneGi** [MicrosoftDocs/OfficeDocs-DeployOffice#12]
Using the GPO, how do I check if the settings were applied? Which registry path on the client computer should this be checked?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 601039de-64e0-6f70-a5c6-f569f7d0cf87
* Version Independent ID: 861e9906-f260-fdcd-9bba-eb86056e51bd
* [Content](https://docs.microsoft.com/en-us/deployoffice/configure-update-settings-for-office-365-proplus)
* [Content Source](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/configure-update-settings-for-office-365-proplus.md)
* Service: o365-administration

**Comment by DHB-MSFT** [comment]
The registry location for these GP settings are HKLM\software\policies\microsoft\office\16.0\common\officeupdate. You can find the registry location of any GP setting by looking at the office2016grouppolicyandoctsettings.xlsx Excel file that is included in the GP ADMX files download from the Microsoft Download Center. Go to the ADMX worksheet, find the setting you're interested in, and then look in column F ("Registry information").  Hope that helps.

**Comment by OneGi** [comment]
Does this conflict in any way with the settings found in \HKLM\Software\Microsoft\Office\ClickToRun\Configuration? 

There are two update location configurations found there, and one that is governing if update is enabled:
- UpdateUrl
- UpdateChannel
- UpdatesEnabled
