### ISSUE TITLE
Setting privacy preferences

### ISSUE THREAD

**Issue by MKUM2020** [MicrosoftDocs/OfficeDocs-DeployOffice#1201]
Where are the preferences actually set?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ea7bb8bf-5d11-87cb-a880-2edc355dca56
* Version Independent ID: fa4bfa40-42bf-bf0d-413d-d67e8ae826b9
* Content: [Use preferences to manage privacy controls for Office for Mac - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/privacy/mac-privacy-preferences)
* Content Source: [DeployOffice/privacy/mac-privacy-preferences.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/mac-privacy-preferences.md)
* Service: **o365-proplus-itpro**
* Sub-service: **office-mac**
* GitHub Login: @pbowden-msft
* Microsoft Alias: **danbrown**

**Comment by pbowden-msft** [comment]
@MKUM2020 The preferences are set in the com.microsoft.office preferences domain. For example, you can run "defaults read com.microsoft.office" from Terminal to view the existing preferences.

**Comment by MKUM2020** [comment]
Thanks Paul.

Just ran the command "defaults read com.microsoft.office" in the mac Terminal.

How do you update the shown preferences?



ConnectedOfficeExperiencesPreference = 1;

    CurrentUserConsentGroupKey = 1;

    DiagnosticDataTypePreference = FullDiagnosticData;

    HasUserSeenEnterpriseFREDialog = 0;

Thanks

________________________________

**Comment by pbowden-msft** [comment]
@MKUM2020 Sure. There's a 'write' verb for the defaults command, so for example, you can run:
`defaults write com.microsoft.office HasUserSeenEnterpriseFREDialog -bool TRUE`

Then, when you run `defaults write com.microsoft.office `command again, you should see the change in state.
The defaults command is useful for setting preferences locally and on-demand. When dealing with higher numbers of devices, you can set these preferences via a Management/MDM tool such as Jamf.
