### ISSUE TITLE
Please further clarify first time installation and preconfigured update channels for Microsoft 365 Apps

### ISSUE THREAD

**Issue by grimson73** [MicrosoftDocs/OfficeDocs-DeployOffice#1207]
Hello,

I would really love to have some extra details on the provided 'Configure the update channel' page.

https://learn.microsoft.com/en-us/deployoffice/overview-update-channels#default-update-channel
_'Current Channel is the default update channel for Microsoft 365 Apps for enterprise, Microsoft 365 Apps for business'_
So, a fresh install without anything configured will give the 'Current Channel'

Therefore, my question is about the choice of update channel for the Microsoft 365 Apps with the following configured:

https://learn.microsoft.com/en-us/deployoffice/overview-update-channels#configure-the-update-channel
Deploying with and how the installation chooses the update channel:

_**ODT Tool:**_
I would presume the OCD ehh ODT ;) tool would explicitly set and use the chosen update channel to install. So the 'correct' installation of the chosen update channel is right at the start. Is this correct? (Seems like a nonsense question but please read on on other installation options)

**_Group Policy:_**
Would an installation of the Microsoft 365 Apps use the GPO setting directly (initial installation) or change the default channel after installation to the GP chosen one? My guess is that the OCD tool cannot read the GPO and therefore installs the default update channel. After the initial setup the GPO provided update channel will be read and will 'reinstall' the App accordingly to the then chosen update channel. Could you elaborate on this please?

**_Microsoft 365 admin center_**
Page text: 'This setting applies to all users in your tenant and only applies to users that install Office for themselves from the portal.'
From the Org Settings page 'Microsoft 365 apps‎ installation options': 'Your choice will apply to both new and existing installations.'
<img width="416" alt="image" src="https://user-images.githubusercontent.com/45716059/220919362-bbaf97d4-2cb2-4f2b-86b9-4497993af799.png">

Q: So this setting counts for the initial installation and also installations already installed from the user portal and only for the installations from this portal?
Also what is the preferred update channel when a GPO is in use AND this setting is in place?

Thanks for clarifying, if possible,
Regards,
Arian! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd18fe4f-5a0e-22cd-61b8-242419c6b18a
* Version Independent ID: d6f7ce9e-09f8-87fb-f05e-07e1a8d0ee01
* Content: [Overview of update channels for Microsoft 365 Apps - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/overview-update-channels#configure-the-update-channel)
* Content Source: [DeployOffice/overview-update-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-update-channels.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @nicholasswhite
* Microsoft Alias: **nwhite**

**Comment by manoth-msft** [comment]
Hi Arian,

we must distinguish "install" and "update". E.g. the policy "Update Channel" only applies to updates. From description "This policy setting controls which update channel Office gets updates from.".

So, for install scenarios (so the setup.exe aka ODT runs), it goes like this:

- If install is triggered through portal, use the channel which is set in the portal.
- If install is triggered through ODT (setup /configure yourfile.xml), it will take whatever is set in the yourfile.xml. E.g. if you selected "Monthly Enterprise" in the OCT, the resulting configuration file will instruct ODT/setup to install from this channel. If no channel is set in configuration.xml, it will use Current Channel.

For updates it goes like this for each device:

- If no settings were specified by the admin (portal install or configuration did not include an update channel) and there is no other method specifying the channel (GPO, configuration profile, SCCM, whatever), it will update from the channel which is set in the portal. This is not a re-install, it's just an update. If the device was on another channel before, it will update to the selected channel. The user experience is the same as during a regular update.

- If settings were specified (GPO, Configuration Profile, <Update channel=""> attribute in ODT), the device will update to this channel. Same as above, no re-install, UI/UX is a regular update. We have a blog which details how the update engine determines the winning setting, further down is the table of the priorities: https://techcommunity.microsoft.com/t5/microsoft-365-blog/understanding-office-365-proplus-updates-for-it-pros-cdn-vs-sccm/ba-p/795728
- The blog is a bit older and is not covering servicing profile. If you have servicing profile enabled and the device is targeted by profiles, the winning update channel selection will come from servicing profile.

Hope this clarifies the process. If not, let me know :)

**Comment by manoth-msft** [comment]
Hi Arian,

we must distinguish "install" and "update". E.g. the policy "Update Channel" only applies to updates. From description "This policy setting controls which update channel Office gets updates from"".

So, for install scenarios (so the setup.exe aka ODT runs), it goes like this:

- If install is triggered through portal, use the channel which is set in the portal.
- If install is triggered through ODT (setup /configure yourfile.xml), it will take whatever is set in the yourfile.xml. E.g. if you selected "Monthly Enterprise" in the OCT, the resulting configuration file will instruct ODT/setup to install from this channel.

For updates it goes like this:

- If no settings were specified by the admin (portal install or configuration did not include an update channel) and there is no other method specifying the channel (GPO, configuration profile, SCCM, whatever), it will update from the channel which is set in the portal. This is not a re-install, it's just an update. If the device was on another channel before, it will update to the selected channel. The user experience is the same as during a regular update.

- If settings were specified (GPO, Configuration Profile, <Update channel=""> attribute in ODT, the device will update to this channel. Same as above, no re-install, UI/UX is a regular update. We have a blog which details how the update engine determines the winning setting, further down is the table of the priorities: https://techcommunity.microsoft.com/t5/microsoft-365-blog/understanding-office-365-proplus-updates-for-it-pros-cdn-vs-sccm/ba-p/795728
- The blog is a bit older and is not covering servicing profile. If you have servicing profile enabled and the device is targeted by profiles, the winning update channel selection will come from servicing profile.
