### ISSUE TITLE
GPO "allow users who arent admins to install language accessory packs" not working when Office COM is enabled

### ISSUE THREAD

**Issue by Marilena-Neaga** [MicrosoftDocs/OfficeDocs-DeployOffice#1211]
[Enter feedback here]

Hello team, 

I have a suggestion regarding the section "Allow users who are not admins to deploy languages". As mentioned in the bug 6175397, when Office COM is enabled, the users can't install languages without admin rights, even if the GPO is set correctly. The rejection statement is: 

“In this case the conflict is that the machines in question are managed via a solution that uses a COM interface. The COM interface is very powerful and allows the admin to specify any update source they choose (SCCM, for example, specifies a different update source for every action).
 
In such an environment there are several concerns:
•	If the new language pack is not supported by the update source, then the machine will not be able to update any further
•	We don't know which language packs the admin has made available, so language pack installation may fail
•	Falling back the well-known CDNs may cause the machine to fall out of compliance with the admin intent
Further, the COM interface assumes that it has control over the update cadence. Taking this change would provide an out of band way for the machine to update, which may take a machine out of compliance with the admin's expectations.

**Ask** 

Kindly also mention in the article the fact that languages can't be deployed without admin rights when the updates are COM managed, as the design change request has been rejected. 

Thank you!   

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a805631-adc3-d006-201d-9ebbdfd3e7c5
* Version Independent ID: 543a9486-1459-07ad-cbb9-1ce9d69dcd95
* Content: [Overview of deploying languages for Microsoft 365 Apps - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/overview-deploying-languages-microsoft-365-apps)
* Content Source: [DeployOffice/overview-deploying-languages-microsoft-365-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-deploying-languages-microsoft-365-apps.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @nicholasswhite
* Microsoft Alias: **nwhite**

**Comment by manoth-msft** [comment]
Thanks for bringing this up, I've added a note on this scenario: 
"When programmatic control of Microsoft 365 Apps updates is enabled, this feature is not available. This is the case when you use Configuration Manager to deploy updates for Microsoft 365 Apps or servicing profiles."
