### ISSUE TITLE
Update documentation to include Bing as an option for ExcludeApp

### ISSUE THREAD

**Issue by happyphunn** [MicrosoftDocs/OfficeDocs-DeployOffice#1214]
Please update the documentation here so it reflects all of the options available within the OCT, such as Bing as an ExcludeApp.  Also, you should probably make it so everything you can do in the configuration XML, by manually editing it, can also be done in the OCT.  I still have to manually edit the file because of the config I want using MSI conditions, and would be really nice to be able to use the OCT and/or actually have all possible options documented correctly in a single location.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f907a7f6-5351-3044-e258-9d18489a08e9
* Version Independent ID: 27d220cf-42e8-1cfc-08aa-586686a9f8b2
* Content: [Configuration options for the Office Deployment Tool - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/office-deployment-tool-configuration-options#excludeapp-element)
* Content Source: [DeployOffice/office-deployment-tool-configuration-options.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office-deployment-tool-configuration-options.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @nicholasswhite
* Microsoft Alias: **nwhite**

**Comment by DHB-MSFT** [comment]
@happyphunn  Thanks for pointing out that Bing was missing from the ExcludeApp list. We've updated the article to include it. Let us know if there are other options that are missing from the article.

@chhopkin  See the comments above about options not currently available in the Office Customization Tool.
