### ISSUE TITLE
Duplicate Items

### ISSUE THREAD

**Issue by matziq** [MicrosoftDocs/OfficeDocs-DeployOffice#1215]
This line is repeated:
If you want to see the next time a device running Windows is scheduled to check with Cloud Policy, look at the FetchInterval under HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common\CloudPolicy. The value is expressed in minutes. For example, 1440, which equates to 24 hours.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f75100b-c7fa-4da3-c8a1-f5ef99208148
* Version Independent ID: 1f75100b-c7fa-4da3-c8a1-f5ef99208148
* Content: [Overview of Cloud Policy service for Microsoft 365 - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/admincenter/overview-cloud-policy?source=docs)
* Content Source: [DeployOffice/admincenter/overview-cloud-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/admincenter/overview-cloud-policy.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @nicholasswhite
* Microsoft Alias: **nwhite**

**Comment by DHB-MSFT** [comment]
@matziq   Thanks for pointing that out. We've removed the duplicate text.
