### ISSUE TITLE
Update channels Question on MS-900 is Super Vague and Answer is not explained Well.

### ISSUE THREAD

**Issue by StinsmanJ** [MicrosoftDocs/OfficeDocs-DeployOffice#1221]
The question:
A company uses Microsoft 365.

The company plans to provide new feature updates to Microsoft Office applications **after extensive testing.**

You need to recommend an update channel for use.

Which channel should you recommend?

Select only one answer.

current channel

monthly enterprise channel

semi-annual enterprise channel (preview) - This answer is correct.

semi-annual enterprise channel

This item tests the candidate's knowledge about Microsoft 365 release channels.

The semi-annual enterprise channel (preview) receives updates every six months, a few months before these are made available to the semi-annual enterprise channel, being recommended for organizations where extensive testing is needed before rolling out any new feature. The current channel receives feature updates as soon as they are ready. The monthly enterprise channel receives updates once a month on a predictable schedule. The semi-annual enterprise channel receives updates every six months, being recommended for organizations where extensive testing is needed before rolling out any new feature.

So how is Semi-Annual Enterprise Chanel not correct when the descriptions for it and the (Preview) are the same:
The semi-annual enterprise channel (preview) receives updates every six months, a few months before these are made available to the semi-annual enterprise channel, **being recommended for organizations where extensive testing is needed before rolling out any new feature**
vs
The semi-annual enterprise channel receives updates every six months, **being recommended for organizations where extensive testing is needed before rolling out any new feature.**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc39fb24-79ef-0402-6a1b-519ebb78285d
* Version Independent ID: cc39fb24-79ef-0402-6a1b-519ebb78285d
* Content: [Overview of update channels for Microsoft 365 Apps - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/updates/overview-update-channels#semi-annual-enterprise-channel-overview)
* Content Source: [DeployOffice/updates/overview-update-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/updates/overview-update-channels.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @nicholasswhite
* Microsoft Alias: **nwhite**

**Comment by DHB-MSFT** [comment]
@manoth-msft   Can you help provide more guidance on this? Thanks.

@StinsmanJ   The short answer would be most users should be on Semi-Annual Enterprise Channel. The "preview" channel is used for testing in advance before rolling out the next Semi-Annual Enterprise Channel. "Preview" channel comes out 3 months in advance to facilitate the testing.

**Comment by manoth-msft** [comment]
Hmm, I agree that the questions from MS-900 is pretty vague. I would also have assumed the correct answer is Semi-Annual, not Semi-Annual (Preview). For Semi-Annual (Preview), the questions should be worded slightly different:

The company plans to provide new feature updates to Microsoft Office applications **after** extensive testing. > Answer should be Semi-Annual
The company plans to provide new feature updates to Microsoft Office applications **for** extensive testing. > Answer should be Semi-Annual (Preview)
