### ISSUE TITLE
Role requirements for Servicing Profile

### ISSUE THREAD

**Issue by RichardArg** [MicrosoftDocs/OfficeDocs-DeployOffice#1222]
Could you add what the Azure AD Role requirements are for editing Service Profiles? Or have a I missed it somewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d3986ef-1183-c725-1510-c30f415a535c
* Version Independent ID: 7d3986ef-1183-c725-1510-c30f415a535c
* Content: [Overview of servicing profile in the Microsoft 365 Apps admin center - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/admincenter/servicing-profile)
* Content Source: [DeployOffice/admincenter/servicing-profile.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/admincenter/servicing-profile.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @nicholasswhite
* Microsoft Alias: **nwhite**

**Comment by DHB-MSFT** [comment]
@RichardArg   Thanks for the suggestion of adding the roles.

@nicholasswhite  Per Richard's comment, let's add this role information to the article. Since not everyone will have read the "overview" article first.
