### ISSUE TITLE
SQL Database is missing ProposedCode column in VbaRemediations table

### ISSUE THREAD

**Issue by ABNOTECHGuy** [MicrosoftDocs/OfficeDocs-DeployOffice#1224]
This issue is in the latest version: 1.2.23020

When creating JSON output files and then importing them into SQL, the VbaRemediations table is missing a ProposedCode column so viewing the Proposed Changes in PowerBI is missing. 
![Screenshot 2023-04-24 153957](https://user-images.githubusercontent.com/19259945/233908988-8c419a7d-46f2-47e8-88d5-54982d2e73df.png)
![Screenshot SQL Columns](https://user-images.githubusercontent.com/19259945/233909815-e87e94d6-f0e0-409a-b580-8e8469196adc.png)

When importing JSON files into the Excel report from the GUI this is not and issue and you can see both the Original Cod and the Proposed Code.
![Screenshot 2023-04-24 153605](https://user-images.githubusercontent.com/19259945/233908593-e9243b12-a96c-4757-86dc-c4600f005013.png)

Can the application please be updated to include this information in the SQL database as it pretty much renders the PowerBI report useless for acting on remediations.

**Comment by DHB-MSFT** [comment]
@ABNOTECHGuy   Please submit this issue to [ReadyForOffice@microsoft.com](mailto:ReadyForOffice@microsoft.com). That email address is monitored by the team responsible for the Readiness Toolkit. Thank you.
