### ISSUE TITLE
Add command line example

### ISSUE THREAD

**Issue by ichiroe** [MicrosoftDocs/OfficeDocs-DeployOffice#1230]
This is customer feedback.

Please add command line example (setup.exe /configure config.xml) with "Change the update channel with the Office Deployment Tool (ODT)" section.

My customer misunderstanding to using /customize switch.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d23ac821-9cb8-8855-598f-d1327df04fac
* Version Independent ID: 78f2127a-0c6b-d236-a415-6215c582ce8b
* Content: [Change the Microsoft 365 Apps update channel for devices in your organization - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/updates/change-update-channels#change-the-update-channel-with-the-office-deployment-tool-odt)
* Content Source: [DeployOffice/updates/change-update-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/updates/change-update-channels.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @nicholasswhite
* Microsoft Alias: **nwhite**

**Comment by manoth-msft** [comment]
Thanks for reporting. I've submitted a change to address the feedback. Should be live within a few days.

**Comment by ichiroe** [comment]
[like]  Ichiro Ebata reacted to your message:
________________________________
