### ISSUE TITLE
Need a way to shut this off for OL on W10 or W11

### ISSUE THREAD

**Issue by JoeBrunsTR** [MicrosoftDocs/OfficeDocs-DeployOffice#1231]
It's great that you took the time to develop this but you also need a way to allow users of the latest OL to turn it off and go back to using the default browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8ac95be-d5b8-b295-3003-fa5ce70dfb55
* Version Independent ID: d2acedb5-834c-8fa6-d917-7316e9bcda3d
* Content: [Microsoft Edge WebView2 and Microsoft 365 Apps - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/webview2-install)
* Content Source: [DeployOffice/webview2-install.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/webview2-install.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by JoeBrunsTR** [comment]
Not it at all.  I can see WebView2 launch and it only provides a single browser web page with no menu bar.

**Comment by DHB-MSFT** [comment]
Best way to provide your feedback to the Outlook product team on this is to go to **Help** > **Feedback** within Outlook.

Other options are the following:

- [Outlook section on feedback portal](https://feedbackportal.microsoft.com/feedback/forum/89a8afa3-2e1c-ec11-b6e7-0022481f8472)
- [Outlook section on TechCommunity](https://techcommunity.microsoft.com/t5/outlook/ct-p/Outlook)
- [Contact support](https://support.microsoft.com/contactus)
