### ISSUE TITLE
Missing Licensing information about Business Premium and Business Standard for Semantic Index 

### ISSUE THREAD

**Issue by poiriersimon** [MicrosoftDocs/OfficeDocs-DeployOffice#1244]
[Enter feedback here]
We can read "Semantic Index for Copilot (for Microsoft 365 E3 and E5 customers)" but it should also include for the SMB/SMC customer the license Business Premium and Business Standard 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27c896eb-5663-49b8-8883-cb4b377a2306
* Version Independent ID: 27c896eb-5663-49b8-8883-cb4b377a2306
* Content: [Data, Privacy, and Security for Microsoft 365 Copilot - Deploy Office](https://learn.microsoft.com/en-ca/DeployOffice/privacy/microsoft-365-copilot?source=docs)
* Content Source: [DeployOffice/privacy/microsoft-365-copilot.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/microsoft-365-copilot.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Taking discussion offline with submitter.
