### ISSUE TITLE
Great post

### ISSUE THREAD

**Issue by tishalane** [MicrosoftDocs/OfficeDocs-DeployOffice#1246]
Practical information that works.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3437d6c-4600-9ba3-4214-37d45f304e4c
* Version Independent ID: f3437d6c-4600-9ba3-4214-37d45f304e4c
* Content: [Use a registry command to install Microsoft 365 Insider on Windows devices - Microsoft 365 Insider](https://learn.microsoft.com/en-us/deployoffice/insider/deploy/registry)
* Content Source: [DeployOffice/insider/deploy/registry.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/insider/deploy/registry.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@tishalane  Thanks. We're glad it helped.
