### ISSUE TITLE
What happens when exclusion dates that go past Patch Tuesday?

### ISSUE THREAD

**Issue by cb7cb7** [MicrosoftDocs/OfficeDocs-DeployOffice#1248]
If an exclusion window were to take devices past the next patch tuesday, what would happen?
For example, using June 2023, if I had a 4 wave rollout with 5 days in between, the default wave would have started on July 3rd.
If a group of machines were targeted with an exclusion date range of July 1st to July 13th, would they get the June updates or the July updates? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d3986ef-1183-c725-1510-c30f415a535c
* Version Independent ID: 7d3986ef-1183-c725-1510-c30f415a535c
* Content: [Overview of servicing profile in the Microsoft 365 Apps admin center - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/admincenter/servicing-profile#set-update-exclusion-dates)
* Content Source: [DeployOffice/admincenter/servicing-profile.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/admincenter/servicing-profile.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @nicholasswhite
* Microsoft Alias: **nwhite**

**Comment by manoth-msft** [comment]
In above scenario the devices would not get any updates at all during the time specified. An Exclusion Window prevents any update commands to be sent to devices covered by the exclusion.

Technically, if an exclusion window is spanning across a Patch Tuesday, the Servicing Profile has the commands ready to update devices to version A (before Patch Tuesday) and version B (after Patch Tuesday), but does not send those commands down to devices as long as they are covered by the Exclusion window.

**Comment by cb7cb7** [comment]
Thank you, I should have clarified that I was looking for what happens right after the exclusion window ends. Which version would they try to patch to on July 14th? If others in their wave (4th wave +20 from Patch Tuesday) would not get patched until July 31st, would they get version A from July 14th to 31st or would they get Version B? If they would get version B in that time frame, would we then need to just apply a rollback to version A?

**Comment by manoth-msft** [comment]
At any given time, Servicing Profiles will move devices to the latest release of Monthly Enterprise (Rollback scenarios aside). So, any in-scope device which checks in before Patch Tuesday gets version A, any device checking in after Patch Tuesday gets version B. 

Same applies to devices which were subject to an exclusion window: Once they get online and sync with the service after the Exclusion Window has expired, those devices will go directly to then then-latest version, regardless of which version the device is currently on or has skipped in the mean time.

**Comment by cb7cb7** [comment]
Thank you!

**Comment by DHB-MSFT** [comment]
@manoth-msft   Thanks for helping with this.
