### ISSUE TITLE
Where is the Internet Based CDN for Office 2019 Professional Plus and Standard

### ISSUE THREAD

**Issue by philipjbailey** [MicrosoftDocs/OfficeDocs-DeployOffice#125]
Hi 
Having a problem installing Office 2019; The VLC only has a server install version at this time.  We have to create our own CDN (Content Delivery Network) on our private network server.  The ODT (Office Delivery Tool) Is then instructed to download the Click-And-Run Installation file from the Server Share.  The VLC ISO is the Server Installation file and this is the case for both Office Pro-Plus 2019 and Office Standard 2019. 

The documents state there is an internet based ODT, but try as I might, I cannot find it anywhere on the internet generally (Google or Bing Searches) or by searching either Git-hub or Microsoft.com.  The majority of the machines are stand-alone and not connected to our network server.

Can anybody point us to the internet based CDN?

**Comment by DHB-MSFT** [comment]
The Office Deployment Tool is available on the [Microsoft Download Center](https://www.microsoft.com/en-us/download/details.aspx?id=49117). If you don't include a [SourcePath](https://docs.microsoft.com/en-us/DeployOffice/configuration-options-for-the-office-2016-deployment-tool#sourcepath-attribute-part-of-add-element) in your configuration.xml file, the Office Deployment Tool will go to the Office Content Delivery Network (CDN) on the Internet to get the Office 2019 installation files.  The Office 2019 installation files aren't available on the Volume Licensing Service Center.  Hope that helps.
