### ISSUE TITLE
Link broken, can't download WebView2 runtime

### ISSUE THREAD

**Issue by lrsperanza** [MicrosoftDocs/OfficeDocs-DeployOffice#1252]
The following link is broken: https://developer.microsoft.com/microsoft-edge/webview2/#download-section
There is no other source to download WebView2 runtime from.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8ac95be-d5b8-b295-3003-fa5ce70dfb55
* Version Independent ID: d2acedb5-834c-8fa6-d917-7316e9bcda3d
* Content: [Microsoft Edge WebView2 and Microsoft 365 Apps - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/webview2-install#webview2-runtime-installation)
* Content Source: [DeployOffice/webview2-install.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/webview2-install.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@lrsperanza   Thanks for letting us know. We'll investigate.
