### ISSUE TITLE
Outdated page

### ISSUE THREAD

**Issue by ccccconnor** [MicrosoftDocs/OfficeDocs-DeployOffice#1257]
[Can you please update this page as the information on how to set these updates has now been outdated.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d23ac821-9cb8-8855-598f-d1327df04fac
* Version Independent ID: 78f2127a-0c6b-d236-a415-6215c582ce8b
* Content: [Change the Microsoft 365 Apps update channel for devices in your organization - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/updates/change-update-channels)
* Content Source: [DeployOffice/updates/change-update-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/updates/change-update-channels.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @nicholasswhite
* Microsoft Alias: **nwhite**

**Comment by DHB-MSFT** [comment]
@ccccconnor   Can you be more specific about what information in the article is outdated?
