### ISSUE TITLE
Add information tooltip about Servicing Profiles

### ISSUE THREAD

**Issue by Lewis-Barry** [MicrosoftDocs/OfficeDocs-DeployOffice#1260]
On page - https://learn.microsoft.com/en-gb/DeployOffice/other/coming-soon-to-microsoft-365-admin-center

It is announced that Servicing Profiles will no longer support Office channel switching, it would be useful to have a backlink or additional information listed on this page to state this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d23ac821-9cb8-8855-598f-d1327df04fac
* Version Independent ID: 78f2127a-0c6b-d236-a415-6215c582ce8b
* Content: [Change the Microsoft 365 Apps update channel for devices in your organization - Deploy Office](https://learn.microsoft.com/en-gb/DeployOffice/updates/change-update-channels)
* Content Source: [DeployOffice/updates/change-update-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/updates/change-update-channels.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @nicholasswhite
* Microsoft Alias: **nwhite**

**Comment by manoth-msft** [comment]
Hi @Lewis-Barry, we are planning to release a new feature into the Microsoft 365 Apps admin center which will allow admins to trigger channel changes on devices. We will update the article once the new feature is broadly available.
