### ISSUE TITLE
Never Mention XML Notepad

### ISSUE THREAD

**Issue by qwirk** [MicrosoftDocs/OfficeDocs-DeployOffice#127]
You never mention your XML notepad download.. needed to properly format the configuration file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [Deploy Office 2019 (for IT Pros)](https://docs.microsoft.com/en-us/DeployOffice/office2019/deploy)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Not sure what you're referring to by XML notepad download. I think you can use any xml editor as long as it creates a valid xml file. One test is whether you can open the xml file in Edge. If it doesn't display in Edge, it's not properly xml formatted. Although there still might be typos or other incorrect entries for the settings. We do have the [Office Customization Tool for Click-to-Run](https://config.office.com) which will help create your xml file, but it's currently in Preview and doesn't currently support Office 2019, but the product team is working on that.

**Comment by qwirk** [comment]
Thanks.

Nice tip on opening in edge.

I prefer not to use 3rd party editors as I am not sure if they are legit or not.  The MSFT XML Notepad worked great.  Have an item in answers.mcirosoft.com under "How to install Office 2019 VL"  that worked to install Office and Project in one pass.  Thanks

**Comment by DHB-MSFT** [comment]
Once the Office Customization Tool for Click-to-Run is out of Preview and supports Office 2019 we'll be updating all our deployment content to point people to use that since that's created & supported & updated by the product team. It's also the basis for part of the Office install wizard in Configuration Manager (Current Branch), and also Intune (if I'm not mistaken).
