### ISSUE TITLE
Group Policy? What is that? 😉

### ISSUE THREAD

**Issue by treestryder** [MicrosoftDocs/OfficeDocs-DeployOffice#1271]
Please add instructions for how to do this with Intune / MDM. I did not find "Use a device-based license for Microsoft 365 Apps for enterprise" in the Settings Catalog.

Thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e52eb9c1-1755-bec5-4ad8-6df59779e041
* Version Independent ID: 10e4cf5d-ea61-806e-f226-1e14265eabe1
* Content: [Device-based licensing for Microsoft 365 Apps for enterprise - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/device-based-licensing)
* Content Source: [DeployOffice/device-based-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/device-based-licensing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @nicholasswhite
* Microsoft Alias: **nwhite**

**Comment by manoth-msft** [comment]
The policy is available through creating a Configuration Profile:
Platform: Windows 10
Profile Type: Settings Catalog
Navigation Node: Microsoft Office 2016 (Machine) > Licensing Settings
Policy: Use a device-based license for Office 365 ProPlus

**Comment by treestryder** [comment]
Thank you. Not sure why I could not find that. I did look.
