### ISSUE TITLE
The Windows Server 2022 Support Lifecycle page link returns a 404

### ISSUE THREAD

**Issue by scarson** [MicrosoftDocs/OfficeDocs-DeployOffice#1272]
This is about an important support lifecycle page Office Docs links to that's broken, not Office Docs itself, but I don't know where else to report this issue. This was the first working recommended docs link from the 404 page. The other /lifecycle/products/windows-server-20XX pages don't have a feedback or report an issue link. Hopefully someone at Microsoft can direct this to the right team. 

I've verified that I receive the same 404 from machines in multiple different U.S.-based data centers.

![image](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/assets/9357767/f72f2e3a-793c-487a-9481-07d68f29feea)

The Windows Server 2022 sections includes:

> For end of support dates for Windows Server 2022, see the [Windows Server 2022 lifecycle](https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2022) page.

This link returns a 404:
https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2022

The structurally identical 2019 and 2016 links do not:
https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2019
https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2016

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 35e85436-141e-3d54-7743-365fba243861
* Version Independent ID: c9afa702-9001-e0cb-3508-ab4b0d97cd46
* Content: [Windows Server end of support and Microsoft 365 Apps - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/endofsupport/windows-server-support)
* Content Source: [DeployOffice/endofsupport/windows-server-support.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/endofsupport/windows-server-support.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @nicholasswhite
* Microsoft Alias: **nwhite**

**Comment by DHB-MSFT** [comment]
@scarson Thanks for bringing that to our attention. We're investigating.

**Comment by stdin82** [comment]
The link now redirect to /windows-server-2022-annual-channel which don't exist either

whereas the annual channel link is
https://learn.microsoft.com/en-us/lifecycle/products/windows-server-annual-channel

**Comment by DHB-MSFT** [comment]
We're waiting to hear back from the team that publishes the lifecycle pages to find out what happened to the Windows Server 2022 page that used to be available.

**Comment by stdin82** [comment]
/windows-server-2022 is now working, but the content is for Windows Server Annual Channel, not Server 2022 LTSC :grinning:

**Comment by DHB-MSFT** [comment]
Yes, we're aware of that. We're in contact with the team that owns that page trying to get the issue resolved.

**Comment by stdin82** [comment]
It's fixed at last
https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2022
https://learn.microsoft.com/en-us/lifecycle/products/windows-server-annual-channel

**Comment by DHB-MSFT** [comment]
Closing. Issue fixed.
