### ISSUE TITLE
Identifiers for the new Teams apps Team classic and Teams (work or school)

### ISSUE THREAD

**Issue by c3474** [MicrosoftDocs/OfficeDocs-DeployOffice#1273]
Is the Team app identifier the same for the new Teams apps? I believe the new Teams apps are called "Microsoft Teams classic" and "Microsoft Teams (work or school)"
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59e840a0-92ac-3ba4-75b3-01a154d67899
* Version Independent ID: 8f7fd243-8f3a-7d32-8433-03b8167aee6f
* Content: [Update Microsoft applications for Mac by using msupdate - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/mac/update-office-for-mac-using-msupdate)
* Content Source: [DeployOffice/mac/update-office-for-mac-using-msupdate.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/mac/update-office-for-mac-using-msupdate.md)
* Service: **o365-proplus-itpro**
* Sub-service: **office-mac**
* GitHub Login: @pbowden-msft
* Microsoft Alias: **pbowden**

**Comment by pbowden-msft** [comment]
@c3474 great question! I just submitted a doc update that should be live later on today. The quick answer is that Teams 1.0 classic will use TEAMS10, and the new Teams 2.1 client uses TEAMS21
