### ISSUE TITLE
Instructions are not valid

### ISSUE THREAD

**Issue by giterdn** [MicrosoftDocs/OfficeDocs-DeployOffice#1279]
This page indicates to go to VLSC and that is incorrect. The correct place to go is Microsoft 365 admin console. Even there I can no longer find the serializer. It just says “this product does not require a product key”

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce6cb9d5-64d9-7af7-2d76-5c2f59c937f3
* Version Independent ID: fd6afd70-cce9-8296-9d73-fb366a069ee2
* Content: [Overview of the Volume License (VL) Serializer - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/mac/volume-license-serializer)
* Content Source: [DeployOffice/mac/volume-license-serializer.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/mac/volume-license-serializer.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @pbowden-msft
* Microsoft Alias: **pbowden**

**Comment by pbowden-msft** [comment]
@giterdn For the VL Serializer, the only place to obtain this is the VLSC, so the link is correct.
