### ISSUE TITLE
This doc needs update on "initialize a channel change" part

### ISSUE THREAD

**Issue by howardzhangmsft** [MicrosoftDocs/OfficeDocs-DeployOffice#1284]
In this doc, the instructions to initialize a channel change are ambiguous.
Please refer to this article for actionable steps 
https://learn.microsoft.com/en-us/deployoffice/updates/change-channel-for-copilot#cloud-update

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d47d9510-b359-0235-3f50-cd6ddd26d056
* Version Independent ID: d47d9510-b359-0235-3f50-cd6ddd26d056
* Content: [Copilot - Move a subset of devices to Current Channel with Servicing Profile - Deploy Office](https://learn.microsoft.com/en-us/DeployOffice/updates/move-devices-channel-servicingprofiles)
* Content Source: [DeployOffice/updates/move-devices-channel-servicingprofiles.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/updates/move-devices-channel-servicingprofiles.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @manoth-msft
* Microsoft Alias: **manoth**

**Comment by manoth-msft** [comment]
Hi Howard, thanks for your feedback. The article on Servicing Profiles will be retired soon. Then the article you linked will be the solely source for switching channels for Copilot scenarios.

**Comment by howardzhangmsft** [comment]
[like]  Howard Zhang reacted to your message:
________________________________
