### ISSUE TITLE
wrong registry key for updatebranch

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#1287]
1. for Current Channel (Preview).
 updatebranch  data should be  **FirstReleaseCurrent**

2. for Beta Channel.
 updatebranch  data should be  **InsiderFast**

registry key proofs
![Screenshot 2023-11-26 165918](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/assets/3296790/0393ebc4-f586-4139-8cbe-9d887125b064)
![Screenshot 2023-11-26 165954](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/assets/3296790/23f81f0e-d9dd-4f6a-a929-2a4d0ef2aadc)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3437d6c-4600-9ba3-4214-37d45f304e4c
* Version Independent ID: f3437d6c-4600-9ba3-4214-37d45f304e4c
* Content: [Use a registry command to install Microsoft 365 Insider on Windows devices - Microsoft 365 Insider](https://learn.microsoft.com/en-us/deployoffice/insider/deploy/registry)
* Content Source: [DeployOffice/insider/deploy/registry.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/insider/deploy/registry.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @nicholasswhite
* Microsoft Alias: **nwhite**

**Comment by RAJU2529** [comment]
@nicholasswhite , Can i create PR to fix this issue ?

**Comment by DHB-MSFT** [comment]
@RAJU2529   The registry keys listed in the article are correct. Those are the most current values. The update channels have been renamed over the years. The values you are referring to are older names, but are still valid, for backwards compatibility. But we prefer if customers use the newer values. Please don't submit a PR. Thanks.

**Comment by RAJU2529** [comment]
@DHB-MSFT , But I used the group policy editor on Windows 11 22635.2771 insider preview , so that above mentioned values are created in registry

**Comment by DHB-MSFT** [comment]
@RAJU2529   Group Policy probably was never updated for the new value. The registry keys listed in the article are correct and the values we prefer customers use. And the value Group Policy set also work.
