### ISSUE TITLE
 configuration support matrix (PDF) url changed

### ISSUE THREAD

**Issue by stdin82** [MicrosoftDocs/OfficeDocs-DeployOffice#1289]
The Windows and Office configuration matrix has moved. Please visit https://aka.ms/windows-office-support-matrix 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 35e85436-141e-3d54-7743-365fba243861
* Version Independent ID: c9afa702-9001-e0cb-3508-ab4b0d97cd46
* Content: [Windows Server end of support and Microsoft 365 Apps - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/endofsupport/windows-server-support)
* Content Source: [DeployOffice/endofsupport/windows-server-support.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/endofsupport/windows-server-support.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @nicholasswhite
* Microsoft Alias: **nwhite**

**Comment by DHB-MSFT** [comment]
@stdin82   Thanks for letting us know about this change of location. We'll update the link in this article and other places in our deployment content where we link to the support matrix.

**Comment by DHB-MSFT** [comment]
@stdin82   Thanks again for letting us know about this change. We've updated the link in this article and other articles where we link to the matrix.
