### ISSUE TITLE
No mention of ProductID:LanguagePack to deploy language Packs

### ISSUE THREAD

**Issue by TheBaban** [MicrosoftDocs/OfficeDocs-DeployOffice#129]
We where able in the past to use ProductID="LanguagePack" to deploy new languages. This was a conveniant way to add the languages to all C2R products without the need to specify the product exclusion used when we deployed OfficeProPlusRetail.
Do we remove this option, meaning we cannot use any more ProductID="LanguagePack" ?
Or do you just forget to mention it in the article "Overview of deploying languages in Office 365 ProPlus"?

**Comment by jwhit-MSFT** [comment]
Thanks for the feedback--I'll look into this and let you know.

**Comment by jwhit-MSFT** [comment]
This feature was included in the Overview of the Office Deployment Tool, but you're right that it wasn't included in the language overview (which is the first place someone would look). I just added it--thanks for the catch. https://docs.microsoft.com/en-us/deployoffice/overview-of-deploying-languages-in-office-365-proplus?branch=master#add-languages-to-existing-installations-of-office-365-proplus

**Comment by TheBaban** [comment]
Thank you. Impressive fast answer 😉

De : J Whitmarsh <notifications@github.com>
Envoyé : mardi 16 octobre 2018 00:14
À : MicrosoftDocs/OfficeDocs-DeployOffice <OfficeDocs-DeployOffice@noreply.github.com>
Cc : TheBaban <thebaban@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [MicrosoftDocs/OfficeDocs-DeployOffice] No mention of ProductID:LanguagePack to deploy language Packs (#129)


This feature was included in the Overview of the Office Deployment Tool, but you're right that it wasn't included in the language overview (which is the first place someone would look). I just added it--thanks for the catch. https://docs.microsoft.com/en-us/deployoffice/overview-of-deploying-languages-in-office-365-proplus?branch=master#add-languages-to-existing-installations-of-office-365-proplus<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdeployoffice%2Foverview-of-deploying-languages-in-office-365-proplus%3Fbranch%3Dmaster%23add-languages-to-existing-installations-of-office-365-proplus&data=02%7C01%7C%7Cd06b5c90b4bb46d64aa508d632eb7de0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636752384340472386&sdata=zJULZrnKBSV2Y6hxCaoDAIlCEonyvJBvf9498a7H2QI%3D&reserved=0>
