### ISSUE TITLE
Unable to install VL Visio along side Office 365

### ISSUE THREAD

**Issue by ckelsoe** [MicrosoftDocs/OfficeDocs-DeployOffice#13]
Typical Microsoft shit - Our company has Office 365 and I have Office 365 Pro Plus installed. I also need Visio which our company has volume licensing for. Microsoft blocks this install. Followed the instructions for the Office Deployment Tool (https://docs.microsoft.com/en-us/DeployOffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016?ui=en-US&rs=en-US&ad=US). It does not work.  Why does Microsoft have to make their products not work together? 

I am getting either 30029-1007 or 30016-25 with the options documented on the link above.

**Comment by DHB-MSFT** [comment]
The 30029-1007 error means there was an invalid argument, and the 30016-25 error means downloading Office failed. Likely issue is an error in the configuration.xml file, so you'll want to double-check your xml file.

**Comment by ckelsoe** [comment]
Thanks. I finally go this working. I still do not understand why MS chooses to make this type of deployment so difficult to achieve.

**Comment by DHB-MSFT** [comment]
I'm glad to hear you got this to work. I have forwarded your feedback to the team that owns this area.
