### ISSUE TITLE
I can't enter my Project Standard 2016 license

### ISSUE THREAD

**Issue by manuelgaytan** [MicrosoftDocs/OfficeDocs-DeployOffice#130]
Hi,

I have a license of Microsoft Project Standard 2016 when I tried to install, the system said me something like that "You have office 365, please install Office Deployment Tool". I install Project Standard 2016 with Office Deployment Tool (ProjectStdXVolume), but when I enter key product it says me "This product key is for the volume-licensed version Microsoft Project Standard 2016, which isn't currently installed...". The about of Project says: Microsoft Project 2016 MSO Product ID: 00368-80000-00000-AA915.

Thanks in advance for your responses.

**Comment by DHB-MSFT** [comment]
@manuelgaytan -- how did you purchase Project Standard 2016?  Did you buy it through a retail store or through volume licensing?  If you are using volume licensing, you'd be getting your product key from the [Volume Licensing Service Center](https://www.microsoft.com/Licensing/servicecenter/default.aspx). If you purchased through a retail store, you can't use ProjectStdXVolume. That can only be used for volume licensed versions.

If you're still having problems, you might want to post your questions to the [Answers forum](https://answers.microsoft.com/) or the Tech Community(https://techcommunity.microsoft.com/). More people are on those sites and you will probably get a faster response/answer. Or you can always contact [Microsoft Support](https://support.microsoft.com/contactus). 

Thanks.
