### ISSUE TITLE
confusion in regsistry path 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#132]
when we  set  
&lt;User Key="software\microsoft\office\16.0\excel\security"
          Name="vbawarnings" 
          Value="3" 
          Type="REG_DWORD" 
          App="excel16" 
          Id="L_VBAWarningsPolicy" /&gt;

above  configuration in a configuration.xml file, after successful installation of office suite, actually  in which registry key  is  added  in the registry 

there are two paths namely 
HKEY_CURRENT_USER\Software\Microsoft\Office\Excel
or
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\Excel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66127c02-c2dc-f6d1-6e83-a6d2b1166731
* Version Independent ID: 27635315-22db-d136-f07e-5169f6207b50
* Content: [Overview of the Office Deployment Tool](https://docs.microsoft.com/en-us/deployoffice/overview-of-the-office-2016-deployment-tool)
* Content Source: [DeployOffice/overview-of-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by chhopkin** [comment]
when you use config.office.com to include application settings in your configuration file, these application settings are written to the User hive.  In your example, vbawarnings is set to the value of 3 at HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Excel\Security.
