### ISSUE TITLE
windows 10 does not support ?

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#133]
except windows 10 ,all other operating systems  are supported 
Windows 7, Windows Vista, Windows Server 2012, Windows Server 2012 R2, Windows Server 2008 and Windows Server 2008 R2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 047d2b74-e963-a006-cb74-29257c409647
* Version Independent ID: 4f274c79-18ae-2c36-19a3-cfb73d7e6cf3
* Content: [Privacy options in Office 2016](https://docs.microsoft.com/en-us/deployoffice/security/privacy-options-in-office)
* Content Source: [DeployOffice/security/privacy-options-in-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/privacy-options-in-office.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Yes, it should work the same way for Windows 10. I'll get the content updated. Thanks for your comment/feedback.

**Comment by DHB-MSFT** [comment]
I updated the topic. I actually removed all the specific operating system version references since they weren't that important.
