### ISSUE TITLE
help me to add regsirty settings

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#134]
i have  office 2016  pro plus  including visio pro and  project pro  products
Please give security setting for VBA warnings  in the  registry settings.
example  excel 2016 , word 2016 , powerpoint 2016 , publisher 2016 , project 2016 , visio 2016 , outlook 2016 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c1ecec1-9305-e786-eb31-f820b682d90d
* Version Independent ID: 14d63999-303f-2092-07cb-e8554a297a30
* Content: [Plan security settings for VBA macros in Office 2016](https://docs.microsoft.com/en-us/deployoffice/security/plan-security-settings-for-vba-macros-in-office)
* Content Source: [DeployOffice/security/plan-security-settings-for-vba-macros-in-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/plan-security-settings-for-vba-macros-in-office.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Are you asking what the registry settings are for these settings? We usually don't recommend editing the registry directly if there is a Group Policy setting that does the equivalent.  If you are interested in the registry settings that are set by Group Policy, look at the office2016grouppolicyandoctsettings.xlsx file that comes with the Group Policy Administrative Template file (ADXM/ADML) download on the [Microsoft Download Center](https://www.microsoft.com/en-us/download/details.aspx?id=49030).

**Comment by RAJU2529** [comment]
yes sir I have already downloaded office 2016 group policy templates and I added in policy definition folder, then I found vba security settings in gpo, I enabled above problems and then updated via cmd, those respective settings are added in registry keys. same I exported and I added in configuration.xml file
