### ISSUE TITLE
Does this supports office 2016 ?

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#138]
This article  gives information only  configure office 365 pro plus products only.
Many of the users using  office 2013 , 2016 home and student products only , But few users are using  office 2016 professional plus .
So please add the instructions how  to configure office 2016 products . 

Thanks to authors 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a0b1ff-0498-505a-6024-b813980d310f
* Version Independent ID: b8057930-b4bd-1304-17ce-5561f837e901
* Content: [Configuration options for the Office Deployment Tool](https://docs.microsoft.com/en-us/deployoffice/configuration-options-for-the-office-2016-deployment-tool#language-element)
* Content Source: [DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by DHB-MSFT** [comment]
This content is aimed at IT Pros/admins who are deploying Office in the enterprise. We don't expect/want home users to be using the Office Deployment Tool to be installing Office. As for Office Professional Plus 2016, it uses Windows Installer (MSI) as the installation technology so this article doesn't apply.

**Comment by RAJU2529** [comment]
i am using office 2016 pro plus with click to run installed apps. moreover Microsoft stopped.msi file installer, so this article may also be usefull to home users also

**Comment by DHB-MSFT** [comment]
My understanding is that Office Professional Plus 2016 is available in a Click-to-Run format, either through an MSDN subscription program or Home Use Program. It is also available via MSI to volume licensed customers. But there's probably very little reason home users would need to use the Office Deployment Tool to configure their installation and in most cases, this content will be more confusing than helpful for home users.  Thanks for your comment/feedback but we have no plans to include Office 2016 retail information to this article.

**Comment by RAJU2529** [comment]
I hope, Microsoft will include for office 2016and 2019 retails configuration files in future.

Sir yesterday I comfigured.xml for office 2016 products and I have successfully downloaded setup files.

if you like to verify means, I share that file to you.

Thanks sir

**Comment by rfevrier** [comment]
Greetings!

I am desperately trying to download and install Office 2016 on CrossOver on my Mac and I can't seem to configure the config.xml file to download (let alone install) the right files.  When I run setup.exe /download config.xml using this setting in the xml file nothing happens.  

<Configuration>
  <Add OfficeClientEdition="32"  Channel="Monthly" Version="16.0.8201.2193">
    <Product ID="O365BusinessRetail">
      <Language ID="en-us" />
    </Product>
  </Add>  
</Configuration>

The version seems to be the issue cause the download works once I remove the version tag.  Can anybody tell me what I am doing wrong?

Regards.
