### ISSUE TITLE
Please add office 2016 suites

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#139]
please add configurations to create office 2016 suites for retail versions  in 
https://config.office.com/
This will be  much useful for  all the users 
Thanks a lot , I am waiting for  new configurations 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a0b1ff-0498-505a-6024-b813980d310f
* Version Independent ID: b8057930-b4bd-1304-17ce-5561f837e901
* Content: [Configuration options for the Office Deployment Tool](https://docs.microsoft.com/en-us/deployoffice/configuration-options-for-the-office-2016-deployment-tool#language-element)
* Content Source: [DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by RAJU2529** [comment]
I agree with your words. but think once about other than enterprise customers also. many users also using office 2016 retail version.
thanking you

**Comment by DHB-MSFT** [comment]
We provide installation guidance for customers (end users/consumers/home users/small businesses) using retail versions of Office on [https://suppport.office.com](https://suppport.office.com) and that info is targeted at their needs. In most cases, retail customers have no need to use the Office Deployment Tool and this content would probably be more confusing than helpful for that audience. Thanks for your comment/feedback.
