### ISSUE TITLE
Couldn't install Skype for Business 2019

### ISSUE THREAD

**Issue by billyoungs** [MicrosoftDocs/OfficeDocs-DeployOffice#141]
How strange. I use the config xml to install Skype for Business 2019. Always failed. Could you take a look?
&lt;Configuration&gt;
  &lt;Add OfficeClientEdition="64"&gt;
    &lt;Product ID="Lync"&gt;
      &lt;Language ID="en-us" /&gt;
    &lt;/Product&gt;
  &lt;/Add&gt;
&lt;Updates Enabled="TRUE" /&gt;
&lt;Display AcceptEULA="TRUE" /&gt;
&lt;Property Name="AUTOACTIVATE" Value="1" /&gt;
&lt;/Configuration&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a0b1ff-0498-505a-6024-b813980d310f
* Version Independent ID: b8057930-b4bd-1304-17ce-5561f837e901
* Content: [Configuration options for the Office Deployment Tool](https://docs.microsoft.com/en-us/DeployOffice/configuration-options-for-the-office-2016-deployment-tool)
* Content Source: [DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by DHB-MSFT** [comment]
I don't think Lync is the correct Product ID to use in your xml file.  Go to [Product IDs that are supported by the Office Deployment Tool](https://support.microsoft.com/en-us/help/2842297/product-ids-that-are-supported-by-the-office-deployment-tool-for-click) and scroll to the bottom of the article. That lists the IDs to use for Skype for Business 2019. Hope that helps.

**Comment by RAJU2529** [comment]
Mr Bilyoungs  ,what error message you getting , will you please upload screenshot of error.
I think Lync.exe is aapplication and part of  office suites.
so you must include any one of the office suites as primary product id.

for example i used configured.xml included office2016pro plus with visio and project
products.

here is my configuration files

https://1drv.ms/u/s!AmZoRRusRV59lGktbjsyzDzQvWU0

**Comment by DHB-MSFT** [comment]
@RAJU2529 -- you don't have to specify a suite as the product ID to get Skype for Business 2019 installed. Skype can be purchased and installed separately from Office. Since the original poster closed the issue, I'm presuming my answer solved his issue.
