### ISSUE TITLE
Shared Activation Issue

### ISSUE THREAD

**Issue by AndyH16** [MicrosoftDocs/OfficeDocs-DeployOffice#142]
I have followed the guide and set up a group policy which applies the setting to our hot desk PCs. This works and Word, etc show up the Shared Computer Activation message in About.

However, as we did this after deploying 365 some of these hot desks were activated using staff licenses (Office 365 Pro). Once these licenses expire it doesn't switch to shared licensing and remains unlicensed. Various error messages such as 0xc004e022 and 0x80004005 pop up when trying to update through the About menu.

I have found how to fix this by using the OSPP.VBS file to remove the listed license. Launching the software then puts it into shared activation and the two text files appears in the %localappdata%\Microsoft\Office\16.0\Licensing location.

Is the software not intelligent enough to know when it has the shared license registry setting it should override any license that it's previously picked up?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e327cac6-ceac-fa8b-18ce-7312023a4acb
* Version Independent ID: b8006cfe-a158-0ef4-075c-089329094333
* Content: [Troubleshoot issues with shared computer activation for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/troubleshoot-issues-with-shared-computer-activation-for-office-365-proplus#Enabled)
* Content Source: [DeployOffice/troubleshoot-issues-with-shared-computer-activation-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/troubleshoot-issues-with-shared-computer-activation-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@AndyH16 -- yes, that's a known issue with the Group Policy that the product team is working to fix. I'll update the documentation to cover what you need to do in these situations. Thanks for the feedback.

**Comment by darrenlinsdell** [comment]
Is there a fix to this issue yet? how can you close an issue without providing the fix?

**Comment by e-tang** [comment]
I don't think it got fixed yet.

**Comment by v-wayu** [comment]
When will this KB be updated?
