### ISSUE TITLE
Readiness tool  Really not supported on office 2016 ?

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#144]
readiness tool does not suported  on office 2016 , just now id downloaded that tool , i installed on C2R office 2016pro plus ,  
This article  must be concentrate only for office 2016, and not previous versions , not  office 365.
Sorry for my bad feedback

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11e62908-a374-7cd0-e7d9-2886a54d7ce9
* Version Independent ID: 165e940a-6802-237d-08e9-5d2589e4d98f
* Content: [Compatibility and telemetry in Office](https://docs.microsoft.com/en-us/DeployOffice/compat/compatibility-and-telemetry-in-office?toc=/deployoffice/office2016/toc.json)
* Content Source: [DeployOffice/compat/compatibility-and-telemetry-in-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/compat/compatibility-and-telemetry-in-office.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Yes, you can install and run the Readiness Toolkit on a computer running Office 2016. But the primary purpose of the Readiness Toolkit is to help organizations determine if they're ready to move to Office 365 ProPlus from an earlier version of Office.
