### ISSUE TITLE
Please include support windows 10 on verify VBA signatutes 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#146]
Today i tried to enable security setting in gpo under
User Configuration\Administrative Templates\Microsoft Office 2016\Security Settings\Trust Center

policy setting is "set the minimum operating system for verifying agile VBA signatures", i tried to enable , but windows 10 os option is not available ,but only Four os are there namely:
windows xp 
windows vista
windows 7
windows 8

Thanking  you for your content 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 047d2b74-e963-a006-cb74-29257c409647
* Version Independent ID: 4f274c79-18ae-2c36-19a3-cfb73d7e6cf3
* Content: [Privacy options in Office 2016](https://docs.microsoft.com/en-us/deployoffice/security/privacy-options-in-office?toc=/deployoffice/office2016/toc.json)
* Content Source: [DeployOffice/security/privacy-options-in-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/privacy-options-in-office.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
I'm investigating/checking.

**Comment by manoth-msft** [comment]
I will close this issue as it is not directly related to a documentation issue. Feel free to post to TechCommunity on any issues.
