### ISSUE TITLE
Sir please give advise

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#147]
Sir  today i come to seen new policy named  DLP  which is located under
User Configuration\Administrative Templates\Microsoft Office 2016\DLP

I searched DLP on google it says Data Loss Protection , i am uisng office 2016 pro plus , What will happend if i enable DLP  , DLP execute on applications boots .

Which are the applications are protected by DLP in office products ?

PLease dont feel bad because i am sasking many questions to you sir , basically i am Teacher in pu college and teaching  Higher mathematics , so i love to ask questions and get solutions 

Thanking you for your content sir

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 047d2b74-e963-a006-cb74-29257c409647
* Version Independent ID: 4f274c79-18ae-2c36-19a3-cfb73d7e6cf3
* Content: [Privacy options in Office 2016](https://docs.microsoft.com/en-us/deployoffice/security/privacy-options-in-office?toc=/deployoffice/office2016/toc.json)
* Content Source: [DeployOffice/security/privacy-options-in-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/privacy-options-in-office.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
I'm not sure what that policy setting does. You might want to post your question on the [Answers forum](https://answers.microsoft.com/) or the [Tech Community](https://techcommunity.microsoft.com/). More people are on those sites and someone there might be able to answer your question.
