### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by greenchevy65** [MicrosoftDocs/OfficeDocs-DeployOffice#148]
Broken Link to InfoPath 2013 (32-bit and 64-bit versions)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ae73873-0e39-3fab-4d9d-3129f7f32345
* Version Independent ID: 3b5ba9ae-756a-149d-81e6-5eda13bf15e6
* Content: [Manage software download settings in Office 365](https://docs.microsoft.com/en-us/DeployOffice/manage-software-download-settings-office-365)
* Content Source: [DeployOffice/manage-software-download-settings-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/manage-software-download-settings-office-365.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
The link is working for me. Might have been a temporary connectivity issue.
