### ISSUE TITLE
Need comprehensive reference for config file

### ISSUE THREAD

**Issue by FC-EricWeller** [MicrosoftDocs/OfficeDocs-DeployOffice#149]
This document provides "Example of a standard configuration file".   It would help if it included links to a comprehensive reference for each element.  For example, the &lt;Add&gt; element is incompletely documented, nor is there a reference linked for available Properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a0b1ff-0498-505a-6024-b813980d310f
* Version Independent ID: b8057930-b4bd-1304-17ce-5561f837e901
* Content: [Configuration options for the Office Deployment Tool](https://docs.microsoft.com/en-us/deployoffice/configuration-options-for-the-office-2016-deployment-tool#add-element)
* Content Source: [DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by RAJU2529** [comment]
here is the configuration files with ODT , sample configuration.xml is modified by me and i included some settings to protect VBA macro settings , also included to download  office 2016 pro plus , visio 2016 pro and project 2016 pro   retail versions 

i havd uploaded files via onedrive  here is the link
https://1drv.ms/u/s!AmZoRRusRV59lGktbjsyzDzQvWU0

**Comment by jwhit-MSFT** [comment]
Hi Eric--Thanks for the feedback. We do try to document all the elements and attributes in the configuration options article, though it's entirely possible we need to add something. Can you clarify what's missing from the Add element?

**Comment by FC-EricWeller** [comment]
Well, ForceUpgrade is the particular part that I was looking for.  I saw something on The Internets that reference a ForceDowngrade command (may not have been that exact verb), but I don’t actually know that it’s a thing….which is why I was looking for a comprehensive list.


Eric F. Weller, IS Applications Manager
300 S. Fourth Street, Suite 1400, Las Vegas, NV 89101
T:702.692.8060
eweller@fclaw.com




PLEASE NOTE:  Effective August 1st, 2018, Fennemore Craig's suite number has changed to Suite 1010.  Our street address, telephone number, fax number and email address remain the same  Thank you for updating your records!


CONFIDENTIALITY NOTICE:
The information contained in this message may be protected by the attorney-client privilege. 
If you believe that it has been sent to you in error, do not read it. Please immediately reply 
to the sender that you have received the message in error. Then delete it. 
Thank you.

**Comment by DHB-MSFT** [comment]
We removed ForceUpgrade from the article because it was for a particular scenario that wasn't really relevant anymore and might have caused confused with newer scenarios. The scenario was upgrading from the 2013 version to the 2016 version of Office 365 ProPlus. But we haven't supported the 2013 version of Office 365 ProPlus since February 2017.  Hope that helps.

**Comment by FC-EricWeller** [comment]
Ah I see.  Alright then, shall we presume that the example provided here IS in fact comprehensive then?


Eric F. Weller, IS Applications Manager
300 S. Fourth Street, Suite 1400, Las Vegas, NV 89101
T:702.692.8060
eweller@fclaw.com




PLEASE NOTE:  Effective August 1st, 2018, Fennemore Craig's suite number has changed to Suite 1010.  Our street address, telephone number, fax number and email address remain the same  Thank you for updating your records!


CONFIDENTIALITY NOTICE:
The information contained in this message may be protected by the attorney-client privilege. 
If you believe that it has been sent to you in error, do not read it. Please immediately reply 
to the sender that you have received the message in error. Then delete it. 
Thank you.

**Comment by jwhit-MSFT** [comment]
The article should cover everything; the specific example of a configuration file only has commonly used examples. One thing to add: we just announced the release of the [Office Customization Tool](https://config.office.com/), which lets you create these configuration files with a web-based interface.
