### ISSUE TITLE
This article needs links for change scenarios

### ISSUE THREAD

**Issue by FC-EricWeller** [MicrosoftDocs/OfficeDocs-DeployOffice#150]
It would be helpful for this article to include a discussion of supported means for changing release channels, and in particular from newer releases to older ones (perhaps on a different channel).  It's a very likely failure scenario to be on a monthly channel and discover that a release has an issue with your environment.  You'd want to be able to roll back to an earlier release and, depending on the issue and how long it would take to resolve, you may need to change some users to a semi-monthly channel to continue receiving security updates until the issue is resolved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cd85e3b-e780-457e-9502-856bc6315bca
* Version Independent ID: 416e351f-13c5-e951-ea81-1650910a7c25
* Content: [Overview of update channels for Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/overview-of-update-channels-for-office-365-proplus?redirectSourcePath=%252fen-us%252farticle%252f9ccf0f13-28ff-4975-9bd2-7e4ea2fefef4)
* Content Source: [DeployOffice/overview-of-update-channels-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-update-channels-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by Derek52** [comment]
I have begun working on an edit to this wiki page, and will submit a PR shortly.

**Comment by DHB-MSFT** [comment]
We're working on a new article to cover switching channels and/or rolling back to a previous build of the same channel. I'll re-open/reply to this issue when we get that article published.  Thanks.

**Comment by FC-EricWeller** [comment]
FWIW, it looks to me in trying to work it out on my own that so long as I change the update channel to match the version I’m deploying (using GP, registry, whatever), I can move back and forth through any currently available monthly, semi-annual, or targeted build with absolutely no issues.


Eric F. Weller, IS Applications Manager
300 S. Fourth Street, Suite 1400, Las Vegas, NV 89101
T:702.692.8060
eweller@fclaw.com




PLEASE NOTE:  Effective August 1st, 2018, Fennemore Craig's suite number has changed to Suite 1010.  Our street address, telephone number, fax number and email address remain the same  Thank you for updating your records!


CONFIDENTIALITY NOTICE:
The information contained in this message may be protected by the attorney-client privilege. 
If you believe that it has been sent to you in error, do not read it. Please immediately reply 
to the sender that you have received the message in error. Then delete it. 
Thank you.

**Comment by DHB-MSFT** [comment]
Are you configured to get updates directly from the internet? If so, yes, that usually is simpler. More complicated if you're getting updates from a network share within your organization. Also simpler if you are specifying a particular version/build, not just specifying a channel. At least that's my current understanding but I'm getting that verified. Nonetheless, more documentation on this scenario has been a common request so we're currently working on that.  Thanks.

**Comment by FC-EricWeller** [comment]
In answer to your question, updates come from WSUS or SCCM depending on the client workstation.


Eric F. Weller, IS Applications Manager
300 S. Fourth Street, Suite 1400, Las Vegas, NV 89101
T:702.692.8060
eweller@fclaw.com




PLEASE NOTE:  Effective August 1st, 2018, Fennemore Craig's suite number has changed to Suite 1010.  Our street address, telephone number, fax number and email address remain the same  Thank you for updating your records!


CONFIDENTIALITY NOTICE:
The information contained in this message may be protected by the attorney-client privilege. 
If you believe that it has been sent to you in error, do not read it. Please immediately reply 
to the sender that you have received the message in error. Then delete it. 
Thank you.
