### ISSUE TITLE
Is DocRecrypt tool  Compatible with office 2016 ?

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#153]
just now I downloaded docRecrypt tool from the website
 https://www.microsoft.com/en-us/download/details.aspx?id=36443

Is really docrecrypt tool compatible with office 2016?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28b7982b-5e7c-0678-8919-10d4147f3525
* Version Independent ID: 16bd8605-ed8a-234d-0ed7-cac3c1745b35
* Content: [Remove or reset file passwords in Office 2016](https://docs.microsoft.com/en-us/deployoffice/security/remove-or-reset-file-passwords-in-office)
* Content Source: [DeployOffice/security/remove-or-reset-file-passwords-in-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/remove-or-reset-file-passwords-in-office.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
I'm investigating/checking.

**Comment by tang607** [comment]
Hi, is there any update regarding the compatibility of the DocRecrypt tool with Office 2016?

**Comment by tang607** [comment]
I have tried and DocRecrypt can work with Office 2016.
