### ISSUE TITLE
how to  remove password from document 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#154]
For example , 
I  have password protected document in C:\documents\myfile.doc
and the required tool also
what command to run cmd , to remove password , could you tell me , below cmd is correct or not 
DocRecrypt.exe  C:\documents\myfile.doc -i lockedfile

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28b7982b-5e7c-0678-8919-10d4147f3525
* Version Independent ID: 16bd8605-ed8a-234d-0ed7-cac3c1745b35
* Content: [Remove or reset file passwords in Office 2016](https://docs.microsoft.com/en-us/deployoffice/security/remove-or-reset-file-passwords-in-office)
* Content Source: [DeployOffice/security/remove-or-reset-file-passwords-in-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/remove-or-reset-file-passwords-in-office.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
I think the correct command would be DocRecrypt.exe  -i C:\documents\myfile.doc.  "Lockedfile" was just an example file name. Sorry if that wasn't clear in the article.

**Comment by RAJU2529** [comment]
sorry sir , i received  th error
 Error: Error_NoCertToUse Last Result: 0x80004005

i have  created   mydoc.docx  using word2016 with protected password "72848472"
i added mydoc.docx to  C:\Users\RAJU\Documents\


i download docrecrypt tool and installed  , it installed in location
C:\Program Files (x86)\Microsoft Office\DOCRECRYPT\DOCRECRYPT.exe

after wards i added  digital signature certificate hash in registry 
[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common\Security\Crypto\EscrowCerts]
"escrowcert01"="bbd20ccabf3780ad15880d30343eddb7"
"escrowcert02"="a43489159a520f0d93d032ccaf37e7fe20a8b419"

"bbd20ccabf3780ad15880d30343eddb7" is my digital signature certificate hash value.
"a43489159a520f0d93d032ccaf37e7fe20a8b419" is thumbprint of microsft root authority sertificate.

then i entered below commands  with administrator rights on cmd

cd /d C:\Program Files (x86)\Microsoft Office\DOCRECRYPT\
DOCRECRYPT.exe -i C:\Users\RAJU\Documents\mydoc.docx

i have attached screenshots

**Comment by jwhit-MSFT** [comment]
I recommend following up with [support or in the forums ](https://docs.microsoft.com/DeployOffice/feedback#get-support-for-problems-with-office)for this issue--thanks.
