### ISSUE TITLE
some doubt on particular sentence

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#155]
And I had  doubt  on this  sentence " Once files are password protected using Office 2016, will not remove the passwords "
If I create a protected word document with password using office 2016  , then others can be able to unlock the password in their computer with using Docrecrypt rool  and with having same certificate ?

Thanking you sir 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28b7982b-5e7c-0678-8919-10d4147f3525
* Version Independent ID: 16bd8605-ed8a-234d-0ed7-cac3c1745b35
* Content: [Remove or reset file passwords in Office 2016](https://docs.microsoft.com/en-us/deployoffice/security/remove-or-reset-file-passwords-in-office)
* Content Source: [DeployOffice/security/remove-or-reset-file-passwords-in-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/remove-or-reset-file-passwords-in-office.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Definitely a word or words missing from that sentence. But can't quite figure out what the missing words are. Might just have to remove that sentence. Thanks for bringing that to our attention.
