### ISSUE TITLE
Can i add trusted location in program files (x86)

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#156]
Can i add trusted location in program files (x86) , because my  office 2016  C2R applications are  installed under the program files (x86)   .
For  more detail locations  I will post  afterwards  
Thanking you sir                   , 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 310f63c4-e8b5-22a5-fdbd-8ff597299b1e
* Version Independent ID: 3c9636d1-486f-dfef-9e1b-2d8d091491c0
* Content: [Designate trusted locations for files in Office 2016](https://docs.microsoft.com/en-us/deployoffice/security/designate-trusted-locations-for-files-in-office)
* Content Source: [DeployOffice/security/designate-trusted-locations-for-files-in-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/designate-trusted-locations-for-files-in-office.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Yes, I think that's possible. FYI, it can be most any folder. It doesn't have to be where your apps are installed. "Program files" folder is just  mentioned in the article in reference to the default locations.
