### ISSUE TITLE
Please give direct link 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#159]
sir  please give direct downlad link  to download the office OCT 2016 , i need  .exe tool

Thanking you sir 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e59bf0fe-339b-3bae-c641-eccec7b64361
* Version Independent ID: acfc0cf7-24f8-9a82-d267-19fa8de9d4b7
* Content: [Office Customization Tool (OCT) 2016 Help Add/Modify Network Server Entry dialog box](https://docs.microsoft.com/en-in/DeployOffice/oct/oct-2016-help-add-modify-network-server-entry-dialog-box)
* Content Source: [DeployOffice/oct/oct-2016-help-add-modify-network-server-entry-dialog-box.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/oct/oct-2016-help-add-modify-network-server-entry-dialog-box.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
There is a direct link in the [OCT overview](https://docs.microsoft.com/DeployOffice/oct/oct-2016-help-overview) topic, which appears on the left side of the page. Also, this article is designed to be primarily accessed from a link in the OCT UI. So in most cases, the customer will already have the OCT installed when they get to this article. Thanks for your comment/feedback.
