### ISSUE TITLE
sorryi cant find those templates in gpo

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#163]
I am using windows 10 64bit 1803 , but i could not find "manage restricted permissions"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a3db35c-e8a8-7935-3fa3-d8b7a1d6f50d
* Version Independent ID: 4e5a8d23-f4f6-93bb-d79d-e7bb4dde7f25
* Content: [Protect sensitive messages and documents by using Information Rights Management (IRM) in Office 2016](https://docs.microsoft.com/en-us/deployoffice/security/protect-sensitive-messages-and-documents-by-using-irm-in-office)
* Content Source: [DeployOffice/security/protect-sensitive-messages-and-documents-by-using-irm-in-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/protect-sensitive-messages-and-documents-by-using-irm-in-office.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
As listed in the article, those settings are under User Configuration\Policies\Administrative Templates\Microsoft Office 2016\Manage Restricted Permissions in the Group Policy Management tool.
