### ISSUE TITLE
I created new keys to make more sucure encryption

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#164]
Thanks for the article .
Just now i created new regsitry keys to make more secure encryptionin the following way .
for office 2016 pro plus retail version 32bit  C2R windows  64bit 

[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Access\Security\Crypto]
"CompatMode"=dword:00000001
[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Excel\Security\Crypto]
"CompatMode"=dword:00000001
[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Powerpoint\Security\Crypto]
"CompatMode"=dword:00000001
[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Word\Security\Crypto]
"CompatMode"=dword:00000001

Please verify above keys , that icreated correct or not, and reply to me sir 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a7c8ce1-0ac0-9bc8-8ba8-5488428af686
* Version Independent ID: 29ca5233-c048-8aab-5661-40416b6bd320
* Content: [Cryptography and encryption in Office 2016](https://docs.microsoft.com/en-us/deployoffice/security/cryptography-and-encryption-in-office)
* Content Source: [DeployOffice/security/cryptography-and-encryption-in-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/cryptography-and-encryption-in-office.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Those appear correct based on the information provided in the article.
