### ISSUE TITLE
SharedPC Activation Limits

### ISSUE THREAD

**Issue by brockettc** [MicrosoftDocs/OfficeDocs-DeployOffice#165]
What is that limit under what time frame? We are looking to utilize Office 365 Pro Plus in the classroom environment where new students will be signing onto the lab machines every class. We will be using sharedpc mode where the profiles will get wiped at log off as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ab31873-7ad3-afde-3c72-8a7fb4f2e551
* Version Independent ID: 19f7f483-9f53-f577-1cd4-d360c0b234fc
* Content: [Overview of shared computer activation for Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus?redirectSourcePath=%2fen-us%2farticle%2f836f882c-8ff6-4f19-8b24-0212e0111c94)
* Content Source: [DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@brockettc -- how many different lab machines would a student log into during the day/week?

We think we've set the  "number of activations over a given time period" limits to accommodate most common shared computer scenarios so that users won't receive any errors. We don't publish specific limits because they are subject to change and we are wary of the possibility that knowledge of the specific limits might be used in a fraudulent manner.

**Comment by brockettc** [comment]
That makes sense.

To cover someone logging in/out a lot I would say 10x a day 40x a week would be the absolute most (classes/library logins). More realistically would be half that.

**Comment by xXjmoXx** [comment]
@DHB-MSFT On the flip side of that, I manage about 1,500 endpoints for over 5,000 users across three physical locations in a college environment. Student's may not be able to use the same computer in the various common areas. They may need to activate in a computer lab used for class, and in that case, they may get the same computer they logged on before. But in the library computer commons, they may not be able to get onto the same computer, as it is a high traffic area, and there are nearly 50 computers in this area alone. 

So what does Microsoft consider reasonable in this case? Over the course of a single semester, a student could potentially log in to 50+ computers over 16 weeks. I really need to know what the risk is that my students would reach that "Reasonable Limit". If I deploy this and suddenly had 100 students line up outside our help desk, I would be looking at a resume generating event. 

Single-Sign on isn't an option for us currently, as our Office 365 is managed and operated by our system office, and we have our own local AD domain. Perhaps someday we will get merged together, but it isn't going to be anytime soon. 

I have been a few conferences now where Microsoft MVP's said to be ready for the day when Microsoft stops offering Office as a standalone, that there would only be the User-based activation and shared-activation of Office 365 proplus. Clearly, if you cannot provide clear guidance to colleges about what to expect for shared-activation, I cannot risk deploying it.

As far as roaming profiles, many forums where the topic has been discussed say to steer clear of roaming profiles, as they get bloated, broken, and are a pain to manage. Our IT staff is always on a shoestring budget, we don't have time to fix things that don't work well.

**Comment by manoth-msft** [comment]
As mentioned before, Microsoft does not publish specifics on this feature. In scenarios with a high device-turnover we recommend to implement Token roaming. The token can be stored in the user's profile or a common network share. This will enable a user to roam between a high number of devices without issues, as the token follows the user and does not have to be generated by the Microsoft service every time. https://docs.microsoft.com/en-us/DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus?redirectSourcePath=%2fen-us%2farticle%2f836f882c-8ff6-4f19-8b24-0212e0111c94#additional-details-about-shared-computer-activation-for-office-365-proplus

@DHB-MSFT I suggest to close this issue.
