### ISSUE TITLE
Checking Macs msupdate configuration has different results in Terminal vs ARD

### ISSUE THREAD

**Issue by ChicagoBubba** [MicrosoftDocs/OfficeDocs-DeployOffice#168]
I have always pushed out Office 2016 update settings to all my Macs to be manual, and then I check to see it was applied. The results are confusing as both ARD and Terminal report different results. Here is the command I'm using to check if the configuration was applied: 
cd /Library/Application\ Support/Microsoft/MAU2.0/Microsoft\ AutoUpdate.app/Contents/MacOS
./msupdate --config

If you notice below, HowToCheck and LastCheckForUpdates differ. Anyone know why or how to fix this and ensure the setting is correct?

**ARD RESULTS:**

iMac-7691
Checking configuration...
{
    AutoUpdateVersion = "4.4.18101400";
    ChannelName = Production;
    **HowToCheck = AutomaticDownload;
    LastCheckForUpdates = "Oct 30, 2018 at 10:27:40 PM";**
    ManifestServer = "";

**TERMINAL RESULTS using SSH to same computer:**

{
AutoUpdateVersion = "4.4.18101400";
    ChannelName = Production;
    **HowToCheck = Manual;
    LastCheckForUpdates = "May 1, 2018 at 8:47:21 AM";**
    ManifestServer = "";

**Comment by DHB-MSFT** [comment]
Our msupdate expert is away this week. If you need a quicker response, I'd suggest posting this question to the [Answers forum](https://answers.microsoft.com/) or the [Tech Community](https://techcommunity.microsoft.com/). More people are on those sites and you will probably get a faster response/answer.
