### ISSUE TITLE
ODT Setting for Desktop Shortcuts

### ISSUE THREAD

**Issue by crew05king** [MicrosoftDocs/OfficeDocs-DeployOffice#169]
Is there a setting within ODT configuration XML file that would create desktop shortcuts when installing office?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a0b1ff-0498-505a-6024-b813980d310f
* Version Independent ID: b8057930-b4bd-1304-17ce-5561f837e901
* Content: [Configuration options for the Office Deployment Tool](https://docs.microsoft.com/en-us/deployoffice/configuration-options-for-the-office-2016-deployment-tool)
* Content Source: [DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by BloomerzUK** [comment]
Not to my knowledge - I know there are taskbar items that can be pinned, but not desktop icons.

**Comment by jwhit-MSFT** [comment]
That's right--there's no way to customize Office shortcuts for Click-to-Run versions of Office. I've given this feedback to the Office engineering team.

**Comment by NeverEnoughCoffeeMan** [comment]
I realize this is a closed Feedback item but another nice-to-have might be an option that moves all shortcuts into a single folder on the Start menu (rather than fling them from the top [Access] to the bottom [Word]).
