### ISSUE TITLE
Need to specify what security context is used to generate the activation token.

### ISSUE THREAD

**Issue by TheBaban** [MicrosoftDocs/OfficeDocs-DeployOffice#171]
the document state:  Office needs to be able to write to that folder location. 
This is too vague. we need to indicate what account is used to write the token file on the folder we specify.
My testing shows that the token is written under the user security context. 
Could you please add that info to the article? So we need to provide to the user read/Writte access to the folder configured to store the token.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ab31873-7ad3-afde-3c72-8a7fb4f2e551
* Version Independent ID: 19f7f483-9f53-f577-1cd4-d360c0b234fc
* Content: [Overview of shared computer activation for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/overview-of-shared-computer-activation-for-office-365-proplus)
* Content Source: [DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by csh** [comment]
@DHB-MSFT Is this any closer to being resolved?

Our org is moving towards a fully Azure AD setup, computers are used by staff and students although we'll periodically see a nice 0x8004005 when SCA is deployed which from my programming experience immediately makes Access Denied come to mind. 

We can't put Azure AD devices in our classrooms with SCA deployed when every nth user is hit with this message, for a premium offering this is quite disappointing.

**Comment by v-olduch** [comment]
It would be nice to have the activation token size as well.

**Comment by 010265mohamadazat** [comment]
ازيك

**Comment by 010265mohamadazat** [comment]
انا بحبك اوى
