### ISSUE TITLE
Couldn't install. Error Code: 30029-1011

### ISSUE THREAD

**Issue by clementechesterlowen** [MicrosoftDocs/OfficeDocs-DeployOffice#173]
We downloaded and tried to install. I also run the office removal tool. This error prompts when installing Office 2019. Below is the configuration file.

&lt;Configuration&gt;
    &lt;Add SourcePath=".\" OfficeClientEdition="64" Channel="PerpetualVL2019"&gt;
        &lt;Product ID="ProPlus2019Volume"&gt;
            &lt;Language ID="en-us" /&gt;
        &lt;/Product&gt;
    &lt;/Add&gt;
    &lt;RemoveMSI All="True" /&gt;
&lt;/Configuration&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [Deploy Office 2019 (for IT Pros)](https://docs.microsoft.com/en-us/deployoffice/office2019/deploy)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by MaceyW** [comment]
<Configuration>
  <Add SourcePath="C:\Users\Admin\Desktop\ODT" OfficeClientEdition="64" Channel="PerpetualVL2019">
      <Product ID="ProPlus2019Volume"  PIDKEY="ENTER KEY HERE" >
         <Language ID="en-us" />
      </Product>
      <Product ID="ProofingTools">
        <Language ID="de-de" />
        <Language ID="ja-jp" />
      </Product>
  </Add>
  <RemoveMSI All="True" />
  <Display Level="FULL" AcceptEULA="TRUE" />
</Configuration>

This is what your first Configuration file should look like.
Run setup /download configuration.xml
Then.....

Once you get to this step setup /configure configuration.xml
You need to go into your ODT folder, and find the new configuration files it created , and select the one you need, and change the cmd in cmd prompt to for EX. setup /configure configuration-Office2019Enterprise.xml

It installs! at least it worked for me it didn't activate with my key, but you can do that manually.

**Comment by MaceyW** [comment]
<Configuration>
  <Add SourcePath="C:\Users\Admin\Desktop\ODT" OfficeClientEdition="64" Channel="PerpetualVL2019">
      <Product ID="ProPlus2019Volume"  PIDKEY="INSERT KEY HERE" >
         <Language ID="en-us" />
      </Product>
      <Product ID="ProofingTools">
        <Language ID="de-de" />
        <Language ID="ja-jp" />
      </Product>
  </Add>
  <RemoveMSI All="True" />
  <Display Level="FULL" AcceptEULA="TRUE" />
</Configuration>

**Comment by MaceyW** [comment]
Configuration
Add SourcePath="." OfficeClientEdition="64" Channel="PerpetualVL2019"
Product ID="ProPlus2019Volume" PIDKEY= ENTER KEY HERE
Language ID="en-us" /
/Product
Product ID="ProofingTools"
Language ID="de-de" /
Language ID="ja-jp" /
/Product
/Add
RemoveMSI All="True" /
Display Level="FULL" AcceptEULA="TRUE" /
/Configuration

**Comment by clementechesterlowen** [comment]
I reconfigured my configuration file and performed the following:
First, "setup /download configuration.xml." And lastly, "setup /configure configuration.xml." 

However, it still gives me the Error Code: 30029-1011. (Couldn't install Office 2019 and use a latest Office Deployment Tool)

**Comment by RAJU2529** [comment]
just now I seen configuration file, 
I noted that, you configured wrongly 

because you trying to office 2019 products , which is not installed in your windows.

make sure which edition, architecture office is installed.
try to replace 2016 or 2013 or 2010 instead of 2019.
once you found all details, again reconfigure and  try to uninstall

**Comment by manoth-msft** [comment]
Closing due to the age of the issue report. Feel free to re-open or open new issue if problem persists.
