### ISSUE TITLE
Office Pro Plus 2019 C2R with Visio Pro 2016 C2R

### ISSUE THREAD

**Issue by kniption** [MicrosoftDocs/OfficeDocs-DeployOffice#178]
What about the scenario of installing Office Pro Plus 2019 C2R with Visio Pro 2016 C2R using volume licensing? Both installs are using the C2R  installation technology. Is this officially supported and if not why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d40c96f3-1c97-b538-ef82-ffbf0eef204d
* Version Independent ID: 2d6883b5-1b5c-dc16-9999-17d0652bfa48
* Content: [Supported scenarios for installing different versions of Office, Project, and Visio on the same computer](https://docs.microsoft.com/en-us/deployoffice/install-different-office-visio-and-project-versions-on-the-same-computer)
* Content Source: [DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@kniption -- Yes, that scenario is supported. They are the same version (16.0) and they use the same installation technology (Click-to-Run). Usually a volume licensed version of Visio Professional 2016 is installed by using Windows Installer (MSI), but you can install it by using Click-to-Run if you follow the steps in this article -- [Use the Office Deployment Tool to install volume licensed versions of Project 2016 and Visio 2016](https://docs.microsoft.com/en-us/deployoffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016). Hope that helps.

**Comment by DHB-MSFT** [comment]
@kniption -- actually, let me double-check one more thing about that scenario before I give my final answer. Sorry. Thanks.

**Comment by DHB-MSFT** [comment]
@kniption -- I've confirmed with the PM that this scenario is supported.

**Comment by DHB-MSFT** [comment]
@kniption -- can you try with the most current version of the Office Deployment Tool? Version 16.0.11107.33602, which was released yesterday. You can download it from here -- https://www.microsoft.com/en-us/download/details.aspx?id=49117. 

As for the channel matching, we have configured volume licensed versions of Project/Visio 2016 to be available in the PerpetualVL2019 channel to support scenarios such as these. 

Thanks.

**Comment by kniption** [comment]
I downloaded the new ODT tool and replaced the setup.exe. I also tried with
and without Channel="PerpetualVL2019" I still receive the update channel
error.


<Configuration>
  <Add OfficeClientEdition="64" Channel="PerpetualVL2019">
    <Product ID="VisioProXVolume" PIDKEY="
*XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX*">
        <Language ID="en-us" />
     </Product>
   </Add>
  <Property Name="AUTOACTIVATE" Value="1" />
  <Display Level="Full" AcceptEULA="TRUE" />
  <Logging Level="Standard" Path="%windir%\Logs\Software" />
</Configuration>

**Comment by DHB-MSFT** [comment]
@kniption -- is there an error code with the error message?  Where are you installing from? Directly from the Office Content Delivery Network (CDN) on the internet?

**Comment by msft-bcorob** [comment]
Hi @kniption , sorry to hear you're having trouble installing Visio alongside Office 2019.  We're not able to reproduce the error that you're getting.  Could you please double-check that the version of the ODT you're using is the latest?  The setup.exe that you call should have a version of 16.0.11107.33602 or later.

Since we're not able to reproduce the problem that you're experiencing, the next step would be to contact Microsoft Support for further assistance. They'll be best suited to help collect the necessary information and investigate further to resolve.

**Comment by msft-bcorob** [comment]
>           How about challenge to install Project 2019 or Visio 2019 (CR2) along with Office 2016 Standard (MSI)?

As noted in the documentation, you can’t install two products together that have the same version but use different installation technologies.  Since Project/Visio 2019 and Office 2016 both use major version 16.0, you won't be able to combine these C2R and MSI products.  To run Project/Visio and Office side by side, choose the Office suite you'll be deploying first and then make sure Project and Visio installation technologies match.  The following are possible:

 - Office 2016 Standard MSI with Project/Visio 2016 MSI
 - Office 2019 Standard C2R with Project/Visio 2016 C2R
 - Office 2019 Standard C2R with Project/Visio 2019 C2R

**Comment by DHB-MSFT** [comment]
@B4h3A  -- to follow up on @msft-bcorob's comment.... Office 2016 Standard, which is only available via volume licensing, is only available in MSI format. It's not available in Click-to-Run format.

**Comment by B4h3A** [comment]
@DHB-MSFT -- Actually I need to install a Project 2019 along with Office 2016 Standard, once that's not possible to install Office 2016 Standard CR2, how can we solve this problem? Could you please provide me a MSI installer for Project 2019?

**Comment by DHB-MSFT** [comment]
@B4h3A -- Project 2019 is only available in Click-to-Run format.

**Comment by B4h3A** [comment]
And what's the solution?

**Comment by msft-bcorob** [comment]
@B4h3A Beginning with Office 2019, MSI deployment for Office client product has been replaced with C2R.  You can use VL downgrade rights to use Project 2016 (MSI) instead of Project 2019 (C2R).  Project 2016 (MSI) is compatible with Office 2016 Standard.

**Comment by emilchik** [comment]
Never mind. I found it. : 
If you’re deploying a volume licensed version of Project 2019 or Visio 2019 along with Office 365 ProPlus, you should specify the same update channel for Project 2019 and Visio 2019 that you’re using for Office 365 ProPlus. For example, “Monthly” for Monthly Channel or “Broad” for Semi-Annual Channel.
