### ISSUE TITLE
Office 365 ProPlus Store version alongside Volume License

### ISSUE THREAD

**Issue by henryed07** [MicrosoftDocs/OfficeDocs-DeployOffice#179]
Is it possible to install Office ProPlus 365 from the store and continue to receive the monthly update from click to run and use .msi for visio and project?

**Comment by DHB-MSFT** [comment]
If you have an MSI version of Project/Visio 2010 or 2013, you can install it on the same device as Office 365 ProPlus (which always uses Click-to-Run). If you have a volume licensed version of Project/Visio 2016 (which uses MSI), you'll need to follow the steps in this article to install Project/Visio 2016 using the Office Deployment Tool and Click-to-Run: [Use the Office Deployment Tool to install volume licensed versions of Project 2016 and Visio 2016](https://docs.microsoft.com/en-us/DeployOffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016). I hope that helps. Thanks for your question.
