### ISSUE TITLE
Office Pro Plus 2016 MSI Project/Visio 2019  C2R

### ISSUE THREAD

**Issue by danbu** [MicrosoftDocs/OfficeDocs-DeployOffice#180]
We have a scenario of personally owned student devices with Office 2016 VL MSI then students trying to use Project/Visio C2R through the Microsoft Imagine program, I believe that version shows up as retail.  Is this supported?  This page used to have a chart with Office 2013 and 2016 MSI versus the C2R installers this is now further complicated with 2019 version not changing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d40c96f3-1c97-b538-ef82-ffbf0eef204d
* Version Independent ID: 2d6883b5-1b5c-dc16-9999-17d0652bfa48
* Content: [Supported scenarios for installing different versions of Office, Project, and Visio on the same computer](https://docs.microsoft.com/en-us/DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer)
* Content Source: [DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by danbu** [comment]
I have tested Office Pro Plus 2019 C2R with Project/Visio 2019 C2R Microsoft Imagine and that does work but the 2019 installer does not support setting the KMS servers so a customized wrapper has to be created to run those commands.

**Comment by CraigHumphrey** [comment]
Can you point at any documentation for this?  We may hit a similar situation.

**Comment by danbu** [comment]
So I am using Inno Setup Complier (http://www.jrsoftware.org/isinfo.php) (it can also sign the package if you have a code signing certificate).  You can play with some of hiding and maybe customize the install box but this works pretty well.  I haven’t used Inno that much it has been around for a while but would like to do some selectable options to have different pre build XML files for 64/32 bit Office 2019 maybe an Office 365 option and maybe even Visio/Project

Here is the .iss file I am using to compile the .EXE (You would update KMS-SERVER.DOMAIN.COM with your server), below that is the Office 2019 config XML file it is pretty straight forward it would be nice to have commands pre/post Office install like the old MSI version.

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={GENERATE A NEW GUID}
AppName=Microsoft Office Pro Plus 2019 64 Bit
AppVersion=1.0
;AppVerName=Microsoft Office Pro Plus 2019 64 Bit
AppPublisher=Company
CreateAppDir=no
OutputDir=C:\Users\admin\Desktop\Office_2019\ISS-Install
OutputBaseFilename=ISS-Office-2019-64bit-v1.0
SetupIconFile C:\Users\admin\Desktop\Office_2019\ISS-Install \iconfile.ico
Compression=lzma
SolidCompression=yes
DisableFinishedPage=yes
RestartIfNeededByRun=no
CreateUninstallRegKey=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: " C:\Users\admin \Office_2019\ISS-Install \setup.exe"; DestDir: "{win}\Temp"; Flags: ignoreversion deleteafterinstall
Source: " C:\Users\admin \Office_2019\ISS-Install \Office2019-x64.xml"; DestDir: "{win}\Temp"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Run]
Filename: "{win}\Temp\setup.exe"; Parameters: "/configure c:\Windows\temp\Office2019-x64.xml"; Flags: runhidden hidewizard
Filename: "{sys}\cscript.exe";Parameters: "{pf64}\Microsoft Office\Office16\ospp.vbs /sethst:KMS-SERVER.DOMAIN.COM"; Flags: runhidden nowait hidewizard
Filename: "{sys}\cscript.exe";Parameters: "{pf64}\Microsoft Office\Office16\ospp.vbs /act"; Flags: runhidden nowait hidewizard


Then the Office2019-x64.xml is just as follows or whatever you generate from https://config.office.com

<Configuration>
  <Add OfficeClientEdition="64" Channel="PerpetualVL2019">
    <Product ID="ProPlus2019Volume">
      <Language ID="en-us" />
    </Product>
  </Add>
  <Updates Enabled="TRUE" />
  <Property Name="AUTOACTIVATE" Value="1" />
</Configuration>

**Comment by flcev** [comment]
Did you find a solution for this? We also have an Office 2016 Std MSI and can't install Project Online.

**Comment by flcev** [comment]
Did you find a solution for this? We also have an Office 2016 Std MSI and can't install Project Online.

**Comment by manoth-msft** [comment]
@flcev The combination of Office 2016 MSI and Visio/Project 2016/2019 Click-to-Run (subscriptions) is not supported as both products have the same major version (16.0), but different installation technologies. There is no supported workaround available for this scenario.

@DHB-MSFT Can be closed as documentation is accurate.
