### ISSUE TITLE
Project and Visio Pro/Sts 2019 via SCCM

### ISSUE THREAD

**Issue by nalifragis** [MicrosoftDocs/OfficeDocs-DeployOffice#183]
hi,

i was wondering if you can create separate packages for Project and Visio 2019 Std and Pro.
As now if we want to deploy those apps via SCCM we have for each application to include all Office source files around 2.1GB - 3 GB  .

Or you can suggest a best practice solution for  those scenarios 

thanks in advance

Nick

**Comment by chhopkin** [comment]
Hi Nick,

The source files for Visio and Project are bundled together with the rest of Office.  I recommend managing a single location that contains all the Office source files for the architecture and channel you are deploying as well as all the languages you plan to support.  Then, within this location, create separate configuration XML files for each of the different configurations, i.e. Office only, Visio only, Office w/ Visio.

Cheers,
Chris Hopkins
Microsoft - Office Deployment

**Comment by nalifragis** [comment]
hi Chris and thanks for the quick reply.

What you are suggesting is ok but the problem is that we have  a lot of remote offices.So one single location as a source it is not a very good idea for us. What we need is to use Software Center and distribute the files to the local DPs .The problem is that we cannot create separate "Applications"  in CM with separate configuration XML files and in the same time use a common source file .So for each one of them  i.e. Office,Visio Std and Pro, Project Std and Pro we need to create a separate application using the same source files multiple times ,occupying more space on the servers and creating unessacary traffic during distribution and installation,

I hope you understand my concerns.

thanks 

Nick

Nick

**Comment by chhopkin** [comment]
Hi Nick,

If you don't mind maybe we can connect on a call to discuss.  My email is chhopkin@microsoft.com.

**Comment by DHB-MSFT** [comment]
Closing the issue since Chris & Nick will be taking this discussion offline.
