### ISSUE TITLE
Activation Limits

### ISSUE THREAD

**Issue by aw3t** [MicrosoftDocs/OfficeDocs-DeployOffice#185]
I'm not crazy about how this article is laid out.  I feel like the statement below should be near the top of the article, in the initial description.

"Activation limits: Normally, users can install and activate Office 365 ProPlus only on up to five computers. Using Office 365 ProPlus with shared computer activation enabled doesn't count against the five computer limit."

The first time reading this page, I missed that information because my first impression of shared computer activation lead me to believe that the 5 device limit was still a concern.  Look at these bullet points in the initial description:

"Three workers at a factory share a computer, each worker using Office on that computer during their eight-hour shift.

Fifteen nurses at a hospital use Office on five different computers throughout the day.

Five employees connect remotely to the same computer to run Office.

Multiple employees use Office on a computer that's located in a conference room or some other public space in the company."

Each one of those points is a scenario that includes no more than 5 devices.  After reading that, I assumed that the 5 device limit was still a concern.

In addition to moving the 'activation limits' section to the top of the article, could those example scenarios be changed to clear things up for others reading this for the first time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ab31873-7ad3-afde-3c72-8a7fb4f2e551
* Version Independent ID: 19f7f483-9f53-f577-1cd4-d360c0b234fc
* Content: [Overview of shared computer activation for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/overview-of-shared-computer-activation-for-office-365-proplus)
* Content Source: [DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@aw3t -- I'll update the intro to make it clearer that the "devices limit" doesn't apply with shared computer activation. Thanks for the feedback to help make the documentation better.

**Comment by aw3t** [comment]
Thanks for the consideration!

**Comment by DHB-MSFT** [comment]
@aw3t -- I updated the article by slightly changing the hospital example and by adding info about limits not applying to the end of the intro section. Thanks again for your feedback.
