### ISSUE TITLE
Office Customization tool page

### ISSUE THREAD

**Issue by Jack0falltech** [MicrosoftDocs/OfficeDocs-DeployOffice#186]
The tool dosnt work in IE, Edge, Chrome or Firefox you cant choose a update channel and none of the other groupings will expand 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67f2376c-177b-110f-9c88-f83d53bd6bc7
* Version Independent ID: a98d74e5-f7dc-c073-4cb9-a8901895a89a
* Content: [Overview of the Office Customization Tool](https://docs.microsoft.com/en-us/DeployOffice/overview-of-the-office-customization-tool-for-click-to-run)
* Content Source: [DeployOffice/overview-of-the-office-customization-tool-for-click-to-run.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-the-office-customization-tool-for-click-to-run.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by DHB-MSFT** [comment]
@Jack0falltech  -- after you select your product, be sure to click Add. Then the other relevant choices should become available. Hope that helps.

**Comment by fishblizz** [comment]
@DHB-MSFT -- there is no ADD button/link to find.

**Comment by DHB-MSFT** [comment]
@fishblizz -- I believe they've updated the UI since November so there isn't an Add button anymore. We'll get the steps updated in the article. Thanks for pointing that out.

**Comment by fishblizz** [comment]
@DHB-MSFT -- Thanks for reply, but I forgot to mention the site isn't working. When you first put out the Office Suite it doesn't reponse. With a bit switching between 32 and 64 bit you can accomplish the form except voor Channel Update and Version, does keep blanked out.

**Comment by DHB-MSFT** [comment]
@fishblizz  -- Thanks for letting us know that you're having problems with the site. We're hearing some other similar reports. The team responsible for that site is investigating.
