### ISSUE TITLE
Failed to download Office 2019 installation file

### ISSUE THREAD

**Issue by SumVanan** [MicrosoftDocs/OfficeDocs-DeployOffice#187]
PS D:\&gt; cd D:\111
PS D:\111&gt; setup /download configuration.xml
The Setup command may only be used inside a Describe block.
所在位置 C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Functions\Describe.ps1:125 字符: 9
+         throw "The $CommandName command may only be used inside a Des ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The Setup comma...Describe block.:String) [], RuntimeException
    + FullyQualifiedErrorId : The Setup command may only be used inside a Describe block.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [部署 Office 2019 （针对 IT 专业人员）](https://docs.microsoft.com/zh-cn/DeployOffice/office2019/deploy)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice-pr.zh-CN/blob/live-sxs/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@SumVanan -- you need to run the Office Deployment Tool (setup.exe) from a Windows command prompt, not a PowerShell command prompt.

**Comment by creativetech1** [comment]
I am using Windows Command Prompt as Administrator and this is what I get.     'setup' is not recognized as an internal or external command, operable program or batch file.

**Comment by ItzLevvie** [comment]
@creativetech1 You don't have to run Office Deployment Tool as an Administrator

**Comment by ItzLevvie** [comment]
@creativetech1 Are you running that command where setup.exe is located?

**Comment by igorcapitanio** [comment]
@creativetech1 first you need downloaded de 'Officedeploymenttoll (ODT)" and extract on folder, so you 'find' a Setup.exe  .. After run Prompt as Administrator on this folder.... setup /download configuration.xml

**Comment by microram** [comment]
> The Setup command may only be used inside a Describe block.

FIX: Use the `.\setup` notation if you are getting this error while in powershell.

**Comment by Tslv65** [comment]
@microram thank you, very very helpful :)
