### ISSUE TITLE
Update timing

### ISSUE THREAD

**Issue by sdcash** [MicrosoftDocs/OfficeDocs-DeployOffice#190]
Is this article correct when it discusses the timing of the scheduled task? It appears the tasks for Office updates now run daily. The article indicates Sunday, Tuesday, Friday.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2324f001-9c0f-8730-0326-747300a87b78
* Version Independent ID: 5123d9b2-e45b-180a-1431-852542e8a1db
* Content: [Overview of the update process for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/overview-of-the-update-process-for-office-365-proplus#feedback)
* Content Source: [DeployOffice/overview-of-the-update-process-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-the-update-process-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@sdcash -- Yes, the scheduled task now runs daily. We need to update the article. Thanks for the reminder.
