### ISSUE TITLE
This doesn't work

### ISSUE THREAD

**Issue by mguyett** [MicrosoftDocs/OfficeDocs-DeployOffice#191]
Even using the Office Click-to-Run configuration tool, this always installs the wrong version of Visio.  I can't activate it.  It's pathetic that Microsoft can't resolve this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e6c0641-503d-7959-2afb-839821cc792f
* Version Independent ID: 046c52d9-4fbe-4fe7-0778-5c1d4138f69e
* Content: [Use the Office Deployment Tool to install volume licensed versions of Project 2016 and Visio 2016](https://docs.microsoft.com/en-us/DeployOffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016?redirectSourcePath=%252fen-us%252farticle%252f82691bd7-a3d5-47ca-8d8a-0ee43ec2c01f)
* Content Source: [DeployOffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@mguyett -- What version of Visio does it install?

**Comment by timmmay** [comment]
Same here, using the VisioProXVolume product ID and when I go to activate using a VL key, it tells me the key is for volume licensed edition which is not installed.

**Comment by kylethompsonpt** [comment]
Code has changed, there is no configuration.xml file any more


![image](https://user-images.githubusercontent.com/47126124/51872784-89822480-230f-11e9-836c-2dcfe4ed69a4.png)

**Comment by williestylez** [comment]
@kylethompsonpt The code hasn't changed, the "configuration.xml" is the generic name for the XML file you need to create. You can use one of the included XML files (that you listed above), as a starting point, or create your own, using additional instructions found in the "Overview of the Office Deployment Tool".

**Comment by williestylez** [comment]
> @timmmay Same here, using the VisioProXVolume product ID and when I go to activate using a VL key, it tells me the key is for volume licensed edition which is not installed.

Did you use the C2R-P key from the licensing site? If so, were you ever able to resolve the issue?

**Comment by rconlee1** [comment]
Is there an answer to above? I just had the same situation with Visio. The keys worked fine a month ago and now I get activation failed.

**Comment by williestylez** [comment]
@rconlee1 The keys they provide in the article are generic keys, that would probably only give you the equivalent of a Trial Period. Those keys would not be for permanent use. If you’ve purchased Visio, you should be using your C2R-P keys which would be on the Microsoft Volume Licensing site.

**Comment by williestylez** [comment]
Just for the record, the procedure worked just fine for me, and the correct version of Visio Pro 2016 installed, as expected. I am using my purchased keys (labeled C2R-P in the licensing site), and they activated just fine, after install. So I don’t anticipate any activation issues in the future. But I’ll definitely keep you all posted, if I have any issue.

**Comment by Shreeingame** [comment]
I noticed after a restart it worked fine. If you are activating using kms then be sure kms is diwcoverable or host cache enabled . Do a restart and check .
null

**Comment by Jluvs2dive** [comment]
Thank you williestylez!  I hadn't even noticed the C2R-P keys.  I've been looking for this answer for awhile.  I don't know why Microsoft has not made it clear in their documents!  I'm up and running because of you!

**Comment by mbalcerzyk** [comment]
I had a lot of problems with installing Project 2016 with these instructions. Finally, I got it working on Windows 10 1903 64 bit running FROM ADMINISTRATIVE COMMAND PROMPT

**Comment by mbalcerzyk** [comment]
... the following command where setup.exe latest version ODT and configuration file were: .\setup.exe /configure .\configurationPr2016.xml
The configurationPr2016.xml is the following:
<Configuration>
  <Add OfficeClientEdition="64" Channel="Monthly">
    <Product ID="ProjectProXVolume" PIDKEY="WGT24-HCNMF-FQ7XH-6M8K7-DRTW9">
      <Language ID="en-us" />
    </Product>
  </Add>
</Configuration>

The license code for the volume license does not work. I have Office 365 license from my university, and Project volume license from national academy of science, who is not interested in getting the keys. I got Project working this way for more than a year now.

**Comment by mbalcerzyk** [comment]
XML does not pass, so figure out substituting _ for triangular brackets
_Configuration_

  _Add OfficeClientEdition="64" Channel="Monthly"_
    _Product ID="ProjectProXVolume" PIDKEY="WGT24-HCNMF-FQ7XH-6M8K7-DRTW9"_
      _Language ID="en-us" /_
    _/Product_

  _/Add_
_/Configuration_

**Comment by avwplace** [comment]
Hi, I got similar issue. When I tried that way, I am stucked at "setup.exe/ download visio.xml". The dialogue box said error, CODE 30029-1007 (0). I do have plenty of storage and working internet access. Please share the Office folder file downloaded from the "setup.exe/ download visio.xml" step or kindly help me to explain. Thank you. :)

**Comment by williestylez** [comment]
> ...When I tried that way, I am stucked at "setup.exe/ download visio.xml". The dialogue box said error, CODE 30029-1007 (0). I do have plenty of storage and working internet access. 

@avwplace the issue you're facing is that you're either:

1. using the wrong command (your syntax above is incorrect, but may just be a typo); it should be: 
 `setup.exe /download visio.xml`
2. You're using the wrong XML filename (make sure your XML file is actually called visio.xml)
3. You're XML file is not located in the same directory that you're working from, or that your setup.exe file is in
4. Or your, XML file is configured incorrectly. Provide the text in the XML file (obscure your key so that you don't expose it to the internet)

The last theory is more of a long shot because I think one of the other three issues is what's really plaguing you.

**Comment by manoth-msft** [comment]
For issue #4, you can use the Office Customization Tool at config.office.com. This allows you to point+click a configuration file and you can be 100% certain that the syntax is correct.

**Comment by manoth-msft** [comment]
Closing due to the age of the initial issue report and it seems to have been resolved. Feel free to open new issue if problem persists.
