### ISSUE TITLE
Automatic removal of activated installs

### ISSUE THREAD

**Issue by HH-Fujitsu** [MicrosoftDocs/OfficeDocs-DeployOffice#196]
Will installations be removed automatically from the portal after a certain period if a user does not log in to a computer which has an activated Office install? We are trying to avoid a situation where a user has some really old installations (for example on a retired computer) using up their activation count.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3c236da-c63a-f789-f1b6-7aeb41f16c1f
* Version Independent ID: 35319bac-d94f-832c-ce79-41bffe5c8d25
* Content: [Overview of licensing and activation in Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/overview-of-licensing-and-activation-in-office-365-proplus)
* Content Source: [DeployOffice/overview-of-licensing-and-activation-in-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-licensing-and-activation-in-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@HH-Fujitsu -- no, Office is never automatically removed in these situations. As an admin, you can go to the Office 365 admin center and edit the user's account, and deactivate Office installs on their behalf. Or users can deactivate installs ([Deactivate Office 365 if you see a "limit reached" error](https://support.office.com/article/767e3560-96ed-4b1c-806d-2fe01c529b1b
)). If they have reached their limit and they try to activate a new installation of Office, I think they'll get the"limit reached" dialog message, with a link to go to their account page and deactivate old installs. Then they can deactivate an older installation. But even if you deactivate an installation, Office still remains on that computer. Just in a "read only" mode and they can re-activate that install if they need to use it (and if they aren't at their limit).  I hope that helps.

**Comment by HH-Fujitsu** [comment]
@DHB-MSFT -- Great, thank you! This answers my question.
