### ISSUE TITLE
Installing Issues VLC Office 2019 STD

### ISSUE THREAD

**Issue by aschaeffer323** [MicrosoftDocs/OfficeDocs-DeployOffice#199]
Hello New to this way of downloading so bare with me. 

I created the configuration.xml from the creator Microsoft provided. The problem I keep having is I ran setup/download configuration.xml Which download to a windows 10 PC. I then ran /configure and it also installed great. 

So I created another XML with a source \\server\office2019 Moved the Office folder from the Windows 10 machine to a network share. 

Logged into another PC and copy ODT and the new XML to it. Ran setup /configure configuration.xml and it keeps returning Error 30182-1011 Couldn't Install We are Sorry we can't continue we weren't able to download a required file. 

I can't seem to get past this error. 

Please Help

<Configuration>
  <Add SourcePath="\\server\warez\_apps\MSOffice2019STD" OfficeClientEdition="64" Channel="PerpetualVL2019" AllowCdnFallback="TRUE" ForceUpgrade="TRUE">
    <Product ID="Standard2019Volume" PIDKEY="XXXXX-XXXXX-XXXXX-XXXXX-XXXXX">
      <Language ID="en-us" />
      <ExcludeApp ID="Groove" />
      <ExcludeApp ID="OneNote" />
      <ExcludeApp ID="OneDrive" />
    </Product>
  </Add>
  <Property Name="SharedComputerLicensing" Value="1" />
  <Property Name="PinIconsToTaskbar" Value="TRUE" />
  <Property Name="SCLCacheOverride" Value="0" />
  <Property Name="AUTOACTIVATE" Value="1" />
  <Updates Enabled="TRUE" />
  <RemoveMSI All="TRUE" />
  <AppSettings>
    <Setup Name="Company" Value="Benefit Resource Inc" />
  </AppSettings>
  <Display Level="Full" AcceptEULA="TRUE" />
</Configuration>

**Comment by aschaeffer323** [comment]
<Configuration>
  <Add SourcePath="\\SERVER\warez\_apps\MSOffice2019STD" OfficeClientEdition="64" Channel="PerpetualVL2019" AllowCdnFallback="TRUE" ForceUpgrade="TRUE">
    <Product ID="Standard2019Volume" PIDKEY="XXXXX-XXXXX-XXXXX-XXXXX-XXXXX">
      <Language ID="en-us" />
      <ExcludeApp ID="Groove" />
      <ExcludeApp ID="OneNote" />
      <ExcludeApp ID="OneDrive" />
    </Product>
  </Add>
  <Property Name="SharedComputerLicensing" Value="1" />
  <Property Name="PinIconsToTaskbar" Value="TRUE" />
  <Property Name="SCLCacheOverride" Value="0" />
  <Property Name="AUTOACTIVATE" Value="1" />
  <Updates Enabled="TRUE" />
  <RemoveMSI All="TRUE" />
  <AppSettings>
    <Setup Name="Company" Value="Benefit Resource Inc" />
  </AppSettings>
  <Display Level="Full" AcceptEULA="TRUE" />
</Configuration>

**Comment by LegalTechAdmin** [comment]
Make sure the folder name you're running the setup from is the same as when the configuration file was created. So if you originally ran it from a folder named Office2019 you'll get that error if you run it from MSOffice2019 on the new machine. Keep the name the same as the original and it may fix the problem.
