### ISSUE TITLE
Would be nice to have the last modification date for documents havings issues

### ISSUE THREAD

**Issue by fabricebo** [MicrosoftDocs/OfficeDocs-DeployOffice#200]
We do not need to modify files containing VBA macros when these files have not been used since years. Having this information in the "VBA Summary' and in the "VBA Results" tabs would be very useful when sorting important and less important files and time gain could be significant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2843afe2-a11d-7d88-8b56-24f131782d01
* Version Independent ID: f8bc6a27-b9f5-a729-b5e3-fdd9ac6642ed
* Content: [Use the Readiness Toolkit to assess application compatibility for Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro)
* Content Source: [DeployOffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by tomdoyle-msft** [comment]
Thanks for the feedback. There are currently no plans to introduce this feature, but it's certainly a valid request and something that we can look at possibly introducing in the future.
