### ISSUE TITLE
Unable to switch from ProPlus365 (shown as retail) to ProPlus2019Volume. 

### ISSUE THREAD

**Issue by rasldasl** [MicrosoftDocs/OfficeDocs-DeployOffice#201]
I ran a pilot of about 50 computers on Office 365 (some with Visio and/or Project 2016 VL) all with C2R installs. Now I'm trying to test an install of ProPlus2019 with volume licensing on those same machines. No matter what method I have used to remove the O365 install it's still being detected by the ProPlus2019VL installer. 

We can't install
The following product(s) can't be installed at the same time:
None
ProjectProRetail
ProPlus2019Volume

(Note - the retail product detected varies but does not even seem to always match what was originally installed.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d40c96f3-1c97-b538-ef82-ffbf0eef204d
* Version Independent ID: 2d6883b5-1b5c-dc16-9999-17d0652bfa48
* Content: [Supported scenarios for installing different versions of Office, Project, and Visio on the same computer](https://docs.microsoft.com/en-us/deployoffice/install-different-office-visio-and-project-versions-on-the-same-computer)
* Content Source: [DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by rasldasl** [comment]
Any updates? Seems to be a similar issue to https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/207

One 365 ProPlus prior to C2R with Project/Visio 2016 VL C2R I had no issues. Only having an issue trying to switch the core ProPlus product from 365 license to VL. I can't find where the licensing is stored remove it cleanly and the installer will not proceed. It does not want to install ProPlus 2019 VL when any part of 365 is installed.

**Comment by manoth-msft** [comment]
Closing due to the age of the issue report. Feel free to re-open or open new issue if problem persists.
