### ISSUE TITLE
link not available 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#202]
privacy in Microsoft office link not available,

so update new link  or remove it sir 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 047d2b74-e963-a006-cb74-29257c409647
* Version Independent ID: 4f274c79-18ae-2c36-19a3-cfb73d7e6cf3
* Content: [Privacy options in Office 2016](https://docs.microsoft.com/en-us/deployoffice/security/privacy-options-in-office#privacyoptions)
* Content Source: [DeployOffice/security/privacy-options-in-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/privacy-options-in-office.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
I've submitted a pull request to update the link's description. The link is working.
@DHB-MSFT Feel free to add label and close this issue
