### ISSUE TITLE
No Mention of Configuration Manager deployments

### ISSUE THREAD

**Issue by Skatterbrainz** [MicrosoftDocs/OfficeDocs-DeployOffice#203]
It would be helpful to provide additional information about deploying Project using Microsoft System Center Configuration Manager (Current Branch).  Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 696c19fd-3bf3-b148-57e3-f0203a036a80
* Version Independent ID: b97bfdbd-fe95-2bd1-0d40-2682cb7c1be6
* Content: [Deployment guide for Project](https://docs.microsoft.com/en-us/deployoffice/deployment-guide-for-project)
* Content Source: [DeployOffice/deployment-guide-for-project.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deployment-guide-for-project.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by Skatterbrainz** [comment]
I'm referring to Project 2016/365 only, since the link to 2019 does mention it.

**Comment by jwhit-MSFT** [comment]
Thanks for the feedback. We've captured this request in our backlog.
