### ISSUE TITLE
Feedback: ClickToRun is inferior to WSUS+MSI

### ISSUE THREAD

**Issue by thx1200** [MicrosoftDocs/OfficeDocs-DeployOffice#204]
ClickToRun uses more internet bandwidth, is more confusing, and provides a worse administrative experience than WSUS+MSI.  The stated reason is that it provides seamless cumulative updates to Office.  
This is proved false easily by the fact that Windows has switched to cumulative updates via WSUS channel.  Office could do the same.  There is no reason for Office to have its own update system.  In previous versions, MSI installers and updates existed, but in 2019 there is no option.  You either have to not upgrade or waste days learning the new update system and then maintaining it on a regular basis.

Maintaining an update channel outside Microsoft Update / WSUS must also cost Microsoft money to maintain.  

Office should abandon ClickToRun entirely and move back to Microsoft Update / WSUS.

Small companies may benefit with ClickToRun, but it is an unnecessary hassle to enterprises.  There is simply no reason that the small benefits of being able to stream Office while installing should outweigh enterprise needs for a single consistent update experience across all Microsoft products.

**Comment by DHB-MSFT** [comment]
Thanks for your feedback. I've sent it on to the Office engineering team responsible for Click-to-Run.
