### ISSUE TITLE
Shared Activation Issue

### ISSUE THREAD

**Issue by LionZum** [MicrosoftDocs/OfficeDocs-DeployOffice#205]
Is this document updated to reflect the steps required eluded to in the below issue?
I do not see any additional steps described beyond setting the key which is what caused our issues as well.
https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/142
For those searching for a resolution below is the script we performed that seems to be resolving the issue.
Script is being executed as a part of PSADT toolkit

		#Get Office bits
		If (Test-Path "$envProgramfiles\Microsoft Office\Office16\ospp.vbs"){
			$officebits = "$envProgramfiles\Microsoft Office\Office16"
		} Else{
			$officebits = "$envProgramFilesX86\Microsoft Office\Office16"
		}
		
		$officeitems = Get-WmiObject -Class SoftwareLicensingProduct -Property "ID, ApplicationId, PartialProductKey, Description, Name, ProductKeyID" -Filter "ApplicationID='0ff1ce15-a989-479d-af46-f275c6370663' and PartialProductKey &lt;&gt; NULL"
		
        Foreach ($office in $officeitems){
            $key = $office.PartialProductKey
			Execute-Process "cscript.exe" -Parameters "`"$officebits\ospp.vbs`" /unpkey:`"$key`""
		}

Question: Would users that activated before fixing the activation continue to have issues until their office credentials are cleared?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ab31873-7ad3-afde-3c72-8a7fb4f2e551
* Version Independent ID: 19f7f483-9f53-f577-1cd4-d360c0b234fc
* Content: [Overview of shared computer activation for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/overview-of-shared-computer-activation-for-office-365-proplus)
* Content Source: [DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by bally-singh** [comment]
Hi LionZum, 

Looks like someone has mentioned it here: 

https://docs.microsoft.com/en-us/deployoffice/troubleshoot-issues-with-shared-computer-activation-for-office-365-proplus

Under the closed comment, there is an issue with applying the GPO after activation has taken place...

**Comment by v-wayu** [comment]
We have users encountered the same issue. When the computer has activated Office with the normal method before, there will be a local license in the machine. SCA cannot create a license token if there are local licenses and Office shows as Unlicensed. The license needs to removed first with OSPP tool. When will this KB be updated and include this?

**Comment by manoth-msft** [comment]
I've submitted pull request #736 to update the documentation on this issue. It is linking off to a description on how to reset activation. Thanks for bringing this up.
@DHB-MSFT Please label and close
