### ISSUE TITLE
provide guidance on using ForceAppShutdown when performing a silent upgrade with RemoveMSI

### ISSUE THREAD

**Issue by TheBaban** [MicrosoftDocs/OfficeDocs-DeployOffice#206]
If we upgrade silently (Display Level=None) using REMOVEMSI=ALL, we should recommand to use ForceAppShutdown=TRUE to make that upgrade successful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d5595cb-3513-fca5-be7c-ec7652c73115
* Version Independent ID: 6f6f02e0-10a9-dbac-7747-a5dc5f395a35
* Content: [Remove existing MSI versions of Office when upgrading to Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/upgrade-from-msi-version)
* Content Source: [DeployOffice/upgrade-from-msi-version.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/upgrade-from-msi-version.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by TheBaban** [comment]
Do you have an update regarding this update of the documentation?

**Comment by manoth-msft** [comment]
The requested piece is covered in the "Configuration options" article which is linked at the bottom. As the article is not calling out Displaylevel=None, we will not add this piece here as it would make the doc harder to read.
