### ISSUE TITLE
Won't install together with Office 365 ProPlus

### ISSUE THREAD

**Issue by Gabriel-Lacatus** [MicrosoftDocs/OfficeDocs-DeployOffice#207]
Downloaded ProjectPro2019Volume as part of the benefits from the MS Partner program. Installer stops with the message 'We can't install: To install this product, first uninstall the following product(s) and try again".
I already have the Office Suite installed as part of Office 365 ProPlus and also Visio 2016 for Office 365. As per this guide: https://docs.microsoft.com/en-us/DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer?toc=/deployoffice/office2019/toc.json#example-installation-scenarios I should be able to install Project Professional 2019 (see second to last example installation scenario in the list) because my existing Office installation is at version 1811 where at least 1808 is required.

Please assist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [Deploy Office 2019 (for IT Pros)](https://docs.microsoft.com/en-us/DeployOffice/office2019/deploy)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by BavoB** [comment]
I encounter a similar problem: I have some Office (2016) ProPlus programs installed, without Visio/Project - I was trying to combine these with Visio/Project Professional 2019, but I also get the uninstall message, although there are only click-to-run Office versionz on my machin, no MSI...
Any useful info regarding this is welcome.

**Comment by githubsteveb** [comment]
Just encountered this. 

I have the following currently installed: 
- Office 365 Pro Plus
- Project for O365 1903

Trying to install the following ODT:
- VisioPro2019Volume

Received error:
![Error](https://user-images.githubusercontent.com/38283300/55814762-1521e980-5ae7-11e9-9808-95a47085e326.jpg)

**Comment by githubsteveb** [comment]
UPDATE! Looks like I've resolved my issue. The key config in the xml was to match whatever my ProPlus update channel is. As I am in the the Targeted channel, i updated the xml from "Monthly" to "Targeted" and boom - VisioVolume installed! :)

```
<Configuration>
  <Add	OfficeClientEdition="64"
	Channel="Targeted" >
    <Product	ID="VisioPro2019Volume".......
```

**Comment by DHB-MSFT** [comment]
@githubsteveb -- Yep, that's correct. Sorry I didn't reply sooner with that info. We do mention that info in the 4th paragraph here -- [Update channel for Office 2019](https://docs.microsoft.com/en-us/DeployOffice/office2019/update#update-channel-for-office-2019), but admittedly that's probably hard to find. We'll see if we can put that info in a more prominent place. Thanks.

**Comment by githubsteveb** [comment]
> @githubsteveb -- Yep, that's correct. Sorry I didn't reply sooner with that info. We do mention that info in the 4th paragraph here -- [Update channel for Office 2019](https://docs.microsoft.com/en-us/DeployOffice/office2019/update#update-channel-for-office-2019), but admittedly that's probably hard to find. We'll see if we can put that info in a more prominent place. Thanks.

Thanks! I think it was the original error message that threw me - about uninstallng pro plus etc! Perhaps a slight update to that would be beneficial/or a error detection catch. Cheers.

**Comment by scromar** [comment]
I've got a similar error, and the issue doesn't seem to be an incorrect update channel. I've currently got Office Professional Plus 2019 installed, but it is not the volume licensed version, it is the version that comes from Microsoft's HUP. When I try to install VisioPro2019Volume, with the update channel set to PerpetualVL2019, I get an error similar to the one shown above: "To install this product, first uninstall the following product(s) and try again. Microsoft Office Professional Plus 2019 - en-us". I don't see anything in the docs that shed light on this issue. Thanks.

**Comment by manoth-msft** [comment]
Closing due to the age of the issue report. Feel free to re-open or open new issue if problem persists.
