### ISSUE TITLE
How did it come to this mess and when is it going to stop?

### ISSUE THREAD

**Issue by Gabriel-Lacatus** [MicrosoftDocs/OfficeDocs-DeployOffice#208]
We license Office 365 through our resellers and let people install the Office desktop apps. Then, we also have various benefits (e.g. Visio, MS Project, etc.) coming from our MS Partner program certifications which seem to be incompatible with the 365-sourced apps. In other words, we are unable to benefit from what we are entitled to because of this complete and utter mess.
While I can understand that there were some (uninspired) technical decisions, I can see that very little seems to be done about it and it keeps going and going for all new versions. As Microsoft customers which license our software from different channels (whether is retail, volume license or other) I expect to be able to use these products that we license. Alternatively you should provide equivalent variants that are compatible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d40c96f3-1c97-b538-ef82-ffbf0eef204d
* Version Independent ID: 2d6883b5-1b5c-dc16-9999-17d0652bfa48
* Content: [Supported scenarios for installing different versions of Office, Project, and Visio on the same computer](https://docs.microsoft.com/en-us/deployoffice/install-different-office-visio-and-project-versions-on-the-same-computer)
* Content Source: [DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by KasJensen** [comment]
Adressed in PR #212 and #211 
In short, you can mix and match them, as long as Office 365 ProPlus is 1808 or newer (Semi-Annual, Targeted as of december 2018), and as long as the update channels are identical across all Office products installed.
Visio 2019 and Project 2019 support the same update channels as Office 365 ProPlus.

The issue is that you need to specify the update channel in the configuration.xml, as Visio and Project 2019 are set to the PerpetualVL2019 update channel by default, with no GUI at install time to change that.

**Comment by CSCIT** [comment]
Addressed, Yes... but I still have the exact same concern and complaint that Gabriel has. We pay a significant amount of money for our 365 plan with Pro Plus and didn't realize the amount of headaches we would get from the incompatibility issues with other VL applications purchased over the past 4 years through other licensing channels. Today, even with 2019 versions with the supposed "click-to-run" fix that has been rolled out we are getting incompatibility errors during the installation.

What I have determined: Microsoft is NOT allowing you to install Office 365 (any upgrade channel) with other non-subscription based Microsoft apps. We have kept up on our SA for Project and Visio over the years and are at a point where we are only able to use them independently. What business user today can function without Office if they need to use Project and Visio? These are also the most expensive applications Microsoft sells which makes things even worse. I refuse to give in and pay a monthly subscription fee for a license we have religiously renewed our SA to ensure we get the latest versions.

**Comment by KasJensen** [comment]
Read the PRs again, please. I assure you, it works if you use compatible versions. 

My scenario: Office 365 ProPlus (subscription) . Visio 2019 (volume license) .
One XML for ProPlus, with update channel SemiAnnualTargeted. One XML for Visio with VL product key, also with update channel SemiAnnualTargeted. YOU DON'T HAVE TO USE PERPETUALVL2019.

Office 365 ProPlus 1808 SemiAnnualTargeted with Visio 2019 SemiAnnualTargeted WILL work on a clean machine, I assure you.
Otherwise you will need to open a support ticket, and not a docs issue.

**Comment by VashJuan** [comment]
Installing a Microsoft product is quickly becoming a full time profession. So many confusing options and now one needs to edit XML files. Uggg.

**Comment by jaYBuBo** [comment]
We are a non-profit and only needed the basic Office apps plus Skype for Business. With 2019, these 2 can't co-exist separately. There is no way we would want to subscribe to Office Pro Plus cause the cost is a lot after doing our sums. Anyone has tried to do this successfully?

**Comment by ichkoj** [comment]
MICROSOFT YOU SUCK BIG TIME
YOUR PRODUCTS ARE UNFINISHED THEY ARE LACKING QA and on top we can't even USE THEM 
YOU REALLY SUCK!!!!

**Comment by ichkoj** [comment]
Microsoft the SOFTWARE company has products created by them but you can't install them on one machine.... fire your developers and product manager and start over

**Comment by stevebauman** [comment]
Man this whole install process of mixing and matching is an absolute mess, honestly. 

Why do I need to edit XML files and run the installer from command line? Was an .ISO with a key that much of a problem? Older versions of office I literally just clicked setup.exe and everything worked, all I had to do was check that the architecture matched. Now this process is being immensely overcomplicated for barely any benefit.

I get the architecture differences (32-bit vs 64-bit) -- but there are way too many versions:

1. Volume Licensed (32-bit / 64-bit)
2. Click-to-run (32-bit / 64-bit)
3. Microsoft Store (32-bit / 64-bit)
4. Windows Installer (MSI) (32-bit / 64-bit)
5. Professional or Standard (32-bit / 64-bit)

Please stop this -- bring me back to the simpler times when all I needed was a key and .ISO 😭

**Comment by jaYBuBo** [comment]
> Did this get fixed? Hope so!

I'm betting on it... NOT. We had to find workarounds to it and it's a pain. There is no way they are going to fix it. We are just forced to live with it. I don't get how they think its ok for Office 2016 and 2019 to have the same major version number hence causing all the issues in the first place. So now just to ensure compatibility, if I have an Office 2019, I cannot install any 2016 version of the standalone apps. It's just wrong and Microsoft doesn't give a damn.

**Comment by ichkoj** [comment]
@jaYBuBo  I'm dealing with MSFT mess on daily basis, cloud and on prem and I really hated their support A LOT. MSFT and ATT were competing for my top 10 hated companies. But I have to admit during the COVID lockdown they increased their O365 support staff and turn around times are probably shortened with 50-70%. It is HUGE increase in response times. Don't get me wrong, we are still having problems with incompetence and people there not knowing the product!!! 
My point is that there is a hope out there for these guys to start listen and start USING LOGIC!!!!
