### ISSUE TITLE
Update Channel for Office 2019 together with Office 365 1808 

### ISSUE THREAD

**Issue by robgrame** [MicrosoftDocs/OfficeDocs-DeployOffice#210]
Even though documentation on Update Channel for Office 2019 section states "“PerpetualVL2019” is the only supported update channel for Office Professional Plus 2019 and Office Standard 2019. It's also the default update channel for volume licensed versions of Project 2019 and Visio 2019"
Later in the same section it states "If you’re deploying a volume licensed version of Project 2019 or Visio 2019 along with Office 365 ProPlus, you should specify the same update channel for Project 2019 and Visio 2019 that you’re using for Office 365 ProPlus. For example, “Monthly” for Monthly Channel or “Broad” for Semi-Annual Channel"
I'm not able to install Visio 2019 together with Office 365 1808, and in addition I don't understand wich update channel I should  use for this scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f5cfe20-90ad-3f7e-8ae8-ff99bd1e1b55
* Version Independent ID: 97b2760a-50a2-f7c0-32ab-20b0420838d1
* Content: [Update Office 2019 (for IT Pros)](https://docs.microsoft.com/en-us/deployoffice/office2019/update)
* Content Source: [DeployOffice/office2019/update.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/update.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by robgrame** [comment]
Thanks Kas, indeed. 
I've been able to solve this issue the same day using the following config file:
<Configuration>
  <Add OfficeClientEdition="64" Channel="Targeted" OfficeMgmtCOM="TRUE" AllowCdnFallback="TRUE" ForceUpgrade="TRUE">
    <Product ID="O365ProPlusRetail">
      <Language ID="it-it" />
      <ExcludeApp ID="Groove" />
      <ExcludeApp ID="OneNote" />
    </Product>
    <Product ID="VisioPro2019Volume">
      <Language ID="it-it" />
      <ExcludeApp ID="Groove" />
    </Product>
    <Product ID="ProjectPro2019Volume">
      <Language ID="it-it" />
    </Product>
  </Add>
  <Property Name="AUTOACTIVATE" Value="1"/>
  <Property Name="FORCEAPPSHUTDOWN" Value="TRUE"/>
  <Property Name="SharedComputerLicensing" Value="0" />
  <Property Name="PinIconsToTaskbar" Value="TRUE" />
  <Property Name="SCLCacheOverride" Value="0" />
  <RemoveMSI All="TRUE" />
  <Display Level="Full" AcceptEULA="TRUE" />
  <Logging Level="Standard" Path="%TEMP%" />
</Configuration>

**Comment by rasldasl** [comment]
Having issues with this as well, going from O365 to VL2019. Even though Visio and Project were never installed they are detected by the installer.

**Comment by manoth-msft** [comment]
Closing due to the age of the issue report. Feel free to re-open or open new issue if problem persists.
