### ISSUE TITLE
Installing Office H&B 2016 Retail with Project STD 2016 Volume

### ISSUE THREAD

**Issue by dcallejas1** [MicrosoftDocs/OfficeDocs-DeployOffice#213]
I got a Office H&B 2016 Retail, and a Project STD 2016 Volume, need to install both in a same machine, I reached for support and they gave me a several steps with Office Deployment Tool but it didn´t work, some of you can guide me how can I edit the XML file and achieve the installation.

**Comment by manoth-msft** [comment]
Closing due to the age of the issue report. Feel free to re-open or open new issue if problem persists.
