### ISSUE TITLE
Mac paths are forward slashes (virgules)

### ISSUE THREAD

**Issue by talkingmoose** [MicrosoftDocs/OfficeDocs-DeployOffice#215]
Your Mac documentation refers to file/directory paths using backslashes (e.g. Library\Containers). Onl Windows uses backslashes for paths. Correct pathing for Unix systems uses forward slashes or virgules (e.g. ~/Library/Containers). And a tilda denotes a user’s home folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c591bb82-b0e8-987b-cac0-720efe120b3b
* Version Independent ID: 9065cc8a-2c6e-3cfc-8d52-f5b0ebc927ad
* Content: [Deploy preferences for Office for Mac](https://docs.microsoft.com/en-us/DeployOffice/mac/deploy-preferences-for-office-for-mac)
* Content Source: [DeployOffice/mac/deploy-preferences-for-office-for-mac.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/mac/deploy-preferences-for-office-for-mac.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@talkingmoose -- Thanks for pointing that out. We've updated the article accordingly.
