### ISSUE TITLE
standalone

### ISSUE THREAD

**Issue by jparekh73** [MicrosoftDocs/OfficeDocs-DeployOffice#217]
When pushing the standalone EXE (i.e. SCCM) or running it manually (where the full MSI wasn't installed), the com-add in report does not work. If we run it on a machine where the MSI was installed and push the command line via SCCM, it works. So do we need to install the full MSI on the PCs first prior to running the scan commands?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2843afe2-a11d-7d88-8b56-24f131782d01
* Version Independent ID: f8bc6a27-b9f5-a729-b5e3-fdd9ac6642ed
* Content: [Use the Readiness Toolkit to assess application compatibility for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro)
* Content Source: [DeployOffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by jparekh73** [comment]
> Yes, you will need to install the full MSI. This is required to help the Readiness Toolkit identify certain add-ins installed that may be installed on the device.

This line is confusing then and should be more explicit on the MSI install requirements.
"There is also a standalone executable that can be run from the command line or used with scripts"

**Comment by tomdoyle-msft** [comment]
Since version 1.2.19184 (released July 4th), you no longer need to install the full MSI and can run the toolkit standalone.

**Comment by madhupn** [comment]
is there any resource to learn more about how the standalone can be deployed and run through SCCM?

**Comment by manoth-msft** [comment]
We are working on providing additional information on how to automate the unattended execution of the ORT.

**Comment by manoth-msft** [comment]
Closing due to the age of the issue report. Feel free to re-open or open new issue if problem persists.
