### ISSUE TITLE
Office 2019 Proffing Tools for normal people (non-Pros)

### ISSUE THREAD

**Issue by jevgenij-martynenko** [MicrosoftDocs/OfficeDocs-DeployOffice#218]
How can home user install additional Office 2019 proffing tools?
All links in the product itself redirect here, but we can't expect ordinary users editing XML files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [Deploy Office 2019 (for IT Pros)](https://docs.microsoft.com/en-us/DeployOffice/office2019/deploy#install-office-2019-by-using-system-center-configuration-manager)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by AKr0nizz** [comment]
Same, highly required feature.

**Comment by jwhit-MSFT** [comment]
Thanks for the feedback--we'll investigate and respond soon.

**Comment by jwhit-MSFT** [comment]
The best article for home users on language packs is [here](https://support.office.com/en-us/article/change-the-language-office-uses-in-its-menus-and-proofing-tools-f5c54ff9-a6fa-4348-a43c-760e7ef148f8). As you likely saw, there's no simple way to download just proofing tools--that requires the Office Deployment Tool, which is designed for deploying in enterprise environments.  It'd be good to get details on your scenario in which this is a highly required--I can pass those along to the product team. Thanks!

**Comment by Vitt1958** [comment]
Just go to https://www.microsoft.com/de-DE/download/details.aspx?id=52668, select your language an enjoy the installation of the MS Office proofing tool you require.

**Comment by AKr0nizz** [comment]
> Just go to https://www.microsoft.com/de-DE/download/details.aspx?id=52668, select your language an enjoy the installation of the MS Office proofing tool you require.

Seems, it is made for Office 2016 and does not work if Office 2016 is not installed in the system. 
After installing it still, want's me to download proofing tools.  Made all possible obvious things like rebooting and resetting, etc.

**Comment by AKr0nizz** [comment]
> The best article for home users on language packs is [here](https://support.office.com/en-us/article/change-the-language-office-uses-in-its-menus-and-proofing-tools-f5c54ff9-a6fa-4348-a43c-760e7ef148f8). As you likely saw, there's no simple way to download just proofing tools--that requires the Office Deployment Tool, which is designed for deploying in enterprise environments. It'd be good to get details on your scenario in which this is a highly required--I can pass those along to the product team. Thanks!

Yeah, sure. I've got MS Office 2019 key from the reseller. After that installed the Office from retail ISO delivered from the official MS CDN. The System (Windows 10) default language is English and the Office language is English. 

So now I need to install proofing tools for Polish, Russian and Spanish. 

When I start typing in a mentioned above languages, I can see a message: Missing Proofing Tools and a button: Download. 

If I press it, it redirects me to:
[https://support.office.com/en-gb/article/language-accessory-pack-for-office-82ee1236-0f9a-45ee-9c72-05b026ee809f?ui=en-US&rs=en-GB&ad=GB](https://support.office.com/en-gb/article/language-accessory-pack-for-office-82ee1236-0f9a-45ee-9c72-05b026ee809f?ui=en-US&rs=en-GB&ad=GB)

After reading the manual I go to Settings > Languages and add the languages I require. The proofing status is "Not installed" and it is the hyperlink.

 If I press it, it redirects me to:
[https://support.office.com/en-gb/article/language-accessory-pack-for-office-82ee1236-0f9a-45ee-9c72-05b026ee809f?ui=en-US&rs=en-GB&ad=GB](https://support.office.com/en-gb/article/language-accessory-pack-for-office-82ee1236-0f9a-45ee-9c72-05b026ee809f?ui=en-US&rs=en-GB&ad=GB)

That is basically the same page.

**Comment by Vitt1958** [comment]
My above link works well with Office 365. I procced the Installation of an additional proofing tool as follows:
1. I have installed Office 365 (perhaps it works with Office 2019)
2. I added the appropriate language in Word (after this step no realy installation was done - the proofing tool is marked as needed but not installed)
3. I have installed the proofing tool via the https://www.microsoft.com/de-DE/download/details.aspx?id=52668 link (after I have select the apropirate languge, the site appeared in that selected language. After it I selected the proofing tool and after a short time (3 seconds) I got the proofing tool in my selected language. I have restarted Word and can now use the added proofing tool).

**Comment by jevgenij-martynenko** [comment]
@vitt1958 the issue applies to Office 2019, not Office 365 ProPlus

**Comment by kecskemethy** [comment]
download necessary Language Accessory Pack for Office 365 from:
(choose appropriate language and bit-version)
https://g.microsoftonline.com/0BX20en/1464

**Comment by jevgenij-martynenko** [comment]
> download necessary Language Accessory Pack for Office 365 from:
> (choose appropriate language and bit-version)
> https://g.microsoftonline.com/0BX20en/1464
This is the same URL that was given in comments before and does not solve the issue

**Comment by mkenny1000** [comment]
@jevgenij-martynenko can you tell me exactly the steps you are following please? I have Office 2019 installed and can install the language accessory packs using this link:
https://support.office.com/en-gb/article/language-accessory-pack-for-office-82ee1236-0f9a-45ee-9c72-05b026ee809f?ui=en-US&rs=en-GB&ad=GB

Just select the language that you want from the drop down, then choose the appropriate pack (64 or 32 bit) and download and run it. When the installation completes, follow from step 2 onwards.

**Comment by SAMT979** [comment]
Just go to https://www.microsoft.com/de-DE/download/details.aspx?id=52668  select your language and download, then
run the .exe file in compatibility mode for windows 7 and it will work 100%
