### ISSUE TITLE
Documentation is wrong for SourcePath functionality

### ISSUE THREAD

**Issue by lucky24lx** [MicrosoftDocs/OfficeDocs-DeployOffice#222]
Tested in most recent build. Documentation states that leaving off the Add element's SoucePath element will cause the /download flag to download the files to the local path is incorrect. It actually attempts to download it to the %userprofile%\appdata\local\temp folder, but never actually places the downloaded files there, and exits silently with no errors in the log file. Thus the SourcePath element is required when using /download

Additionally, running /configure works even if /download has not been run (Office will be installed successfully by downloading a temporary installer to the %temp% folder), but if /download *has* been run and there are *some* files downloaded into the \Office folder, but not the ones needed for the current /configure file (E.G. different architecture x86 vs x64), running /configure will fail without putting anything into the log file, and will display an error to the screen (if not run in silent mode): error 30028-1021. This is even though there's obviously code to do a temporary download if the source files aren't found in the \Office\ subfolder. This should be made more consistent.

**Comment by jwhit-MSFT** [comment]
Thanks for the detailed feedback. I'll investigate and respond soon.

**Comment by jwhit-MSFT** [comment]
For the first issue, I ran a test on the latest version of the ODT and the files downloaded correctly without a sourcepath specified. Perhaps there was another issue in the configuration file? For the second issue, I'll pass the comments on to the engineering team that owns the tool, so they can investigate. Thanks again.
