### ISSUE TITLE
ODT does not support Retail edition with ISO.

### ISSUE THREAD

**Issue by ericbl** [MicrosoftDocs/OfficeDocs-DeployOffice#225]
I have a Visual Studio Entreprise subcription with keys for the Retails editions of Office2019.
I almost lost one full day fighting with ODT to install Office2019ProPlus Retails in order to exclude some application.
I installed and uninstalled Office and Visio more than 5 times!
ODT seems to support only volume and O365 licenses, but not the retails keys. 

I tried with direct install (CDN), previous download, and also specifying the mounted ISO file as source. No installation was compatible with my keys.

Eventually, I found the help on external forum (mydigitallife) with one member proposing this script:
https://github.com/abbodi1406/WHD/blob/master/scripts/YAOCTRI_v4.0.zip
Simple, straightforward, I could install Office2019ProPlusRetail excluding some app and installing Visio together.

Why the hell is Microsoft making stuff so complicated? Why can't we have a simple switch on the main setup (from the ISO) where we could choose all these options?
Installing the older Office (95-2010) used to be much simpler, with the installer offering the option which app to install.

I wonder how many work hours are lost in all companies world wide with the current complicated installer (where no option is available)? Only in my company, I saw many colleagues fighting for hours to understand which version to install and how.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [Deploy Office 2019 (for IT Pros)](https://docs.microsoft.com/en-us/deployoffice/office2019/deploy)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by ItzLevvie** [comment]
To me it seems like you're trying to use the PIDKEY attribute on a Retail edition which would never work as it was meant and made specifically for Volume editions. If that's not what you did then please share the configuration file you've used to deploy Office 2019 (Retail) + Visio 2019 (Volume) on your system but failed.

ODT configurations I have used below yielded no issues and deployed successfully.

1)
```
<Configuration>
  <Add OfficeClientEdition="64">
    <Product ID="ProPlus2019Retail">
      <Language ID="en-us" />
    </Product>
    <Product ID="VisioPro2019Volume">
      <Language ID="en-us" />
    </Product>
  </Add>
</Configuration>
```

2)
```
<Configuration>
  <Add SourcePath="D:\ProPlus2019Retail_from_ISO" OfficeClientEdition="64">
    <Product ID="ProPlus2019Retail">
      <Language ID="en-us" />
    </Product>
    <Product ID="VisioPro2019Volume">
      <Language ID="en-us" />
    </Product>
  </Add>
</Configuration>
```

**Comment by ericbl** [comment]
Please clearly mention in the docs that PIDKEY attribute is NOT supported on a Retail edition!

I now tried a similar configuration file as yours for DVD, and always get the error message:
"Couldn't install
We can't continue because we aren't able to download a required file".

`<Configuration>
  <Add SourcePath="H:" OfficeClientEdition="64">
    <Product ID="ProPlus2019Retail">
      <Language ID="en-us" />
      <Language ID="fr-fr" />
      <Language ID="de-de" />
      <ExcludeApp ID="Groove" />
      <ExcludeApp ID="OneNote" />
      <ExcludeApp ID="OneDrive" />
      <ExcludeApp ID="Lync" />
      <ExcludeApp ID="Access" />
      <ExcludeApp ID="Outlook" />
    </Product>
    <Product ID="VisioPro2019Retail">
      <Language ID="en-us" />
      <Language ID="fr-fr" />
      <Language ID="de-de" />
      <ExcludeApp ID="Groove" />
      <ExcludeApp ID="OneDrive" />
    </Product>
  </Add>
  <Property Name="PinIconsToTaskbar" Value="TRUE" />
  <Property Name="SCLCacheOverride" Value="0" />
  <Updates Enabled="TRUE" />  
  <RemoveMSI All="TRUE" />
</Configuration>`


I then tried again without specifying the  SourcePath, so the installer downloaded all again and installed first the retail version, but then when I wanted to active it, I did not get the chance to enter my key. I then got an update which switched my Office installation to Office 365. And the configuration file was ignored, I got all app (e.g. incl. Access) installed.
What the hell is going on here? It just confirm the installer does not want the Retail edition.
So I have again to uninstall Office2019!

Back to the YAOCTRI_v4.0 tool, I first tried specifiy the SemiAnnual channel with Retail. But again got an issue with the update: after the installation, everything worked fine, but the update downgraded the dvd RTM edition (16.0.10730) to a preview version 16.0.9126.2336, still on Retail though.
I just tried with the monthly channel on retail, but again, once the installation was finished, the update switch my installation to Office 365 ProPlus with all app installed.

So I am out of my options, I see no way to keep Office 2019 Retail, so I am giving up and will try my chance with Office 2016...
