### ISSUE TITLE
E1 user using computer used by a E3 user

### ISSUE THREAD

**Issue by toxarisswe** [MicrosoftDocs/OfficeDocs-DeployOffice#229]
Hello.

Let´s say we have a computer that is used by two user. User1 is licensed with E1 and User2 is licensed with E3. Will the User1 be able to use Office with full functionality as long as User2 refresh the grace period?

I guess its not possible but when I test this scenario, it seams to work that way. All thou I haven't tested for a longer period of time som I'm not sure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3c236da-c63a-f789-f1b6-7aeb41f16c1f
* Version Independent ID: 35319bac-d94f-832c-ce79-41bffe5c8d25
* Content: [Overview of licensing and activation in Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/overview-of-licensing-and-activation-in-office-365-proplus)
* Content Source: [DeployOffice/overview-of-licensing-and-activation-in-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-licensing-and-activation-in-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by Craig-Lisovich** [comment]
Does this end up being a violation of the license agreement?  Has there been a way found to resolve this issue?

**Comment by MJP-MSFT** [comment]
I cannot answer any legal questions regarding the licensing agreement. I would ask that you contact your Microsoft account executive and they will put you in contact with a licensing executive.

From the technical aspect you will see after the E3 users activates office and the E1 user signs in that office says Belongs to the E3 users UPN. In Office 365 ProPlus version 1910 and greater this will not be an issue anymore based on the Licensing improvements mentioned in the above article.
