### ISSUE TITLE
Exclusion option

### ISSUE THREAD

**Issue by wrooot** [MicrosoftDocs/OfficeDocs-DeployOffice#231]
I can't test this preview myself, so maybe it is already possible, but it would be useful to have an option to exclude some groups if you apply a policy to some main root group, which combines all users. Because some users might need macros and so on.

---
#### Išsami dokumento informacija

⚠ *Neredaguokite šio skyriaus. To reikia docs.microsoft.com ➟ „GitHub“ problemoms sieti.*

* ID: dfa63a94-daaa-9491-213e-f0329f6299b1
* Version Independent ID: 47fe5a3a-ee7c-a7f7-b913-ca0ac3c063e0
* Content: [Overview of the Office client policy service (Preview) for Office 365 ProPlus](https://docs.microsoft.com/lt-lt/DeployOffice/overview-office-client-policy-service)
* Content Source: [DeployOffice/overview-office-client-policy-service.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-office-client-policy-service.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by chhopkin** [comment]
Exclusion is not a capability in the preview but it is a feature that we are considering.
