### ISSUE TITLE
How to use ODT with Office 2019 ProPlus Retail img?

### ISSUE THREAD

**Issue by rido-ramadan** [MicrosoftDocs/OfficeDocs-DeployOffice#232]
I want to exclude Skype for Business and Access (and many more), since my company don't use it. I got a license key, but when I tried using ODT, ater I successfully install it, my key is considered invalid.

I made my own ODT:
```xml
<Configuration>
  <Add OfficeClientEdition="64"
       Channel="PerpetualVL2019"
       AllowCdnFallback="TRUE"
       ForceUpgrade="TRUE">
    <Product ID="ProPlus2019Volume" PIDKEY="25_digit_from_my_provider">
      <Language ID="MatchOS" />
      <ExcludeApp ID="Groove" />
      <ExcludeApp ID="OneNote" />
      <ExcludeApp ID="OneDrive" />
      <ExcludeApp ID="Lync" />
      <ExcludeApp ID="Access" />
    </Product>
  </Add>
  <Property Name="SharedComputerLicensing" Value="0" />
  <Property Name="PinIconsToTaskbar" Value="FALSE" />
  <Property Name="SCLCacheOverride" Value="0" />
  <Updates Enabled="TRUE" />
  <RemoveMSI All="TRUE" />
  <AppSettings>
    <User Key="software\microsoft\office\16.0\word\options" Name="mapstdsizes" Value="1" Type="REG_DWORD" App="word16" Id="L_AllowA4Letterpaperresizing" />
  </AppSettings>
  <Logging Level="Off" />
</Configuration>
```

But it failed. Instead he gave me .img file to install, however, I still want to exclude those apps. What do I do?

**Comment by RAJU2529** [comment]
@rido-ramadan. Replace  " "25_digit_from_my_provider"   to  WRSTF-RYB23-WLIXA-LIKE2-THIS6


replace  with "WRSTF-RYB23-WLIXA-LIKE2-THIS6"  with your real product key

**Comment by manoth-msft** [comment]
The configuration likes legit. I would recommend to use config.office.com to build the XML, if it still does not work, work with the provider of the PIDKey to double check if it is actually an Office 2019 VL key.

Do to the age of this issue I will close it for now. Feel free to re-open or open a new issue.
