### ISSUE TITLE
Office Client KMS activation diagnostic tool

### ISSUE THREAD

**Issue by bakinnan** [MicrosoftDocs/OfficeDocs-DeployOffice#234]
I followed the instructions on the diagnostic tool, but the tool doesn't work for Office 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d5eff63-106d-9679-a548-6f68b30d712b
* Version Independent ID: b8c1d0db-a564-48b7-3d2b-c5aec5ab0d46
* Content: [Troubleshoot volume activation of Office](https://docs.microsoft.com/en-us/deployoffice/vlactivation/troubleshoot-volume-activation-of-office)
* Content Source: [DeployOffice/vlactivation/troubleshoot-volume-activation-of-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/vlactivation/troubleshoot-volume-activation-of-office.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
@DHB-MSFT 1 year old, can we close?

**Comment by bakinnan** [comment]
Yes
