### ISSUE TITLE
change the sentance

### ISSUE THREAD

**Issue by jrani1006** [MicrosoftDocs/OfficeDocs-DeployOffice#235]
change the sentance (표준 2019 프로젝트 ==&gt; Project Standard 2019)

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: da0ced28-ffb1-1924-6fc7-24265bc95c42
* Version Independent ID: b261a792-c076-2221-65f0-1d2ac52fef7a
* Content: [Office 2019 (IT 전문가 위한) 개요](https://docs.microsoft.com/ko-kr/deployoffice/office2019/overview#feedback)
* Content Source: [DeployOffice/office2019/overview.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice-pr.ko-KR/blob/live-sxs/DeployOffice/office2019/overview.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
Unfortunately we were not able to identify the actual ask. Due to the ague of this issue report, I will close it for now. Feel free to open a new issue if problem persists.
