### ISSUE TITLE
"the top level Configuration Manager site server must have internet access" requirement is too broad

### ISSUE THREAD

**Issue by davidpaMSFT** [MicrosoftDocs/OfficeDocs-DeployOffice#238]
"the top level Configuration Manager site server must have internet access" requirement should be replaced with the list of specific URLs required for Office 365 updates to sync. This is because giving top level site server "internet access" for (sole) purpose of Office 365 updates sync is hard to justify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44a78111-ae98-5b26-b349-3e62960f02c4
* Version Independent ID: 23052a9d-431b-1367-791f-ef2f137d4c47
* Content: [Manage updates to Office 365 ProPlus with System Center Configuration Manager](https://docs.microsoft.com/en-us/DeployOffice/manage-updates-to-office-365-proplus-with-system-center-configuration-manager#requirements-for-using-configuration-manager-to-manage-office-365-client-updates)
* Content Source: [DeployOffice/manage-updates-to-office-365-proplus-with-system-center-configuration-manager.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/manage-updates-to-office-365-proplus-with-system-center-configuration-manager.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by noriko-nishhimura0677** [comment]
Thank u a lot,too.

**Comment by davidpaMSFT** [comment]
Thank you J Whitmarsh for looking into this. Unfortunately, these are very broad. Please keep in mind that software updates are normally synced by a Software Update Point (SUP) site system which communicates with WSUS which in turns communicates with Microsoft endpoints. However, Office 365 updates are the only ones that require the server hosting the Site Server role (not the SUP/WSUS) to have Internet access. Since most of the Office 365 update sync is still done by WSUS, based on observation the site server itself only needs access to very limited number of URLs. In another doc issue item it was mentioned by Microsoft Sr. Support Escalation Engineer that "only officecdn.microsoft.com was required prior to CM1806. CM1806 and above also require config.office.com". Is there a way to have this confirmed in order to "better explain our guidance relating to these wildcards" as noted in row 78 of the article you referenced?

**Comment by jwhit-MSFT** [comment]
I'll review with the engineering team and update as needed--thanks for the input.
