### ISSUE TITLE
Live view configuration

### ISSUE THREAD

**Issue by erottier** [MicrosoftDocs/OfficeDocs-DeployOffice#239]
Who designed this new interface?? Never change a winning team they say. Well they did and it is not good.

What I miss: A clear interface that shows me the configuration in a live window. 90% of the time I come to that page to look at how something is spelled when changing something in the config file. I DO NOT want to download the file and edit it to see what I want!

What I find fugly: All new interfaces are designed to be touch friendly or something. I'd like an interface that is sleek (like the old site who is now disabled!!) small and usable on large high res monitors. Like about 90% of the users of this site.

Please, please make it like the old site and everyone can be happy again.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 67f2376c-177b-110f-9c88-f83d53bd6bc7
* Version Independent ID: a98d74e5-f7dc-c073-4cb9-a8901895a89a
* Content: [Overview of the Office Customization Tool](https://docs.microsoft.com/nl-nl/DeployOffice/overview-of-the-office-customization-tool-for-click-to-run)
* Content Source: [DeployOffice/overview-of-the-office-customization-tool-for-click-to-run.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-the-office-customization-tool-for-click-to-run.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by jwhit-MSFT** [comment]
Hi erottier--Thanks for the feedback--it's always important for us to hear what's not working for customers. I've given your feedback to the engineering team. Sorry for the frustration--
Jason
