### ISSUE TITLE
RDS w/ O365 clarify license requirements

### ISSUE THREAD

**Issue by dfw111** [MicrosoftDocs/OfficeDocs-DeployOffice#240]
[https://docs.microsoft.com/en-us/DeployOffice/deploy-office-365-proplus-by-using-remote-desktop-services](url)

I would like to see clarification around this bullet point. Specifically, what are the licensing requirements regarding running Office 365 E3/E5 users on a Remote Desktop Services server. Do we need any additional/separate license of Office ProPlus? And is Server 2016 a minimum requirement or can we run 2012R2? 

> A supported version of RDS or Windows with Office 365 ProPlus, which includes any of the following:
    Windows 8.1
    Windows Server 2016
    Currently supported Windows 10 SAC release

**Comment by manoth-msft** [comment]
@DHB-MSFT Can we update the article to just link off to the System requirements?

**Comment by manoth-msft** [comment]
Thanks for the feedback. We submitted PR #811 to address this issue and clarify the system requirements.
