### ISSUE TITLE
Missing 1803 9126.2351 in OCT

### ISSUE THREAD

**Issue by vidmantask** [MicrosoftDocs/OfficeDocs-DeployOffice#242]
Missing last Office365 version released (2019.01.08) 1803 9126.2351 in Office Customization Tool in [web](https://config.office.com/) and SCCM.

I already made installation by selecting 9126.2336 and changed in .xml to 2351 then made application in SCCM. But just curious is it working as intended? Because i want to use SCCM Office365 Installer.
![image](https://user-images.githubusercontent.com/46774280/51300711-906a8680-1a35-11e9-8f97-45f42f69ea35.png)

Vidmantas

**Comment by DHB-MSFT** [comment]
@vidmantask  -- thanks for bringing this to our attention. The teams responsible for the tools are investigating. We'll get back to you when we know more.

**Comment by vidmantask** [comment]
Tool no longer supported ?
![image](https://user-images.githubusercontent.com/46774280/52766898-635bc480-3031-11e9-8d84-4eb7bb66df67.png)

**Comment by DHB-MSFT** [comment]
@vidarmsft  -- apologies for not getting back to you sooner. Currently the tool is updated twice a week, so there might be a lag between when a version/build is released and when it appears in the drop-down list. It appears this has been the case for builds released on Patch Tuesday (2nd Tuesday of every month). The team responsible for the tool is aware of this issue (as well as the absense of Version 1708 in the list) and is actively looking to improve their proccesses for updating this tool with the all the relevant versions/builds in a more timely manner  Thanks again for your feedback to make this tool better and more useful for customers.

**Comment by vidmantask** [comment]
@DHB-MSFT Thank you for information.

**Comment by vidmantask** [comment]
Tool was not updated as it should be...
1808 10730.2080 was added in about 7 days (Hooray). Other versions was not updated.
![image](https://user-images.githubusercontent.com/46774280/53714778-5e33ad80-3e58-11e9-843a-171a64f1ce81.png)
