### ISSUE TITLE
Les Licences Office 365 ProPlus en RDS, raisons techniques ou légales ?

### ISSUE THREAD

**Issue by DidierCunillera** [MicrosoftDocs/OfficeDocs-DeployOffice#245]
Vous évoquez le fait que, je cite, " Si vous utilisez les services Bureau à distance (RDS)", mais qu'en est-il si on n'utilise pas les services de bureaux à distance de Microsoft, mais un logiciel de bureaux à distance concurrent (c.-à-d. d'un autre éditeur), a-t-on le droit d'installer des licences Office 365 Business Premium ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 6da18a8b-9e96-0155-7b30-9c211070d793
* Version Independent ID: 5a7e610a-bfcb-d9cc-03f7-589d970128d9
* Content: [Déployer Office 365 ProPlus à l’aide des services Bureau à distance](https://docs.microsoft.com/fr-fr/deployoffice/deploy-office-365-proplus-by-using-remote-desktop-services)
* Content Source: [DeployOffice/deploy-office-365-proplus-by-using-remote-desktop-services.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice-pr.fr-FR/blob/live-sxs/DeployOffice/deploy-office-365-proplus-by-using-remote-desktop-services.md)
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
As long as the 3rd party solution requires RDS to be configured/enabled on the server, our restrictions still apply. As far as I know, all 3rd party solutions require RDS to be enabled on the server.
@DHB-MSFT Please close
