### ISSUE TITLE
Error Code: 30088-1007 (0) when trying to downnload proofing tools

### ISSUE THREAD

**Issue by rcallbeck** [MicrosoftDocs/OfficeDocs-DeployOffice#246]
I work in an environment that requires we install all the proofing tools.

When I try to run setup.exe /download config.xml I get Error Code: 30088-1007 (0)

Some of the file do download before it fails.

I'm using the latest ODT setup.exe from https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/172

XML file:

<Configuration>
  <Add SourcePath="C:\Temp\proof" 
       OfficeClientEdition="64" 
       Channel="Broad">
    <Product ID="ProofingTools">
       <Language ID="af-za"/>
       <Language ID="sq-al"/>
       <Language ID="ar-sa"/>
       <Language ID="hy-am"/>
       <Language ID="as-in"/>
       <Language ID="az-Latn-az"/>
       <Language ID="bn-bd"/>
       <Language ID="bn-in"/>
       <Language ID="eu-es"/>
       <Language ID="bs-latn-ba"/>
       <Language ID="bg-bg"/>
       <Language ID="ca-es"/>
       <Language ID="ca-es-valencia"/>
       <Language ID="zh-cn"/>
       <Language ID="zh-tw"/>
       <Language ID="hr-hr"/>
       <Language ID="cs-cz"/>
       <Language ID="da-dk"/>
       <Language ID="nl-nl"/>
       <Language ID="en-us"/>
       <Language ID="et-ee"/>
       <Language ID="fi-fi"/>
       <Language ID="fr-fr"/>
       <Language ID="gl-es"/>
       <Language ID="ka-ge"/>
       <Language ID="de-de"/>
       <Language ID="el-gr"/>
       <Language ID="gu-in"/>
       <Language ID="ha-Latn-ng"/>
       <Language ID="he-il"/>
       <Language ID="hi-in"/>
       <Language ID="hu-hu"/>
       <Language ID="is-is"/>
       <Language ID="ig-ng"/>
       <Language ID="id-id"/>
       <Language ID="ga-ie"/>
       <Language ID="xh-za"/>
       <Language ID="zu-za"/>
       <Language ID="it-it"/>
       <Language ID="ja-jp"/>
       <Language ID="kn-in"/>
       <Language ID="kk-kz"/>
       <Language ID="rw-rw"/>
       <Language ID="sw-ke"/>
       <Language ID="kok-in"/>
       <Language ID="ko-kr"/>
       <Language ID="ky-kg"/>
       <Language ID="lv-lv"/>
       <Language ID="lt-lt"/>
       <Language ID="lb-lu"/>
       <Language ID="mk-mk"/>
       <Language ID="ms-my"/>
       <Language ID="ml-in"/>
       <Language ID="mt-mt"/>
       <Language ID="mi-nz"/>
       <Language ID="mr-in"/>
       <Language ID="ne-np"/>
       <Language ID="nb-no"/>
       <Language ID="nn-no"/>
       <Language ID="or-in"/>
       <Language ID="ps-af"/>
       <Language ID="fa-ir"/>
       <Language ID="pl-pl"/>
       <Language ID="pt-pt"/>
       <Language ID="pt-br"/>
       <Language ID="pa-in"/>
       <Language ID="ro-ro"/>
       <Language ID="rm-ch"/>
       <Language ID="ru-ru"/>
       <Language ID="gd-gb"/>
       <Language ID="sr-cyrl-rs"/>
       <Language ID="sr-latn-rs"/>
       <Language ID="sr-cyrl-ba"/>
       <Language ID="nso-za"/>
       <Language ID="tn-za"/>
       <Language ID="si-lk"/>
       <Language ID="sk-sk"/>
       <Language ID="sl-si"/>
       <Language ID="es-es"/>
       <Language ID="sv-se"/>
       <Language ID="ta-in"/>
       <Language ID="tt-ru"/>
       <Language ID="te-in"/>
       <Language ID="th-th"/>
       <Language ID="tr-tr"/>
       <Language ID="uk-ua"/>
       <Language ID="ur-pk"/>
       <Language ID="uz-Latn-uz"/>
       <Language ID="vi-vn"/>
       <Language ID="cy-gb"/>
       <Language ID="wo-sn"/>
       <Language ID="yo-ng"/>
    </Product>
  </Add>
  
  <Logging Level="Standard" Path="C:\temp" /> 
  
  <Property Name="FORCEAPPSHUTDOWN" Value="TRUE" />
</Configuration>

**Comment by rcallbeck** [comment]
OK, I went through it line by line and there error is being caused by Catalan (Valencia):
<Language ID= "ca-es-valencia"/>

**Comment by jwhit-MSFT** [comment]
Thanks for the feedback. The XML file is not coming through in the comments--can you try again and paste it without the XML markup? Perhaps that's causing it to be stripped.

**Comment by jwhit-MSFT** [comment]
Closing this issue for now--we'll reopen it if you want to provide the XML for us to investigate. Thanks again for raising the issue.
