### ISSUE TITLE
The "Activate Office" fails to load

### ISSUE THREAD

**Issue by fitzmik** [MicrosoftDocs/OfficeDocs-DeployOffice#247]
After confirming that there is "no activation key installed" on my windows 10 image with pre installed office 365 Pro 2019, on first run.. the grace period license key is installed. The online "Activate Office" service fails to run. Who do you ensure that the Activate online utility runs while preventing the the grace period license from installing? The article fails to address this issue. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a003f6a-2edb-3303-01c1-41a63ce82260
* Version Independent ID: 203d6b80-acd5-566a-3f6c-be1852ae8909
* Content: [Deploy Office 365 ProPlus as part of an operating system image](https://docs.microsoft.com/en-us/deployoffice/deploy-office-365-proplus-as-part-of-an-operating-system-image)
* Content Source: [DeployOffice/deploy-office-365-proplus-as-part-of-an-operating-system-image.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-office-365-proplus-as-part-of-an-operating-system-image.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by RAJU2529** [comment]
@fitzmik. If office 365 comes with preinstalled windows 10 means, then OEM installed the trial  version of office 365.  so its not a  full version. You must buy a new license key for office 365. 
Buy from microsoft store using Microsoft account , get the key. open office  365 , login to microsoft account , enter the key , click to activate

**Comment by manoth-msft** [comment]
I will close this issue due to the time passed since it was opened. If there are still technical issues, please post to https://techcommunity.microsoft.com/t5/microsoft-365-apps-for/bd-p/Microsoft365Apps. For documentation issues, please open a new issue here in GitHub.
