### ISSUE TITLE
Office 365 Licensing Token Issues

### ISSUE THREAD

**Issue by jriling** [MicrosoftDocs/OfficeDocs-DeployOffice#248]
Hello,

I am referencing an old post and from my recent Googling I can't seem to find a straight answer on the resolution of this issue:

https://answers.microsoft.com/en-us/msoffice/forum/all/troubles-with-shared-computer-activation-office/95b76bcd-cd6e-4cff-9d7c-3beea747cb06

https://www.reddit.com/r/msp/comments/7x8xdm/licensing_issues_with_server_2016_rds_and/

Removing the *.authString.txt and *.signingCert.txt does infact work, as a workaround, but I don't consider that a solution. It keeps recurring for multiple users at a particular client.

Any help would be greatly appreciated.
![img_4770](https://user-images.githubusercontent.com/46976910/51636840-3895b900-1f28-11e9-97e8-bb92272e97e9.jpg)
![img_4770](https://user-images.githubusercontent.com/46976910/51636859-421f2100-1f28-11e9-9226-ec6fcf205195.jpg)

The environment is Server 2016, Office 2016, no roaming profiles.  Shared Computer Activation.

**Comment by manoth-msft** [comment]
I will close this issue due to the time passed since it was opened. If there are still technical issues, please post to https://techcommunity.microsoft.com/t5/microsoft-365-apps-for/bd-p/Microsoft365Apps. For documentation issues, please open a new issue here in GitHub.
