### ISSUE TITLE
O365 Office Readiness Toolkit error on Win7 clients

### ISSUE THREAD

**Issue by Jim1103** [MicrosoftDocs/OfficeDocs-DeployOffice#249]
Hi Guys, 

I have a really annoying issue. We deployed Readiness Toolkit to several clients via SCCM. 
The Operating systems are Win10 64 bit and Win7 SP1 32bit.
After the successful installation we run a script on the clients remotely as it is suggested in the related MS article:

ReadinessReportCreator.exe -mru -output \\xynetworkshare\Client_SCCM_Reports\O365_ReadinessReports -silent -addinscan

This works fine on all Win 10 64bit clients, the vba and add-in json files are stored on the network location but this process doesn't work on the Win 7 SP1 clients (.NET 4.5.2).
The issue is the same even I install the Toolkit manually and run the tool as logged on user (or run as administrator) locally.
The experienced error:

Log Name:      Application
Source:        Application Error
Date:          2019.01...
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      xy computer
Description:
Faulting application name: ReadinessReportCreator.exe, version: 1.2.18353.6, time stamp: 0x5c1a7ead
Faulting module name: GeneralTel.dll, version: 10.0.18231.1001, time stamp: 0xda9621f1
Exception code: 0xc0000409
Fault offset: 0x00081a92
Faulting process id: 0x85c
Faulting application start time: 0x01d4acb30ee4093b
Faulting application path: C:\Program Files\Microsoft Readiness Toolkit for Office\ReadinessReportCreator.exe
Faulting module path: C:\Program Files\Microsoft Readiness Toolkit for Office\GeneralTel.dll

Please let me know if it’s a known issue and We would be very grateful  if You had any recommendation to resolve it.

Thank in advance,
Jim

**Comment by DHB-MSFT** [comment]
@Jim1103  -- sorry for the delay in responding. Please email the Readiness Toolkit team at ReadyForOffice@microsoft.com and they'll help you troubleshoot the problem.

**Comment by DecRaf** [comment]
This issue have been fixed in the lastest release of Readiness Toolkit for Office add-ins and VBA (version 1.2.19059)
