### ISSUE TITLE
Can Microsoft Office 2013 ProPlus 32bit and Visio for O365 MNO 32bit being installed in the same machine?

### ISSUE THREAD

**Issue by honleung** [MicrosoftDocs/OfficeDocs-DeployOffice#252]
Can Microsoft Office 2013 ProPlus 32bit and Visio for O365 MNO 32bit being installed in the same machine?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d40c96f3-1c97-b538-ef82-ffbf0eef204d
* Version Independent ID: 2d6883b5-1b5c-dc16-9999-17d0652bfa48
* Content: [Supported scenarios for installing different versions of Office, Project, and Visio on the same computer](https://docs.microsoft.com/en-us/deployoffice/install-different-office-visio-and-project-versions-on-the-same-computer)
* Content Source: [DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by CraigHumphrey** [comment]
I suspect they're talking about Office 2013 MSI, rather that C2R.

We're in a similar situation with Office 2016 MSI and Project/Visio Pro Online (C2R?).

**Comment by manoth-msft** [comment]
Office 2013 MSI + Visio 365 C2R are supported. They entertain different major versions (15.0 and 16.0) and are using different deployment technologies.

Office 2016 MSI +  Visio/Project 365 are not supported, they have different deployment technologies, but the same major version (16.0). Check out the two first bullet points in the article:

https://docs.microsoft.com/en-us/deployoffice/install-different-office-visio-and-project-versions-on-the-same-computer
"You can't install two products together that have the same version but use different installation technologies. You can't install two products of different versions together if both products use Click-to-Run as the installation technology and those products have overlapping Office applications."

**Comment by manoth-msft** [comment]
@DHB-MSFT to be closed
