### ISSUE TITLE
Does DocRecrypt really work?

### ISSUE THREAD

**Issue by tang607** [MicrosoftDocs/OfficeDocs-DeployOffice#253]
I have tried DocRecrypt on Word 2016 and 2013 and not one time it works. I have follow the guide to setup the private key and the cert, deploy the cert to the client, changed the registry value, but still "NoCertToUse". I don't even know is what is wrong with my setting or cert because there is so little information for investigation. 
Also does DocRecrypt work with Office 2016? And has anyone ever got this thing to work at all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28b7982b-5e7c-0678-8919-10d4147f3525
* Version Independent ID: 16bd8605-ed8a-234d-0ed7-cac3c1745b35
* Content: [Remove or reset file passwords in Office 2016](https://docs.microsoft.com/en-us/deployoffice/security/remove-or-reset-file-passwords-in-office)
* Content Source: [DeployOffice/security/remove-or-reset-file-passwords-in-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/remove-or-reset-file-passwords-in-office.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by tang607** [comment]
OK. I have finally manage to get DocRecrypt working in Office 2013 & 2016. 
I have to setup the Windows CA in the domain controller so to issue the user cert. Enroll the cert in certmgr.msc by the user certificate template.
The public cert in the end user and the cert with private key in the server should be placed in Current User -> Personal Store in both computer.
Don't try to setup the registry value, use the admin template to deploy the escrow hash value.
And finally, the -o option in the DocRecrypt command is needed, if only -i is specified then it will not work.

**Comment by basemgiham** [comment]
Please Help tang607

I can't do it 
I have to setup the Windows CA in the domain controller so to issue the user cert. Enroll the cert in certmgr.msc by the user certificate template.
The public cert in the end user and the cert with private key in the server should be placed in Current User -> Personal Store in both computer.
