### ISSUE TITLE
Visio Standard worked and then became not activated

### ISSUE THREAD

**Issue by jamacher** [MicrosoftDocs/OfficeDocs-DeployOffice#259]
We have several Visio 2016 standard installs.  We installed with the deployment tool and the provided Visio Standard 2016 
VisioStdXVolume NY48V-PPYYH-3F4PX-XJRKJ-W4423 key above.  This worked without issue.  Then several people all of a sudden are getting activation failed now.  Reinstalled and same results failed activation.  We are using the shared Office365 install.  Any help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e6c0641-503d-7959-2afb-839821cc792f
* Version Independent ID: 046c52d9-4fbe-4fe7-0778-5c1d4138f69e
* Content: [Use the Office Deployment Tool to install volume licensed versions of Project 2016 and Visio 2016](https://docs.microsoft.com/en-us/deployoffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016)
* Content Source: [DeployOffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by jacktose** [comment]
I had the same issue with Visio Pro 2016. Install worked a month ago, and Visio was activated. I tried to use it today and it says it's not.

**Comment by lunaturk** [comment]
This continues to be a problem exactly as reported previously. Unable to use our volume licensed Visio Professional 2016 product alongside Office 365 installed apps.  When will we have a working solution? Thank  you!

**Comment by DHB-MSFT** [comment]
Can the device see/contact the KMS Server? You can use the [ospp.vbs script](https://docs.microsoft.com/en-us/deployoffice/vlactivation/tools-to-manage-volume-activation-of-office#the-osppvbs-script) to check that. If you continue to have problems, we recommend that you contact [Support](https://support.microsoft.com/contactus) as they are the resource best equipped to do this sort of troubleshooting.

**Comment by jacktose** [comment]
I figured it out in my case, and it was about seeing the server.
I had turned off DHCP, so I was no longer getting the DNS suffix that was required to resolve the server on my machine. I manually added my org's suffix as “DNS suffix for this connection” and restarted. Then I could resolve the server and Visio re-authorized.

**Comment by DHB-MSFT** [comment]
@jacktose -- glad you were able to get your issue resolved.
