### ISSUE TITLE
Where is the XLS sheet

### ISSUE THREAD

**Issue by gd2009** [MicrosoftDocs/OfficeDocs-DeployOffice#26]
Where is the xls sheet ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55294e60-d66b-2f01-755b-70622f688057
* Version Independent ID: ae3a1a61-61e7-9126-54dc-0e61f7d46704
* Content: [Best practices Group policy and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/best-practices/best-practices-group-policy-and-office-365-proplus#policy-settings-added-with-office-2016)
* Content Source: [DeployOffice/best-practices/best-practices-group-policy-and-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/best-practices/best-practices-group-policy-and-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
It's included in the Administrative Template download, found here -- https://www.microsoft.com/en-us/download/details.aspx?id=49030.
