### ISSUE TITLE
Microsoft.ACE.OLEDB.12.0' provider not included in Office 2019?

### ISSUE THREAD

**Issue by gordonAndersen** [MicrosoftDocs/OfficeDocs-DeployOffice#261]
Seem that Microsoft.ACE.OLEDB.12.0' provider is not included in Office 2019 installation. Is this true?

**Comment by DHB-MSFT** [comment]
@gordonAndersen -- looking at some search results, I don't think it's absence is particular to Office 2019. It seems like a possible solution is to download/install the [Microsoft Access Database Engine 2010 Redistributable](https://www.microsoft.com/en-US/download/details.aspx?id=13255).  If this doesn't help, I suggest you post your question to Microsoft’s [Answers forum](https://answers.microsoft.com/) or [Tech Community](https://techcommunity.microsoft.com/), or you can contact [support](https://support.microsoft.com/contactus).
