### ISSUE TITLE
Incorrect information about the registry key of SCA

### ISSUE THREAD

**Issue by xadozuk** [MicrosoftDocs/OfficeDocs-DeployOffice#263]
In the documentation, it's stipulated that the key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\16.0\Common\Licensing is a DWORD value.
With this section related to App-V, we could infer that the key for ClickToRun (given just above) HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration would be a DWORD value too.

However, when you try to set it as a DWORD value, Office doesn't pickup the setting.
If you use ODT to deploy Office 365 with SCA, the registry key is created with the type REG_SZ.

I think the documentation should clearly state the correct type for the registry key.

Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ab31873-7ad3-afde-3c72-8a7fb4f2e551
* Version Independent ID: 19f7f483-9f53-f577-1cd4-d360c0b234fc
* Content: [Overview of shared computer activation for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/overview-of-shared-computer-activation-for-office-365-proplus)
* Content Source: [DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
I've submitted pull request #752 to clarify the actual reg type required. Thanks for your feedback!

@DHB-MSFT Please merge #752 and then close this issue. Thanks.

**Comment by manoth-msft** [comment]
#752 has been merged, @jwhit-MSFT please close this issue
