### ISSUE TITLE
New Office Deployment

### ISSUE THREAD

**Issue by sknouse** [MicrosoftDocs/OfficeDocs-DeployOffice#265]
Please Fire who ever came up with 
Volume licensed versions of Visio 2019 are available directly from the Office CDN instead of from the Volume Licensing Service Center.
You had something that worked and people could deal with. Then in Typical Microsoft fashion you had to go and screw it up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3fc30fd-858c-d1cd-0729-6eb72ef7975a
* Version Independent ID: aa690d1d-8e25-6de1-9a83-7acd851fed7a
* Content: [Deployment guide for Visio](https://docs.microsoft.com/en-us/DeployOffice/deployment-guide-for-visio?toc=/deployoffice/office2019/toc.json)
* Content Source: [DeployOffice/deployment-guide-for-visio.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deployment-guide-for-visio.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by msft-bcorob** [comment]
Hello @sknouse, sorry to hear you are dissatisfied with the way Office Click-to-Run products are acquired.  Can you explain a bit more what you are having difficulty with?  Perhaps we can clarify the steps or improve the process here.
