### ISSUE TITLE
Typo ja-jp

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-DeployOffice#267]
https://docs.microsoft.com/ja-jp/DeployOffice/vlactivation/activate-office-by-using-mak

"UserOperations"の設定を有効にするのには dword:00000001 を =
無効にするには、設定 UserOperations"= dword:00000000
↓
有効にするには、"UserOperations" = dword：00000001と設定します。
無効にするには、"UserOperations" = dword：00000000と設定します。

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a2fe572-95d3-c2db-7a27-19ef0ba74b20
* Version Independent ID: dfeea1f8-be9b-60ad-36e8-04da2458da28
* Content: [Activate volume licensed versions of Office by using MAK](https://docs.microsoft.com/en-us/DeployOffice/vlactivation/activate-office-by-using-mak)
* Content Source: [DeployOffice/vlactivation/activate-office-by-using-mak.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/vlactivation/activate-office-by-using-mak.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@hyoshioka0128  -- thanks for catching that. We've updated the en-us version, so the ja-jp should be updated soon as well.
