### ISSUE TITLE
Application identifiers are lowercase when they should be capitalized

### ISSUE THREAD

**Issue by ryantgrimes** [MicrosoftDocs/OfficeDocs-DeployOffice#268]
The application identifiers should be all uppercase, not lowercase.  Otherwise none of this works.  For example Outlook should be OPIM2019 and not opim2019.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59e840a0-92ac-3ba4-75b3-01a154d67899
* Version Independent ID: 8f7fd243-8f3a-7d32-8433-03b8167aee6f
* Content: [Update Office for Mac by using msupdate](https://docs.microsoft.com/en-us/deployoffice/mac/update-office-for-mac-using-msupdate)
* Content Source: [DeployOffice/mac/update-office-for-mac-using-msupdate.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/mac/update-office-for-mac-using-msupdate.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @pbowden-msft
* Microsoft Alias: **danbrown**

**Comment by brunerd** [comment]
Hmm, the documentation says: Identifiers are not case-sensitive.

**Comment by ryantgrimes** [comment]
Well I put them in lowercase and updates didn't work.  I capitalized them and it worked.  I didn't change anything else.

**Comment by DHB-MSFT** [comment]
@ryantgrimes  -- Our Mac PM has confirmed that the application identifiers are not case-sensitive. If you're still having problems, we recommend you try one of the support options listed here -- [Get support for problems with Office](https://docs.microsoft.com/en-us/deployoffice/feedback#get-support-for-problems-with-office).

**Comment by brunerd** [comment]
Note: If you are using these application identifiers as part of a custom payload in a Configuration Profile (a pretty slick way to ensure all apps are "registered" for updates to appear even if the user has not signed in and run them), then the Application IDs MUST be in CAPS or MAU will not "see" the udpates.

**Comment by brunerd** [comment]
Except for MSau04... apparently that it special.

**Comment by pbowden-msft** [comment]
Thanks @brunerd - I'll get the doc fixed.
