### ISSUE TITLE
Project 2016 installs, but is not activated. Volume license code is not accepted.

### ISSUE THREAD

**Issue by mbalcerzyk** [MicrosoftDocs/OfficeDocs-DeployOffice#27]
Project 2016 Pro installs if done accordingly, but is not activated. Volume license code is not accepted. I have the license of Office 365 Click-to-run from my university, which does not include Project 2016 license. There is reference to activation at https://docs.microsoft.com/es-es/DeployOffice/vlactivation/plan-volume-activation-of-office but in my university (@us.es) or CSIC (@csic.es) it seems not to work. 
Marcin

**Comment by DHB-MSFT** [comment]
Sorry for the delay in responding. Has your school/organization purchased a volume licensed version of Project Professional 2016? They need to have done that (and set up volume activation) for the steps in https://docs.microsoft.com/DeployOffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016 to work.
