### ISSUE TITLE
Removing Onedrive

### ISSUE THREAD

**Issue by aihorden** [MicrosoftDocs/OfficeDocs-DeployOffice#270]
Most people need to remove OneDrive for Business, NOT OneDrive.  You fixed the problem on the document released today - https://docs.microsoft.com/en-us/onedrive/exclude-or-uninstall-previous-sync-client - But clarification is needed in this document as well.   Using the same name for 3 different products really confuses people.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66127c02-c2dc-f6d1-6e83-a6d2b1166731
* Version Independent ID: 27635315-22db-d136-f07e-5169f6207b50
* Content: [Overview of the Office Deployment Tool](https://docs.microsoft.com/en-us/DeployOffice/overview-of-the-office-2016-deployment-tool#feedback)
* Content Source: [DeployOffice/overview-of-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by jwhit-MSFT** [comment]
Thanks for the catch. I'll update the article soon--should be fixed by the end of the week.
