### ISSUE TITLE
Please confirm the group name

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/OfficeDocs-DeployOffice#275]
Instead of "Update channel: Choose Semi-Annual Channel for the installation package for the pilot group" 
should say "Update channel: Choose Semi-Annual Channel for the installation package for the BROAD group"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56455cc-de1d-7daa-bae1-8a344625bc71
* Version Independent ID: 8bafdb99-1562-bc9d-c27b-596250dee4e2
* Content: [Deploy Office 365 ProPlus from the cloud](https://docs.microsoft.com/en-us/DeployOffice/deploy-office-365-proplus-from-the-cloud)
* Content Source: [DeployOffice/deploy-office-365-proplus-from-the-cloud.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-office-365-proplus-from-the-cloud.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by jwhit-MSFT** [comment]
Thanks for catching that--I just updated it. Should be live soon. We love getting feedback through these discussions, but you're also welcome to submit these changes directly as a pull request, if you want to next time--that'll get you listed as a contributor on the article :-)

**Comment by jwhit-MSFT** [comment]
Thanks for catching that--I just updated it. Should be live soon. We love getting feedback through these discussions, but you're also welcome to submit these changes directly as a pull request, if you want to next time--that'll get you listed as a contributor on the article :-)

**Comment by zlDev** [comment]
Great, didn’t know that, will do next time. :thumbs:

On 13 Feb 2019, at 18:56, J Whitmarsh <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for catching that--I just updated it. Should be live soon. We love getting feedback through these discussions, but you're also welcome to submit these changes directly as a pull request, if you want to next time--that'll get you listed as a contributor on the article :-)

**Comment by pedro-roeseler** [comment]
Just to had that in step 3 you are saving the Broad Group .xml file as config-pilot-SAC.xml but in point 5 you mention it as \\Server\Share\O365\config-broad-SAC.xml.
