### ISSUE TITLE
Added to Inutne management?

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/OfficeDocs-DeployOffice#290]
In Intune when deploying Office 365 you can choose what apps are installed. Teams is not listed there, when will it be added? If it isn't there is it installed by default or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7936ca5e-c658-4956-b174-99eaf1eb67d4
* Version Independent ID: 9ecc0b61-a941-f5e1-96c3-d32fae59eacd
* Content: [Deploy Microsoft Teams with Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/teams-install)
* Content Source: [DeployOffice/teams-install.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/teams-install.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@hoyty76 -- thanks for your question. Currently there's no definite ETA for when the Teams toggle will appear in the Intune UI. So for now, I'll remove the reference to Intune. 

Without the toggle, whether Teams is installed by default will be determined by which update channel and which version you choose to install. If an update channel/version is chosen that supports the default installation of Teams (for example, Version 1902 of Monthly Channel), then Teams will be installed by default. But if you choose an update channel that doesn't have that capability (for example, Version 1808 of Semi-Annual Channel), Teams won't be installed by default.  Hope that helps.

**Comment by DHB-MSFT** [comment]
FYI, Intune references have been removed from the article for now.
