### ISSUE TITLE
Questions about HOW they will do this

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-DeployOffice#291]
Someone needs to explain whether or not there will still be the same per-user profile install or if it will behave like all the other office apps. Ever twitter thread I've seen that points to the roadmap item or this documentation has been asking this question.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7936ca5e-c658-4956-b174-99eaf1eb67d4
* Version Independent ID: 9ecc0b61-a941-f5e1-96c3-d32fae59eacd
* Content: [Deploy Microsoft Teams with Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/teams-install)
* Content Source: [DeployOffice/teams-install.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/teams-install.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@npherson -- thanks for the question. Will reply back when we have an answer and will update the article as needed.

**Comment by DHB-MSFT** [comment]
@npherson  -- Teams will be installed with Office 365 ProPlus in the same manner Teams is currently installed if you had used the existing Teams MSI installer. For each new user that signs into the device, the Teams installer will launch and the Teams application will be installed in the user's appdata folder.  

Hope that answers your question. I'll make an update to the article to include that info.  Thanks again for your question, which helps make the documentation better.

**Comment by npherson** [comment]
Thank you for the answer! While it is incredibly disappointing that this is how it will work, at least enterprises know and can start planning how to mitigate the pain. Can we update the document to make it clear that the existing Teams installer behavior won’t change with this like everyone is hoping?

**Comment by DHB-MSFT** [comment]
@npherson  -- yes, I plan to update the article today/tomorrow to make it clear that the Teams install behavior isn't changing.

**Comment by DHB-MSFT** [comment]
FYI, article updated. See 2nd bullet point in the "Additional info" section at the end of the article. Thanks again for your question/feedback. It helps make the documentation better.
