### ISSUE TITLE
Delivery Optimization? 

### ISSUE THREAD

**Issue by PiKappZ746** [MicrosoftDocs/OfficeDocs-DeployOffice#292]
Will the Teams client updates leverage Delivery Optimization? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7936ca5e-c658-4956-b174-99eaf1eb67d4
* Version Independent ID: 9ecc0b61-a941-f5e1-96c3-d32fae59eacd
* Content: [Deploy Microsoft Teams with Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/teams-install)
* Content Source: [DeployOffice/teams-install.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/teams-install.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@PiKappZ746  -- We're checking on this. Will let you know what we find out and will update the article as needed. Thanks for your question.

**Comment by DHB-MSFT** [comment]
@PiKappZ746 -- We're fairly certain Team isn't able to make use of Delivery Optimization for updates, but we're double-checking with another source.

**Comment by DHB-MSFT** [comment]
@PiKappZ746  -- Got confirmation from a 2nd source that Teams doesn't make use of Delivery Optimization. Thanks for your question.
