### ISSUE TITLE
Example installation scenarios

### ISSUE THREAD

**Issue by Gaurav0327** [MicrosoftDocs/OfficeDocs-DeployOffice#293]
Need to add more Examples in this list:

1. Office Professional Plus 2016 (MSI : 16.0.) with Project 2019 (C2R: 16.0): 
Not Supported : You can’t install two products together that have the same version but use different installation technologies. Office 2019 is available only in C2R technology and has the same version similar to the Office 2016 product i.e. 16.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d40c96f3-1c97-b538-ef82-ffbf0eef204d
* Version Independent ID: 2d6883b5-1b5c-dc16-9999-17d0652bfa48
* Content: [Supported scenarios for installing different versions of Office, Project, and Visio on the same computer](https://docs.microsoft.com/en-us/deployoffice/install-different-office-visio-and-project-versions-on-the-same-computer)
* Content Source: [DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by koehjo** [comment]
Why on earth has Microsoft created this mess? In addition to version compatibility we have to worry about installation technique? Who has tine for this? As a tech writer with 20 some years of experience, I have never seen a worse explanation of a company's bungling development process!

**Comment by DHB-MSFT** [comment]
@koehjo -- If you have suggestions for the product team, you can post them here -- https://odinsiders.uservoice.com/.  If you have suggestions on how to improve this article, you can post them here.  Thanks.
