### ISSUE TITLE
Updating Office Activation ID's:

### ISSUE THREAD

**Issue by Gaurav0327** [MicrosoftDocs/OfficeDocs-DeployOffice#295]
Office 2010 - Bfe7a195-4f8f-4f0b-A622-Cf13c7d16864
Office 2013 - 2E28138A-847F-42BC-9752-61B03FFF33CD
Office 2016 - 98ebfe73-2084-4c97-932c-c0cd1643bea7
Office 2019 - 70512334-47B4-44DB-A233-BE5EA33B914C

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dffd0c18-e6ff-d0df-771d-8082d6473fbe
* Version Independent ID: 3b0adc2b-464e-bf01-9a4f-6098301d57c4
* Content: [Configure a KMS host computer to activate volume licensed versions of Office](https://docs.microsoft.com/en-us/deployoffice/vlactivation/configure-a-kms-host-computer-for-office)
* Content Source: [DeployOffice/vlactivation/configure-a-kms-host-computer-for-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/vlactivation/configure-a-kms-host-computer-for-office.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
The Office 2010 and Office 2013 activation IDs for KMS are documented in these 2 articles:  

- [Prepare and set up the Office 2013 KMS host](https://docs.microsoft.com/previous-versions/office/office-2013-resource-kit/dn385356(v=office.15))
- [Deploy volume activation of Office 2010](https://docs.microsoft.com/previous-versions/office/office-2010/ee624357%28v%3doffice.14%29)
