### ISSUE TITLE
VDI Installation question - 

### ISSUE THREAD

**Issue by Ramonin** [MicrosoftDocs/OfficeDocs-DeployOffice#296]
Does this still mean that the application installs into the user profile instead of the machine? Please provide a VDI section 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7936ca5e-c658-4956-b174-99eaf1eb67d4
* Version Independent ID: 9ecc0b61-a941-f5e1-96c3-d32fae59eacd
* Content: [Deploy Microsoft Teams with Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/teams-install)
* Content Source: [DeployOffice/teams-install.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/teams-install.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@Ramonin -- Teams will be installed with Office 365 ProPlus in the same manner Teams is currently installed if you had used the existing Teams MSI installer. For each new user that signs into the device, the Teams installer will launch and the Teams application will be installed in the user's appdata folder.

Hope that answers your question. I'll make an update to the article to include that info.

**Comment by Ramonin** [comment]
Awesome thank you

Ramon Infante
Principal Program Manager Office 365 CXP
Microsoft
Office: +1 (425)538-0610
Mobile: 201-647-4962
ramonin@microsoft.com<mailto:ramonin@microsoft.com>




[http://mysignature.azureedge.net/files/L_Microsoft.png]
[CHANGE  PRACTITIONER  Prosci]

**Comment by DHB-MSFT** [comment]
FYI, article updated. See 2nd bullet point in the "Additional info" section at the end of the article. Thanks again for your question/feedback. It helps make the documentation better.

**Comment by Ramonin** [comment]
Nice job Thank you

Ramon Infante
Principal Program Manager Office 365 CXP
Microsoft
Office: +1 (425)538-0610
Mobile: 201-647-4962
ramonin@microsoft.com<mailto:ramonin@microsoft.com>




[http://mysignature.azureedge.net/files/L_Microsoft.png]
[CHANGE  PRACTITIONER  Prosci]
