### ISSUE TITLE
Overly Complicating a Simple Process

### ISSUE THREAD

**Issue by philipGN** [MicrosoftDocs/OfficeDocs-DeployOffice#298]
Leave it to Microsoft to take a simple software install to a new level of unnecessary complexity...  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [Deploy Office 2019 (for IT Pros)](https://docs.microsoft.com/en-us/DeployOffice/office2019/deploy)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by philipGN** [comment]
I don't want a comment or some shady remark that belittles the issue.... have a nice day.

**Comment by Havoc481** [comment]
same. cant get the download to work. im stuck on the xml setup/download command.

**Comment by philipGN** [comment]
i hear ya, we were able to overcome the issues with a little trial and error.  our XML file needed some tweaking, and just so you know, after setup /download configuration.xml command, depends on your bandwidth, it just takes enough time to download, when done, you get the C:\ prompt back.  With the setup /configure configuration.xml command, you have to meet certain requirements like, ALL office products must be removed, ALL of them... including the older stuff, conversion utilities, sign-in assistant, anything.  the cleanup tool doesn't do the extra stuff.

So when you run the /configure command, you can see it working and adding icons to the start menu, and eventually, depending on the speed of the computer, it should return you to a command prompt when done.

hope that helps, we were literally in the same boat until we spent 2hrs writing the steps down, tweaking the XML to our needs...  good luck

**Comment by scrouthtv** [comment]
@philipGN did you manage to change the installation location to a different one that C:?

**Comment by DHB-MSFT** [comment]
@scrouthtv -- You can't change the location of the installation.
