### ISSUE TITLE
A list of ProductIDs would be very useful.

### ISSUE THREAD

**Issue by zebulonsmith** [MicrosoftDocs/OfficeDocs-DeployOffice#299]
Including a list of ProductIDs for the Click2Run installs in this doc for use with the <remove> tag would be incredibly useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66127c02-c2dc-f6d1-6e83-a6d2b1166731
* Version Independent ID: 27635315-22db-d136-f07e-5169f6207b50
* Content: [Overview of the Office Deployment Tool](https://docs.microsoft.com/en-us/deployoffice/overview-of-the-office-2016-deployment-tool)
* Content Source: [DeployOffice/overview-of-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by DHB-MSFT** [comment]
@zebulonsmith -- This is probably the info you're looking for:  [Product IDs that are supported by the Office Deployment Tool](https://support.microsoft.com/en-us/help/2842297/product-ids-that-are-supported-by-the-office-deployment-tool-for-click).  There is a link to it in the documentation about the [Product ID](https://docs.microsoft.com/en-us/DeployOffice/configuration-options-for-the-office-2016-deployment-tool#id-attribute-part-of-product-element) used in the configuration.xml file. Hope that helps.
