### ISSUE TITLE
Visio/Project 2019 with Office 365 Home from Microsoft Store

### ISSUE THREAD

**Issue by Stahlreck** [MicrosoftDocs/OfficeDocs-DeployOffice#302]
Could it please be possible to install Visio/Project C2R without them having to always remove all other Office applications downloaded from the Windows (now Microsoft) Store and then reinstall them automatically as C2R? (except OneNote since thank god at least one app was rewritten out of this mess).

Please either fix this or just bring ALL Office apps into the Micrrosoft Store...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d40c96f3-1c97-b538-ef82-ffbf0eef204d
* Version Independent ID: 2d6883b5-1b5c-dc16-9999-17d0652bfa48
* Content: [Supported scenarios for installing different versions of Office, Project, and Visio on the same computer](https://docs.microsoft.com/en-us/deployoffice/install-different-office-visio-and-project-versions-on-the-same-computer)
* Content Source: [DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by RAJU2529** [comment]
@Stahlreck . yes possible you need only   office  2019  project or office 2019 visio C2R  installation files.

You need to download from setup.office.com, login to Microsoft account , enter the product key and download the file, run with admin rights.

i followed the  same , i installed office 2016 project pro  and  visio pro

**Comment by manoth-msft** [comment]
Currently there is no intention to change our support stance. We support apps of the same major version only when they are installed through the same deployment technology (MSI or C2R or Centennial (Store)). I will close this issue based on the age of the feedback.
