### ISSUE TITLE
Wrong Information

### ISSUE THREAD

**Issue by driods** [MicrosoftDocs/OfficeDocs-DeployOffice#303]
This statement 
4) Select Continue on the pop-up windows and download the .iso file that contains the VL Serializer package file.   
The link downloads a pkg (package) file and no information of VL serializer is available. :-(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce6cb9d5-64d9-7af7-2d76-5c2f59c937f3
* Version Independent ID: fd6afd70-cce9-8296-9d73-fb366a069ee2
* Content: [Overview of the Volume License (VL) Serializer](https://docs.microsoft.com/en-us/deployoffice/mac/volume-license-serializer)
* Content Source: [DeployOffice/mac/volume-license-serializer.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/mac/volume-license-serializer.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@driods -- We've updated the VLSC download steps. Hopefully that makes it clearer and you can get the iso file downloaded.

**Comment by driods** [comment]
Thanks Daniel. 
Please let me know if you have checked/tested the steps actually work. 
When I login to our VLSC portal, I can't find the option to download .iso , 

The file that downloads is this 
Microsoft_Office_16.16.19021001_Installer .pkg (Not .iso ) 

Regards

**Comment by driods** [comment]
[MicrosoftVLSC.pdf](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/files/2904571/MicrosoftVLSC.pdf)

**Comment by driods** [comment]
Hi Daneil,
This is a bit strange. I logged  into our VLSC portal using safari on a Mac book and I was able to see a separate download link for Volume License Serializer for Office.  It would be better if there is a side note mentioning the same.
