### ISSUE TITLE
Office Customization Tool - Teams is not a listed app to Exclude

### ISSUE THREAD

**Issue by capnjax21** [MicrosoftDocs/OfficeDocs-DeployOffice#304]
Your tip suggests to use the config.office.com to build the office customization xml. Teams is not listed under the "Turn apps on or off to include or exclude them from being deployed" section. Teams should be listed as an app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7936ca5e-c658-4956-b174-99eaf1eb67d4
* Version Independent ID: 9ecc0b61-a941-f5e1-96c3-d32fae59eacd
* Content: [Deploy Microsoft Teams with Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/teams-install)
* Content Source: [DeployOffice/teams-install.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/teams-install.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@capnjax21 -- For the Teams on/off toggle to appear when using the [Office Customization Tool](https://config.office.com), you have to select an Office Suite, update channel, and version that includes the Teams installation. For example, if you choose Office 365 Business + Monthly Channel, you will see the Teams toggle appear.  The OCT is designed to only give you selections that are appropriate for the suite + update channel + version that you have chosen. Hope that helps.
