### ISSUE TITLE
"For OneDrive for Business, use Groove" sentence is incorrect

### ISSUE THREAD

**Issue by braggcolin** [MicrosoftDocs/OfficeDocs-DeployOffice#305]
The "For OneDrive for Business, use Groove" sentence is incorrect.

For OneDrive for Business you use OneDrive as shown by the bullet points above the sentence.

The sentence should read:
"For Sharepoint Workspace, use Groove"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a0b1ff-0498-505a-6024-b813980d310f
* Version Independent ID: b8057930-b4bd-1304-17ce-5561f837e901
* Content: [Configuration options for the Office Deployment Tool](https://docs.microsoft.com/en-us/deployoffice/configuration-options-for-the-office-2016-deployment-tool#excludeapp-element)
* Content Source: [DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by jwhit-MSFT** [comment]
Thanks for this feedback. I investigated the request with a OneDrive writer; based on that conversation, I think the existing statement is correct. SharePoint Workspace refers to an even earlier version--2010, I believe.
