### ISSUE TITLE
Adding <Product ID="ProofingTools"> forces install of all Applications

### ISSUE THREAD

**Issue by heldchen** [MicrosoftDocs/OfficeDocs-DeployOffice#307]
I am using
```
<Configuration>
    <Add OfficeClientEdition="64" Channel="Current">
        <Product ID="Word2019Retail">
            <Language ID="en-us"/>
            <Language ID="de-de" />
        </Product>
        <Product ID="Excel2019Retail">
            <Language ID="en-us"/>
            <Language ID="de-de" />
        </Product>
    </Add>
    <Updates Enabled="TRUE"/>
    <RemoveMSI All="TRUE" />
    <Display Level="Full" AcceptEULA="TRUE"/>
</Configuration>
```
to only have Word & Excel installed. this works fine until I also add ProofingTools to the configuration.xml:
```
<Configuration>
    <Add OfficeClientEdition="64" Channel="Current">
        <Product ID="Word2019Retail">
            <Language ID="en-us"/>
            <Language ID="de-de" />
        </Product>
        <Product ID="Excel2019Retail">
            <Language ID="en-us"/>
            <Language ID="de-de" />
        </Product>
        <Product ID="ProofingTools">
            <Language ID="en-us" />
            <Language ID="de-de" />
            <Language ID="fr-fr" />
        </Product>
    </Add>
    <Updates Enabled="TRUE"/>
    <RemoveMSI All="TRUE" />
    <Display Level="Full" AcceptEULA="TRUE"/>
</Configuration>
```
instead of installing Word, Excel and the 3 proofing languages, all Office apps are installed along with the selected proofing languages.

**Comment by heldchen** [comment]
running setup with two different configs twice (apps first, then proofiling tools second) works.

**Comment by jwhit-MSFT** [comment]
Thanks for the feedback. I'm investigating this and will get back with an answer.

**Comment by msft-bcorob** [comment]
Hi @heldchen , from the steps you describe it sounds like you actually have some additional Office suite already installed on your PC, perhaps preinstalled.  Can you check in Add/Remove programs to see if you have any other Office products installed?

In general, the right way to get only some Office apps and not others in a suite is to use the [<ExcludeApp/> functionality](https://docs.microsoft.com/en-us/deployoffice/configuration-options-for-the-office-2016-deployment-tool#excludeapp-element).  Using the standalones "Word2019Retail" and "Excel2019Retail" is only supported when purchasing those specific products.

**Comment by heldchen** [comment]
@msft-bcorob this was happening on a fresh windows 10 pro installation on a new device. I did have the full 2019 suite installed at one time tho during my trial & errors, but made sure to uninstall any previous attempt before trying again.

I did however found a way to get to the desired state (word + excel +proofing tools) by using `ExcludeApp` within the `<Product ID="ProofingTools">` node, i.e.
```
<Configuration>
  <Add OfficeClientEdition="64" Channel="Current">
    <Product ID="ProPlus2019Retail">
      <ExcludeApp ID="Access2019Retail"/>
      <ExcludeApp ID="Outlook2019Retail"/>
      <ExcludeApp ID="PowerPoint2019Retail"/>
      <ExcludeApp ID="Publisher2019Retail"/>
      <ExcludeApp ID="SkypeforBusiness2019Retail"/>
      <ExcludeApp ID="Access" />
      <ExcludeApp ID="Groove" />
      <ExcludeApp ID="Lync" />
      <ExcludeApp ID="OneDrive" />
      <ExcludeApp ID="OneNote" />
      <ExcludeApp ID="Outlook" />
      <ExcludeApp ID="PowerPoint" />
      <ExcludeApp ID="Publisher" />
      <ExcludeApp ID="Teams" />
      <Language ID="en-us" />
    </Product>
    <Product ID="ProofingTools">
      <Language ID="de-de" />
      <Language ID="fr-fr" />
      <ExcludeApp ID="Access2019Retail"/>
      <ExcludeApp ID="Outlook2019Retail"/>
      <ExcludeApp ID="PowerPoint2019Retail"/>
      <ExcludeApp ID="Publisher2019Retail"/>
      <ExcludeApp ID="SkypeforBusiness2019Retail"/>
      <ExcludeApp ID="Access" />
      <ExcludeApp ID="Groove" />
      <ExcludeApp ID="Lync" />
      <ExcludeApp ID="OneDrive" />
      <ExcludeApp ID="OneNote" />
      <ExcludeApp ID="Outlook" />
      <ExcludeApp ID="PowerPoint" />
      <ExcludeApp ID="Publisher" />
      <ExcludeApp ID="Teams" />
    </Product>
  </Add>
  <Updates Enabled="TRUE" Channel="Current" />
  <RemoveMSI />
  <Display Level="Full" AcceptEULA="TRUE" />
</Configuration>
```
I still think it it's a bit weird that the ProofingTool setup would pull in all of the office programs unless they are excluded specifically.
