### ISSUE TITLE
It is March 4, build 1902 soon?

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/OfficeDocs-DeployOffice#309]
According to this page 1902 will be out by end of February but according to https://docs.microsoft.com/en-us/officeupdates/update-history-office365-proplus-by-date it still isn't out? Any timeline updates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7936ca5e-c658-4956-b174-99eaf1eb67d4
* Version Independent ID: 9ecc0b61-a941-f5e1-96c3-d32fae59eacd
* Content: [Deploy Microsoft Teams with Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/teams-install)
* Content Source: [DeployOffice/teams-install.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/teams-install.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@hoyty76 -- Version 1902 was released to Monthly Channel this afternoon. The table in the article has been updated accordingly.
