### ISSUE TITLE
Teams recommendations

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/OfficeDocs-DeployOffice#313]
There are no recommendations for Teams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce2587dd-9e3e-efdb-dc12-49ffcc8dfd44
* Version Independent ID: 8c98e559-ee79-61a8-2177-7f47d9325dec
* Content: [OneDrive for Business and VDI environments](https://docs.microsoft.com/en-us/deployoffice/rds-onedrive-business-vdi)
* Content Source: [DeployOffice/rds-onedrive-business-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/rds-onedrive-business-vdi.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi
@jwhit-MSFT to be closed
