### ISSUE TITLE
What about new Office ProPlusdeployment on VDI and Terminal server/CITRIX environment?

### ISSUE THREAD

**Issue by TheBaban** [MicrosoftDocs/OfficeDocs-DeployOffice#314]
What will happen when we deploy Office on a VDI/CITRIX environment?
Do we will by default deploy TEAMS with Office?

If we use non persistant profile, the TEAMS installation will be lost.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7936ca5e-c658-4956-b174-99eaf1eb67d4
* Version Independent ID: 9ecc0b61-a941-f5e1-96c3-d32fae59eacd
* Content: [Deploy Microsoft Teams with Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/teams-install)
* Content Source: [DeployOffice/teams-install.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/teams-install.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@TheBaban -- we've added this info to the article:

If you plan to use Teams in a Virtual Desktop Infrastructure (VDI) environment, see [Teams for Virtualized Desktop Infrastructure](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi). Teams installed with Office 365 ProPlus as described in this article isn't currently supported in VDI environments.

Hope that helps.
