### ISSUE TITLE
Outlook 2016 integrating with OneNote for Win 10 for Meeting Notes...

### ISSUE THREAD

**Issue by benedictcooper** [MicrosoftDocs/OfficeDocs-DeployOffice#315]
Hi, thanks for the good summary article, clarifies a lot of issues but was wondering, you mention that: "Microsoft has updated its add-ins for OneNote, such as providing integration with Outlook, to work with OneNote for Windows 10."

However there still seems to be an issue with creating meeting notes in Outlook 2016 and them opening in OneNote for Win 10 as per this discussion: https://techcommunity.microsoft.com/t5/OneNote/Windows-10-OneNote-and-Office-365-Outlook-no-way-to-add-meeting/m-p/314564/highlight/false#M516

I have looked at the COM Add-Ins but there is still only one available ("OneNote Notes about Outlook items") and it doesn't work in my setup for meeting notes.  Any ideas when an updated (or a new) add-in would be available?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2319f44f-09fc-2649-2667-58fa159e3151
* Version Independent ID: 0b6c5c52-edaa-436d-95dd-0943d0b0c303
* Content: [Deployment guide for OneNote](https://docs.microsoft.com/en-us/deployoffice/deployment-guide-onenote#feedback)
* Content Source: [DeployOffice/deployment-guide-onenote.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deployment-guide-onenote.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
Our documentation here is focused on the deployment, servicing and management of C2R-based products and less focused on the features of individual apps. We would recommend you to either raise a case through Microsoft Support (if this is available to you) or file/+1 a request through https://onenote.uservoice.com/. As we resurrected the OneNote 2016 apps, there is nothing wrong sticking to them.
@DHB-MSFT to be closed
