### ISSUE TITLE
Stop Teams from auto installing for all users of machine?

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/OfficeDocs-DeployOffice#316]
Can we make teams not to this "For each new user that signs into the device, the Teams installer runs and the Teams application is installed in the user's AppData folder." Sometimes we only want for a user on a machine and not every person who ever logs into machine for the rest of time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7936ca5e-c658-4956-b174-99eaf1eb67d4
* Version Independent ID: 9ecc0b61-a941-f5e1-96c3-d32fae59eacd
* Content: [Deploy Microsoft Teams with Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/teams-install)
* Content Source: [DeployOffice/teams-install.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/teams-install.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@hoyty76 -- Thanks for the feedback. I suggest you make your suggestion here -- [Teams feedback forum](https://microsoftteams.uservoice.com/forums/555103-public). That way other customers can comment on and "vote for" your suggestion. And that site is directly monitored by the Teams product team.
