### ISSUE TITLE
What the heck Microsoft!

### ISSUE THREAD

**Issue by wtrent879** [MicrosoftDocs/OfficeDocs-DeployOffice#320]
, we cannot just simply click setup anymore? Are you going out of your way to make your software more difficult to install and use after all these years of making the best software? http://www.openoffice.org

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [Deploy Office 2019 (for IT Pros)](https://docs.microsoft.com/en-us/deployoffice/office2019/deploy#feedback)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by wtrent879** [comment]
...plus no status feedback while the software is installing, geez.

**Comment by colepep** [comment]
You're saying Microsoft should build both of you custom installers? Along with every customer? Not everyone has the same needs and requirements, this tool is actually very useful if you can do more than double-click an exe.
