### ISSUE TITLE
Windows 10 1809 and New Email Account Outlook 2019

### ISSUE THREAD

**Issue by ALyman1** [MicrosoftDocs/OfficeDocs-DeployOffice#322]
Have a new machine running the latest version of Windows 10, 1809. Installed Office Standard 2019 (it shows Office 365 when opening Outlook for some reason) and trying to add an email account to a hosted exchange server, but I keep getting a Windows Security popup that won't go away no matter what I enter.

**Comment by jwhit-MSFT** [comment]
I'd recommend reaching out to support for this issue, or one of our support forums. Links can be found here: https://docs.microsoft.com/en-us/deployoffice/feedback
