### ISSUE TITLE
SourcePath - to what?

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/OfficeDocs-DeployOffice#323]
If we donload the Office 2019 iso file , does the SourcePath just contain the path and filename for Office2019.iso?
Or do we have to mount the iso and SourcePath defines the drive letter?
Or must we unpack the ISO-File and SourcePath defines the path to the directory which contains the extracted files?
Or must we mount the iso and start setup with some parameters to extract Office 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a0b1ff-0498-505a-6024-b813980d310f
* Version Independent ID: b8057930-b4bd-1304-17ce-5561f837e901
* Content: [Configuration options for the Office Deployment Tool](https://docs.microsoft.com/en-us/deployoffice/configuration-options-for-the-office-2016-deployment-tool)
* Content Source: [DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by DHB-MSFT** [comment]
@schittli -- There's isn't an iso file for Office 2019. There are a series of files and folders. If you are downloading the Office 2019 installation files to put on a network share, then the SourcePath is used to specify that share and the Office 2019 installation files are downloaded there from the Office Content Delivery Network (CDN) on the internet when you use the /download switch with the Office Deployment Tool. If you are installing Office 2019 from a network share, you use the SourcePath to specify the location of that share so the device where Office is being installed on knows where to go to get the installation files (when you're using the /configure switch with the Office Deployment Tool). There's more info in our [Deploy Office 2019](https://docs.microsoft.com/en-us/deployoffice/office2019/deploy) article. Hope that helps.

**Comment by schittli** [comment]
Thank you very much for your answer!, 
but in the Microsoft Partner Portal we can find "Office Professional Plus 2019" and Microsoft offers this ISO-File:
> SW_DVD5_Office_Professional_Plus_64Bit_English_-6_OfficeOnlineSvr_MLF_X21-90444.ISO

It looks like not even Microsoft knows what's the content of this ISO-File, because the Filename talks about _Office Professional Plus_ and _Office Online Server_, so we expect we've got both: an ISO file with Office Professional Plus and the Office Online Server.

Unfortunately, the _Deploy Office 2019 "Docs"_ does not answer the question of how to address this ISO-File in the xml file.

#### Btw.: compared to almost 20 years ago, this deploy is a nightmare:
20 years ago, we could click 3 times or pass a parameter - and Office was installed.
Today, we have to study the painful _28dcba1b7c06a85ba8a633e23a2ff3db.pdf_ (this is Microsofts name for the Deployment guide for Office 2019) and read 56 pages. M$ was not even able to offer a default working(!) xml file combined with e.g. a Powershell script so that customers can execute one command - and Office gets downloaded (if necessary), installed and configured.
As I mentioned: just as it worked 20 years ago.

**Comment by RAJU2529** [comment]
@schittli. Just extract the iso, using WinRAR or 7-zip. Then run setup.exe to  complete installation

**Comment by frknl** [comment]
20 years ago, i think no IT guys out there like today.
This document targets system admins. If you don't how to extract data path from a iso file don't blame others
cheers

**Comment by frknl** [comment]
20 years ago, i think no IT guys out there like today.
This document targets system admins. If you don't know how to extract a data folder from a iso file don't blame others
cheers

**Comment by manoth-msft** [comment]
Raju is correct. Mount the ISO or extract it to a folder and run setup.exe from the root. If needed, you can modify the configuration.xml, but you don't have to specify a sourcepath as long as you don't change the file/folder structure. Setup will automatically detect that the source files are located in the Office\Data\16.0.xxxxx.xxxxx subfolder and leverage those.
