### ISSUE TITLE
Proofing tools installed but not selectable

### ISSUE THREAD

**Issue by gregecslo** [MicrosoftDocs/OfficeDocs-DeployOffice#324]
Hi!

We successfuly deployed O2019 with proofing tools.
But we have just one issue. 
Serbian (latin) proofing tools ARE installed but not working in office apps (Outlook, Word ...).

![proof1](https://user-images.githubusercontent.com/17081737/54924560-f4656b80-4f0c-11e9-8bde-39ef537f02ce.JPG)
![proof2](https://user-images.githubusercontent.com/17081737/54924562-f4fe0200-4f0c-11e9-8f64-4bfe1c263162.JPG)

If this is not deploy error or install error but rather app error, can you please report it upstream?

Thanks!

**Comment by jwhit-MSFT** [comment]
Thanks the feedback--I've passed this issue to the product team to investigate.

**Comment by RAJU2529** [comment]
@gregecslo.  You must enable that particular language under windows settings --time& language -- language, add that language. once installation completed, you will see proofing language

**Comment by gregecslo** [comment]
Hi!

We tried it but it doesn’t work.
We have numerous other proofing tools installed and they work just fine just Serbian doesn’t.

I still believe its a bug.

Regards, Gregor

**Comment by gregecslo** [comment]
Hello!
This is not resolved, still unable to set proofing language to Serbian.

**Comment by gregecslo** [comment]
Hi.

Can someone please take a second look at this one?
This is still not resolved, proofing tools for Serbian LATIN still don`t work.
We deployed 13 others that do work ok, just this one doesn`t.

Can you please reopen this issue?

Thanks!

**Comment by jwhit-MSFT** [comment]
Thanks for the feedback. I just passed this information along to the product team so they can investigate. In the meantime, I recommend working with [support ](https://docs.microsoft.com/en-us/DeployOffice/feedback#get-support-for-problems-with-office) to address this issue.

**Comment by jwhit-MSFT** [comment]
Quick update: the product team is investigating and looking at getting this fixed. I'll update with a status when I hear more. Thanks again for catching this.

**Comment by gregecslo** [comment]
Hi!
Issue is resolved and confirmed working.

Thanks again!

**Comment by jwhit-MSFT** [comment]
Glad to hear it--and thanks again for catching this.
