### ISSUE TITLE
Configuration Manager, UpdateURL and Schedule Tasks

### ISSUE THREAD

**Issue by ahcash** [MicrosoftDocs/OfficeDocs-DeployOffice#33]
Hi there,
Great documentation.  However, would like to find out :

1. How "Office Automatic Update" schedule task is going to affect this?
2.  Will "Manage Office 365 Client" Client Policy in SCCM achieve the same thing here?
3.  If there were "UpdateURL" specified previously, will a manual triggered update still use the content in the URL?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44a78111-ae98-5b26-b349-3e62960f02c4
* Version Independent ID: 23052a9d-431b-1367-791f-ef2f137d4c47
* Content: [Manage updates to Office 365 ProPlus with System Center Configuration Manager](https://docs.microsoft.com/en-us/DeployOffice/manage-updates-to-office-365-proplus-with-system-center-configuration-manager)
* Content Source: [DeployOffice/manage-updates-to-office-365-proplus-with-system-center-configuration-manager.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/manage-updates-to-office-365-proplus-with-system-center-configuration-manager.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by JGruszczyk** [comment]
Hi! Please see your answers below:

1. When the Office COM Object is enabled, the schedule task still runs but it does not perform update searches as that is managed by ConfigMgr. However we still always recommend to leave the scheduled task running as it performs other events outside of updates

2. Yes there are three ways to enable the Office COM object - the client policy setting in ConfigMgr you referenced, Group Policy Object, and through the configuration XML file via Office Deployment Tool

3. Correct - if the UpdateURL address points to a location, a manual trigger of the Office update mechanism (officec2rclient.exe) will reference this UpdateURL. However when using ConfigMgr to manage updates the UpdateURL value is ignored, and in recent Office builds when the Office COM Object is enabled the "Update Now" button featured in the Office apps is disabled preventing end users from calling the update mechanism themselves. This means only an elevated user could call it via command line, not via the Office UI, keeping all users being managed by ConfigMgr and not the UpdateURL
