### ISSUE TITLE
You're joking, RIGHT?

### ISSUE THREAD

**Issue by christopherdengler** [MicrosoftDocs/OfficeDocs-DeployOffice#330]
This is a joke, right?  In order to exclude certain products from installation users must edit XML configuration files?  So, IN ADDITION to the fact that you CANNOT install Office on ANY other drive other than C: with some really obscure registry hack (which can and does screw up your system), people can't uninstall programs from the Office Suite that they NEVER USE?  What happened to Microsoft?  This is not rocket science?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66127c02-c2dc-f6d1-6e83-a6d2b1166731
* Version Independent ID: 27635315-22db-d136-f07e-5169f6207b50
* Content: [Overview of the Office Deployment Tool](https://docs.microsoft.com/en-us/deployoffice/overview-of-the-office-2016-deployment-tool#feedback)
* Content Source: [DeployOffice/overview-of-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by jwhit-MSFT** [comment]
Thanks for the feedback--I've passed it along to the product team.

**Comment by jwhit-MSFT** [comment]
Also, you're welcome to provide this feedback directly to the engineering team in the Office 365 uservoice forum--see the link on this feedback page: https://docs.microsoft.com/en-us/deployoffice/feedback

**Comment by christopherdengler** [comment]
If they haven’t listened to this request in the last 3 years, they’re not going to listen now.  I worked at Microsoft for a long time.  It’s not the same company.  Good luck, though.

**Comment by charles-steiger** [comment]
That I have to use a deployment tool to choose which elements of Office I want to install, as a home user, is ridiculous.

My next steps will be:
1. Migrate Microsoft Office apps that I use to a virtual machine
2. Find replacements for all Office apps
3. Migrate to replacement office suite
4. Delete virtual machine
5. Now I only have to use Office at work, where I don't really have a choice

Laters

**Comment by christopherdude** [comment]
@jwhit-MSFT - I appreciate your optimism, but no one has touched this bug/feature (whatever you want to call it) in years.  If you'd like to walk this down to the "Office Team" there in whatever building they're in these days, I'm sure tens of thousands of people would be thankful.
