### ISSUE TITLE
RDSH Support

### ISSUE THREAD

**Issue by mvdveer85** [MicrosoftDocs/OfficeDocs-DeployOffice#331]
Will the support statement about the OneDrive Desktop App on RDSH be reviewed as a result of the FSLogix acquisition?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce2587dd-9e3e-efdb-dc12-49ffcc8dfd44
* Version Independent ID: 8c98e559-ee79-61a8-2177-7f47d9325dec
* Content: [OneDrive for Business and VDI environments](https://docs.microsoft.com/en-us/deployoffice/rds-onedrive-business-vdi#feedback)
* Content Source: [DeployOffice/rds-onedrive-business-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/rds-onedrive-business-vdi.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
Article was updated to reflect the FSLogix support.
