### ISSUE TITLE
SCCM Supported

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/OfficeDocs-DeployOffice#332]
Wording around SCCM support should be clarified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d68af5b0-45f7-53db-8cee-f03a9ce8bd9b
* Version Independent ID: f94fd8f0-6a0f-7eda-f87d-ad904a9e62f7
* Content: [Choose how to manage updates to Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/choose-how-to-manage-updates-to-office-365-proplus)
* Content Source: [DeployOffice/choose-how-to-manage-updates-to-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/choose-how-to-manage-updates-to-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
We made several changes to the documentation, e.g. #695 to clarify. Thanks for bringing this up.
@DHB-MSFT to be closed
