### ISSUE TITLE
Clarify requirements

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/OfficeDocs-DeployOffice#333]
Great article overall.
Would like to see note on whether "Excel 2010 or later" and "Microsoft Access Database Engine 2010 Redistributable (only if you're using a Click-to-Run version of Access)" are applicable only to computer consuming gathered JSON files into the resulting spreadsheet, or also to end user computers where data is gathered from.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2843afe2-a11d-7d88-8b56-24f131782d01
* Version Independent ID: f8bc6a27-b9f5-a729-b5e3-fdd9ac6642ed
* Content: [Use the Readiness Toolkit to assess application compatibility for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro#feedback)
* Content Source: [DeployOffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
We submitted pull request #739 to clarify the requirements for certain scenarios (data gathering vs. creating reports). Thanks for the feedback.
@jwhit-MSFT to be closed
