### ISSUE TITLE
Incomplete

### ISSUE THREAD

**Issue by NeverEnoughCoffeeMan** [MicrosoftDocs/OfficeDocs-DeployOffice#335]
This page is an adequate introduction but amazingly lacking in detail. And don't bother trying to fill the gaps with the Office Customization Tool; it's equally shallow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a0b1ff-0498-505a-6024-b813980d310f
* Version Independent ID: b8057930-b4bd-1304-17ce-5561f837e901
* Content: [Configuration options for the Office Deployment Tool](https://docs.microsoft.com/en-us/deployoffice/configuration-options-for-the-office-2016-deployment-tool#remove-element)
* Content Source: [DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by jwhit-MSFT** [comment]
Thanks for the feedback. It'd be good to know what details you're looking for--we may cover them in other articles, or we may have a gap we need to fill in. Let me know and I can investigate.
