### ISSUE TITLE
Shared vs 'Standard' Activation

### ISSUE THREAD

**Issue by bahnjee** [MicrosoftDocs/OfficeDocs-DeployOffice#336]
Small college here.  I have two related questions:
(1.)  I was planning on creating two SCCM deployments.  One for student PCs (a Shared install for PCs which will have many students logging on) and one for employee PCs (a 'Standard' install for PCs which will _usually_ have only one employee logging on).  However, it occurs to me that I could deploy just the one Shared install and thereby have only one deployment to manage.

Is there anything wrong with this method?

(2.)  I know that using the Shared activation doesn't count against the 5 available installs for users.  Does the 'Standard' activation count against these 5 installs?  If so, I'll have to go with SCA on all PCs because our instructors log on to many lab PCs and would end up having problems.

**Comment by manoth-msft** [comment]
There is nothing wrong with your approach, go ahead.
@DHB-MSFT to be closed
