### ISSUE TITLE
Can't use the Office Customization Tool?

### ISSUE THREAD

**Issue by NickMo1** [MicrosoftDocs/OfficeDocs-DeployOffice#337]
I'm logged in using my user-created corporate account (same one I use to access our VLSC)
When I follow the link to the OCT it says I don't have permission to access the site.  
When I try to manually edit the XML it throws an error asking if my internet connection is working or if I have enough free space.  The components download fine with the default xml, but I need to customize it. 
joys of new technology, thanks click to run, RIP msi installs :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67f2376c-177b-110f-9c88-f83d53bd6bc7
* Version Independent ID: a98d74e5-f7dc-c073-4cb9-a8901895a89a
* Content: [Overview of the Office Customization Tool](https://docs.microsoft.com/en-us/deployoffice/overview-of-the-office-customization-tool-for-click-to-run)
* Content Source: [DeployOffice/overview-of-the-office-customization-tool-for-click-to-run.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-the-office-customization-tool-for-click-to-run.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by DHB-MSFT** [comment]
@NickMo1 -- I've seen that internet/free space error message before when I have a syntax error in my xml file. One way to check is to see if you can open the xml file in your web browser. If it doesn't open there, you have an xml syntax error.

Also, have you tried to go to [https://config.office.com](https://config.office.com) in a private browser session, so it doesn't use your credentials?  You should be able to get to the main page and then choose Create in the lower left of the page.

Hope that helps.
