### ISSUE TITLE
The Tip URL is no longer resolving

### ISSUE THREAD

**Issue by kyjeeper** [MicrosoftDocs/OfficeDocs-DeployOffice#338]
On the section for "Apply updates automatically from an on-premises location to Office 365 ProPlus", the URL for the Tip is no longer valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d68af5b0-45f7-53db-8cee-f03a9ce8bd9b
* Version Independent ID: f94fd8f0-6a0f-7eda-f87d-ad904a9e62f7
* Content: [Choose how to manage updates to Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/choose-how-to-manage-updates-to-office-365-proplus#feedback)
* Content Source: [DeployOffice/choose-how-to-manage-updates-to-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/choose-how-to-manage-updates-to-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@kyjeeper  -- thanks for pointing that out. They recently retired/turned off a bunch of TechNet blog sites, and that was one of them.  We'll remove that Tip from the article. Thanks for the feedback.

**Comment by DHB-MSFT** [comment]
Tip removed from the article.
