### ISSUE TITLE
adding a language as input to powerpoint is too complicated

### ISSUE THREAD

**Issue by kkashyap2011** [MicrosoftDocs/OfficeDocs-DeployOffice#339]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f9346af-b153-c6de-0a1e-02764754497e
* Version Independent ID: e25eb944-49c0-5f51-47f3-63edca7ee151
* Content: [Customize language setup and settings for Office 2016](https://docs.microsoft.com/en-us/DeployOffice/office2016/customize-language-setup-and-settings-for-office-2016#feedback)
* Content Source: [DeployOffice/office2016/customize-language-setup-and-settings-for-office-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2016/customize-language-setup-and-settings-for-office-2016.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by kkashyap2011** [comment]
Adding a new language as input is too complicated in powerpoint. why cant it be just a list where you select it.  so difficult to install new packages and locate where to install etc. this could be made much easier. adding sanskrit is important to me. Please help.

**Comment by jwhit-MSFT** [comment]
To add a language to Office on your computer, try this article: https://support.office.com/en-us/article/add-an-editing-language-or-set-language-preferences-in-office-663d9d94-ca99-4a0d-973e-7c4a6b8a827d?ui=en-US&rs=en-US&ad=US. The above article is for deploying languages to hundreds of computers.
