### ISSUE TITLE
Remote Desktop Session Hosts

### ISSUE THREAD

**Issue by m4ngo** [MicrosoftDocs/OfficeDocs-DeployOffice#34]
Would users on a Remote Desktop Session Host see these update notifications if the Group Policy settings are not configured?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67822bd8-e17c-5e0b-2ad8-f51325dcb30d
* Version Independent ID: 2a10d821-4fa6-9e06-232c-7d6cba683615
* Content: [End-user update notifications for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/end-user-update-notifications-for-office-365-proplus)
* Content Source: [DeployOffice/end-user-update-notifications-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/end-user-update-notifications-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
I believe users on RDSH will see update notifications, but I'm trying to get confirmation that's actually the case.

**Comment by DHB-MSFT** [comment]
Yes, users on RDSH should see those notifications. Office wouldn't update if any user had any Office apps running, since all users are running on the same computer and Click-to-Run (the installation/update technology) is installed/runs per computer, not per user.  Hope that helps.
