### ISSUE TITLE
Support Lifecycle

### ISSUE THREAD

**Issue by FullStackEngN** [MicrosoftDocs/OfficeDocs-DeployOffice#340]
It's confused about the support lifecycle.

This sentence states 18 months support.
&gt; The semi-annual feature update releases of Office 365 ProPlus are supported for 18 months, starting from the initial release.

But in this sample, it only give 15 months support, from Jan 8, 2019 to Mar 2020. If it's 18 months support, then end date should be June, 2020.

&gt;For example, on September 11, 2018, Version 1808 of Office 365 ProPlus was released to Semi-Annual Channel (Targeted). On January 8, 2019, Version 1808 is scheduled to be made available to Semi-Annual Channel and will be supported in Semi-Annual Channel until March 2020. 

Please confirm, Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cd85e3b-e780-457e-9502-856bc6315bca
* Version Independent ID: 416e351f-13c5-e951-ea81-1650910a7c25
* Content: [Overview of update channels for Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/overview-of-update-channels-for-office-365-proplus#feedback)
* Content Source: [DeployOffice/overview-of-update-channels-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-update-channels-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@FullStackEngN -- the support duration starts when a version is released to Semi-Annual Channel (Targeted).  So in the example, Version 1808 was released in September 2018 to Semi-Annual Channel (Targeted) and 4 months later, Version 1808 was released in Semi-Annual Channel. Version 1808 is supported until March 2020, which is 14 months later. So 4 +14 = 18.  We'll see if we can make that clearer in the article. Thanks for the feedback.
