### ISSUE TITLE
Not working on Edge or IE but is on Chrome

### ISSUE THREAD

**Issue by jmanning16** [MicrosoftDocs/OfficeDocs-DeployOffice#341]
Unable to select any options from dropdowns in edge or IE.

Also no options come up at all for the Select a Channel drop down as well.

**Comment by jmanning16** [comment]
Came across this because of the below error that comes up when clicking 'Go to the Office Customization Tool' in the SCCM client but then discovered that it called edge and edge didn't work either

![image](https://user-images.githubusercontent.com/44354111/55930563-3ad4fd00-5c65-11e9-9176-176a5b9fceca.png)

**Comment by DHB-MSFT** [comment]
@jmanning16 -- Thanks for letting us know that you're having problems with the site. We're hearing some other similar reports. The team responsible for that site is investigating.

**Comment by jwhit-MSFT** [comment]
Looks like it's working now--please let us know if you run into any more issues.
