### ISSUE TITLE
SourcePath variable should include a trailing \

### ISSUE THREAD

**Issue by willaymond** [MicrosoftDocs/OfficeDocs-DeployOffice#342]
If you don't include a trailing \ on your SourcePath in your configuration file, your /download will end up in the wrong place (know this from experience).

Why they don't show it correctly above, I have no idea. You'll note they sometimes use it in the DownloadPath which I would assume is also very important.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a0b1ff-0498-505a-6024-b813980d310f
* Version Independent ID: b8057930-b4bd-1304-17ce-5561f837e901
* Content: [Configuration options for the Office Deployment Tool](https://docs.microsoft.com/en-us/deployoffice/configuration-options-for-the-office-2016-deployment-tool#feedback)
* Content Source: [DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by jwhit-MSFT** [comment]
Thanks for the feedback. This is working in my test with or without the trailing \, but I'll investigate further and update if needed.
