### ISSUE TITLE
PDF versus online article

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/OfficeDocs-DeployOffice#343]
The &lt;Donwload PDF&gt; copy has a different last update compared to the online article.
November 2018 versus march 2019.
Can you please ensure they are in line?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6da18a8b-9e96-0155-7b30-9c211070d793
* Version Independent ID: 5a7e610a-bfcb-d9cc-03f7-589d970128d9
* Content: [Deploy Office 365 ProPlus by using Remote Desktop Services](https://docs.microsoft.com/en-us/deployoffice/deploy-office-365-proplus-by-using-remote-desktop-services#feedback)
* Content Source: [DeployOffice/deploy-office-365-proplus-by-using-remote-desktop-services.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-office-365-proplus-by-using-remote-desktop-services.md)
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@teomonda -- I just clicked Download PDF and the version I got (in English) shows March 1, 2019 as the last update date.

![image](https://user-images.githubusercontent.com/32883970/56050891-e2077200-5d01-11e9-9d05-33169c014611.png)

**Comment by teomonda** [comment]
You are right, now it shows correctly.
It did not a few hours ago 😊

**Comment by DHB-MSFT** [comment]
@teomonda -- that's very odd. But thanks for asking us about it.
