### ISSUE TITLE
Deployment from Cloud?

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/OfficeDocs-DeployOffice#344]
Wouldn't that be from Intune? not from local fileshare? Not many fileshares in the cloud world

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56455cc-de1d-7daa-bae1-8a344625bc71
* Version Independent ID: 8bafdb99-1562-bc9d-c27b-596250dee4e2
* Content: [Deploy Office 365 ProPlus from the cloud](https://docs.microsoft.com/en-us/DeployOffice/deploy-office-365-proplus-from-the-cloud)
* Content Source: [DeployOffice/deploy-office-365-proplus-from-the-cloud.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-office-365-proplus-from-the-cloud.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by jwhit-MSFT** [comment]
Deploy from Intune is here: https://docs.microsoft.com/en-us/intune/apps-add-office365. You can also deploy from the cloud using the Office Content Delivery Network as a source for the Office bits, which is what this article covers. Let me know if that answers your question.

**Comment by JeremyTBradshaw** [comment]
@jwhit-MSFT It does seem odd that deployment from Intune isn't included the Microsoft 365 Apps Deployment guide itself.  The link you provided is legit, but why is it orphaned off on its own?
