### ISSUE TITLE
What about Intune?

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/OfficeDocs-DeployOffice#345]
Seems like Intune is missing from Deployment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff6a078e-6113-c6b3-d675-b5ae97d8787b
* Version Independent ID: 9073d780-7d8b-7acb-6a95-544f6d0a62b9
* Content: [Deployment guide for Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/deployment-guide-for-office-365-proplus?wt.mc_id=4039827)
* Content Source: [DeployOffice/deployment-guide-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deployment-guide-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by jwhit-MSFT** [comment]
Thanks for the feedback. We have plans to add this to the Office repo in the future. For now, we recommend using the Intune docs, particularly this article: https://docs.microsoft.com/en-us/intune/apps-add-office365.
