### ISSUE TITLE
Error on pilot test [ERROR]	[VbaWorkflows]

### ISSUE THREAD

**Issue by HPE-GV** [MicrosoftDocs/OfficeDocs-DeployOffice#346]
Greetings !
-We are running a pilote test prior to a full audit on files shares only +30TB in multiple sites.
The pilot test is a no go with a failed result (empty xlsm) and many error in the logs that I can not found in any support discussion:

-When opening the report the xlsm popup the readiness report has encounter a problem that may result in unexpeted behavior.

-The report is empty.

-The logs is 130 MB with many recurring error:

364'243files for a total of  306GB
2019/4/3_16:27:35:930	[ERROR]	[VbaWorkflows]	Expected file to contain VBA but encountered MissingVbaException	TagId:0000	
2019/4/13_17:48:5:493	[ERROR]	[Report]	Writing Excel Report Exception! Exception of type 'System.OutOfMemoryException' was thrown.    at System.Text.StringBuilder.ToString()
2019/4/13_17:48:5:499	[Info]	[UI]	OnWorkflowEnded ExcelReportWriting ScanningError	TagId:97nuw	
2019/4/15_9:16:49:771	[ERROR]	[Common]	No ReadyServiceUrl retrieved from config provider	TagId:97yj1	
2019/4/15_9:16:50:21	[Info]	[UI]	Check version service call failed! Error: Object reference not set to an instance of an object.

Can someon assist ??.

Best regards,

Huges.

**Comment by DHB-MSFT** [comment]
@HPE-GV  -- For problems with the Readiness Toolkit, contact ReadyForOffice@microsoft.com. They should be able to help you.
