### ISSUE TITLE
Error  in  administrative  templates 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#348]
yesterday I downloaded   32bit version templates from this  site 
https://www.microsoft.com/en-us/download/details.aspx?id=49030
  , and I copied  all .admx  and .adml files  to  policydefinitions  folder.
but  today  I tried  to open group policy editor  , I  received  errors  message . 
problem is in office16.admx  file only

Resource '$(presentation.L_ConnectedOfficeExperiences)' referenced in attribute presentation could not be found

But if  delete new  office16.admx  and  I  replaced  with old  office16.admx  ,  goo  works  fine  without  issues 
Please look in these  issues and  rectify soon 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad6ffab-7521-ff87-74ed-bb3a721cb64d
* Version Independent ID: 3a3feee5-6cec-ebdd-c459-0155b355541d
* Content: [What's new for admins in Office 2016](https://docs.microsoft.com/en-us/deployoffice/office2016/what-s-new-for-admins-in-office-2016#feedback)
* Content Source: [DeployOffice/office2016/what-s-new-for-admins-in-office-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2016/what-s-new-for-admins-in-office-2016.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@RAJU2529  -- There is a new set of admx & adml files that were posted on Friday 19 April 2019.  Please download those and see if the same problem occurs.

**Comment by RAJU2529** [comment]
Thanks for the information. Just now I downloaded from official website.

In new version,  there is a language problem   

all .adml files are not written in English language 

all .adml0 files are written in English language.
 So please change extension.adml0 to .adml  for default English language.

Then Reupload to the server for download.

All .admx files are written in English language .
 
I copied required files after changing the extension name to policydefinition folder.

For finding issues and review, give me one day time.
Thanks a lot sir.
Don't cLose this request

**Comment by DHB-MSFT** [comment]
@RAJU2529  -- Sorry, but I don't understand your comment about the languages. I just tested the new admx/adml files, testing in both English and French, and the policy settings are showing up in the correct languages, as expected.

**Comment by RAJU2529** [comment]
No sir. I was opened the .adml file using notepad,  it was opened in other language than English language

**Comment by RAJU2529** [comment]
The following is  not an issues , But I  am giving suggestions  to make office 2016 further better and easy use by users and remember exact position 

In every Office 2016 or 2019 Applications, In group policy office templates ,  Please add the following options 
01. Allow background saves
02. Save autorecover info
02. Save Autorecover info every minutes 
03. Default file format
04. Set default compatibility mode on file creation

Under the each application  if  supported  by 
01. Microsoft Access 2016\Access Options\Save  
02. Microsoft Excel 2016\Excel Options\Save  
03. Microsoft OneNote 2016\OneNote Options\Save  
01. Microsoft Outlook 2016\Outlook Options\Save  
01. Microsoft PowerPoint 2016\PowerPoint Options\Save  
01. Microsoft Publisher 2016\Publisher Options\Save  
01. Microsoft Vision 2016\Visio Options\Save  
01. Microsoft Word 2016\Word Options\Save  



Track changes and compare
01. Compare resulting document

under the each application  if  supported  by 
01. Microsoft Access 2016\Access Options\Track changes and compare
02. Microsoft Excel 2016\Excel Options\Track changes and compare
03. Microsoft OneNote 2016\OneNote Options\Track changes and compare
01. Microsoft Outlook 2016\Outlook Options\Track changes and compare
01. Microsoft PowerPoint 2016\PowerPoint Options\Track changes and compare
01. Microsoft Publisher 2016\Publisher Options\Track changes and compare
01. Microsoft Vision 2016\Visio Options\Track changes and compare
01. Microsoft Word 2016\Word Options\Track changes and compare

Thanks for  your  kind  information and replies . I think you are  the creator of  Policy templates. Great work sir. Excellent
