### ISSUE TITLE
Need to warn about Exchange Online Requirement

### ISSUE THREAD

**Issue by giterdn** [MicrosoftDocs/OfficeDocs-DeployOffice#349]
I've found that by installing Office from the Mac App store, the version of Outlook that it installs will not work with an on-prem Exchange mailbox, only an Exchange Online mailbox.  Please include this in your 'differences' and 'cautions'.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bca0ba76-cbbf-563b-6baa-7a09cd742e87
* Version Independent ID: 578cb671-6328-b85f-3b07-813b073e810f
* Content: [Deploy Office for Mac from the Mac App Store](https://docs.microsoft.com/en-gb/deployoffice/mac/deploy-mac-app-store?toc=%2Fdeployoffice%2Ftoc.json#feedback)
* Content Source: [DeployOffice/mac/deploy-mac-app-store.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/mac/deploy-mac-app-store.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @pbowden-msft
* Microsoft Alias: **danbrown**

**Comment by pbowden-msft** [comment]
Thanks for the heads-up @giterdn We're investigating this now, as your results are unexpected.

**Comment by msm-fc** [comment]
FWIW I'm using Office from the Mac App Store with an on-prem Kerio Connect server with no problems. Check to make sure your autodiscover address and PTR records are set correctly.

**Comment by giterdn** [comment]
Since I wrote this, I found the necessary steps to make this work - it is not obvious how to get to the screen where you can connect to an on-prem server, but there is a way.
