### ISSUE TITLE
The Apps switch for muspdate is not working

### ISSUE THREAD

**Issue by MrEdLuo** [MicrosoftDocs/OfficeDocs-DeployOffice#35]
Running **./msupdate -l** clearly shows updates available

_**Loaner05:MacOS loaner$ ./msupdate -l
Checking for updates...
Updates available:
  ONMC15  OneNote Update 16.12.0 (18041000)
  XCEL15  Excel Update 16.12.0 (18041000)
  PPT315  PowerPoint Update 16.12.0 (18041000)
  OPIM15  Outlook Update 16.12.0 (18041000)
  MSWD15  Word Update 16.12.0 (18041000)**_

Running **./msupdate -i -a ONMC15,XCEL15,PPT315,MSWD15** refuses to install the updates for specified apps

Loaner05:MacOS loaner$ ./msupdate -i -a ONMC15,XCEL15,PPT315,MSWD15
Detecting and downloading updates...
No updates applied

**Comment by pbowden-msft** [comment]
Thanks for the bug report. Yes, this is a known issue in the 3.18 release. The bug number tracking the issue on our side is #2292004.

Paul.
