### ISSUE TITLE
SCCM managing Office 365 updates?

### ISSUE THREAD

**Issue by riatheone** [MicrosoftDocs/OfficeDocs-DeployOffice#350]
Apparently this now has been included in SCCM? A linky would be nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2324f001-9c0f-8730-0326-747300a87b78
* Version Independent ID: 5123d9b2-e45b-180a-1431-852542e8a1db
* Content: [Overview of the update process for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/overview-of-the-update-process-for-office-365-proplus#feedback)
* Content Source: [DeployOffice/overview-of-the-update-process-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-the-update-process-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by byteben** [comment]
https://docs.microsoft.com/en-us/deployoffice/manage-updates-to-office-365-proplus-with-system-center-configuration-manager
