### ISSUE TITLE
Typo "Outlook is a an exception"

### ISSUE THREAD

**Issue by LarochelleFanny** [MicrosoftDocs/OfficeDocs-DeployOffice#353]
I believe there is a typo in this section "Outlook is a an exception" shouldn't it be "Outlook is an exception".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d22aec53-c328-ee44-0b01-475d6ee3f940
* Version Independent ID: 2b39a702-7f42-9b63-d27b-af4806646770
* Content: [Overview of optional connected experiences in Office](https://docs.microsoft.com/en-us/DeployOffice/privacy/optional-connected-experiences#research)
* Content Source: [DeployOffice/privacy/optional-connected-experiences.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/optional-connected-experiences.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@LarochelleFanny  -- yes, that's a mistake. Thanks for noticing and letting us know. Issue has been fixed.
