### ISSUE TITLE
[LOC] Possibly incorrect source text in an article

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-DeployOffice#354]
Hello,

During translations of one of the articles it was brough to our attention that there might be an error in the sentence below:

**Failure to sign in will result in the users being able to use the app**

Which does not make sence

The sentence can be found within the article below:
https://docs.microsoft.com/en-us/deployoffice/privacy/essential-services

GH article:
https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/essential-services.md

![image](https://user-images.githubusercontent.com/47977325/57079791-60e43f00-6cf1-11e9-8f2a-3b6a065c65e0.png)

**Comment by DHB-MSFT** [comment]
@OfficeGlobal  -- thanks for bringing this to our attention. We're checking into it, but I suspect there's a "not" missing from that sentence.

**Comment by DHB-MSFT** [comment]
@OfficeGlobal -- we have received confirmation that the sentence is missing the word "not."  We've updated the article and re-published. Thanks for bringing this to our attention.
