### ISSUE TITLE
Need clarity on updates with SCCM 

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/OfficeDocs-DeployOffice#356]
In step 2 it says "We recommend updating your client devices automatically from the Office CDN" and "If you choose to manage the updates directly, you can do so with Configuration Manager by downloading the updates and deploying them from distribution points."

However, in https://docs.microsoft.com/en-us/deployoffice/deploy-office-365-proplus-with-system-center-configuration-manager it says "When deploying with the Office Client Management dashboard and Office 365 Installer wizard, you must manage updates with Configuration Manager as well.".

So need clarity if can be Office deployed with SCCM but updated later on from CDN.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b314dc73-e63b-9712-a4b1-9171ad6b7e82
* Version Independent ID: d3b16d76-6883-4e52-9c32-4699379d40c8
* Content: [Plan your enterprise deployment of Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/plan-office-365-proplus#feedback)
* Content Source: [DeployOffice/plan-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/plan-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by bmilbauer** [comment]
Hey Juan,

Not a microsofter but yes you can deploy Office 365 ProPlus with SCCM and choose to update it via the CDN. I personally don't recommend using the CDN unless all your computers with O365 ProPlus are Windows 10 with delivery optimization enabled and functional. Also keep in mind if you don't manage the updates with SCCM, the day Microsoft releases a feature update to Office to the channel your clients are on, ALL of those clients will install that feature update as if it was a normal monthly update. Sorry if that sounds confusing. Feel free to reach out.

**Comment by jwhit-MSFT** [comment]
Thanks for the feedback. We're updating this content, in part to address this contradiction. Updated content will specify how to deploy from Configuration Manager and update automatically from the Office CDN. (Or manage updates with Configuration Manager, if that better meets your requirements.)
