### ISSUE TITLE
Allow the use of additional optional connected experiences in Office doesn't work properly

### ISSUE THREAD

**Issue by hrrysckr** [MicrosoftDocs/OfficeDocs-DeployOffice#360]
Disabling 'Allow the use of additional optional connected experiences in Office' only prevents the dialog pop-up in Outlook. The File &gt; Account &gt; Account Privacy &gt; Manage Settings box is not available in Outlook, however in any other application the pop-up appears and the Manage Settings option is available.

This is not consistent when we are trying to prevent this being shown to users completely.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef4debee-6a1e-53c7-7bec-2dbd208f4f2d
* Version Independent ID: b93ad6a2-0976-6f5f-7aae-1756079bdc1d
* Content: [Use policy settings to manage privacy controls for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/privacy/manage-privacy-controls#feedback)
* Content Source: [DeployOffice/privacy/manage-privacy-controls.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/manage-privacy-controls.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@hrrysckr  -- not sure if this is related to your comment, but we've found an issue with this policy setting (and the other 3 policy settings related to connected experiences).

For now, to disable one of these policy settings by using the Group Policy Management tool, you need to select the **Enabled** radio button and then choose **Disabled** from the drop-down list in the **Options** section. Selecting the **Disabled** radio button won't disable these policy settings.

We're working to fix this issue. In the meantime, we've added an Important callout to the content to let admins know about this issue.

**Comment by hrrysckr** [comment]
This does look to be related! Thank you.

**Comment by DHB-MSFT** [comment]
@hrrysckr -- Wanted to let you know that an updated set of Group Policy files was published yesterday (Tuesday 28 May) that fixes this problem. So you should download the updated ADMX/ADML files from https://www.microsoft.com/en-us/download/details.aspx?id=49030. We'll update this article to let others know about the updated ADMX/ADML files. Thanks for bringing this issue to our attention so that we could get it fixed.

**Comment by tiherz** [comment]
This bug seems to be still present in Intune. I just tested these policies with an AAD joined and Intune managed client and hat to perform the same workaround to get it working.
