### ISSUE TITLE
Poster links aren't working

### ISSUE THREAD

**Issue by edemilliere** [MicrosoftDocs/OfficeDocs-DeployOffice#361]
https://go.microsoft.com/fwlink/?LinkId=626680
https://go.microsoft.com/fwlink/?LinkId=626681
http://download.microsoft.com/download/E/2/5/E259F199-A7E5-4C4A-B684-B0920888DF52/ChangeManagementinOffice365.vsdx
http://download.microsoft.com/download/E/2/5/E259F199-A7E5-4C4A-B684-B0920888DF52/ChangeManagementinOffice365.pdf

Those links won't work, can you please correct them ? This one seems to work (I found it by searching by file name in Google) https://www.microsoft.com/en-us/download/details.aspx?id=49141
I'm sure this is the last version.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37dc62b3-b7ac-6365-c30c-bee3b1c15b4a
* Version Independent ID: 0f81b8e7-bb6e-180d-9449-5c9d34c64c6e
* Content: [Change management for Office 365 clients](https://docs.microsoft.com/en-us/deployoffice/change-management-for-office-365-clients)
* Content Source: [DeployOffice/change-management-for-office-365-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/change-management-for-office-365-clients.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@edemilliere -- Those links seem to be working now. It might have been a temporary issue. Thanks.
