### ISSUE TITLE
Why did MS turn installation into rocket science?

### ISSUE THREAD

**Issue by LJ9999** [MicrosoftDocs/OfficeDocs-DeployOffice#363]
All I want to do is uninstall Outlook. That's all! And I can't do it because I cannot untangle 20 web pages of rocket science about manipulating XML files in infinite combinations.

When all I need is a stupid checkbox to uncheck or an uninstall button to press.

This is so believable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a0b1ff-0498-505a-6024-b813980d310f
* Version Independent ID: b8057930-b4bd-1304-17ce-5561f837e901
* Content: [Configuration options for the Office Deployment Tool](https://docs.microsoft.com/en-us/DeployOffice/configuration-options-for-the-office-2016-deployment-tool?redirectSourcePath=%252fen-us%252farticle%252fd3879f0d-766c-469c-9440-0a9a2a905ca8)
* Content Source: [DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by jwhit-MSFT** [comment]
Thanks for the feedback--it's good to hear the request so we can prioritize the feature on the engineering team. I agree that the approach in this article (including editing XML files) is overkill for this scenario--it's more useful in an enterprise setting when deploying to hundreds or thousands of computers.
