### ISSUE TITLE
'Need to implement an uninstall button for Outlook.

### ISSUE THREAD

**Issue by LJ9999** [MicrosoftDocs/OfficeDocs-DeployOffice#364]
And please make sure it's not disabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b314dc73-e63b-9712-a4b1-9171ad6b7e82
* Version Independent ID: d3b16d76-6883-4e52-9c32-4699379d40c8
* Content: [Plan your enterprise deployment of Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/plan-office-365-proplus#step-3---choose-your-update-channels)
* Content Source: [DeployOffice/plan-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/plan-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by jwhit-MSFT** [comment]
Thanks for the feedback. I'd suggest adding this request to the [user voice site for Outlook](https://outlook.uservoice.com/).
