### ISSUE TITLE
visio online plan 2 with ms office 2016 standard (msi)

### ISSUE THREAD

**Issue by haikucat** [MicrosoftDocs/OfficeDocs-DeployOffice#366]
will this combination work? what ms office suite will work with Visio online plan 2? or conversely, what Visio plan will work with MS Office 2016 standard (msi)? also, which skype for business version will work with Visio online plan 2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d40c96f3-1c97-b538-ef82-ffbf0eef204d
* Version Independent ID: 2d6883b5-1b5c-dc16-9999-17d0652bfa48
* Content: [Supported scenarios for installing different versions of Office, Project, and Visio on the same computer](https://docs.microsoft.com/en-us/deployoffice/install-different-office-visio-and-project-versions-on-the-same-computer#feedback)
* Content Source: [DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
Visio Online Plan 2 can be combined with Microsoft 365 Apps, Office 2019 or Office 2016 retail (no VL, no MSI).
