### ISSUE TITLE
Deploy from Cloud-Intune?

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-DeployOffice#367]
Does the deployment from the Cloud approach mean using Intune, or something else? Please add some guidance for organizations that have SCCM setup to co-manage with Intune. This is not specifically addressed currently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b314dc73-e63b-9712-a4b1-9171ad6b7e82
* Version Independent ID: d3b16d76-6883-4e52-9c32-4699379d40c8
* Content: [Plan your enterprise deployment of Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/plan-office-365-proplus)
* Content Source: [DeployOffice/plan-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/plan-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by jwhit-MSFT** [comment]
Thanks for the request--that helps us prioritize the hybrid scenario in our backlog. 

There is more info on deploying with Intune in the Intune documentation: [Assign Office 365 apps to Windows 10 devices with Microsoft Intune](https://docs.microsoft.com/en-us/intune/apps-add-office365). T[he deploy from the cloud](https://docs.microsoft.com/en-us/deployoffice/deploy-office-365-proplus-from-the-cloud) scenario called out in our planning article covers using the ODT to deploy bits from the cloud.
