### ISSUE TITLE
Teams - existing install of Office 365 ProPlus - date & update 

### ISSUE THREAD

**Issue by jbadia01** [MicrosoftDocs/OfficeDocs-DeployOffice#371]
When will the dates for Teams release existing installs of _Office 365 ProPlus - Semi-Annual Channel (Targeted)_ be determined? 
will Teams release for existing proplus installs be based on a certain update version? as the monthly channel has version 1906 associated with it. 

Thanks.

**Comment by DHB-MSFT** [comment]
@jbadia01 -- Yes, the addition of Teams to existing versions of Semi-Annual Channel (Targeted) will start with a particular version, just like Monthly Channel. Once we know the version, we'll update the article. Same with the date...once we know that, we'll update the article. Thanks for your question.

**Comment by DHB-MSFT** [comment]
@jbadia01  -- For Semi-Annual Channel (Targeted), it's Version 1908 which was released on 10 September 2019. The [table in the article](https://docs.microsoft.com/deployoffice/teams-install#what-about-existing-installations-of-office-365-proplus) has all the most current info about versions and dates. Hope that helps.
