### ISSUE TITLE
Policy Setting Description does not match Registry Setting

### ISSUE THREAD

**Issue by esplichal** [MicrosoftDocs/OfficeDocs-DeployOffice#372]
disconnectedstate controls "Allow the use of connected experiences in Office" while controllerconnectedservicesenabled controls, "Allow the use of additional optional connected experiences in Office"

This is reversed in the article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef4debee-6a1e-53c7-7bec-2dbd208f4f2d
* Version Independent ID: b93ad6a2-0976-6f5f-7aae-1756079bdc1d
* Content: [Use policy settings to manage privacy controls for Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/privacy/manage-privacy-controls#feedback)
* Content Source: [DeployOffice/privacy/manage-privacy-controls.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/manage-privacy-controls.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@esplichal -- thanks for catching that. We'll get it fixed right away.

**Comment by DHB-MSFT** [comment]
@esplichal  -- article has been fixed and re-published. Thanks again for letting us know about this.
