### ISSUE TITLE
 Office Content Delivery Network

### ISSUE THREAD

**Issue by kcsportal** [MicrosoftDocs/OfficeDocs-DeployOffice#373]
Something on my network is blocking me from using the config file to download Office via the Office Customization Tool. What IP address and ports do I need to white list in order to allow the files to download?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67f2376c-177b-110f-9c88-f83d53bd6bc7
* Version Independent ID: a98d74e5-f7dc-c073-4cb9-a8901895a89a
* Content: [Overview of the Office Customization Tool](https://docs.microsoft.com/en-us/DeployOffice/overview-of-the-office-customization-tool-for-click-to-run)
* Content Source: [DeployOffice/overview-of-the-office-customization-tool-for-click-to-run.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-the-office-customization-tool-for-click-to-run.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by DHB-MSFT** [comment]
This article should have the info you need -- [Office 365 URLs and IP address ranges
](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
