### ISSUE TITLE
What to do after getting Data folder

### ISSUE THREAD

**Issue by Chri3sss** [MicrosoftDocs/OfficeDocs-DeployOffice#374]
Ok, so I followed the instructions in OfficeDocs-DeployOffice and I have a folder called "16.0.10344.20008> which the instructions said to expect. What do I do now? Looking in the folder I see a OfficeClickToRun.exe but get an error message can't run because ApiClient.dll was not found. 
Also to check, I was trying to get Office 2019, is a folder starting with "16" correct?
Thanks

**Comment by DHB-MSFT** [comment]
@Chri3sss -- Yes, a folder starting with 16 is correct. Now that you've downloaded the installation files, you need to run the Office Deployment Tool in /configure mode to do the installation.  All the steps should be covered in the [Deploy Office 2019](https://docs.microsoft.com/en-us/deployoffice/office2019/deploy) article.

**Comment by Chri3sss** [comment]
That worked perfectly, thanks
