### ISSUE TITLE
Annoying use of language

### ISSUE THREAD

**Issue by Cybersal7** [MicrosoftDocs/OfficeDocs-DeployOffice#376]
This page contains the text "your organization’s admin may have provided you with the ability to use one or more cloud-backed services (also referred to as “optional connected experiences”). 

Further down the page I see the phrase 'the ability to use optional connected experiences'. You don't 'USE an experience', you HAVE an experience.  Using language in this weird way makes for an un-nerving and slightly uncomfortable experience and makes me feel that my software is being provided to me by aliens . Have you not read the bit in the Cluetrain Manifesto about TechnoLatin? (Try Bing-ing it).  

If it's a service, call it a service - don't confuse me with multiple words for the same thing!

 I hope you find this feedback helpful.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d22aec53-c328-ee44-0b01-475d6ee3f940
* Version Independent ID: 2b39a702-7f42-9b63-d27b-af4806646770
* Content: [Overview of optional connected experiences in Office](https://docs.microsoft.com/en-gb/deployoffice/privacy/optional-connected-experiences#feedback)
* Content Source: [DeployOffice/privacy/optional-connected-experiences.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/optional-connected-experiences.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Thanks for your feedback. We'll share this feedback with those that are responsible for this terminology.

**Comment by Cybersal7** [comment]
Thanks!
