### ISSUE TITLE
How do I create the msi file without the click-to-run tool?

### ISSUE THREAD

**Issue by bugsy316** [MicrosoftDocs/OfficeDocs-DeployOffice#377]

**Comment by DHB-MSFT** [comment]
Are you asking about Office 2019?  If so, Office 2019 isn't available in MSI format.

**Comment by bugsy316** [comment]
I'm currently running Microsoft Office 365 ProPlus 1905 (Build 11629.20214) and used the current OCT to create the XML and download the source files. You would usually then use the Click-to-run to create the installer package with the option of creating a msi installer file. This option is has been retired. Need to package for deployment.

**Comment by DHB-MSFT** [comment]
@bugsy316 That capability was available in a similar tool that was available on GitHub, but that tool was not supported by the Office deployment product team. The OCT is supported, but there are no plans to include the MSI functionality from that other tool.

**Comment by bugsy316** [comment]
Thanks Daniel.
