### ISSUE TITLE
Won't install!!

### ISSUE THREAD

**Issue by pgw3000** [MicrosoftDocs/OfficeDocs-DeployOffice#378]
Another bloody helpful message from MS

Any ideas what the problem is?
<img width="960" alt="CantInstall" src="https://user-images.githubusercontent.com/32594328/59378626-a7937300-8d4c-11e9-9547-d7a9b9b2cc4f.png">

**Comment by RAJU2529** [comment]
@pgw3000. Go to below site ,, download and  run official uninstall tool.
**https://support.office.com/en-us/article/Uninstall-Office-from-a-PC-9dd49b83-264a-477a-8fcc-2fdf5dbf61d8**

Please some do the following.
01.disable  antivirus  and firewall  for some time
02.connect to the internet and run the tool with admin rights.
03. follow on screens instructions and proceed further and then restart the windows
04.use ccleaner software clean unwanted registry  keys  and temp files
05.  Install the required office product.
