### ISSUE TITLE
Already deployed fix doesn't seem to work

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/OfficeDocs-DeployOffice#381]
We have a machine which was moved from one user to another and has the "your copy of Office doesn't work in a shared computer scenario" now. Rather than redeploy I attempted to use the registry fix detailed below:

If you've already deployed Office 365 ProPlus, you can enable shared computer activation on a computer by using Registry Editor to add a string value of SharedComputerLicensing with a setting of 1 under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration. 

This doesn't work, as I'm still getting the error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ab31873-7ad3-afde-3c72-8a7fb4f2e551
* Version Independent ID: 19f7f483-9f53-f577-1cd4-d360c0b234fc
* Content: [Overview of shared computer activation for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/overview-of-shared-computer-activation-for-office-365-proplus)
* Content Source: [DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by RAJU2529** [comment]
@StuBeck32. You and another user name @brbish   having same problems.
Let wait for some days. Other experienced users will help

**Comment by manoth-msft** [comment]
When switching an already activated device to SCA, you should remove the already existing activation: https://docs.microsoft.com/en-us/office/troubleshoot/activation/reset-office-365-proplus-activation-state

**Comment by StuBeck32** [comment]
Thank you for including a multi step article on a single page.
________________________________
