### ISSUE TITLE
Question on Roaming the activation token

### ISSUE THREAD

**Issue by brbish** [MicrosoftDocs/OfficeDocs-DeployOffice#387]
In section “How Shared Computer activation works for Office 365 Pro Plus” it says: If the user is licensed for Office 365 ProPlus, a licensing token is stored on the computer in the user's profile folder, and Office 365 ProPlus is activated …. If a user goes to another computer that also is enabled for shared computer activation, the same steps occur. There is a different licensing token for each computer that the user logs on to.

Later in “Additional details about shared computer activation for Office 365 ProPlus“ it says: Starting with Version 1704 of Office 365 ProPlus, you can configure the licensing token to roam with the user's profile 
•	And To edit the registry, go to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration, add a string value of SCLCacheOverride, and set the value to 1. Also, add a string value of SCLCacheOverrideDirectory and set the value to the path of the folder to save the licensing token.

Question is: What is the second section above (with the registry key changes) for if the licensing token is already stored in the user’s profile folder? Does this second option do something different; i.e. possibly is the token different; i.e. not computer specific? Or is this second part applicable to versions of Office where the roaming of the activation key isn't in the user's profile as it is now? And if so, at what version was this change made?

Thanks,

Brent Bishop with the FSLogix team. We help roam user profiles and Office 365 data caches and so understanding this information is important to us.

**Comment by RAJU2529** [comment]
This question is  too different  to answer from myside , Let wait for some days, This article authors might will help

**Comment by brbish** [comment]
Any comment here? My original question might be confusing because it took me a minute or two to figure out what I was saying. So the simplified question is: It says in one spot that the licensing is already in the profile. So if that is the case, what does the new reg value (SCLCacheOverrideDirectory) do or what does it do differently? Is it just if you want to place the licening file somewhere other than the default location in the profile? If so this could be made more clear that it is only needed for non-default locations because to me it seems to say that it is needed if you want the licensing token in the profile.

**Comment by MJP-MSFT** [comment]
Hello @brbish 

Sorry for the delay. BY default the apps stores the SCA token in local appdata. The SCLCacheoverride option allows the Admin to move that location to another desired location. Some admins want to store it elsewhere which is what this reg key enables. SCLCacheoverride set to 1 and SCLcacheoverridedirectory with a path to a location that you choose.
