### ISSUE TITLE
Method for managing updates via client settings in SCCM not mentioned

### ISSUE THREAD

**Issue by eckermike** [MicrosoftDocs/OfficeDocs-DeployOffice#388]
Details of this method listed in this other doc

https://docs.microsoft.com/en-us/sccm/sum/deploy-use/manage-office-365-proplus-updates#change-the-update-channel-after-you-enable-office-365-clients-to-receive-updates-from-configuration-manager

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44a78111-ae98-5b26-b349-3e62960f02c4
* Version Independent ID: 23052a9d-431b-1367-791f-ef2f137d4c47
* Content: [Manage updates to Office 365 ProPlus with System Center Configuration Manager](https://docs.microsoft.com/en-us/deployoffice/manage-updates-to-office-365-proplus-with-system-center-configuration-manager#feedback)
* Content Source: [DeployOffice/manage-updates-to-office-365-proplus-with-system-center-configuration-manager.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/manage-updates-to-office-365-proplus-with-system-center-configuration-manager.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by jwhit-MSFT** [comment]
Updated SCCM docs to reflect recommended method for managing updates. Thanks for catching this--and apologies for the delay.
