### ISSUE TITLE
Supported RDS version and old references

### ISSUE THREAD

**Issue by rsparnaaij** [MicrosoftDocs/OfficeDocs-DeployOffice#389]
https://docs.microsoft.com/en-us/deployoffice/deploy-office-365-proplus-by-using-remote-desktop-services#what-you-need-to-get-started

Here it states that only Windows Server 2016 is supported but more versions are mentioned here;
https://products.office.com/en-us/office-system-requirements

Both listings do not include a reference to Windows Server 2019.

But even when you only support Windows Server 2016 for RDS usage, in [the next section](https://docs.microsoft.com/en-us/deployoffice/deploy-office-365-proplus-by-using-remote-desktop-services#install-office-365-proplus-on-an-rds-server), you are providing a link to install RDS on Windows Server 2008 R2. Later [you are again](https://docs.microsoft.com/en-us/deployoffice/deploy-office-365-proplus-by-using-remote-desktop-services#install-office-365-proplus-on-a-shared-virtual-machine) referencing Windows Server 2008 R2 configuration instructions, and the [Related Topics](https://docs.microsoft.com/en-us/deployoffice/deploy-office-365-proplus-by-using-remote-desktop-services#install-office-365-proplus-on-a-shared-virtual-machine) section contains only links for Windows Server 2008 R2, 2012 and 2012 R2 but none for Windows Server 2016.

**Comment by rsparnaaij** [comment]
This recent blog post contains some interesting info which could be good to be included in the official documentation; https://www.microsoft.com/en-us/microsoft-365/blog/2019/07/01/improving-office-app-experience-virtual-environments/

**Comment by manoth-msft** [comment]
I've submitted PR #811 to include the updated system requirements as well as updated the links to remove any Windows Server 2008 references. Good catch and thanks for bringing it to our attention!
