### ISSUE TITLE
Unable to install only proofing tool without the full language pack office 2019 pro

### ISSUE THREAD

**Issue by panoscool** [MicrosoftDocs/OfficeDocs-DeployOffice#390]
I am using office 2019 pro and is impossible to download and install the proofing tool separately I mean without the full language pack

**Comment by RAJU2529** [comment]
@panoscool. We can download all language proofing tools  from below link
[](https://support.office.com/en-us/article/Language-Accessory-Pack-for-Office-82ee1236-0f9a-45ee-9c72-05b026ee809f)

and information link
[](https://support.office.com/en-us/article/change-the-language-office-uses-in-its-menus-and-proofing-tools-f5c54ff9-a6fa-4348-a43c-760e7ef148f8)

**Comment by panoscool** [comment]
I don't need the full language pack but only the proofing tool, like it was in office 2007.

**Comment by RAJU2529** [comment]
above site consists of  separate languages in separate download
