### ISSUE TITLE
When will Office Pro Plus Semi annual channel 1902 be available in Customisation tool?

### ISSUE THREAD

**Issue by Rish8** [MicrosoftDocs/OfficeDocs-DeployOffice#395]
When will the Office Pro Plus Semi annual channel 1902 build be available in the Customisation tool?
It has been released to semi annual channel this week, but its not appearing in the drop-down list when creating a configuration xml file?

thanks

**Comment by DHB-MSFT** [comment]
@Rish8 -- We're hoping to have it appear later today or tomorrow. There is a known issue with a delay between when builds are released and when they appear in the Office Customization Tool drop-down list.  The product team that works on the tool is trying to develop a solution so there isn't this delay.
