### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by smoothdruid** [MicrosoftDocs/OfficeDocs-DeployOffice#397]
"After the installation is complete, don't open any Office programs. If you open an Office program, you are prompted to sign-in and activate. Even if you don't sign in and you close the Activate Office dialog box, a temporary product key is installed"

Does this include Teams? I install Office 365 in Audit Mode. I then install other applications for which I need to restart the computer. When I do, Teams open automatically and asks to sign in. Does that count as part of the above warning?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a003f6a-2edb-3303-01c1-41a63ce82260
* Version Independent ID: 203d6b80-acd5-566a-3f6c-be1852ae8909
* Content: [Deploy Office 365 ProPlus as part of an operating system image](https://docs.microsoft.com/en-us/deployoffice/deploy-office-365-proplus-as-part-of-an-operating-system-image#feedback)
* Content Source: [DeployOffice/deploy-office-365-proplus-as-part-of-an-operating-system-image.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-office-365-proplus-as-part-of-an-operating-system-image.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
No, it doesn't. Teams has its own activation mechanism and does not cause an Office activation. Hope this answers your questions.
