### ISSUE TITLE
Possible values: NoDiagnosticData

### ISSUE THREAD

**Issue by afield1235** [MicrosoftDocs/OfficeDocs-DeployOffice#401]
Hello,
Why is diagnostic data mandatory? There needs to be a complete opt out option. There is no reason for mandatory collection in 2019. Please change this right away. We are already going to start looking into ways to programmatically blacklist any of this traffic. It's none of your business.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea7bb8bf-5d11-87cb-a880-2edc355dca56
* Version Independent ID: fa4bfa40-42bf-bf0d-413d-d67e8ae826b9
* Content: [Set a preference for diagnostic data in Office for Mac](https://docs.microsoft.com/en-us/deployoffice/mac/set-preference-diagnostic-data)
* Content Source: [DeployOffice/mac/set-preference-diagnostic-data.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/mac/set-preference-diagnostic-data.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @pbowden-msft
* Microsoft Alias: **danbrown**

**Comment by afield1235** [comment]
Update on this please.

**Comment by RAJU2529** [comment]
Purpose of collecting diagnostic data for fixing issues and adding improvements in the next monthly updates, that's why data is collected.
But we can prevent by using GPO and by the registry keys.
