### ISSUE TITLE
Nice page but where can opt out of your data collection process? I don't want MS to have access to any of my data please.

### ISSUE THREAD

**Issue by Indigosometimes** [MicrosoftDocs/OfficeDocs-DeployOffice#402]
Make it easy to opt out of your data collection please.  If diagnostics are necessary then make it on a case by case basis and only for the incident. Otherwise please stay out and collect nothing.  I'm sure ALL users want that and resent further intrusions into their privacy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 144e9c53-1af0-12f0-c083-7775acdc791e
* Version Independent ID: 147f8437-1e9b-1f17-6a20-43904596003b
* Content: [Essential services for Office](https://docs.microsoft.com/en-us/deployoffice/privacy/essential-services#feedback)
* Content Source: [DeployOffice/privacy/essential-services.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/essential-services.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by theMonkeyFactory** [comment]
I agree!! The pop-up started on my computer yesterday. As far as I can tell this is in reference to 'Office 365'. I specifically have Mac Office 2011 to avoid these intrusions, and do not have an auto update turned on. My data is mine and I do not appreciate the threat from MS, especially as it is obvious in today's world that no one can promise to protect the data once they have it. How do I get the pop-up to stop, and keep my computer and data protected?

**Comment by jimbathgate** [comment]
I have the same issue.  I am NOT a professional and have no idea what these 10 pages of gobbly gook are and why I should be bothered about them.  I have a 2011 version of Office that works fine for my needs.  Where is the unsubscribe button for this?  I can't even find the "quit" button on the application that opened on startup.  This seems to be an intrusion on my right to be left alone.

**Comment by theMonkeyFactory** [comment]
Just got off phone with Apple. I also couldn’t quit the MicrosoftOffice Update App that appeared with the pop-up yesterday. Then today, it started preventing my computer from shutting down because I hadn’t accepted the pop-up. I also use 2011 for the purpose of avoiding this kind of….

Apple had me force quit it. Click on the App, then Command/Option/Esc, then choice to force quit the App. It shut down my whole computer in the process, but seemed to work. The App came back up, but I was able to quit it.

**Comment by theMonkeyFactory** [comment]
I take that back. It has just chosen to pop back up on its own. Any help would be graciously appreciated! It’s like a virus.

**Comment by AeroBB** [comment]
Couple of further related items for consideration - It is not clear from this page that the "encrypted" user name collected is anonymous and there is other information that would narrow any identification triangulation which falls into this worrying category.  Also it is not clear where to find the instructions on how to run the Diagnostic Data Viewer on MacOS/IOS.  The requirement to improve/support Office is not in dispute here, however the avoidance of data misappropriation is both essential and paramount.

**Comment by theMonkeyFactory** [comment]
Agreed.
:-)

**Comment by GiantCrocodile** [comment]
Any news on this? This information is very much needed.

**Comment by GiantCrocodile** [comment]
@DHB-MSFT Hi! Can we have an update on this?
