### ISSUE TITLE
misdirected to this page from autoupdate notice

### ISSUE THREAD

**Issue by spiritcapsule** [MicrosoftDocs/OfficeDocs-DeployOffice#403]
On my Mac, where I have Office 365 installed, Microsoft Autoupdate displayed a Required Data Notice showing an incomplete sentence with a Learn More link. I clicked Learn more to continue reading the Required Data Notice and I was taken to this page which at the top explicitly states that it applies to "Office client software installed on a computer running Windows". I'm not on a computer running Windows so I should not have been taken to this page. Where do I read the required data notice for Mac users???

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 144e9c53-1af0-12f0-c083-7775acdc791e
* Version Independent ID: 147f8437-1e9b-1f17-6a20-43904596003b
* Content: [Essential services for Office](https://docs.microsoft.com/en-us/deployoffice/privacy/essential-services)
* Content Source: [DeployOffice/privacy/essential-services.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/essential-services.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by umgpg** [comment]
Same here. Also instructions to disable or opt out are needed.

**Comment by e40** [comment]
It feels to me like you send us to this page so that we can't find the needle in the haystack we are looking for (you tricking us into agreeing to privacy violations).

SHAME ON YOU, Microsoft.

**Comment by jwhit-MSFT** [comment]
The Learn More link should now go to the correct article. Please let us know if that's not the case. Thanks!

**Comment by gorticus** [comment]
What is the _correct article_?  Jibber-jabber about `Essential Services` as a way to obfuscate opt-out instructions, or _actual opt-out instructions_?  I'd prefer straight forward opt-out instructions.

**Comment by spiritcapsule** [comment]
@gorticus agreed. in @jwhit-MSFT  's comment above, it says let them know if the Learn More link does not now go to the correct article. Problem is, I have no way to get the notice with the Learn More link back to check it. I never did find the correct article.

**Comment by DHB-MSFT** [comment]
Thanks for letting us know. We'll look into this.
