### ISSUE TITLE
semi-annual channel doesn't contains teams 

### ISSUE THREAD

**Issue by cheddarq** [MicrosoftDocs/OfficeDocs-DeployOffice#405]
There is something wrong with the date when Teams starts being installed with new installations of Office 365 ProPlus 

Semi-Annual Channel Version 1902 | July 9, 2019 doesn't contain teams, customer download this but it still doesn't contain Teams, please help to fix this, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7936ca5e-c658-4956-b174-99eaf1eb67d4
* Version Independent ID: 9ecc0b61-a941-f5e1-96c3-d32fae59eacd
* Content: [Deploy Microsoft Teams with Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/teams-install)
* Content Source: [DeployOffice/teams-install.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/teams-install.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by JohnGGeo** [comment]
Apparently this blog post https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/What-s-New-in-Microsoft-Teams-June-2019/ba-p/730501 is correct and the doc is wrong. I've opened another Issue regarding this to correct the doc.

**Comment by DHB-MSFT** [comment]
@cheddarq, @JohnGGeo -- I just did a new install of the most current version of Semi-Annual Channel (Version 1902, Build 11328.20368) and it does contain Teams. After the Office installation is complete, you should see an entry for Teams Machine-Wide Installer in Add/Remove Programs in Control Panel. But Teams doesn't actually install for the user until the user signs out and signs back in.  Hope that helps.
