### ISSUE TITLE
Is it possible to deploy MS Office 365 64 bits together with Teams 32 bits?

### ISSUE THREAD

**Issue by honleung** [MicrosoftDocs/OfficeDocs-DeployOffice#406]
Is it possible to deploy MS Office 365 64 bits together with Teams 32 bits?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7936ca5e-c658-4956-b174-99eaf1eb67d4
* Version Independent ID: 9ecc0b61-a941-f5e1-96c3-d32fae59eacd
* Content: [Deploy Microsoft Teams with Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/teams-install#feedback)
* Content Source: [DeployOffice/teams-install.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/teams-install.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by honleung** [comment]
Or can we install the the Teams machine wide installer 32 bits separately?
If yes, where can we get the installer?

**Comment by baardhermansen** [comment]
Yes to all of your questions. See statements on the current page:  https://docs.microsoft.com/en-us/deployoffice/teams-install#additional-information-about-installing-microsoft-teams.

@officedocsbot close
