### ISSUE TITLE
Office 2016 missing from the products list

### ISSUE THREAD

**Issue by GeoSimos** [MicrosoftDocs/OfficeDocs-DeployOffice#409]
Hello,

I would like to ask why the Office 2016 products are missing from the config tool's products list.
Is there a workaround for us wanting to create configuration files for Office 2016 or we can proceed with 2019 and change the version references in the produced xml config files?

Thank you,

**Comment by DHB-MSFT** [comment]
@GeoSimos  -- Are you trying to install volume licensed versions of Office 2016?  For example, Office Professional Plus 2016.  If so, those versions of Office use Windows Installer (MSI) as the installation technology.  The Office Customization Tool online at https://config.office.com is only used to create configuration files for versions of Office that use Click-to-Run as the installation technology. For example, Office 365 ProPlus or Office Professional Plus 2019.  Hope that helps.
