### ISSUE TITLE
Will the auto-start GPO work on version Office 2016 16.0.4849.100 

### ISSUE THREAD

**Issue by grkoop** [MicrosoftDocs/OfficeDocs-DeployOffice#416]
My customer is eager to use the Auto-start group policy.  Does it work if their Office version is 16.0.4849.100

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7936ca5e-c658-4956-b174-99eaf1eb67d4
* Version Independent ID: 9ecc0b61-a941-f5e1-96c3-d32fae59eacd
* Content: [Deploy Microsoft Teams with Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/teams-install#feedback)
* Content Source: [DeployOffice/teams-install.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/teams-install.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@grkoop -- Thanks for your question. We're checking with the Teams product team. We'll get back to you when we get an answer from them.

**Comment by grkoop** [comment]
Any word on this??

Thank you.

Kind regards,

Gregg Koop
Senior Technical Account Manager, MBA, PMP
Microsoft US Public Sector Services – State/Local Government
gregg.koop@microsoft.com<mailto:gregg.koop@microsoft.com>
cell: (908) 391-5656

Microsoft Support Hotline       1-800-936-3100
Cybersecurity Incident Support: Microsoft Premier Incident Response<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdownload.microsoft.com%2Fdownload%2F5%2F1%2F6%2F516F59A7-91EE-4463-8612-C85FD3BEBDC7%2Fmicrosoft-incident-response-and-recovery-process-brief.pdf&data=02%7C01%7CGregg.Koop%40microsoft.com%7C8276db865a2c49ca6dfc08d6e56d699c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636948655414461448&sdata=ZMNOwvnJB%2BV1WTWdPj7Z479Ynhoo0iaz3RSkx0G2UGk%3D&reserved=0>

**Comment by DHB-MSFT** [comment]
@grkoop -- Didn't get a response, so have resent them the question.

**Comment by DHB-MSFT** [comment]
Following up offline. Depending on what we hear from the PM, we'll update the article accordingly.
