### ISSUE TITLE
Teams deployment schedule doesn't take into account telemetry.

### ISSUE THREAD

**Issue by JohnGGeo** [MicrosoftDocs/OfficeDocs-DeployOffice#417]
https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/What-s-New-in-Microsoft-Teams-June-2019/ba-p/730501
This blog post is apparently superseding this doc. I opened a ticket w/ Microsoft and they pointed to the blog post, saying this is why this doc is wrong please update this doc to match what the blog post is showing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7936ca5e-c658-4956-b174-99eaf1eb67d4
* Version Independent ID: 9ecc0b61-a941-f5e1-96c3-d32fae59eacd
* Content: [Deploy Microsoft Teams with Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/teams-install)
* Content Source: [DeployOffice/teams-install.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/teams-install.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@JohnGGeo  -- can you clarify what you mean by "doesn't take into account telemetry" and precisely which part of the article is in contradiction with the blog post?  Thanks.

**Comment by JohnGGeo** [comment]
Apparently Office Updates are only targeting a subset of installs to include teams in the update. Fresh installs do include teams however not all updates so this doc states

Monthly Channel | Version 1902 | March 4, 2019
-- | -- | --

Also see MS Ticket #15543168
Thanks,


Monthly Channel | Version 1902 | March 4, 2019
-- | -- | --

**Comment by DHB-MSFT** [comment]
@JohnGGeo  -- yes, that is correct. Teams being added to existing installs is being rolled out over several weeks.  That's why we included this sentence in the article:

*This will be a gradual rollout over several weeks, so not all existing installations will immediately get Teams added when Office is updated.*

**Comment by JohnGGeo** [comment]
For example, if you're using Version 1904 in Monthly Channel and you update to Version 1906, Teams will be installed on the device as part of the update to Version 1906.

That example is misleading then. Sorry I'm not trying to be difficult it is just difficult to understand as that sentence says next few weeks but then the example and table below that say 1906 it'll be there so some clarification perhaps or if it will be there in all 1906 builds then it should be there in all those builds and that's not the behavior I'm seeing.

**Comment by DHB-MSFT** [comment]
@JohnGGeo -- thanks for the feedback. We'll see if we can re-word to make it clearer.

**Comment by DHB-MSFT** [comment]
@JohnGGeo  -- we've made some changes to the wording of the "existing installations" section that hopefully better explain the scenario (while trying to avoid many of the grisly details). 

Also, starting with Version 1908 (Build 11929.20300), which is being released today in Monthly Channel and Semi-Annual Channel (Targeted), the behavior of adding Teams to existing installs should be more predictable.  

Thanks again for providing feedback to help improve our documentation.

**Comment by JohnGGeo** [comment]
Thank you! That does look more clear.
