### ISSUE TITLE
list of registry keys to clear the experimentation cache is incomplete

### ISSUE THREAD

**Issue by SilviuTanasescu** [MicrosoftDocs/OfficeDocs-DeployOffice#419]
following a customer request, we have tested and noticed that in order to clear the experimentation cache - to disable experimentation - we need to remove the following registry keys :

(as stated in the article) 
HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common\Experiment
HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common\ExperimentEcs
HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common\ExperimentTas

but also:
HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common\ExperimentConfigs

Please add it to the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6ef3e29-a629-703b-f84e-b8e8645b1297
* Version Independent ID: 797ccf0a-655d-24bc-b77c-ce05157a7e29
* Content: [Guidance for deploying Office 365 ProPlus in a GCC High or DoD environment](https://docs.microsoft.com/en-us/deployoffice/deploy-office-365-proplus-in-gcc-high-dod#feedback)
* Content Source: [DeployOffice/deploy-office-365-proplus-in-gcc-high-dod.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-office-365-proplus-in-gcc-high-dod.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by rpodric** [comment]
This never actually made it in.
