### ISSUE TITLE
Reduced functionality mode and licences

### ISSUE THREAD

**Issue by quarkyuk** [MicrosoftDocs/OfficeDocs-DeployOffice#42]
Please can it be updated with clarification on whether an install in reduced funtionality mode still requires a licence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3c236da-c63a-f789-f1b6-7aeb41f16c1f
* Version Independent ID: 35319bac-d94f-832c-ce79-41bffe5c8d25
* Content: [Overview of licensing and activation in Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/overview-of-licensing-and-activation-in-office-365-proplus)
* Content Source: [DeployOffice/overview-of-licensing-and-activation-in-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-licensing-and-activation-in-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* Product: **unspecified**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
I think that might already be covered in the article by this information: "You can remove a user's license (for example, if the user leaves your organization). After you do this, any installations of Office 365 ProPlus that the user had go into reduced functionality mode."

**Comment by quarkyuk** [comment]
Thanks. I am not sure if that quite covers it, because I can hear in my
head, licence specialists saying "That only covers removal of a licence,
not installing before a licence is assigned." It seems like the unactivated
mode works similar to the old "viewer" applications, so shouldn't need a
licence. If unactivated Office requires a licence though, it would be good
to know vendors like Dell and Lenovo provide it on an OEM build. Specific
confirmation one way or the other would be really useful on a Microsoft web
page.

**Comment by DHB-MSFT** [comment]
I got confirmation that a license isn't required for reduced functionality mode. But, the user will get prompted to sign in/activate every time they open an Office app, such as Word or Excel.  I'll add something along those lines to the reduced functionality mode section in the article. Thanks for your comment/feedback/suggestion.

**Comment by quarkyuk** [comment]
Thanks, that will be really appreciated!

**Comment by DHB-MSFT** [comment]
I added some info about the "no license" scenario to the reduced functionality mode section. I hope that is enough clarification. Thanks again for your feedback.
