### ISSUE TITLE
Microsoft 365 Business on RDS

### ISSUE THREAD

**Issue by nathantemples** [MicrosoftDocs/OfficeDocs-DeployOffice#420]
With the release of Shared Activation for Microsoft 365 Business can we load 365 Business Office on an RDS server?  This is NOT clear in the article.

**Comment by manoth-msft** [comment]
I've submitted PR #811 to clarify the conditions under which Microsoft 365 Apps for Business can be used on RDS (when the plan Microsoft 365 Business is used). Thanks!
