### ISSUE TITLE
[LOC] Typo in an article

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-DeployOffice#423]
**FileName:** overview-privacy-controls.md
**URL:** https://docs.microsoft.com/en-us/deployoffice/privacy/overview-privacy-controls
**Author:** danbrown

Could you please check: 
"_To see what diagnostic data is being sent to Microsoft, you can use the Diagnostic Data Viewer, which you can download and install for free from the Microsoft Store. 7 For more information, see the following:_" paragraph?
It seems there is an extra number "7" 

![image](https://user-images.githubusercontent.com/47977325/62866623-8978cd80-bd11-11e9-9b08-db8735f2f3bb.png)

**Comment by jwhit-MSFT** [comment]
Thanks for catching that--I just fixed it. Should be live soon.
