### ISSUE TITLE
"The major version of Office 2019 is staying at 16.0"? please explain the reasoning behind this.

### ISSUE THREAD

**Issue by uranthos** [MicrosoftDocs/OfficeDocs-DeployOffice#424]
As a developer who interops with office, I have already come across some issues between office 2019 and 2016 where the execution path needs to be different. How am I to tell now which office version I am interacting with since they have the same version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da0ced28-ffb1-1924-6fc7-24265bc95c42
* Version Independent ID: b261a792-c076-2221-65f0-1d2ac52fef7a
* Content: [Overview of Office 2019 (for IT Pros)](https://docs.microsoft.com/en-us/deployoffice/office2019/overview#feedback)
* Content Source: [DeployOffice/office2019/overview.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/overview.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by stdin82** [comment]
The sole way to differentiate Office 2019 and 2016 is through registry value ProductReleaseIds  
`[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration]`

if it contain the word **2019** then it's Office 2019, otherwise Office 2016 (or Office 365)

**Comment by RAJU2529** [comment]
I also have same question as like  @uranthos.
 for office 2013, it's called 15.0
for office 2016 it's called 16.0
for office 2019 it's called ??

**Comment by manoth-msft** [comment]
You can also parse the HKLM\SW\MSFT\Windows\CurrentVersion\Uninstall keys for the Office 2016 and Office 2019 strings.

@DHB-MSFT Not related to documentation, question answered. Please close

**Comment by RAJU2529** [comment]
@manoth-msft . Please answer, why microsoft still keeping 16.0 version for office 2019 ,is there any special reason behind this . I can't exact answer other than from Microsoft office software team. 
Before closing this PR,  I need answer

**Comment by manoth-msft** [comment]
The major version is the same, because Office 2016, 2019 as well as the Microsoft 365 apps all are based on the same code base regarding APIs and the object model. A major version change indicates a major change of such APIs and the object model.

**Comment by RAJU2529** [comment]
> The major version is the same, because Office 2016, 2019 as well as the Microsoft 365 apps all are based on the same code base regarding APIs and the object model. A major version change indicates a major change of such APIs and the object model.

@manoth-msft . Thanks, sir. I am happy now
