### ISSUE TITLE
Remove ALL = true

### ISSUE THREAD

**Issue by dropri** [MicrosoftDocs/OfficeDocs-DeployOffice#426]
When you use "Remove ALL = true", this removes ALL the Office 365 products... not just all Office 365 Pro Plus products....
I think it's a bit confusing, because OPP doesn't include Visio and Project, while this attribute DOES remove these apps as well. Maybe it's worth clarifying.

**Comment by jwhit-MSFT** [comment]
That's a good fix--thanks for recommending it. If you want, you can propose the update directly as a pull request--that gets you listed (accurately!) as a contributor for the content. To edit the article, make sure you're signed into GitHub and click "Edit" on the top righthand side of the article.

**Comment by jwhit-MSFT** [comment]
Hi dropri--Thanks for the pull request. I commented on it separately, but wanted to call out here that we need it resubmitted to make the update.

**Comment by dropri** [comment]
@jwhit-MSFT - Thanks, I raised another pull request, but I don't think it's the right way again... for some reason I cannot open pull requests any other way...
In any case, I don't care to be mentioned in the article, as long as it's clear for others - if you can do it, I don't mind.

https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/pull/436

![image](https://user-images.githubusercontent.com/38348029/63451666-a497bb80-c43c-11e9-999d-45c146464a25.png)

**Comment by jwhit-MSFT** [comment]
Updated the configuration options article with this detail. Thanks again for the suggestion.
