### ISSUE TITLE
Apply updates automatically from an on-premises location

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/OfficeDocs-DeployOffice#428]
Any chance of fleshing out the "Apply updates automatically from an on-premises location to Office 365 ProPlus" section with some more details?  What does the Structure need to look like?  Can I have 32 and 64bit O365 updating from the same share? If so what do the sub-folders need to look like?  If I deploy different apps selections of office ( i.e. Word, ppt, excl only and a Word,ppt,excl,outlook,access,visio to some others) do I just run a /download with the one that has the most apps?

and what's the suggested way of keeping this up-to-date automatically?  Seems like such a backwards step vs just putting them into WSUS as a category & allowing WindowsUpdates todo its thing...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d68af5b0-45f7-53db-8cee-f03a9ce8bd9b
* Version Independent ID: f94fd8f0-6a0f-7eda-f87d-ad904a9e62f7
* Content: [Choose how to manage updates to Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/choose-how-to-manage-updates-to-office-365-proplus)
* Content Source: [DeployOffice/choose-how-to-manage-updates-to-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/choose-how-to-manage-updates-to-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by jwhit-MSFT** [comment]
Thanks for the feedback, mattsmacblog--it's a good request and it's helpful to see the specific details that you need. In our [planning article](https://docs.microsoft.com/en-us/deployoffice/plan-office-365-proplus#step-2---choose-how-to-manage-updates), we recommend either doing automatic updates from the Office CDN or, if managing updates more directly, using Configuration Manager. I'm assuming that you want to manage updates from a local source without Configuration Manager. Right now, we have a [deploy from a local source article](https://docs.microsoft.com/en-us/deployoffice/deploy-office-365-proplus-from-a-local-source). I'll add manage updates from a local source to our backlog--we'll monitor customer need to see if we can invest in it.
