### ISSUE TITLE
Semi-Annual Channel Delayed Feature Updates

### ISSUE THREAD

**Issue by dreblen** [MicrosoftDocs/OfficeDocs-DeployOffice#43]
This page gives hints that it's possible to skip a feature update within the semi-annual channel because of the overlapping support windows ("customers who want to update once a year will be able to do so"), but no indication is given for how to accomplish this. From looking into this, it seems that the only way to do this is to specify build numbers manually as indicated in this document: https://docs.microsoft.com/en-us/deployoffice/delay-receiving-feature-updates-from-deferred-channel-for-office-365-proplus
It would be good to include a reference to this documentation so the intended implementation isn't ambiguous.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd18fe4f-5a0e-22cd-61b8-242419c6b18a
* Version Independent ID: d6f7ce9e-09f8-87fb-f05e-07e1a8d0ee01
* Content: [Overview of update channels for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/overview-of-update-channels-for-office-365-proplus#visual-representation-of-the-update-channels-for-office-365-proplus)
* Content Source: [DeployOffice/overview-of-update-channels-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-update-channels-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* Product: **unspecified**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Thanks for your feedback/suggestion. I've added a bullet point about this in the "Additional information" section at the end of the article.

**Comment by dreblen** [comment]
Thank you. The new bullet point is very helpful.
