### ISSUE TITLE
Got it to work, but had to overcome discrepancies

### ISSUE THREAD

**Issue by ty-appstocloud** [MicrosoftDocs/OfficeDocs-DeployOffice#432]
In our Windows 10 Azure-based client, the following steps made the shared license and roaming work using Group Policy and/or registry edits.  There are disconnects between this page's details, the ADMX files for Office 16, and what the programs are actually doing.  First, I tried using the registry instructions above, and they did not work. Then, I added the ADMX/ADML files to c:\Windows\PolicyDefinitions and used Group Policy to add entries. 

I used procmon to show what registry keys were being queried.  I used Excel and later Word and traced what the programs were doing.

ClickToRun registry location:
The doc says to go to 
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration 
But the key that Procmon showed being queried was
HKLM\SOFTWARE\Microsoft\Office\ClickToRun\REGISTRY\MACHINE\Software\Microsoft\Office\16.0\Common\Licensing
I did not attempt to go further with direct adds of registry entries, as I wanted the eventual solution to use Group Policy.

Next, I used Group Policy on the local machine to enable 
"Use shared computer activation" and
"Specify the location to save the licensing token used by shared computer activation" - for this one, it lets you set a folder location.  For the Folder location I used %appdata%\Microsoft\Office\16.0\Licensing, which puts the two license files on the roaming profile.  In our Citrix setup, Citrix puts the roaming profile on a shared drive, so the user will get the same profile from any desktop.  Note: I used the same directory structure that the default setup uses, just to keep with the convention.  I found that the directory has to already exist, or else Excel would go back to the default of  %localappdata%\Microsoft\Office\16.0\Licensing

Those settings in group policy resulted in the following registry entries under HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\office\16.0\common\licensing:
sclcacheoverride   DWORD value 1
sclcacheoverridedirectory   REG_SZ value %appdata%\Microsoft\Office\16.0\Licensing
sharedcomputericensing   DWORD value 1

Shared Activation was working, but procmon showed that after reading sclcacheoverride, Excel never read sclcacheoverridedirectory, and therefore, it put the license files in the local profile.  I then manually deleted sclcacheoverride and added 
sclcacheoverride REG_SZ 1 (a string value instead of a DWORD value)

Now everything worked, and the license files were placed on the roaming profile.  It seems like the DWORD value would be the more correct way to implement the sclcacheoverride flag, and that the implementation of Office in checking that flag is mistaken to look for a string.  To override the ADMX behavior, we will need to use "AdditionalRegistryEntries" in our OU group policy to see if we can deploy that string value to all desktops.
Ty

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ab31873-7ad3-afde-3c72-8a7fb4f2e551
* Version Independent ID: 19f7f483-9f53-f577-1cd4-d360c0b234fc
* Content: [Overview of shared computer activation for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/overview-of-shared-computer-activation-for-office-365-proplus)
* Content Source: [DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by JamieWilsonCC** [comment]
With the latest ADMX sclcacheoverride is set as REG_SZ rather then DWORD. Version issue?
