### ISSUE TITLE
No internet access 

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/OfficeDocs-DeployOffice#433]
We noticed that when the client has no internet access and therefore can’t access the web service endpoints mentioned in the documentation, the scanner crashes. When running in command line mode without addin option , it works.

I suggest to highlight this in the documentation and ideally the team responsible for the development of the tool catches this issue and handles this without the tool crashing 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2843afe2-a11d-7d88-8b56-24f131782d01
* Version Independent ID: f8bc6a27-b9f5-a729-b5e3-fdd9ac6642ed
* Content: [Use the Readiness Toolkit to assess application compatibility for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro)
* Content Source: [DeployOffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@alexverboon -- thanks for mentioning this. We've forwarded this on to the engineering team responsible for the Readiness Toolkit. For future reference, if you encounter other issues with the Readiness Toolkit, you can email them directly at readyforoffice@microsoft.com (the email is listed in the article).  Once we hear back from them about this issue, we'll update the article accordingly. Thanks again for your feedback.
