### ISSUE TITLE
Seriously?

### ISSUE THREAD

**Issue by marktheiii** [MicrosoftDocs/OfficeDocs-DeployOffice#434]
Come on, Microsoft. This is silly at this point. If you don't want to support non-subscription products then get rid of them. If you're going to continue rolling them out, because you don't want to lose that clientele, then support them properly. Having a well-documented and built out workaround for existing products doesn't make any sense. If you understand the problem, why it occurs, and how to fix it then just put the fix into the production release. Quit making people jump through hoops because you don't want to support both platforms. 

It just looks like a big temper tantrum.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e6c0641-503d-7959-2afb-839821cc792f
* Version Independent ID: 046c52d9-4fbe-4fe7-0778-5c1d4138f69e
* Content: [Use the Office Deployment Tool to install volume licensed versions of Project 2016 and Visio 2016](https://docs.microsoft.com/en-us/DeployOffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016?redirectSourcePath=%252fen-us%252farticle%252f82691bd7-a3d5-47ca-8d8a-0ee43ec2c01f#feedback)
* Content Source: [DeployOffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by jwhit-MSFT** [comment]
Thanks for the feedback, marktheiii. I know your concern is broader than this, but I'll note that part of the complexity in this particular article is handling deploying volume-licensed products alongside subscription products. 

To share this feedback directly with the product team, you can add a comment to uservoice site: https://odinsiders.uservoice.com/

**Comment by marktheiii** [comment]
The complexity has been solved by a handful of lines in an xml file. This is something that a setup program can handle navigating, especially since that's exactly how the setup program currently operates. Not deploying this as a standard fix is a choice, not a necessity.
