### ISSUE TITLE
Topic is missing "Insiders" channel

### ISSUE THREAD

**Issue by rflaming** [MicrosoftDocs/OfficeDocs-DeployOffice#438]
From the site https://erwinbierens.com/switch-office-2016-to-monthly-targeted-channel/

Note - You can use this command to switch to any channel using the corresponding Channel keyword listed below: 

Channel  Keyword in CMD or ODT  
  Monthly Channel (Targeted)    Channel=”Insiders“ or Channel=”FirstReleaseCurrent“  
  Monthly Channel    Channel=”Monthly” or Channel=”Current“  
  Semi-annual Channel (Targeted)    Channel=”Targeted” or Channel=”FirstReleaseDeferred“  
  Semi-annual Channel    Channel=”Broad” or Channel=”Deferred“

**Comment by RAJU2529** [comment]
@rflaming. Sir if possible mention the Microsoft docs website, from where you foundout the issue.

**Comment by rflaming** [comment]
@Raju2529

I read your request as: please add a reference to the Office365 topic on doc.microsoft.com to which this issue is associated.

Assuming I've interpreted your request as you intended, below are the English - United States (aka en-us) title and link

Title: "How to switch from Semi-Annual Channel to Monthly Channel for the Office 365 suite"
Link: https://docs.microsoft.com/en-us/office365/troubleshoot/administration/switch-channel-for-office-365
