### ISSUE TITLE
Adding to an existing O365 installation

### ISSUE THREAD

**Issue by AquinoN** [MicrosoftDocs/OfficeDocs-DeployOffice#439]
There is no information on this page regarding how to deploy Visio as an addition to an already installed instance of O365.  With as many issues as the community has with this, it would be nice to see some clear guidance on how to properly add/remove visio/project to/from an existing installation.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3fc30fd-858c-d1cd-0729-6eb72ef7975a
* Version Independent ID: aa690d1d-8e25-6de1-9a83-7acd851fed7a
* Content: [Deployment guide for Visio](https://docs.microsoft.com/en-us/deployoffice/deployment-guide-for-visio#feedback)
* Content Source: [DeployOffice/deployment-guide-for-visio.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deployment-guide-for-visio.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by TiloGit** [comment]
this table answered some of my questions: 

https://docs.microsoft.com/en-us/deployoffice/install-different-office-visio-and-project-versions-on-the-same-computer?toc=/deployoffice/office2019/toc.json

but lots of open tickets on this one.

**Comment by manoth-msft** [comment]
Submitted PR to help clarify.
