### ISSUE TITLE
AUTOACTIVATE Property

### ISSUE THREAD

**Issue by NeverEnoughCoffeeMan** [MicrosoftDocs/OfficeDocs-DeployOffice#440]
Just a quick observation. If you use the Office Customization Tool (config.office.com), your collection of deployment settings might contain this Property element:

&lt;Property Name="AUTOACTIVATE" Value="FALSE" /&gt;

Yet the documentation states the allowed values for the optional AUTOACTIVATE property are "0" and "1". Are these values (FALSE and 0; TRUE and 1) interchangeable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a0b1ff-0498-505a-6024-b813980d310f
* Version Independent ID: b8057930-b4bd-1304-17ce-5561f837e901
* Content: [Configuration options for the Office Deployment Tool](https://docs.microsoft.com/en-us/DeployOffice/configuration-options-for-the-office-2016-deployment-tool#feedback)
* Content Source: [DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by DHB-MSFT** [comment]
@NeverEnoughCoffeeMan -- thanks for bringing this to our attention. We'll double-check with the engineering/product team and get back to you.

**Comment by DHB-MSFT** [comment]
@NeverEnoughCoffeeMan -- according to the PM for the Office Customization Tool, this is a bug in the tool.  The documentation (0, 1) is correct. They have filed a bug to get this fixed in the OCT. Thanks again for bringing this to our attention.

**Comment by chhopkin** [comment]
Thank you for reporting this.  The bug has been resolved and the fix is now in production.
