### ISSUE TITLE
Office preferences .plist

### ISSUE THREAD

**Issue by csiket18** [MicrosoftDocs/OfficeDocs-DeployOffice#443]
Hello,

First I want to apologize if this isn't the right place to ask this question and if you wouldn't mind pointing me in the right direction if that is that case.

So to give you a little background I am a systems administrator at a medium-firm, and we are a Mac shop. I am trying to deploy custom preferences to all out users that use Office 365. Here you give one example of a preference we can use to "manually check" for updates. https://docs.microsoft.com/en-us/deployoffice/mac/deploy-preferences-for-office-for-mac

I was wondering if there were a "defaults write" command that would allow me to toggle this particular setting in Word and Excel. Something like this below:
`defaults write ~/Library/Group\ Containers/UBF8T346G9.Office/com.microsoft.officeprefs.plist DefaultAutoSave -bool True`

![Screen Shot 2019-09-05 at 7 34 19 PM](https://user-images.githubusercontent.com/29467566/64443094-350e0700-d09f-11e9-994c-b65951e089ae.png)
This is the setting I would like to change

**Comment by pbowden-msft** [comment]
@csiket18 thanks for your message. Unfortunately, there is no 'defaults write' based preference for this one, as the data is stored in a SQLite database rather than a regular plist. Are you looking for a way to disable AutoSave? Just wondering what the use case is.

**Comment by csiket18** [comment]
Well, we actually do not use OneDrive or any Cloud (3rd party) system. We are maintaining an on-site File system and I would like to default certain settings for our users. Seeing as AutoSave will not work for anything besides OneDrive. I would like to avoid our users saving anything to their OneDrive

**Comment by csiket18** [comment]
If I may ask how would me as an administrator distribute company-wide settings?

**Comment by pbowden-msft** [comment]
@csiket18 ahh, I see. If you're deploying Office 2019 Volume License, you may want to look into the 'SignInOptions' key which will prevent users logging on to OneDrive/OneDrive for Business. More info at https://macadmins.software (Preferences tab).
For mass distribution of preferences, MDM is your best approach. In the enterprise space, tools such as Jamf Pro are popular.
