### ISSUE TITLE
Emailed ReadyForOffice@microsoft.com, undeliverable

### ISSUE THREAD

**Issue by carlneustaedter** [MicrosoftDocs/OfficeDocs-DeployOffice#444]
Sending an email to ReadyForOffice@microsoft.com generates the following bounce message:
 
Your message to omexconeint@microsoft.com couldn't be delivered.

The group omexconeint only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2843afe2-a11d-7d88-8b56-24f131782d01
* Version Independent ID: f8bc6a27-b9f5-a729-b5e3-fdd9ac6642ed
* Content: [Use the Readiness Toolkit to assess application compatibility for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro#feedback)
* Content Source: [DeployOffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@carlneustaedter -- The owners of that email address have implemented a fix, but it might take 24 hours to be updated in the system. Thanks again for bringing this problem to our attention.

**Comment by DHB-MSFT** [comment]
@carlneustaedter -- we were able to send an email to that address today without receiving the delivery error, so looks like the problem has been fixed.
