### ISSUE TITLE
Wrong download - I get Office 365 not Office 2019 Standard

### ISSUE THREAD

**Issue by ccpvwtech** [MicrosoftDocs/OfficeDocs-DeployOffice#446]
I went through the steps to get Office 2019 Standard - but Office 365 was installed with a link to the service Volume Licensing. I tried again with a customer service rep and got the same results. I don't seem to be able to download Office 2019. What happens if you get Office 365 instead of Office 2019 - can you make it work and give it a MAK key?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [Deploy Office 2019 (for IT Pros)](https://docs.microsoft.com/en-us/DeployOffice/office2019/deploy#feedback)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@ccpvwtech -- We just did a test and were able to download and install Office Standard 2019 using the Office Deployment Tool with this simple configuration.xml file

```
<Configuration>
  <Add OfficeClientEdition="64" Channel="PerpetualVL2019">
    <Product ID="Standard2019Volume">
      <Language ID="en-us" />
    </Product>
  </Add>
</Configuration>
```

What are you using for Channel and Product ID in your configuration.xml file?

**Comment by ccpvwtech** [comment]
I had the same file - does your file say Office 365 when you open it - is
there a place to put in the MAK key - is your domain verified - or do you
use domain.onmicrosoft.com

**Comment by ccpvwtech** [comment]
I had both channel and product ID right but when I went to do an analysis
it said Retail not Volume Licensing on the install- used Volume Activation
Manager version 2 which did not let me add a key - in any case it looks for
KMS not MAK keys - so there were no keys in the system as I am doing this
on a single laptop.

**Comment by ccpvwtech** [comment]
All fixed turned out there was a key for Office 365 which had been uninstalled on my machine – but the key was obscuring the Office 2019 key – once it was removed all was well. It took hours of MS Support and my time to try to fix.  Very annoying as I had successfully used a script like yours some time ago on another computer.

**Comment by DHB-MSFT** [comment]
@ccpvwtech -- Glad to hear the problem got resolved, but sorry to hear it took so much time to figure out. For future reference, the Microsoft Support and Recovery Assistant can help with some Office installation and activation issues. For more info,  see [About the Microsoft Support and Recovery Assistant](https://support.office.com/article/e90bb691-c2a7-4697-a94f-88836856c72f).

**Comment by ccpvwtech** [comment]
Thanks for your email – believe me I did run the MS SARA before calling support – a last resort!
