### ISSUE TITLE
No timestamp when signing XLA?

### ISSUE THREAD

**Issue by davidm-mdxt** [MicrosoftDocs/OfficeDocs-DeployOffice#45]
Despite editing group policy (Security-&gt;Digital Signatures) timestamp server name, timestamp server timeout, minimum XAdES-T, and request XAdES-T, I STILL can't get Excel 2016 to sign my XLA with a timestamp. :-(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 242a3c84-8a8e-a71b-f225-534303a007bb
* Version Independent ID: 9ff203bb-d7da-40fb-2fec-f99f79c17c43
* Content: [Use digital signatures with Office 2016](https://docs.microsoft.com/en-us/deployoffice/security/use-digital-signatures-with-office#configsigs)
* Content Source: [DeployOffice/security/use-digital-signatures-with-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/use-digital-signatures-with-office.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
You might want to consider posting on https://answers.microsoft.com or https://techcommunity.microsoft.com. Someone there might be able to help you troubleshoot your problem. If that doesn’t help, you might need to consider contacting Microsoft Support at https://support.microsoft.com/en-us/contactus/.
