### ISSUE TITLE
When it's updated to a new semi-annual feature release

### ISSUE THREAD

**Issue by Justin-Shi** [MicrosoftDocs/OfficeDocs-DeployOffice#451]
From the document, I don't see that when the current release will be updated to a new semi-annual feature release.
For example, I'm in Semi-Annual channel. I have 1808 installed on my machine but & it's still in support duration. Now a new version 1902 is available for Semi-Annual channel. When the release dates is coming in January and July, my Office will be updated to 1902(latest build) even the 1808 is in it's duration? 
If so, is there any way to prevent this happen until 1808 is close it's end of supporting?

**Comment by DHB-MSFT** [comment]
@Justin-Shi   Depends on how you are configured to get updates for Office. If you're configured to get updates automatically from the Office Content Delivery Network (CDN) on the internet, then each time there is a new feature release/version for Semi-Annual Channel (in January and July), you'll automatically get updated to that new version.  If you want to stay on the older (but still supported version, such as 1808), then you'll have to do some manual configuration. We mention this scenario in the 2nd to last bullet point in our [Overview of update channels](https://docs.microsoft.com/DeployOffice/overview-of-update-channels-for-office-365-proplus#additional-information-about-the-update-channels-for-office-365-proplus) article.

_We recommended that you use the most current version of Semi-Annual Channel. But, if you have a specific business need to delay receiving a feature update from Semi-Annual Channel in January or July, you can configure Office to not receive that feature update, but still receive the most current security updates for the previous version. For more information on how to do that, see [Delay receiving feature updates from Semi-Annual Channe](https://docs.microsoft.com/DeployOffice/delay-receiving-feature-updates-from-deferred-channel-for-office-365-proplus)). For information about which versions of Semi-Annual Channel are supported and until when, see [Release information for updates to Office 365 ProPlus](https://docs.microsoft.com/officeupdates/release-notes-office365-proplus)._

Hope that helps.

**Comment by Justin-Shi** [comment]
Cool, that's helpful. Thanks very much!
