### ISSUE TITLE
Inconsistent Naming of Restiry Setting and Confusing Descriptions

### ISSUE THREAD

**Issue by mitechzone** [MicrosoftDocs/OfficeDocs-DeployOffice#452]
The following registry keys have different suffixes "Disabled" vs "Enabled", yet same values.

The documentation is not clear what's the behavior of enabling each key. For example,

DisconnectedState   1=Enabled 2=Disabled

According to my testing, the documentation does not match the behavior. When it's set to 2 (Disable), it's supposed to "Disable" "DisconnectedState", i.e. in "Connected State". However, the value 2 disallows the use of connected experience. 

UserContentDisabled   1=Enabled 2=Disabled

In order to disable User Content, should this be 1 (Enabled) or 2 (Disabled)?

DownloadContentDisabled   1=Enabled 2=Disabled

In order to disable Download Content, should this  be 1 (Enabled) or 2 (Disabled)?

ControllerConnectedServicesEnabled   1=Enabled 2=Disabled

In order to disable Controller Connected Services, should this be 1 (Enabled) or 2 (Disabled)?

Would also recommend linking the phrases "connected experiences in Office" in the "Control privacy settings by editing the registry" table to [DeployOffice/privacy/connected-experiences.md]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef4debee-6a1e-53c7-7bec-2dbd208f4f2d
* Version Independent ID: b93ad6a2-0976-6f5f-7aae-1756079bdc1d
* Content: [Use policy settings to manage privacy controls for Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/privacy/manage-privacy-controls#feedback)
* Content Source: [DeployOffice/privacy/manage-privacy-controls.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/manage-privacy-controls.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@mitechzone  -- Yes, those registry setting names are somewhat confusing. Unfortunately when devs create the code they don't always synch up the registry setting name with the policy setting name.  Just ignore the actual name of the registry setting.....they could have just as easily been called SettingA, SettiingB, etc. It doesn't really matter. 

What's important is that if you want to, for example, turn off the use of "connected experiences in Office that download online content" you want to use the DownloadContentDisabled setting and you want to set it to "2" (which is the equivalent of choosing the "Disabled" radio button in the Group Policy Management tool, which is where admins usually set these settings.)  

A description of each of the policy settings is available earlier in the article, along with links to other relevant articles, such as a list of connected experiences. For example, [Policy setting for connected experiences that download online content](https://docs.microsoft.com/en-us/DeployOffice/privacy/manage-privacy-controls#policy-setting-for-connected-experiences-that-download-online-content) explains that policy setting and links off to an article which lists which connected experiences fall into that category. "Optional connected experiences" is covered earlier as well and also has a link to an article with more information about them, including examples -- [Overview of optional connected experiences in Office](https://docs.microsoft.com/en-us/DeployOffice/privacy/optional-connected-experiences).

Hope that helps.
