### ISSUE TITLE
Include instructions to run the tool

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/OfficeDocs-DeployOffice#453]
I always forget /download doesnt install anything.

You need to run /configure to do the install.

setup /download configuration-Office2019Enterprise.xml
setup /configure configuration-Office2019Enterprise.xml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a0b1ff-0498-505a-6024-b813980d310f
* Version Independent ID: b8057930-b4bd-1304-17ce-5561f837e901
* Content: [Configuration options for the Office Deployment Tool](https://docs.microsoft.com/en-us/DeployOffice/configuration-options-for-the-office-2016-deployment-tool?redirectSourcePath=%252fen-us%252farticle%252fd3879f0d-766c-469c-9440-0a9a2a905ca8#feedback)
* Content Source: [DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by jwhit-MSFT** [comment]
Thanks for the feedback, eschrader. We cover the use of the tool (including download and configure) in the [overview article](https://docs.microsoft.com/en-us/deployoffice/overview-of-the-office-2016-deployment-tool#get-started-with-the-office-deployment-tool). I'll see if we can make that link more prominent in the configuration options article.
