### ISSUE TITLE
6th license activation

### ISSUE THREAD

**Issue by SLeuthold** [MicrosoftDocs/OfficeDocs-DeployOffice#458]
I thought the behavior changed, where upon the 6th license activation, O365 will automatically remove the license from the device that is the oldest activated in the list. Please confirm.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3c236da-c63a-f789-f1b6-7aeb41f16c1f
* Version Independent ID: 35319bac-d94f-832c-ce79-41bffe5c8d25
* Content: [Overview of licensing and activation in Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/overview-of-licensing-and-activation-in-office-365-proplus#feedback)
* Content Source: [DeployOffice/overview-of-licensing-and-activation-in-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-licensing-and-activation-in-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@SLeuthold -- are you referring to the "Automatic sign out" capability mentioned in this recent [blog post](https://techcommunity.microsoft.com/t5/Office-365-Blog/Office-365-Client-Licensing-and-Activation-Improvements/ba-p/763694)?  If so, the blog post does say it will be a gradual roll out process, so it might not be available yet for you:

_In August, we’ll start slowly rolling out these changes to commercial customers on Monthly Channel. The roll-out will continue to Semi-Annual Channel (Targeted) in January 2020._

Hope that helps.

**Comment by SLeuthold** [comment]
Yes, thank you!




[cid:InvokeV2_320x123_a1057048-27ef-466c-97e5-e700c239d335.png]<http://www.InvokeLLC.com>

[cid:Twitter_b17288c0-c42e-4e7b-bc77-033c4322b063.png]   <https://twitter.com/InvokeLLC>  [cid:Facebook_df83b2d8-63dc-4240-81e8-612606d7af58.png]    <https://www.facebook.com/InvokeLLC/>  [cid:LinkedIn_c54ffc3c-9f7d-485b-81ad-8b3c147d5a66.png]  <https://www.linkedin.com/company/7798865/>



Stephen Leuthold / Principal Consultant
Stephen.Leuthold@InvokeLLC.com<mailto:Stephen.Leuthold@InvokeLLC.com>
+1 (713) 553-1639

Invoke, LLC
+1 (713) 909-0411
118 Vintage Park Blvd. #W
Houston, Texas 77070
https://InvokeLLC.com


________________________________

Invoke is a 6x Microsoft Gold Partner
[cid:MicrosoftPartner_Logo_6x_300x109_1d6dcca0-33f8-4dee-bfcf-c81cd5db20d3.png]
