### ISSUE TITLE
setup.exe wont run

### ISSUE THREAD

**Issue by samohtrelhe** [MicrosoftDocs/OfficeDocs-DeployOffice#46]
Hi
The extracted Setup.exe will not run.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a003f6a-2edb-3303-01c1-41a63ce82260
* Version Independent ID: 203d6b80-acd5-566a-3f6c-be1852ae8909
* Content: [Deploy Office 365 ProPlus as part of an operating system image](https://docs.microsoft.com/en-us/deployoffice/deploy-office-365-proplus-as-part-of-an-operating-system-image)
* Content Source: [DeployOffice/deploy-office-365-proplus-as-part-of-an-operating-system-image.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-office-365-proplus-as-part-of-an-operating-system-image.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Do you get an error message? What are you typing at the command line when running setup.exe?
