### ISSUE TITLE
teams doesn't installed in 1908 monthly channel.

### ISSUE THREAD

**Issue by cheddarq** [MicrosoftDocs/OfficeDocs-DeployOffice#464]
[Enter feedback here]
Hi There,

Customer uses ODT + SCCM to deploy office 1908 (Build 11929.20300), Teams doesn't installed in some of customer's physical machines, but installed in live devices that mirro the physical devices.

Customer complained about below description in this doc:
 Important

If you're updating your existing installation of Office 365 ProPlus to Version 1908 (Build 11929.20300) or later, Teams will be added. To complete the installation of Teams after the update, either restart the device or have the user log off and log back on.

below are customer complain letter after reading this article:
**Of course I appreciate that there is the GPO mechanism to prevent this, however what my issue is here, as previously mentioned, is how Microsoft have said that Teams will now become mandatory as part of 1908 and how it WASN’T thoroughly communicated!**

Please provide me some advise if this is normal behavior and if we can modify this doc to be more accurate, thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7936ca5e-c658-4956-b174-99eaf1eb67d4
* Version Independent ID: 9ecc0b61-a941-f5e1-96c3-d32fae59eacd
* Content: [Deploy Microsoft Teams with Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/teams-install#feedback)
* Content Source: [DeployOffice/teams-install.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/teams-install.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@cheddarq -- Teams should be installed for that version/build of Monthly Channel. We suggest you contact Microsoft Support so that they can troubleshoot the issue.
