### ISSUE TITLE
Visio 2016 Pro Volume won't accept license key

### ISSUE THREAD

**Issue by gmmiller96** [MicrosoftDocs/OfficeDocs-DeployOffice#465]
We used the Deployment Tool to install Visio 2016 Pro Volume (used the ID and PIDKEY for such), but after the install when we tried to apply the license key we have that's for Visio 2016 Pro Volume License, Visio rejects the key with a message that the key we entered was for Visio 2016 Pro Volume License and that is not compatible with the version installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e6c0641-503d-7959-2afb-839821cc792f
* Version Independent ID: 046c52d9-4fbe-4fe7-0778-5c1d4138f69e
* Content: [Use the Office Deployment Tool to install volume licensed versions of Project 2016 and Visio 2016](https://docs.microsoft.com/en-us/deployoffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016#feedback)
* Content Source: [DeployOffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by RAJU2529** [comment]
@gmmiller96. Check  that product  that you installed in about option.
 use  the convertor script which converts retail to VL.  here is the website

https://gist.github.com/roldaojr/8f8cebaa44c6ac34d2f08df2145083c7
