### ISSUE TITLE
Requirements question - possible inconsistency

### ISSUE THREAD

**Issue by JasonH-Msft** [MicrosoftDocs/OfficeDocs-DeployOffice#466]
This article mentions Office version must be at least 1908:  https://docs.microsoft.com/en-us/DeployOffice/overview-of-security-policy-advisor.  This appears to conflict (typo?) with the version 1808 mentioned in this article.  Please clarify.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa63a94-daaa-9491-213e-f0329f6299b1
* Version Independent ID: 47fe5a3a-ee7c-a7f7-b913-ca0ac3c063e0
* Content: [Overview of the Office cloud policy service for Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/overview-office-cloud-policy-service#feedback)
* Content Source: [DeployOffice/overview-office-cloud-policy-service.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-office-cloud-policy-service.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by DHB-MSFT** [comment]
@JasonH-Msft  -- We checked with the PMs responsible for Office cloud policy service and Security Policy Advisory and those are the correct requirements. Security Policy Advisory shipped after Office cloud policy service and Security Policy Advisory relies on some elements only found in Version 1908 or later.  Thanks for checking.
