### ISSUE TITLE
Cannot customise a Professional Plus 2019 Retail installation

### ISSUE THREAD

**Issue by Noexpert** [MicrosoftDocs/OfficeDocs-DeployOffice#467]
Hi,

all I want to do is to only install Word and Excel.

I downloaded my installation file which is called:
Setup.x86.en-US_ProPlus2019Retail_XXXXX-XXXXX-XXXXX-XXXXX-XXXXX_TX_PR_

I've spent most of the day with all sorts of different permutations of which none work.

This is the configuration file generated by https://config.office.com/:
```
</Configuration>  
<Add OfficeClientEdition="64" SourcePath="C:\Users\user\Desktop">
    <Product ID="ProPlus2019Retail">
      <Language ID="MatchOS" />
      <ExcludeApp ID="Access" />
      <ExcludeApp ID="Groove" />
      <ExcludeApp ID="Lync" />
      <ExcludeApp ID="OneDrive" />
      <ExcludeApp ID="OneNote" />
      <ExcludeApp ID="Outlook" />
      <ExcludeApp ID="PowerPoint" />
      <ExcludeApp ID="Publisher" />
    </Product>
    <Product ID="LanguagePack">
      <Language ID="MatchOS" />
      <Language ID="en-gb" />
      <ExcludeApp ID="Access" />
      <ExcludeApp ID="Groove" />
      <ExcludeApp ID="Lync" />
      <ExcludeApp ID="OneDrive" />
      <ExcludeApp ID="OneNote" />
      <ExcludeApp ID="Outlook" />
      <ExcludeApp ID="PowerPoint" />
      <ExcludeApp ID="Publisher" />
    </Product>
  </Add>
  <Updates Enabled="TRUE" />
</Configuration>
```

Could someone please help?

Thank you

**Comment by DHB-MSFT** [comment]
@Noexpert -- I don't think you can use a configuration.xml with that sort of installation file. Have you tried using just the [Office Deployment Tool](https://docs.microsoft.com/DeployOffice/overview-of-the-office-2016-deployment-tool) and that configuration.xml?  For example, you can [download](https://go.microsoft.com/fwlink/p/?LinkID=626065) the Office Deployment Tool (which is a file named setup.exe file), copy the configuration.xml to the same folder, then from an elevated command prompt, run setup.exe /configure configuration.xml.  That will install Office directly from the internet, using the settings you've specified in the configuration.xml. file. Hope that helps.

**Comment by Noexpert** [comment]
Hi @DHB-MSFT and thanks for the reply.

Indeed, that's what I've tried but it's failed every time.
But that was when I had downloaded the installation file and using that install .

In that case, do I need to omit the `SourcePath` entirely, or replace it with something else?

And could you please check whether the remaining config file does indeed work at your end?
That would really help.

Thank you.

**Comment by Noexpert** [comment]
Hi,

I've tried with this command:
`setup.exe /configure config.xml
`
and this config file:
```<Configuration>  
<Add OfficeClientEdition="64" SourcePath="C:\Users\user\Desktop\office">
    <Product ID="ProPlus2019Retail">
      <Language ID="MatchOS" />
      <ExcludeApp ID="Access" />
      <ExcludeApp ID="Groove" />
      <ExcludeApp ID="Lync" />
      <ExcludeApp ID="OneDrive" />
      <ExcludeApp ID="OneNote" />
      <ExcludeApp ID="Outlook" />
      <ExcludeApp ID="PowerPoint" />
      <ExcludeApp ID="Publisher" />
    </Product>
  </Add>
  <Updates Enabled="TRUE" />
</Configuration>```

I'm getting error code 30029-1011 (0).

I run the Office uninstall support tool as advised [here](https://support.office.com/en-us/article/error-code-30029-1011-when-installing-office-889d0ca8-1418-43f7-959e-334752b4a756). It reported taht no Office installations were found.

Any ideas how to resolve this issue?

Thanks
