### ISSUE TITLE
SignInOptions=3 documented in this article is not available in the ADMX Office 2016

### ISSUE THREAD

**Issue by TheBaban** [MicrosoftDocs/OfficeDocs-DeployOffice#47]
The Office 2016 admin template enables us to configure signinoptions to value 0,1,2,4. The value 3 (AD DS only) is not listed in the possible values. So we don't have the same values documented in this article and in the admin template.
We need to fix, either, the ADMX or this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eca2f9f0-5e82-1e55-4a38-829b16b919e6
* Version Independent ID: 40f0a2a1-3c10-cdd6-40ec-56b48a0f37d2
* Content: [Identity, authentication, and authorization in Office 2016](https://docs.microsoft.com/en-us/deployoffice/security/identity-authentication-and-authorization-in-office#feedback)
* Content Source: [DeployOffice/security/identity-authentication-and-authorization-in-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/identity-authentication-and-authorization-in-office.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Fairly certain the registry key values are correct. So it would be the admin templates that would need to be updated to include the "AD DS only" option. I'm trying to track down someone who can verify and then update the admin templates.  Thanks for your comment/feedback.

**Comment by DHB-MSFT** [comment]
I've confirmed that the registry key values in the article are correct. The admin templates did not get updated. Will try to make that happen. Thanks again for your comment/feedback.
