### ISSUE TITLE
Software Download Settings page

### ISSUE THREAD

**Issue by davidmwilliams** [MicrosoftDocs/OfficeDocs-DeployOffice#472]
Perhaps worth indicating the path to Software Download Settings is via Admin / Settings / Services and AddIns

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ae73873-0e39-3fab-4d9d-3129f7f32345
* Version Independent ID: 3b5ba9ae-756a-149d-81e6-5eda13bf15e6
* Content: [Manage software download settings in Office 365](https://docs.microsoft.com/en-us/deployoffice/manage-software-download-settings-office-365#feedback)
* Content Source: [DeployOffice/manage-software-download-settings-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/manage-software-download-settings-office-365.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@davidmwilliams -- thanks for the suggestion. We've updated the article with a Tip near the top with those steps.
