### ISSUE TITLE
"PerpetualVL2019" channel doesn't seem to work for retail, only "current" does

### ISSUE THREAD

**Issue by wmassingham** [MicrosoftDocs/OfficeDocs-DeployOffice#478]
I wasn't able to get "PerpetualVL2019" working as the channel for 2019 proplus or standard retail; I had to use "current". Is this documentation inaccurate?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f5cfe20-90ad-3f7e-8ae8-ff99bd1e1b55
* Version Independent ID: 97b2760a-50a2-f7c0-32ab-20b0420838d1
* Content: [Update Office 2019 (for IT Pros)](https://docs.microsoft.com/en-us/deployoffice/office2019/update#update-channel-for-office-2019)
* Content Source: [DeployOffice/office2019/update.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/update.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@wmassingham -- PerpetualVL2019 is the correct channel for **_volume licensed_** versions of Office 2019. which this article is focused on. PerpetualVL2019 won't work for retail versions of Office 2019. We'll try to make that clearer in this article. Thanks for the question/feedback.
