### ISSUE TITLE
Thanks sir

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#480]
Thanks to the author for mentioned the downloading link for administrative templates for office  2016.
I added to windows 10, I modified the policy settings for English language templates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cd85e3b-e780-457e-9502-856bc6315bca
* Version Independent ID: 416e351f-13c5-e951-ea81-1650910a7c25
* Content: [Overview of update channels for Office 365 ProPlus](https://docs.microsoft.com/en-in/DeployOffice/overview-of-update-channels-for-office-365-proplus?redirectSourcePath=%252fen-us%252farticle%252f9ccf0f13-28ff-4975-9bd2-7e4ea2fefef4)
* Content Source: [DeployOffice/overview-of-update-channels-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-update-channels-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by jwhit-MSFT** [comment]
We're glad the link helped!
