### ISSUE TITLE
Licensing Requirements

### ISSUE THREAD

**Issue by bchris999** [MicrosoftDocs/OfficeDocs-DeployOffice#481]
According to the service description here: https://docs.microsoft.com/en-gb/office365/servicedescriptions/office-applications-service-description/office-applications-service-description
Office 365 ProPlus only supports Remote Desktop Services (RDS) *when purchased through a Volume Licensing Program*. This should be **heavily** highlighted on this page as people who purchase Office ProPlus through a CSP provider or from Microsoft directly (which I should imagine is a large percentage) wouldn't be in compliance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6da18a8b-9e96-0155-7b30-9c211070d793
* Version Independent ID: 5a7e610a-bfcb-d9cc-03f7-589d970128d9
* Content: [Deploy Office 365 ProPlus by using Remote Desktop Services](https://docs.microsoft.com/en-us/deployoffice/deploy-office-365-proplus-by-using-remote-desktop-services)
* Content Source: [DeployOffice/deploy-office-365-proplus-by-using-remote-desktop-services.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-office-365-proplus-by-using-remote-desktop-services.md)
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by RAJU2529** [comment]
@jwhit-MSFT. Please verify above PR and accept if correct

**Comment by manoth-msft** [comment]
I've incorporated this feedback to PR #811. Thanks for highlighting.
