### ISSUE TITLE
What about older SAC versions? 

### ISSUE THREAD

**Issue by lkuhn65** [MicrosoftDocs/OfficeDocs-DeployOffice#482]
Can an older SAC version still in support be used after Jan 2020 on Windows 7 until it's natural end of support date, such as 1909, for instance? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48fc8b7e-ec90-1bf8-77b6-326d0c6edf0a
* Version Independent ID: f9c1e74f-001e-e8f7-edc1-2d3a8efa8f5c
* Content: [Windows 7 end of support and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/windows-7-support#feedback)
* Content Source: [DeployOffice/windows-7-support.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/windows-7-support.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@lkuhn65  -- No version of Office 365 ProPlus will be supported on Windows 7 after 14 January 2020. But we won't block you from installing "older" versions (for example, Version 1902 of Semi-Annual Channel) on Windows 7. They just won't be supported.
