### ISSUE TITLE
Office Standard and Access Standalone on same PC.

### ISSUE THREAD

**Issue by debido666** [MicrosoftDocs/OfficeDocs-DeployOffice#484]
How do I install Office 2019 Standard and Access 2019 Standalone on the same PC (two different PIDKEY)? When I install Access after Office, both packages lose activation.  I have the correct Office and Access XML's, they activate fine installed individually. How do I make them play nice?

**Comment by RAJU2529** [comment]
@debido666. I have little about the office 2019 standard, i don't think this edition is available.
If you received the office 2019 standard in iso format, you can extract the file, modify the configuration XML file not to install access or delete the line belongs to access.

For more information, visit below site for  how to deploy office 2019
**https://docs.microsoft.com/en-us/deployoffice/office2019/deploy**

**Comment by debido666** [comment]
Both were purchased from TechSoup. Non ISO edition is available. 
**XML for Standard.**
<Configuration>
  <Info Description="Office Standard 2019 (64-bit)" />
  <Add OfficeClientEdition="64" Channel="PerpetualVL2019">
    <Product ID="Standard2019Volume" PIDKEY="#####-#####-#####-#####-#####">
      <Language ID="en-us" />
    </Product>
  </Add>
  <RemoveMSI />
  <Display Level="Full" AcceptEULA="TRUE" />
</Configuration>

**XML for Access standalone.**
<Configuration>
  <Info Description="Access 2019 (64-bit)" />
  <Add OfficeClientEdition="64" Channel="PerpetualVL2019">
    <Product ID="ProPlus2019Volume" PIDKEY="#####-#####-#####-#####-#####">
      <Language ID="en-us" />
      <ExcludeApp ID="Excel" />
      <ExcludeApp ID="Groove" />
      <ExcludeApp ID="Lync" />
      <ExcludeApp ID="OneNote" />
      <ExcludeApp ID="Outlook" />
      <ExcludeApp ID="PowerPoint" />
      <ExcludeApp ID="Publisher" />
      <ExcludeApp ID="Word" />
    </Product>
  </Add>
  <RemoveMSI />
  <Display Level="Full" AcceptEULA="TRUE" />
</Configuration>

**Comment by debido666** [comment]
I think I figured it out.
TechSoup has the wrong xml for installing Access.
It should be:
`<Configuration>
  <Info Description="Access 2019 (64-bit)" />
  <Add OfficeClientEdition="64" Channel="PerpetualVL2019">
    <Product ID="Access2019Volume" PIDKEY="N3VHM-GKVHF-KDJ6X-XYBYY-CWHHH">
      <Language ID="en-us" />
    </Product>
  </Add>
  <RemoveMSI />
  <Display Level="Full" AcceptEULA="TRUE" />
</Configuration>`

**Comment by debido666** [comment]
Yep, I have Office 2019 Standard installed and activated with Access 2019 installed and activated.

**Comment by RAJU2529** [comment]
@debido666. That nice you have solved your case. Now you will able to modify config.xml .

So close this issue from your side
