### ISSUE TITLE
STOP "Learn More" yellow banner opening every page

### ISSUE THREAD

**Issue by ellenble** [MicrosoftDocs/OfficeDocs-DeployOffice#485]
EVERY SINGLE PAGE I open now with the new update has this banner that won't go away. Even if I go to another page and come back to the one where I clicked the x, it comes back! It will not die! This is my worst nightmare.

![Screen Shot 2019-11-13 at 8 43 18 PM](https://user-images.githubusercontent.com/11526206/68827300-50c0fb00-0656-11ea-8119-335b9ca48600.png)

I clicked the learn more, didn't help. 

PLEASE stop this alert it is seriously ruining my day. It is an incredible eyesore and annoyance.

I cannot do any work. No matter what I do I cannot get rid of the banner. It seems you are forcing people to change their privacy settings by annoying them. I use this for work and my organization has these setting disabled by default so nothing I can do.

I am getting carpal tunnel from closing this banner 100 times today.

Please fix this ASAP.

Also, why did you remove the keyboard shortcut/menu option to Show/Hide the navigation panel? It is genuinely hurting my hands to have to use the mouse so often when I didn't even need to before to navigate OneNote Mac. Are you guys not developers?

I am one more bad feature change from moving to different note-taking software and never using this app again.

**Comment by DHB-MSFT** [comment]
@ellenble -- Thanks for your feedback. We've forwarded this on to the teams responsible for OneNote and for the privacy settings notifications.

**Comment by DHB-MSFT** [comment]
@Ellenble -- the OneNote team is in the process of deploying a fix that will allow you to dismiss that banner. It will probably be available in the next few days. Make sure you're running at least Version 16.30.

Thanks for bringing this issue to our attention.

**Comment by DHB-MSFT** [comment]
@ellenble -- For suggestions on how to improve OneNote for Mac, such as adding keyboard shortcuts, we suggest you submit your suggestion to the OneNote for Mac UserVoice site (https://onenote.uservoice.com/forums/327165-onenote-for-mac) where other customers can "vote" for your suggestion.
