### ISSUE TITLE
Setup for SSO

### ISSUE THREAD

**Issue by Typhoon87** [MicrosoftDocs/OfficeDocs-DeployOffice#494]
Is there further documentation that explains how the Single sign-on for this works? The docuemnt says the use of SSO is recommended, like that sounds wonderful, however the document seems void of any any explanation how to turn it and test?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ab31873-7ad3-afde-3c72-8a7fb4f2e551
* Version Independent ID: 19f7f483-9f53-f577-1cd4-d360c0b234fc
* Content: [Overview of shared computer activation for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/overview-of-shared-computer-activation-for-office-365-proplus)
* Content Source: [DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@Typhoon87  -- we don't cover single sign-on (SSO) details in this article because SSO is related to identity management, not deployment & configuration of Office. How to implement SSO depends on how you are managing user identities in your organization. There are other articles available that cover single sign-on, such as [Single sign-on to applications in Azure Active Directory](https://docs.microsoft.com/azure/active-directory/manage-apps/what-is-single-sign-on).

**Comment by Typhoon87** [comment]
Hello DBH- 
It still seems there should be further information as to how this relates to Office Shared Activation should be provided. The article states

"Office is activated using the user credentials that the user provides to sign in to Windows, as long as the user has been assigned a license for Office 365 ProPlus. "

We have local AD synced to Azure AD and the users have student Office license with shared activation in them. Yet are still prompted to activate each time they first log into a lab machine. How would one go about troubleshooting that type of scenario. The given documentation is devoid of any such useful information. We know AD works, we know sync to Azure AD works, we know the office licenses work. Where would I start troubleshooting? If SSO is already set up the docs currently provide nothing to go on.

**Comment by MJP-MSFT** [comment]
Hello @Typhoon87 

There are many items in play when activating Office. The flow is below:
How does sign-in on a web browser with Seamless SSO work?
The sign-in flow on a web browser is as follows:

The user tries to access a web application (for example, the Outlook Web App - https://outlook.office365.com/owa/) from a domain-joined corporate device inside your corporate network.

If the user is not already signed in, the user is redirected to the Azure AD sign-in page.

The user types in their user name into the Azure AD sign-in page.

 Note

For certain applications, steps 2 & 3 are skipped.

Using JavaScript in the background, Azure AD challenges the browser, via a 401 Unauthorized response, to provide a Kerberos ticket.

The browser, in turn, requests a ticket from Active Directory for the AZUREADSSOACC computer account (which represents Azure AD).

Active Directory locates the computer account and returns a Kerberos ticket to the browser encrypted with the computer account's secret.

The browser forwards the Kerberos ticket it acquired from Active Directory to Azure AD.

Azure AD decrypts the Kerberos ticket, which includes the identity of the user signed into the corporate device, using the previously shared key.

After evaluation, Azure AD either returns a token back to the application or asks the user to perform additional proofs, such as Multi-Factor Authentication.

If the user sign-in is successful, the user is able to access the application.
Snippet from: https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-sso-how-it-works 


With that said, which version of Office is installed and what version of Windows 10 are you running? 

In closing, i'd recommend opening a Premier support case to get a proper case created and isolation of the issue. In most cases I have see WIN10 and ProPlus versions run into issues with the WAM flow called out here:
https://docs.microsoft.com/en-us/office365/troubleshoot/administration/connection-issue-when-sign-in-office-2016 

Hope this helps!
