### ISSUE TITLE
Detect shared computer activation status

### ISSUE THREAD

**Issue by mitechzone** [MicrosoftDocs/OfficeDocs-DeployOffice#499]
Is there any documentation on programmatically detecting shared computer activation status?

Background:

We deploy official Office certification exams worldwide. We detect Office license status to make sure candidates do not need to deal with Office activation during the timed exam.

Currently, we use WMI to query license status for non-shared activations. However, we couldn't find any documented way to detect the same for shared computer activation. Neither OSPP or ROIScan can detect the status of shared computer activation.

What we tried so far:

We tried to directly parse the licensing token `authString` file in the `%localappdata%\Microsoft\Office\16.0\Licensing` folder. It appears the file base name is the activation GUID of the SKU. For example, `{149dbce7-a48e-44db-8364-a53386cd4580}` for SKU `Office16O365ProPlusR_Subscription1`.

Inside the `authString` file, the values are delimited by an underscore _:

1. The activation GUID
2. ? Possibly machine key (4 bytes, base64 encoded)
3. ? Possibly an ADAL refresh token (GUID followed by _ADAL) for token renewals. (base64 encoded)
4. SID of the account. Does it always end with a semi-colon?
5. Valid from (ISO 8601 UTC)
6. Valid to (ISO 8601 UTC)
7. ? Possibly an HMAC/KMAC signature that can be used to verify the licensing token against the `signingCert` file (256 bytes, base64 encoded)

A few questions:

1. Is there any way we can detect the shared license status of the current user without reading the licensing token directly (so we don't have to deal with roaming licensing tokens)?

2. If not, how does Office handle the case where multiple tokens exist in the same folder?

3. How do we know if a licensing token (i.e. the `authString` file) is applicable to the current machine?

More and more school districts have moved to shared computer activation. Any documentation or assistance would be highly appreciated.

Thanks!

@DHB-MSFT

**Comment by DHB-MSFT** [comment]
@mitechzone -- Thanks for your question. We've forwarded it on to some of our other shared computer activation experts to see if they know of a way to do it.  You might also want to post your question on the [Office 365 ProPlus section on the Microsoft  Tech Community site](https://techcommunity.microsoft.com/t5/Office-365-ProPlus/bd-p/O365ProPlus). There might someone out there who knows a way to do it.

**Comment by mitechzone** [comment]
@DHB-MSFT Thanks. Happy Thanksgiving!

**Comment by DHB-MSFT** [comment]
Closing since we covered this offline in email.
