### ISSUE TITLE
Please provide link to office.

### ISSUE THREAD

**Issue by nclinch** [MicrosoftDocs/OfficeDocs-DeployOffice#50]
Please provide links to office scrub or describe how to get it.

**Comment by jwhit-MSFT** [comment]
Hi--

We just released a new feature in the Office Deployment Tool that removes existing MSI versions of Office. For more details, see [this article](https://docs.microsoft.com/en-us/deployoffice/upgrade-from-msi-version). If that doesn’t meet your needs, I’d recommend contacting Premier Support, who can provide you with other tools, including OffScrub. 
 
Hope that helps—and let us know if the RemoveMSI feature works for you.

Jason
