### ISSUE TITLE
cmd prompt not recognized by Windows 10

### ISSUE THREAD

**Issue by slant6power** [MicrosoftDocs/OfficeDocs-DeployOffice#500]
'set up' not recognized as a valid command for Windows 10. What is correct command?

Thanks much,

dg.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [Deploy Office 2019 (for IT Pros)](https://docs.microsoft.com/en-us/deployoffice/office2019/deploy#feedback)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@slant6power -- "setup" should be one word. And you should be running the command from the folder where you downloaded and extracted the Office Deployment Tool to.  Hope that helps.

**Comment by slant6power** [comment]
Have 'setup' as one word.

When you say 'should be running the command from the folder where you 
downloaded'.  I am not familiar with MS, used to Linux where I would 
'cd' to desired folder. What is example of command prompt in MS to work 
in desired folder? Thanks much!


-- 
David Gowler
Office Manager

Cooperative Development Institute
P.O. Box 1051
Northampton, MA 01061-1051
dgowler@cdi.coop
1-877-NE-COOPS

413-665-1271 (ext.5)

Fax: 413-541-8300

www.cdi.coop

**Comment by DHB-MSFT** [comment]
@slant6power -- you can use the CD command from a Windows command prompt as well. 

For example, when you go to an elevated command prompt (that is, running the command prompt as administrator, which you'll need to do to install Office using the setup command), you will probably be taken to C:\Windows\system32.  You can then do CD\ to get to the root of C: drive. From there you can use CD command again to navigate to the folder where you saved the Office Deployment Tool.  For example,  CD downloads\ODT.  Once you're in that folder, just run setup /configure configuration.xml to install Office. (for the last argument, use the name of the xml file that you created).  Hope that helps.

**Comment by slant6power** [comment]
Sorry, one last question. Can you use sudo su in MS to become root? 
Thanks much!

-- 
David Gowler
Office Manager

Cooperative Development Institute
P.O. Box 1051
Northampton, MA 01061-1051
dgowler@cdi.coop
1-877-NE-COOPS

413-665-1271 (ext.5)

Fax: 413-541-8300

www.cdi.coop

**Comment by DHB-MSFT** [comment]
@slant6power  -- sorry I'm not familiar with the sudo su command. I don't think it's available in Windows. But you can run the command prompt, registry editor, etc as an admin, even if you're signed in with a non-admin account. It will just prompt you to enter the username & password of your admin account.  When we say to run an elevated command prompt, we're referring to "Run as administrator" when you start the command prompt.  Like in this screenshot:

![image](https://user-images.githubusercontent.com/32883970/69759901-03459300-1118-11ea-867c-b7f64cf60b96.png)

**Comment by slant6power** [comment]
Thanks much!

-- 
David Gowler
Office Manager

Cooperative Development Institute
P.O. Box 1051
Northampton, MA 01061-1051
dgowler@cdi.coop
1-877-NE-COOPS

413-665-1271 (ext.5)

Fax: 413-541-8300

www.cdi.coop

**Comment by RAJU2529** [comment]
@slant6power. sir you may use below commands 
open  cmd with administrator rights and then type below command

C:\ODT\setup.exe /configure C:\ODT\configuration.xml
