### ISSUE TITLE
How do I deploy in other languages?

### ISSUE THREAD

**Issue by RipRapRob** [MicrosoftDocs/OfficeDocs-DeployOffice#502]
On this page it says "Download the Office Deployment Tool from the Microsoft Download Center."

On that page (https://www.microsoft.com/en-us/download/details.aspx?id=49117) it says "Important! Selecting a language below will dynamically change the complete page content to that language." and below that; Language: English.

I want to deploy in Danish but I can't find a way to change the language from English on, where I download the Office Deployment Tool. 

Help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66127c02-c2dc-f6d1-6e83-a6d2b1166731
* Version Independent ID: 27635315-22db-d136-f07e-5169f6207b50
* Content: [Overview of the Office Deployment Tool](https://docs.microsoft.com/en-us/deployoffice/overview-of-the-office-2016-deployment-tool#feedback)
* Content Source: [DeployOffice/overview-of-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by RAJU2529** [comment]
@RipRapRob. you can download the proofing tools for all the languages and then install with an administrator rights

go to the below website and click the radio button 
and then select the danish language

**https://support.office.com/en-us/article/Language-Accessory-Pack-for-Office-82ee1236-0f9a-45ee-9c72-05b026ee809f**


![upload](https://user-images.githubusercontent.com/3296790/69880924-5888cc80-12f1-11ea-872c-d1d49a67a177.JPG)

**Comment by RAJU2529** [comment]
@RipRapRob. ODT is available only English only. But you configure the xml file and deploy office  in danish language
just by replacing the "en-us"   to "da-dk" in the following configuration files 

configuration-Office365-x64.xml
configuration-Office365-x86.xml
configuration-Office2019Enterprise.xml


you can edit by using notepad, after editing, you must save as .xml

**Comment by DHB-MSFT** [comment]
@RipRapRob -- @RAJU2529  is correct. The Office Deployment Tool itself is English only, but you can modify the sample xml file to install Office in Danish.  

If you need to deploy multiple languages in an organization, see this article for more information -- [Overview of deploying languages in Office 365 ProPlus](https://docs.microsoft.com/deployoffice/overview-of-deploying-languages-in-office-365-proplus).
