### ISSUE TITLE
Technical support of OneNote for Windows 10 vs. technical support of OneNote 2016

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/OfficeDocs-DeployOffice#503]
After a technical issue with OneNote for Windows 10 and a reply from a CSP's technical support there is a need for clarification in the docs if the OneNote for Windows 10 application is out of scope for technical support by CSPs as it's not an Office 365 application but a Windows 10 app.

If there's a difference in technical support by Microsoft and technical support by CSP's for OneNote for Windows 10 compared to the support for OneNote 2016 then this is a huge showstopper which must be mentioned because it has a big impact on which version will be deployed.

If this topic is covered somewhere else, please provide me with a link to it. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2319f44f-09fc-2649-2667-58fa159e3151
* Version Independent ID: 0b6c5c52-edaa-436d-95dd-0943d0b0c303
* Content: [Deployment guide for OneNote](https://docs.microsoft.com/en-us/deployoffice/deployment-guide-onenote#feedback)
* Content Source: [DeployOffice/deployment-guide-onenote.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deployment-guide-onenote.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@GiantCrocodile  -- thanks for your comment/question. We're checking with our technical support experts.

**Comment by DHB-MSFT** [comment]
@GiantCrocodile -- we checked with our technical support team that covers OneNote and they said there shouldn't be any difference in support between the 2 versions. If you're still having an issue, you should contact Microsoft Support and they can investigate further directly with you and with your CSP.
