### ISSUE TITLE
Office ODT not working Setup with any xml doesn't work

### ISSUE THREAD

**Issue by aaronpartida** [MicrosoftDocs/OfficeDocs-DeployOffice#505]
I've been using Office ODT for over a year now to deploy Microsoft office 365 and this week it stopped working, so I downloaded the latest ODT tool extracted the setup.exe and it just closes and doesn't run, no error or anything.  If I specify a location to download the file I get the following error: 30088-1007 (0), which seems to be generic.  Did anything recently change this week?  I did over 5 installs last week without an issue.  I tried 2 different internet connections.  I've tried different xml files.

**Comment by DHB-MSFT** [comment]
@aaronpartida  -- I just downloaded the most current ODT from the Microsoft Download Center and was able to use it to both download the Office installation files to a local device as well as install Office directly from the CDN.  So maybe 2 possibilities in your case -- temporary networking issue or syntax error in your xml file. One way to test the xml file is see if it can be opened in IE. You can also try using https://config.office.com to create your xml file and see if that works.

**Comment by aaronpartida** [comment]
Hi DHB-MSFT,

While on WIFI I am now able to download the software into a folder, but it does not install.  It does a pop up and then disappears.  I am downloading O356ProPlusRetail with english and ja-jp proofing tools.  it looks like this:

<Configuration>
  <Add SourcePath="C:\Temp\software\extract\Office2019" OfficeClientEdition="64" Channel="Monthly">
    <Product ID="O365ProPlusRetail">
      <Language ID="en-us" />
	  <ExcludeApp ID="OneDrive" />
    </Product>
	<Product ID="ProofingTools">
         <Language ID="ja-jp" />
    </Product>
   </Add>

  <Updates Enabled="TRUE" Channel="Monthly" />
  
  <RemoveMSI All="True" />

  <Display Level="none" AcceptEULA="TRUE" />

  <Property Name="AUTOACTIVATE" Value="1" />

</Configuration>
-------------------------------------------------------------------------
This has worked for about a year and never have I run into this issue

Let me know what you think.

Thank you for your help
-Aaron

**Comment by RAJU2529** [comment]
@aaronpartida.Try to  disable controlled folder access. and disable temporarily windows defender.
Run setup.exe  using command prompt

**Comment by aaronpartida** [comment]
Hi Varadharajan,

It must have been something on Microsoft’s end, it started working on its own.  The download started working every time at first on Friday.  Then the installer started working this Monday.

Thank you for your help.

-Aaron

**Comment by DHB-MSFT** [comment]
@aaronpartida  -- Glad to hear it's working for you.
