### ISSUE TITLE
Edit policy configuration

### ISSUE THREAD

**Issue by Everink** [MicrosoftDocs/OfficeDocs-DeployOffice#506]
When editting an existing policy, it's impossible to change the Assigned group to another group. If this is intended behaviour might want to update the docs with that info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa63a94-daaa-9491-213e-f0329f6299b1
* Version Independent ID: 47fe5a3a-ee7c-a7f7-b913-ca0ac3c063e0
* Content: [Overview of the Office cloud policy service for Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/overview-office-cloud-policy-service#feedback)
* Content Source: [DeployOffice/overview-office-cloud-policy-service.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-office-cloud-policy-service.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by chhopkin** [comment]
Thank you for the feedback.  This is behavior that is part of the initial design.  Currently you can create a copy of a policy configuration and edit the new copy to change targeting of groups.  For our next feature update we are working on improvements to the group targeting functionality to make this easier.
