### ISSUE TITLE
File Not Found...

### ISSUE THREAD

**Issue by TomoharuMisawa** [MicrosoftDocs/OfficeDocs-DeployOffice#509]
it's error. cscript.exe "%programfiles%\Microsoft Office\Office15\ospp.vbs" /dstatus

this is ok. cscript.exe "%programfiles%\Microsoft Office\Office16\ospp.vbs" /dstatus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a003f6a-2edb-3303-01c1-41a63ce82260
* Version Independent ID: 203d6b80-acd5-566a-3f6c-be1852ae8909
* Content: [Deploy Office 365 ProPlus as part of an operating system image](https://docs.microsoft.com/en-us/deployoffice/deploy-office-365-proplus-as-part-of-an-operating-system-image?WT.mc_id=M365-MVP-5002496)
* Content Source: [DeployOffice/deploy-office-365-proplus-as-part-of-an-operating-system-image.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-office-365-proplus-as-part-of-an-operating-system-image.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by RAJU2529** [comment]
office 15 means  office 2013.
and office 16 means office 2016

**Comment by TomoharuMisawa** [comment]
Yes, well known.

but, ProPlus 2013 was Not supported.
https://docs.microsoft.com/en-us/office/troubleshoot/support/2013-versions-of-office-365

**Comment by RAJU2529** [comment]
@TomoharuMisawa. Office 2013 on office 365 is  ended support , so you must upgrade to  office 2019 or office 2016

**Comment by DHB-MSFT** [comment]
@TomoharuMisawa -- Thank you for bringing this error to our attention. We've updated the article with the correct folder name.
