### ISSUE TITLE
Support for OneDrive

### ISSUE THREAD

**Issue by entusdictus** [MicrosoftDocs/OfficeDocs-DeployOffice#51]
Is OneDrive standalone also supported by msupdate? If yes, what's the identifier?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59e840a0-92ac-3ba4-75b3-01a154d67899
* Version Independent ID: 8f7fd243-8f3a-7d32-8433-03b8167aee6f
* Content: [Update Office 2016 for Mac by using msupdate](https://docs.microsoft.com/en-us/DeployOffice/mac/update-office-for-mac-using-msupdate)
* Content Source: [DeployOffice/mac/update-office-for-mac-using-msupdate.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/mac/update-office-for-mac-using-msupdate.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @pbowden-msft
* Microsoft Alias: **danbrown**

**Comment by pbowden-msft** [comment]
Hi there. No, OneDrive standalone doesn't update through Microsoft AutoUpdate. It has its own mechanism to update.

Thanks, Paul.
