### ISSUE TITLE
GPO does not affect update channel when managed by SCCM

### ISSUE THREAD

**Issue by mhouston100** [MicrosoftDocs/OfficeDocs-DeployOffice#510]
The GPO itself states that the setting only affects the channel when downloading directly from the CDN. I've confirmed in testing that the GPO does nothing. To manage update the channel when using SCCM you have to set both registry keys:

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration!UpdateChannel
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration!CDNBaseUrl

To match the channel you want.

I haven't been able to set in stone the exact procedure but after changing the registry keys above, I also:

* Restarted the 'Microsoft Office Click-to-Run Service'
* Manually ran the 'Office Automatic Updates 2.0' scheduled task
* Run the SCCM actions for Hardware Inventory, Computer Policy and Update deployment

I believe just being patient would affect the same result but may take several hours for all the processes to run.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d23ac821-9cb8-8855-598f-d1327df04fac
* Version Independent ID: 78f2127a-0c6b-d236-a415-6215c582ce8b
* Content: [Change the Office 365 ProPlus update channel for devices in your organization](https://docs.microsoft.com/en-gb/deployoffice/change-update-channels)
* Content Source: [DeployOffice/change-update-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/change-update-channels.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by mhouston100** [comment]
Also, I'm not sure I understand why this needs to be so complicated. Is the Microsoft recommended method to purely use ODT and deploy that as an application / package from SCCM?

**Comment by RAJU2529** [comment]
@mhouston100. I seen particular setting to update office product through CDN or another location in GPO so please check in GPO that you have entered another server location to get update office

**Comment by davguent** [comment]
@mhouston100 Can take a look at the following blog posting which has additional details which may help.
How to manage Office 365 ProPlus Channels for IT Pros
https://techcommunity.microsoft.com/t5/Office-365-Blog/How-to-manage-Office-365-ProPlus-Channels-for-IT-Pros/ba-p/795813.  Policy is respected and may require 24 hour delay to take effect.  Often I hear this concern from IT Pros who are performing validation within compressed timeframe.  Let me know if this resolves concern.  Thank you.

**Comment by lexios** [comment]
I confirm, that the GPO does not change the Channel in the registry under:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration
Although the Policy has applied under:
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\office\16.0\common\officeupdate

Repeatedly ran the Automatic Updates 2.0 Task, restarted C2R service and also rebooted. 
Also, Office hasn't been recently installed neither recently updated. 

The GPO does nothing when managing Office through SCCM/MEMCM as it seems.

**Comment by davguent** [comment]
The GPO will only add value under HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\office\16.0\common\officeupdate
updatebranch=%nameyouassigned%.  That is all.  The scheduled task Office Automatic Updates 2.0' scheduled task will then detect the policy key and reflect channel change in value "UpdateChannel".  The backstage of Office will not reflect the new channel name until at least once successful update.  Further, you can accelerate lab validation by using steps in comments from blog https://techcommunity.microsoft.com/t5/Office-365-Blog/How-to-manage-Office-365-ProPlus-Channels-for-IT-Pros/ba-p/795813

**Comment by lexios** [comment]
Cancel that, I don't know -and shouldn't play a role- how updating the ADMX files to the latest version caused the client to change channel. Probably pure coincidence as there was no change on the actual values under Policies in the registry. So, I confirm IT WORKS.
