### ISSUE TITLE
So dumn

### ISSUE THREAD

**Issue by bmansf** [MicrosoftDocs/OfficeDocs-DeployOffice#511]
Can't just download an installer?  As much as Office licenses cost you would think some asshat at Microsoft could afford to make it easy to install without having to deal with a bunch of crap like this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [Deploy Office 2019 (for IT Pros)](https://docs.microsoft.com/en-us/DeployOffice/office2019/deploy)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by RAJU2529** [comment]
you can download the Click 2 run installer with office 2019 or 2016  product key

just go to office.com/setup and sign with with Microsoft account and follow the instructions displayed in on-screen

**Comment by DHB-MSFT** [comment]
@bmansf -- If you have suggestions for the product team on how to improve deploying Office, you can submit them here -- https://odinsiders.uservoice.com/.

**Comment by seamonkey420** [comment]
how about using msi's and doing what worked just fine for the last 20+ years? CTR sucks.. been using office and installing it since Office 97... 

also how does one customize the installation of office 2019? is there an OCT for 2019? prob not. heck, there isn't even a link to the full list of options for the XML config files; what displaylevel options are there?

**Comment by DHB-MSFT** [comment]
@seamonkey420 -- See both of the Tips in the [Create the configuration.xml](https://docs.microsoft.com/DeployOffice/office2019/deploy#create-the-configurationxml) section of the article. The first tip refers to the Office Customization Tool for Click-to-Run, which you can use to customize an Office 2019 installation. The second tip has a link to more information about the various settings available, including the [Display element](https://docs.microsoft.com/DeployOffice/configuration-options-for-the-office-2016-deployment-tool#display-element).
