### ISSUE TITLE
Configuration file download

### ISSUE THREAD

**Issue by bmansf** [MicrosoftDocs/OfficeDocs-DeployOffice#512]
Would it be possible to just put the necessary configuration xml file on the Volume Licensing site so we do not need to configure Microsoft's installer?  It is quite ridiculous that Microsoft can't even provide an installer that is ready to use after paying for a product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [Deploy Office 2019 (for IT Pros)](https://docs.microsoft.com/en-us/deployoffice/office2019/deploy)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by RAJU2529** [comment]
@bmansf . Yes you can get default configuration file for office 365 .
which is included in office deployment tool 
you can download from below link

https://www.microsoft.com/en-us/download/details.aspx?id=49117

**Comment by DHB-MSFT** [comment]
@bmansf -- As @RAJU2529 mentioned, there is a sample configuration file available with the [Office Deployment Tool download](https://www.microsoft.com/en-us/download/details.aspx?id=49117). It's named configuration-Office2019Enterprise.xml.  

Also, the [Office Customization Tool](https://config.office.com) provides "Standard configurations" for volume licensed installations that you can download and use.

If you have suggestions for the product team on how to improve deploying Office, you can post them here -- https://odinsiders.uservoice.com/.
