### ISSUE TITLE
HelpShift

### ISSUE THREAD

**Issue by JonOfBallard** [MicrosoftDocs/OfficeDocs-DeployOffice#515]
...is not owned by Microsoft afaik, but some of the related services in this scenario are. -JonL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d22aec53-c328-ee44-0b01-475d6ee3f940
* Version Independent ID: 2b39a702-7f42-9b63-d27b-af4806646770
* Content: [Overview of optional connected experiences in Office](https://docs.microsoft.com/en-us/deployoffice/privacy/optional-connected-experiences#feedback)
* Content Source: [DeployOffice/privacy/optional-connected-experiences.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/optional-connected-experiences.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@JonOfBallard -- thanks for bringing that to our attention. We are working on getting that reference corrected.

**Comment by DHB-MSFT** [comment]
@JonOfBallard -- article has been updated.
