### ISSUE TITLE
Microsoft 365 admin center shows Release preferences: Standard release and Targeted release

### ISSUE THREAD

**Issue by rsoakford** [MicrosoftDocs/OfficeDocs-DeployOffice#517]
I just went to https://admin.microsoft.com/Adminportal/Home?source=applauncher#/companyprofile to check "Release preferences: Choose how your organization gets new features and service updates from Office 365" for our tenant and was confused by the following terminology: "Standard release" and "Targeted release".

Neither this page, nor the pages it links to mention that terminology so could someone please clarify: does "Standard release" = monthly and "Targeted release" = semi-annual (targeted)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cd85e3b-e780-457e-9502-856bc6315bca
* Version Independent ID: 416e351f-13c5-e951-ea81-1650910a7c25
* Content: [Overview of update channels for Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/overview-of-update-channels-for-office-365-proplus#BKMK_MC)
* Content Source: [DeployOffice/overview-of-update-channels-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-update-channels-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by rsoakford** [comment]
Related to my earlier comment #517, elsewhere in the same tenant at https://portal.office.com/AdminPortal/Home#/Settings/Apps under "Office software download settings" we have set for users to get feature updates "Every 6 months (Semi-Annual channel)" - is this setting related to the Office 365 "Release preferences" option under Company profile?

**Comment by DHB-MSFT** [comment]
@rsoakford  -- Here is the article that's supposed to explain the Standard/Targeted terminology:  [Set up the Standard or Targeted release options in Office 365](https://docs.microsoft.com/office365/admin/manage/release-options-in-office-365).

In general, Targeted release is intended to give you early access to upcoming changes to the Office 365 services, like the admin center, Exchange Online, SharePoint Online, etc.

There is a relationship between choosing Standard/Targeted release and what you have chosen on the **Office software download settings** page. 

- If you choose "Targeted release" for your tenant (or for a subset of your users), and then you choose "Every 6 months (Semi-Annual Channel)", when you install Office from the Office 365 portal, you will get Office builds from Semi-Annual Channel (Targeted), which is the preview channel for Semi-Annual Channel. 
- If you choose "Targeted release" for your tenant (or for a subset of your users), and then you choose "Every month (Monthly Channel)", when you install Office from the Office 365 portal, you will get Office builds from Monthly Channel (Targeted), which is the preview channel for Monthly Channel.

The presumption is that if you want targeted/preview versions of Office 365 services, you'll want the targeted/preview versions of Office for the Office channel that you have selected.


- If you choose "Standard release" for your tenant, and then you choose "Every 6 months (Semi-Annual Channel)", when you install Office from the Office 365 portal, you will get Office builds from Semi-Annual Channel. 
- If you choose Standard release" for your tenant, and then you choose "Every month (Monthly Channel)", when you install Office from the Office 365 portal, you will get Office builds from Monthly Channel.

For more information about the channels for Office, see [Overview of update channels for Office 365 ProPlus](https://docs.microsoft.com/DeployOffice/overview-of-update-channels-for-office-365-proplus).

We hope this explanation helps. Thanks for your question. We will try to update/add to the content to make this clearer/easier to find & understand.

**Comment by rsoakford** [comment]
Thank you for clarifying the relationship between the releases for _Office 365 services_ and _Office software download settings_, @DHB-MSFT 😊
