### ISSUE TITLE
Differences between VL Editions of Project vs Project Online Desktop Client

### ISSUE THREAD

**Issue by xlZeroAccesslx** [MicrosoftDocs/OfficeDocs-DeployOffice#520]
I couldn't find this on docs.microsoft.com. It would be beneficial to publish a section comparing the two. 

What are the differences between Project Professional 2019 and Project Online desktop client?
The core features of the two products are identical with one exception. Project Online desktop client includes Kanban boards. Project Professional has a perpetual license. Once activated, the software will not expire. Use of the Project Online desktop client requires an active Project Plan 3 or Project Plan 5 subscription.

https://products.office.com/en-us/project/microsoft-project-faq

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 696c19fd-3bf3-b148-57e3-f0203a036a80
* Version Independent ID: b97bfdbd-fe95-2bd1-0d40-2682cb7c1be6
* Content: [Deployment guide for Project](https://docs.microsoft.com/en-us/deployoffice/deployment-guide-for-project)
* Content Source: [DeployOffice/deployment-guide-for-project.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deployment-guide-for-project.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by jwhit-MSFT** [comment]
Thanks for the feedback. I've passed it along to the writers for Project.
