### ISSUE TITLE
Browser Hijack?

### ISSUE THREAD

**Issue by ceturc** [MicrosoftDocs/OfficeDocs-DeployOffice#521]
This unexpected Chrome Browser Hijack will confuse and disappoint my end users and create extra helpdesk calls for my org.  Please don't do this.

Reddit thread where I heard about this change:  https://www.reddit.com/r/sysadmin/comments/es6xp5/office_365_proplus_to_change_chromes_default/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by rheibel** [comment]
Can you clarify if this will affect Microsoft EDU versions e.g 'Office 365 A1 Plus for students' and will 'Microsoft Search in Bing' follow the same DNS based 'safe search' enforcement as bing.com or will schools need to implement new network level safe search enforcement before version 2002 is made available for student BYOD devices in February 2020.

**Comment by Deshke** [comment]
* will this also be the case on Mac Installations
* how to prevent his on Mac

**Comment by auzdark** [comment]
This is definitely a browser hijack and will be reported and blacklisted as such. Thanks for the heads up.

**Comment by jpb6github** [comment]
Please do document how to implement this feature if desired, but please don't force this change on our users as a default action or make us have to disable it!

**Comment by neekless** [comment]
100% browser hijacking. Malware behavior.

**Comment by chrissie1234** [comment]
I guess Microsoft wants another antitrust case, or a fine by the EU. I'd suggest, forget this whole 'feature', else I guess even antivirussoftware will have to mark the installation of Office as a virus. This is 100% a PuP (potentially unwanted program).

**Comment by 4oo4** [comment]
Bing is terrible at directing users to ads and malware, so we avoid it at all costs. Whatever integration this is supposed to bring is absolutely not worth the security risk, which we can not tolerate at the company where I work where security is paramount. Not to mention the end user frustration this will cause too..

Are you really that desperate that you'll resort to malware tactics to push your terrible search engine on people?

**Comment by ItzMichaelPhillips** [comment]
Wow @ItzLevvie you're a petty piece of shit

**Comment by DHB-MSFT** [comment]
@Deshke  -- There are no plans at this time to include Office for Mac. We'll update the article to make that clearer.
