### ISSUE TITLE
BrowserModifier

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/OfficeDocs-DeployOffice#527]
Please add this to Microsoft Security Intelligence Definitions so that Windows Defender detects and removes this threat as for other similar software:
"This browser modifier installs add-ons or extensions to your Internet browser without asking you or confirming that you want to install them."
https://www.microsoft.com/en-us/wdsi/threats/threat-search?query=BrowserModifier

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by scqless** [comment]
Using Microsoft's own words against them... Nice.

Microsoft's own product is malware according to another Microsoft product.
