### ISSUE TITLE
Office 2019?

### ISSUE THREAD

**Issue by jones948** [MicrosoftDocs/OfficeDocs-DeployOffice#528]
Is Office 2019 VL going to be affected by this at any point?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#which-locations-will-receive-microsoft-search-in-bing-with-office-365-proplus)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
There are no plans at this time to include volume licensed versions of Office 2019. We'll update the article to make that clearer.
