### ISSUE TITLE
Are you out of your minds?

### ISSUE THREAD

**Issue by iloving** [MicrosoftDocs/OfficeDocs-DeployOffice#530]
Are you intentionally trying to cause a helpdesk nightmare?  What is wrong with you people?

This is absolutely unacceptable.  The fact that there is a GPO to disable it doesn't change that.  Now our IT department has to deal with additional unexpected work to mitigate something that nobody asked for.  

Meanwhile anyone that doesn't have an IT department to back them up is going to cause all sorts of confusion.  Have you people seriously learned nothing from the last time you tried to force feed people with unwanted products?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by SlayerOU812** [comment]
I agree.  This is just opening the flood gates to new law suits as well as problems for help desk individuals.
