### ISSUE TITLE
WOW

### ISSUE THREAD

**Issue by ldleasher** [MicrosoftDocs/OfficeDocs-DeployOffice#537]
If you check the About info in Chrome you will notice that is not your app.  What makes you think you can mess with it is beyond my understanding.  I have to assume Satya made a bet with Tim Cook to see who could piss off the most people the fastest and Staya is hell bent on winning that bet.  If so, nicely played.  You are certainly going to win unless Tim actually lights someone on fire.  But that is just my 2 cents... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by scqless** [comment]
M$ hasn't been the same since Nadella took over... and to think that I was once excited about someone from the technical side of the company taking the helm... I certainly didn't think we'd be seeing boneheaded moves such as this one.
