### ISSUE TITLE
malware indeed

### ISSUE THREAD

**Issue by fjleon1980** [MicrosoftDocs/OfficeDocs-DeployOffice#540]
if you already have bing as a default search engine on chrome, the extension won't get installed. this is proof the only purpose of this extension is to change your search engine from google to bing without your consent.

this is basically malware

**Comment by fjleon1980** [comment]
i'm glad this was fixed. thanks!

**Comment by scqless** [comment]
Don't say thanks... they shouldn't be congratulated for backpedaling on a stupid move.
