### ISSUE TITLE
I just blocked bing.com for the entire organization

### ISSUE THREAD

**Issue by jcampbellburns** [MicrosoftDocs/OfficeDocs-DeployOffice#543]
This is due to malware (defined as any software which, among other things, installs browser extensions without approval) pointing to this website.

Also, I'll be reevaluating our continued used of Office365 in light of this. LibreOffice and Google Docs both don't automatically install browser extensions which override default browser behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by lawtonj404** [comment]
I agree it’s Absolute stupidity from Microsoft, this needs to be stopped. As users we have a right of choice, I do not choose bing because I personally prefer another search provider, this is a disgrace and will take weeks to resolve as many clients don’t have group policy.

**Comment by Lepidopterist** [comment]
Thirded.  DNS block ahoy.

**Comment by jcampbellburns** [comment]
Microsoft closed this ticket without addressing the concern.

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making a few changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
