### ISSUE TITLE
Let MS know your thoughts on the ODI Uservoice

### ISSUE THREAD

**Issue by netresults-scott** [MicrosoftDocs/OfficeDocs-DeployOffice#545]
https://odinsiders.uservoice.com/forums/920533-distribution-upgrades-servicing/suggestions/39494872-do-not-force-push-bing-as-the-default-search-engin

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-ca/deployoffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by pke** [comment]
Uservoice has been pretty much useless all through Windows/Windows Phone times. Not wasting my time. This place here is as good as any. Let them be 1000s of GH issues for them to walk through and close.
