### ISSUE TITLE
This is an extremely hostile, hateful move.

### ISSUE THREAD

**Issue by aolives** [MicrosoftDocs/OfficeDocs-DeployOffice#547]
This isn't what's best for users, this isn't what's best for the platform.
This is abhorrent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by Slogmeister** [comment]
You are right.  We have spent too much time trying to escape the eternal hell of browser hijacking.  For this to be a part of Microsoft Office is overstepping bounds and purposefully sabotaging the user.  There are alternatives to Office and the other 365-suite products. Maybe it's time to kiss M$ goodbye.
