### ISSUE TITLE
Keep your malware out of Chrome

### ISSUE THREAD

**Issue by Kevin-at-MQ** [MicrosoftDocs/OfficeDocs-DeployOffice#548]
This article is hopefully full of typos and needs to be revised to state that a Bing virus extension will not be force-installed into someone else's application.

Sorry, but nobody wants to use Bing in Chrome.  We chose to install Chrome rather than use Microsoft's two pre-installed browsers.  We're aware of our ability to install extensions IF WE WANT THEM INSTALLED!!!  So what makes you think we want you to break the software we actually chose?  I'll be sure to submit every signature of the malicious extension I find to the top 70+ antivirus software companies so they can update their virus definitions accordingly.  I'll advise others to do the same so we make sure it doesn't spread.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by TravitoDLM** [comment]
Bing sucks. No one likes bing. MS should let it die. Their first clue should have been that they have to offer rewards points just to get people to use it.
