### ISSUE TITLE
Version tracking and planning can be confusing with multiple tracks being "supported".  ex: Semi-Annual Channel 1705 and 1708 both listed (which didn't actually roll in 05 or 09 btw)

### ISSUE THREAD

**Issue by MicrosoftIsABoatOnFireWithAHoleInIt** [MicrosoftDocs/OfficeDocs-DeployOffice#55]
Instead of just:
 "July 10, 2018 New features are released to Semi-Annual Channel.
This version of Semi-Annual Channel is supported until September 2019.
The next release with new features is scheduled for January 8, 2019. "

please add the actual version numbers in this list.  They are known entities but for us Admin monkeys there multiple to pick from, MS has changed nomenclature 3 times since launch, maint windows have shifted multiple times and all this is almost impossible to explain to non-experts at this point (which we need to be able to do).  It would help us clarify planning if the exact 18XX, 19XX numbers were listed in here and tied back to the release information and release notes pages.  ex: 1708 (which was supposed to be released\called 1707) was tested over 4 months (1703-1707) and was released to prod in 1710 after the designed semi-annual channel maint window but isn't called 1710 and wasn't replaced by 1803 as expected in 1804 and delayed until 1805 but is now being rolled in 1807.   wait...what?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cd85e3b-e780-457e-9502-856bc6315bca
* Version Independent ID: 416e351f-13c5-e951-ea81-1650910a7c25
* Content: [Overview of the upcoming changes to Office 365 ProPlus update management](https://docs.microsoft.com/en-us/deployoffice/overview-of-the-upcoming-changes-to-office-365-proplus-update-management#BKMK_Upcoming)
* Content Source: [DeployOffice/overview-of-the-upcoming-changes-to-office-365-proplus-update-management.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-the-upcoming-changes-to-office-365-proplus-update-management.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Thanks for your comment/feedback/suggestions. For the most up-to-date release information for Office 365 ProPlus, go to Release information for updates to Office 365 ProPlus.

Since all of the changes discussed in the “upcoming changes” article have been implemented and since we've incorporated information about these changes into our other content (for example, our overview article about update channels), we're going to retire the “upcoming changes” article.
