### ISSUE TITLE
Disgraceful abuse of Microsoft’s position

### ISSUE THREAD

**Issue by Andrewsimmans** [MicrosoftDocs/OfficeDocs-DeployOffice#551]
This is disgraceful if I want to use Bing then it should be up to me. It is not acceptable for Microsoft to try and force this. Going down this path will discourage the use of Microsoft products as Microsoft becomes Big Brother forcing us to do what you want us to do!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by brendan-sherrin** [comment]
+1
