### ISSUE TITLE
Are you all completely out of your minds?

### ISSUE THREAD

**Issue by TravitoDLM** [MicrosoftDocs/OfficeDocs-DeployOffice#555]
In what world does this strike anyone as remotely okay to push with a freaking office application suite? Especially one as expensive as Office. You CANNOT do this to our students. We have no way to opt them out because they're not on a domain so group policy doesn't work, and they use the "Install Office" button on the website, not a customized installer.

Seriously. WHAT ARE YOU THINKING? G-Suite is looking very tempting right now. Half of our students are already used to Google docs because you all have already lost my ENTIRE STATE'S public K-12 institutions as customers. Maybe it's time the universities move too...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making a few changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
