### ISSUE TITLE
Extremely bad move

### ISSUE THREAD

**Issue by skeptic90210** [MicrosoftDocs/OfficeDocs-DeployOffice#557]
We are a university. We have no control over student BYODs and our helpdesk will be swamped by student complaints.

DO NOT DO THIS!!! (Yes, I am shouting.)

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making a few changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
