### ISSUE TITLE
This is NOT ok. 

### ISSUE THREAD

**Issue by msoundCGI** [MicrosoftDocs/OfficeDocs-DeployOffice#558]
Changing the selected search engine in the users browser without permission or installing an extension is not acceptable behavior. Doing this in a browser from another company is anti-competitive. Forcing admins to perform extra work to prevent this from occurring in their ORG is disrespectful. This extension should be considered Mal-Ware and its forced installation is borderline criminal. Microsoft has no right to modify another companies browser just because it happens to be installed on the same computer as Office. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making a few changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
