### ISSUE TITLE
ProPlus activated on way more than 5 computers

### ISSUE THREAD

**Issue by dhoegl** [MicrosoftDocs/OfficeDocs-DeployOffice#56]
One of our customers (corporate E3 license) has activated ProPlus on 10 different computers.
 See attached screenshot.

According to all documentation, the limit is supposed to be 5.
Why is she allowed to do this?

![more_than_10_activations](https://user-images.githubusercontent.com/25856019/41794228-8c2d8962-7613-11e8-839d-d86f8e0d6f9a.PNG)

**Comment by johmarkMSFT** [comment]
Hi @dhoegl, thanks for getting in touch. 
I believe that with a corporate E3 license, Office can be installed by a user on 5 PCs or Macs, 5 tablets (Windows, iPad, and Android), and 5 phones, giving a possible total of 15 devices. You can count 2-in-1 Windows devices, such as the Microsoft Surface Pro, as either a PC or a tablet.
More information can be found here: [https://products.office.com/en-ie/business/office-365-enterprise-e3-business-software](https://products.office.com/en-ie/business/office-365-enterprise-e3-business-software)
