### ISSUE TITLE
Browser hijacking like in the 90s. Are you nuts?

### ISSUE THREAD

**Issue by kgbvax** [MicrosoftDocs/OfficeDocs-DeployOffice#565]
Words fail me. When will MS stop shoving unwanted "features" down our throats?
The Old Microsoft is back it seems. Please don't go through with this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by caspChristian** [comment]
@ItzLevvie dowvote? is it you that build this pile of 💩 or what? (downvote removed, but still would like to know)
