### ISSUE TITLE
DO. NOT. WANT.

### ISSUE THREAD

**Issue by EG-AASI** [MicrosoftDocs/OfficeDocs-DeployOffice#567]
I can't believe I've had to spend time out of my day to put in place countermeasures and automated removal of what is certainly going to be a dumpster fire of an idea. This is absurd.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by thx1200** [comment]
THIS!  I just had to spend 30 minutes downloading the new ADMX templates, copying them up to our forests and deploying a new GPO in all of them just to block this.  This is insanity.

**Comment by jleger88** [comment]
Make matters worse, on our tenant we can't even see any of the policies in Intune to prevent this forced deployment... Administrative Template doesn't have "Don't install extension for Microsoft Search in Bing that makes Bing the default the search engine". But if you're on legacy internal domain you can copy the ADMX template to get the required GPO configured. Also within Intune, there's no option to Exclude Bing within Configure App Suite! Guess you have to manually import your XML like the early Intune days to make sure it's not included in your app push. Really need all areas covered, they missed the boat on modern management! I'm thinking maybe the Admin Template can be somehow manually deployed through ADMX ingestion. Either way, it's a headache to come up with the countermeasures on modern management, wayyyy too much overhead!

**Comment by EG-AASI** [comment]
@jleger88 You definitely have me beat on the scope of what it is going to take to prevent or remove this.

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making a few changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
