### ISSUE TITLE
Retarded bullcrap

### ISSUE THREAD

**Issue by caspChristian** [MicrosoftDocs/OfficeDocs-DeployOffice#573]
So you are saying that Office will now install spyware into a 3:rd parrty application.

1. This is unethical, Bing should be eradicated, not promoted!
2. This is of extremely high privacy consern
3. This might even be illegal!

If this does happen, I will make sure that you will have to pay the price!

> If you decide to deploy Microsoft Search in Bing in your organization, we recommend that you at least send an email to your users to explain the reason behind the upcoming change, the benefits of using Bing to search workplace information, and when they can expect to see the change occur.

Well if I decide to not deploy it, I shouldn't have to do anything, now you are forcing admins all over to MAKE CHANGES to prevent this stupidity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.

**Comment by caspChristian** [comment]
"Since then, we’ve heard from many customers who are excited about the value Microsoft Search provides through Bing and the simplicity of deploying that value through Office 365 ProPlus"

That is pure lies, Pure excueses! And that is not enough! @DHB-MSFT
