### ISSUE TITLE
What is the first thing we do after setting up windows? 

### ISSUE THREAD

**Issue by mgrollejr** [MicrosoftDocs/OfficeDocs-DeployOffice#574]
Well after silencing Cortana and setting up a local user and not using a Microsoft Account?  We install Chrome and set it up as the default browser. Why? Because Edge and Bing suck.  Just one more hoop for admins to jump through. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by lawtonj404** [comment]
Absolute stupidity from Microsoft, this needs to be stopped. As users we have a right of choice, I do not choose bing because I personally prefer another search provider, this is a disgrace and will take weeks to resolve as many clients don’t have group policy.

**Comment by card13** [comment]
I have to laugh on a few levels. The biggest being, this is why MS had to create N editions of Windows, because they tried this with XP and the EU said No Choice = No Sell Here. Why can't MS learn from its mistakes?

**Comment by joveice** [comment]
Don't forget about blocking all the data collection stuff and disabling automatic updates

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
