### ISSUE TITLE
Stop Google Chrome Browser Changes Feb 2020

### ISSUE THREAD

**Issue by lawtonj404** [MicrosoftDocs/OfficeDocs-DeployOffice#577]
Effectively this is a Chrome Browser Hijack will confuse and disappoint my end users and create extra helpdesk calls for my organisation. Please don't implement this change, as a partner it creates huge issues for clients and reflects badly on us and Microsoft.

This needs to be optional via the admin dashboard and not enabled by default.

If this is implemented we will quite happily migrate 3700 office 365 users to GSuite. We will also be cancelling our partnership with immediate affect.

Browser Search is a personal choice and should not be forced. Cortana already offers the same functionality and neither my clients or myself want to see this change implemented.

Bing is outdated, poor quality, frustrating and lacks clarity in results, also seems a bit of a kick in the nuts when you just used the chromium browser to build edge.

I have also written a letter to the European Commission based on the announcement received via email from Microsoft today. I will be actively encouraging others to do the same over the coming days and ask you stop the implementation until proper consultation with users, partners and customers is obtained.

Office 365 is a great product that we have promoted for the last 8 years, but this is a step too far and creates a huge workload to undo especially for smaller business clients without GP deployment.

Further complaints seen on Reddit: https://www.reddit.com/r/sysadmin/comments/es6xp5/office_365_proplus_to_change_chromes_default/

**Comment by lawtonj404** [comment]
How will this be forced on personal devices that users bring into the workplace? This is not going to be suitable for BYOD and nothing in documentation.

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
