### ISSUE TITLE
Junk

### ISSUE THREAD

**Issue by spacklewoof** [MicrosoftDocs/OfficeDocs-DeployOffice#578]
BING cannot even find technical article on support.microsoft.com as good as Google can and you re literally forcing us to switch?  This is such a bad idea on so many levels.  I guess this is the Microsoft we should expect, after windows 7 blank desktops, forced trickery to get people to upgrade from a good OS to a marginal one, and CONSTANT switching of default apps like PDF reader and edge that IS SO TERRIBLE YOU ARE REPLACING IT WITH A CHROME WANNABE!  you don't own these desktops, you don't own chrome, what make you think you have ANY RIGHT WHATSOEVER to make these changes?  Nothing.  You're doing for self-serving reasons only, disregarding the wishes of the people that made you successful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by kslen** [comment]
They want you to drag your ass through a jungle of psuedo-related pages filled with ads, not provide you with the content you're looking for.
