### ISSUE TITLE
It's not April 1st...?

### ISSUE THREAD

**Issue by SysAnon** [MicrosoftDocs/OfficeDocs-DeployOffice#579]
This is not a good idea. Think about the poor helpdesk folks around the world Microsoft! It is browser hijacking plain and simple, as soon as I got the email I started to look for a way to prevent it in our organization to try and prevent a hellish day of running around and resetting browsers and removing extensions. Please do not go through with this plan. It will upset any and every sysadmin I have ever met. This is coming from someone who is a big proponent of your services in so many other ways.

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
