### ISSUE TITLE
German translation wrong

### ISSUE THREAD

**Issue by manoth-msft** [MicrosoftDocs/OfficeDocs-DeployOffice#58]
[Hier Feedback eingeben]

The table listing the different severities for VBA list in en-us "Limited remediation required" and "Significant remediation required". The german version of the table lists "Eingeschränkte Korrektur erforderlich" (limited remediation) twice, but no "significant" equivalent.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a54af1b9-ed71-9aa2-f34a-5d92611b23e8
* Version Independent ID: 933e76d8-97c9-2850-4630-4e19b82d8c5a
* Content: [Verwenden des Readiness Toolkits zum Bewerten der Anwendungskompatibilität von Office 365 ProPlus](https://docs.microsoft.com/de-de/deployoffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro)
* Content Source: [DeployOffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice-pr.de-DE/blob/live-sxs/DeployOffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Thanks for bringing this to our attention. I've forwarded this on to our localization team and they'll investigate and work to get it fixed.

**Comment by DHB-MSFT** [comment]
This issue has now been fixed. Thanks again for bringing this to our attention.
