### ISSUE TITLE
Document missing information on BYOD

### ISSUE THREAD

**Issue by dsnorton** [MicrosoftDocs/OfficeDocs-DeployOffice#582]
The documentation is missing the information on how to disable it in an organization for personal devices not managed by the enterprises heavy weight systems.  Can you please document the method to enable opt-in requirement for those devices not under the control of the organization?

**Comment by lawtonj404** [comment]
This needs to be option in admin panel and not default behaviour.

Browser search engine is a user choice and should not be mandated. It’s our right to choice and no business system is going to take that away.

Looks like we are migrating 1000s of users to GSuite if this change is implemented.

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
