### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by FreeLampie** [MicrosoftDocs/OfficeDocs-DeployOffice#587]
This should be an administrative decision, not forced on admins to now have to explain why this change is happening and so on. Please remove this nobody wants it.

**Comment by jozefizso** [comment]
Greed.

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
