### ISSUE TITLE
Missing Information, Windows 10 Home - Disable Extension.

### ISSUE THREAD

**Issue by lawtonj404** [MicrosoftDocs/OfficeDocs-DeployOffice#588]
Missing information on how to disable in Win 8/10 endpoint running “HOME” SKU.

This is a terrible implementation, this should be an optional element in 365 Admin Centre that is disabled by default.

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
