### ISSUE TITLE
Seriously? Reverse this decision NOW!

### ISSUE THREAD

**Issue by tebbuttresearch** [MicrosoftDocs/OfficeDocs-DeployOffice#592]
This is invasive, the instructions for disabling this are confusing and unnecessarily complicated. Please reconsider this "feature" as it sounds more like a bug.  "...your end users will not be able to change the default search engine" is malware and bad faith. Will we be able to uninstall and then reinstall Chrome without this stupidity automatically applied?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by tebbuttresearch** [comment]
Oh, and what happens when people try running the command
C:\Program Files (x86)\Microsoft\DefaultPackPC\MainBootStrap.exe uninstallAll 
without any quotation marks?
'C:\Program' is not recognized as an internal or external command, operable program or batch file

**Comment by DHB-MSFT** [comment]
@tebbuttresearch -- thanks for catching the error in the command syntax. We'll get the article updated.

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
