### ISSUE TITLE
This update is horse s**t

### ISSUE THREAD

**Issue by tullydwyer** [MicrosoftDocs/OfficeDocs-DeployOffice#595]
![802556b9491e84f42732da0649d5041d](https://user-images.githubusercontent.com/7508115/72950090-071f2a00-3dd6-11ea-9717-7d6998bccef1.jpg)

This update is not ok and we should not have to explain why.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-gb/deployoffice/microsoft-search-bing)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by brendan-sherrin** [comment]
+1
