### ISSUE TITLE
Fantastic, more stuff I have to block, thanks for wasting my time

### ISSUE THREAD

**Issue by taskvalanche** [MicrosoftDocs/OfficeDocs-DeployOffice#596]
Seriously, as soon as I get back to the office tomorrow registry keys are going in place, GPOs are being edited.  I'm blacklisting the extension ID in the Google GPO.  Lets see how many other ways I can lock this out.  Bad, bad, bad idea.  I don't want to be explaining to my users why their search suddenly looks different and is utterly, pathetically useless.  Seriously, Bing couldn't find a fart in a bean eating convention.  It's hopeless.  Forcing people to use it won't improve the situation, it'll just make for frustrated, angry users.  You want to drive traffic to Bing, make it less terrible.  Resorting to sketchy late 90s era shady toolbar pusher level tactics of sneaking in hard changes to peoples settings is just unscrupulous and pretty much outright malicous.

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
