### ISSUE TITLE
Another establishment that blocks Bing here.

### ISSUE THREAD

**Issue by lsmith-sash** [MicrosoftDocs/OfficeDocs-DeployOffice#604]
Did Microsoft learn nothing from the whole browser anti-competition issues with the EU several years ago?

As an educational establishment, we find that Bing does a poor job of filtering content and block it's use across all of our sites.
What is more concerning however, is the fact that you seem to feel it's acceptable to interfere with software outside of your own.

It is a reasonable expectation that you will add to and improve your own products, but not for you to try and alter our deployment of other products.

If you want to continue down this path, it should at least be possible to block the change at an organisational level, we shouldn't have to alter every method of deployment just to disable this unwanted change.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-gb/DeployOffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by RichPN23** [comment]
This is unacceptable. You simply cannot change the behavior of another product by another vendor to promote your own search engine no matter how much a supposed benefit this may be to the user. This needs to be stopped, now or at the very least by OFF by default with the tenant admin able to switch on if they deem of use.

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
