### ISSUE TITLE
WHAT THE ACTUAL FUCK??!

### ISSUE THREAD

**Issue by theMatthes** [MicrosoftDocs/OfficeDocs-DeployOffice#606]
Excuse me what the fuck, what the fuck is this shit you have posted? What the actual fucking fuck is this fucking garbage? You call that a post? You call that a FEATURE? Pathetic. Were you even thinking before you posted that absolute fucking garbage?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
While we appreciate feedback, please remember that comments are subject to the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). Locking this conversation because of inappropriate language.
