### ISSUE TITLE
Bing is now blocked as company wide search engine 

### ISSUE THREAD

**Issue by mslucass** [MicrosoftDocs/OfficeDocs-DeployOffice#608]
GPO as per instruction
installation for new pc's as per instruction
firewall blocked

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
