### ISSUE TITLE
Intune 'Check Box' does not exist

### ISSUE THREAD

**Issue by auzdark** [MicrosoftDocs/OfficeDocs-DeployOffice#609]
This check box does not exist in 'configure app suite'

"Microsoft Intune
If you're deploying Office 365 ProPlus by using Intune, you can clear the Set default search engine to Microsoft Search in Bing check box on the Configure App Suite pane."

**Comment by DHB-MSFT** [comment]
@auzdark  -- We updated the article yesterday afternoon with this information about Intune:

![image](https://user-images.githubusercontent.com/32883970/73001454-586bf100-3db7-11ea-994f-b2ce3af6eff5.png)
