### ISSUE TITLE
ODT downloads full office instead only visio

### ISSUE THREAD

**Issue by elctronnized** [MicrosoftDocs/OfficeDocs-DeployOffice#61]
Is there a possibility to only download Visio instead of the whole office package with odt?
my conf xml:
![image](https://user-images.githubusercontent.com/40791712/42213253-85022b18-7eb8-11e8-8bc1-dccbbe87bcf7.png)

<Configuration>
  <Add OfficeClientEdition="32" >
    <Product ID="
VisioStdXVolume " PIDKEY="NY48V-PPYYH-3F4PX-XJRKJ-W4423 ">
        <Language ID="en-us" />
     </Product>
   </Add>  
</Configuration>

**Comment by DHB-MSFT** [comment]
No, that's not possible. When you download using the ODT, it downloads the files for Office, Project, and Visio together, regardless of what you specify for the product ID. For example, the non-language specific files for Office, Project, and Visio are in the stream-x86.x-none.dat file for a 32-bit download.
