### ISSUE TITLE
Completely unacceptable

### ISSUE THREAD

**Issue by jpjm** [MicrosoftDocs/OfficeDocs-DeployOffice#612]
Office 365 subscriptions represent a large investment for a lot of organisations, this is malware-like behavior. Allow people to test it for themselves and roll it out if they think it's a good idea, maybe even put it in Edge if some product manager is so proud of it that they feel that they have to push this out to people. Changing settings in other browsers is not OK and I expect to see Chrome blocking this extension as soon as you try to deploy it.

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
