### ISSUE TITLE
2002 version?

### ISSUE THREAD

**Issue by Absoblogginlutely** [MicrosoftDocs/OfficeDocs-DeployOffice#615]
I'm assuming this needs to be edited to read the 2020 version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing?fbclid=IwAR2533BRaRXu7o-EEZv67hXp78SdP8JQxJ_m_HyUTwmNlfzUPFxB6QCULLg)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by peterlewis** [comment]
Versioning uses YYMM format, so whilst it might feel like it's harking back to yesteryear, 2002 is correct.
