### ISSUE TITLE
please do not do this

### ISSUE THREAD

**Issue by danielpugh** [MicrosoftDocs/OfficeDocs-DeployOffice#619]
option to do this presented to the user so they can confirm or deny = yes
automatic install = support nightmare/antitrust eu/problem

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
