### ISSUE TITLE
The generic Visio Professional 2016 pidkey listed above stopped working and now continually prompts for activation

### ISSUE THREAD

**Issue by johnso74** [MicrosoftDocs/OfficeDocs-DeployOffice#62]
As we are a MS Partner, we don't have access through the VLSC to obtain an updated C2R-P key.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e6c0641-503d-7959-2afb-839821cc792f
* Version Independent ID: 046c52d9-4fbe-4fe7-0778-5c1d4138f69e
* Content: [Use the Office Deployment Tool to install volume licensed editions of Visio 2016 and Project 2016](https://docs.microsoft.com/en-us/DeployOffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016)
* Content Source: [DeployOffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by msft-bcorob** [comment]
Hi John, if you are an MS Partner, please contact Partner support for a compatible Visio C2R-P key.
