### ISSUE TITLE
This is almost as offensive as removing a Santa's Hat from the Settings icon in VSCode because one person took offense to it

### ISSUE THREAD

**Issue by isaacsanfran** [MicrosoftDocs/OfficeDocs-DeployOffice#622]
No, actually, this is worse.  This will actually impede production for thousands of businesses (including your own paying customers)!  If you feel the need to inconvenience your freeloading customers like how mobile games throw ads everywhere, by all means.  But to sabotage the productivity of people who are giving you money _for the privilege_ to run your software?   This is a new level of insanity, I do declare!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by darthcircuit** [comment]
🎅🎅🎅🎅🎅🎅🎅
