### ISSUE TITLE
Guys, April 1st is still over two months away!!!

### ISSUE THREAD

**Issue by ericxw** [MicrosoftDocs/OfficeDocs-DeployOffice#625]
This is insane. I cannot comprehend who in the right mind decided they had the right to control what happens in other software. This is text book malware behavior.

For the past few years I had be somewhat impressed at Microsoft's activities. This change really shows its horns. Now my guys have to disable this for our whole company and I'll have to help everyone I know to fix. You can't force someone to use what they've tried so hard to avoid for years!

I guess it's time to add Microsoft Office to this list: https://en.wikipedia.org/wiki/Browser_hijacking

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#which-locations-will-receive-microsoft-search-in-bing-with-office-365-proplus)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
