### ISSUE TITLE
Microsoft Has NO Right!

### ISSUE THREAD

**Issue by Dschrepfer** [MicrosoftDocs/OfficeDocs-DeployOffice#629]
I find this a completely repulsive move on Microsoft's part.  We should not have to create a GPO to stop this.  Once again Microsoft does the wrong thing.

I hope they listen, but they won't.

https://odinsiders.uservoice.com/forums/920533-distribution-upgrades-servicing/suggestions/39494872-do-not-force-push-bing-as-the-default-search-engin

**Comment by Dschrepfer** [comment]
If you are an Admin in Office 365, go to the message center and down vote it.

**Comment by ninken** [comment]
It's not your device it's Microsoft device!

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
