### ISSUE TITLE
I consider this to be a criminal offence

### ISSUE THREAD

**Issue by dmartensson** [MicrosoftDocs/OfficeDocs-DeployOffice#630]
I have explicitly installed Firefox and selected a search engine of my preference.

ANY other program that changes this without asking permission is making unauthorized changed to my computer.

That is usually called to be malware.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing?irgwc=1&OCID=AID2000142_aff_7792_1246483&tduid=(ir__nqogtbi6ugkfrmsc0j6eqfyk0e2xljfuprxltoz000)(7792)(1246483)((9094539a906fee27ed177fc8754b90dc)(190946)(2809631)(1.729639)())(9094539a906fee27ed177fc8754b90dc)&irclickid=_nqogtbi6ugkfrmsc0j6eqfyk0e2xljfuprxltoz000#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by ItsBildo** [comment]
Get a lawyer and specifically cite the following:

18 U.S. Code § 1030. Fraud and related activity in connection with computers.

(5)
(A) knowingly causes the transmission of a program, information, code, or command, and as a result of such conduct, intentionally causes damage without authorization, to a protected computer;
(B) intentionally accesses a protected computer without authorization, and as a result of such conduct, recklessly causes damage; or
(C) intentionally accesses a protected computer without authorization, and as a result of such conduct, causes damage and loss.

The term “exceeds authorized access” means to access a computer with authorization and to use such access to obtain or alter information in the computer that the accesser is not entitled so to obtain or alter.
