### ISSUE TITLE
Opposition to this Change

### ISSUE THREAD

**Issue by camxct** [MicrosoftDocs/OfficeDocs-DeployOffice#632]
I would like to vocalize my opposition to this upcoming change. Microsoft does not "own" Google Chrome and you have not been authorized to modify their application in this way.

The modification of *future* installations would not be a problem and perhaps a minor annoyance on the administration side of things (legal would be another), however, force-changing the settings on a User for arbitrary reasons circles the drain of "unlawful," and **is effectively browser hi-jacking**.

**18 U.S. Code § 1030. Fraud and related activity in connection with computers.**

(5)
(A) knowingly causes the transmission of a program, information, code, or command, and as a result of such conduct, intentionally causes damage without authorization, to a protected computer;
(B) **intentionally accesses a protected computer without authorization**, and as a result of such conduct, recklessly causes damage; or
(C) **intentionally accesses a protected computer without authorization**, and as a result of such conduct, causes damage and loss.

The term “**exceeds authorized access**” means to access a computer with authorization and to use such access to obtain or alter information in the computer that the _accesser_ is not entitled so to obtain or alter.

I urge Microsoft to immediately reconsider and ultimately stop this upcoming change.

EDIT: Legal citation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.

**Comment by caspChristian** [comment]
@DHB-MSFT Where is the apology for doing something illegal?
