### ISSUE TITLE
Feature Request: ASK Toolbar Auto-installation

### ISSUE THREAD

**Issue by tinfever** [MicrosoftDocs/OfficeDocs-DeployOffice#633]
Modern productivity has been dramatically reduced with the removal of the ASK toolbar from recent internet browsers. While you are installing Bing and Candy Crush on everything, could you also please automatically install the ASK toolbar to allow us to continue to diversify our leading edge value-added services for our clients?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by netresults-scott** [comment]
Interesting idea. What are your thoughts on having Clippy return - he could crypto the HD and then offer to decrypt if the user kindly installs the Bing bar and demonstrates loyalty to MS by Bing'ing at least 100 times a day.... or else.

**Comment by tinfever** [comment]
That's a pretty good idea. What if... Windows could automatically mine cryptocurrencies by maxing out the CPU in the background, by default, for a 10% discount on Bing rewards! You could even have it automatically configure other computers on the network to mine as well to collect Bing Mining Referral Rewards!

**Comment by netresults-scott** [comment]
If those Bing Mining Referral Rewards can be applied towards airfare to Redmond so I can participate in the soon to be announced 'Pillory the MS Product Manager who greenlit Bing-Chrome', I'm all in!
