### ISSUE TITLE
Enjoy your EU antitrust lawsuit

### ISSUE THREAD

**Issue by towellabs** [MicrosoftDocs/OfficeDocs-DeployOffice#634]
You deserve it and I hope you get burned again like the IE search antitrust lawsuit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by ericxw** [comment]
Looks like they intentionally left out EU for this. I think they specifically made a decision to avoid a lawsuit there. Apparently everywhere else is fair game. Who cares about the law and ethics? Sigh.

This is after changing Windows licensing to prevent running in AWS/GCP.

**Comment by legitosaurus** [comment]
@ericxw That's not true.
>[At this time, the extension will only be installed on devices in the following locations, based on the IP address of the device:](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#which-locations-will-receive-microsoft-search-in-bing-with-office-365-proplus)
Australia
Canada
**France**
**Germany**
India
**United Kingdom** (For a little bit longer)
United States

**Comment by lawtonj404** [comment]
I didn’t realise France Germany and the U.K. were leaving the EU?

**Comment by alrekr** [comment]
> 
> 
> I didn’t realise France Germany and the U.K. were leaving the EU?

The law regarding Brexit was signed by the British Queen yesterday so UK is indeed leaving the EU coming February. 

Just about as bad an idea as changing default search provider in a third-party browser.

**Comment by ItsBildo** [comment]
If I see this change happen on my users, know I WILL submit legal action as this is effectively browser hi-jacking.

18 U.S. Code § 1030. Fraud and related activity in connection with computers.

(5)
(A) knowingly causes the transmission of a program, information, code, or command, and as a result of such conduct, intentionally causes damage without authorization, to a protected computer;
(B) intentionally accesses a protected computer without authorization, and as a result of such conduct, recklessly causes damage; or
(C) intentionally accesses a protected computer without authorization, and as a result of such conduct, causes damage and loss.

The term “exceeds authorized access” means to access a computer with authorization and to use such access to obtain or alter information in the computer that the accesser is not entitled so to obtain or alter.

I will get lawyers involved.

**Comment by ericxw** [comment]
> @ericxw That's not true.
> 
> > [At this time, the extension will only be installed on devices in the following locations, based on the IP address of the device:](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#which-locations-will-receive-microsoft-search-in-bing-with-office-365-proplus)
> > Australia
> > Canada
> > **France**
> > **Germany**
> > India
> > **United Kingdom** (For a little bit longer)
> > United States

My mistake. I think I was just too angry at this decision and glanced through it.

**Comment by MattWeatherford** [comment]
I note that Microsoft adding this browser hijack puts Office 365 proplus in the same list/category on Wikipedia as "Coupon Server"

**Comment by towellabs** [comment]
@ItzLevvie Such a coward downvoting instead of posting.
