### ISSUE TITLE
Why not stop at installing Bing in Chrome?  I want it installed on ALL my apps!

### ISSUE THREAD

**Issue by computerdan** [MicrosoftDocs/OfficeDocs-DeployOffice#636]
Why not stop at installing Bing on Chrome?  I want it installed on ALL my apps as default source-of-all-knowledge! /s ;)

**Comment by seagull** [comment]
I want Bing installed directly into my eyeballs so I never have to read my bills again

**Comment by NiryaAestus** [comment]
Install Bing in the Kitchen Sink please.
https://www-archive.mozilla.org/docs/web-developer/samples/kitchensink.xml
