### ISSUE TITLE
Sending the Wrong Message: Adoption, not Assimilation

### ISSUE THREAD

**Issue by marmstrong94** [MicrosoftDocs/OfficeDocs-DeployOffice#637]
Throw my hat in the ring of people that thinks this is a poor decision on a number of levels. The maximum I find acceptable is simply adding the extension without changing the default search engine and the method by which it can be changed--though I think that's still shady, it at least doesn't forcedly change the behavior of your users' browsers. No one is remotely interested in having their browser changed in any way. They have had it set that way for a reason and the most you can do is advertise that Bing includes MS search which has the capability to drive value. It is not yours to push people to see that value. I get it, I understand the value in MS Search, but this is much much too far and should be changed. Any focus group or survey could have told you that this was not a good idea. Even MVPs are stating that this is a poor choice.

I've been more positive about the trajectory of Microsoft in recent years, but this seems to reveal some sickly familiar attitudes to encroach in places that are not theirs to touch. It makes me think that the positive things I've seen are only a façade to the same old Microsoft. And it's quite ironic to me that there has been so much talk of adoption of things that have value, like Teams or even Bing Search, but this isn't adoption, this is force-feeding.

I look forward to the backpedal on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by ninken** [comment]
Did Steve Ballmer become CEO again?

**Comment by lawtonj404** [comment]
Adoption needs choice, when you say no you mean no...

I think MSFT need to watch the video about consent ...

**Comment by ClaraPotato** [comment]
https://www.youtube.com/watch?v=oQbei5JGiT8

This is very relevant here.

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
