### ISSUE TITLE
Don't resort to malware

### ISSUE THREAD

**Issue by mscott5861** [MicrosoftDocs/OfficeDocs-DeployOffice#639]
I hope Microsoft will reconsider its tone-deaf and ill-advised plan to bundle malware with Office365 ProPlus, beginning in February.

Your reputation has made some hard-won gains among the tech community over the past several years. This will be an extremely fast and effective way to erase them.

**Comment by taskvalanche** [comment]
Seriously.  How hard would it have been to set up the back end stuff and say "okay, if you want to use this, push out this extension, it's available in the app store!"  If they are assuming we have GPO support and all the deployment tools to block this extension, we can use those same tools just as easily to distribute the extension if we so choose.  The fact they are forcing it on and making us jump through those hoops to turn it off really ruins the way the entire thing is viewed from "a new enhanced search for your business" to "another way to prop up your justifiably unloved search engine."

Microsoft had really climbed in how they are perceived in the industry and it took quite a while and a lot of positive moves to do that, things like this can just wipe it out in an instant.

**Comment by scqless** [comment]
Has M$ even improved how they're perceived by customers at all? Like yeah they've improved collaboration with open-source communities and all, but they've kept treating their paying customers like dirt, from the home users to the enterprise. I used to be a Windows guy but you can't even use Windows 10 any more without it nagging you to sign into a MS account for everything... In fact, as I've recently discovered, you can't even create a local account in Windows 10 Home OOBE unless you've disconnected yourself from the network. Total bull.

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.

**Comment by scqless** [comment]
Great, but that customer feedback shouldn't have needed to be said to begin with @DHB-MSFT. If Microsoft valued their customers, respect for their computing needs should come naturally.

Recent trends show Microsoft values short-term goals over customer trust, and that's unfortunate.
