### ISSUE TITLE
Search extension shouldn't be installed automatically

### ISSUE THREAD

**Issue by xfix** [MicrosoftDocs/OfficeDocs-DeployOffice#640]
The search extension is installed automatically. This is an issue, as this means the extension will not work if Chrome gets modified to automatically remove that extension (side-loading extensions is not supported by Chrome, see: https://blog.chromium.org/2013/11/protecting-windows-users-from-malicious.html).

If somebody intentionally installs the extension, they will lose access to the extension when Chrome gets updated to automatically remove the extension as Chrome will have no idea whether somebody did install extension intentionally or not.

This means that even businesses that want to install the Bing extension won't be able to.

Please don't apply extension automatically, this is very likely to break the extensions for companies that actually want to use it.

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
