### ISSUE TITLE
Changing Search to Bing Automatically in Office Pro Plus, and automatic installation of Chome Extension.

### ISSUE THREAD

**Issue by ccsjnw** [MicrosoftDocs/OfficeDocs-DeployOffice#642]
[Enter feedback here]

Microsoft, you are crazy to even consider this. What are your executives thinking?
The backlash from your customers will be deafening. These are *not* your choices to make and change on the fly! Your tactics are very underhand and it's really no better than browser hi-jacking.

If you want a reason for your business customers to jump-ship away from Office - this is it...
It's madness. Don't do it.

James.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by legitosaurus** [comment]
> Away from office?

... to what?

**Comment by ninken** [comment]
Lets see we have... 
FreeOffice
LibreOffice
WPS Office
iWork
Calira
OfficeSuite
Polaris Office
OnlyOffice
Word Perfect
Apache OpenOffice

**Comment by legitosaurus** [comment]
I see you can copy and paste from TechRadar.

How many of those are feasible to deploy to a large company?
LibreOffice is plagued by compatibility issues.
iWork is Mac only.
Calligra cannot edit DOCX and DOX formats.
WPS Office & Polaris Office has ads and no pricing for ad-free version.
OnlyOffice appears to have a lack of documentation and support.
WordPerfect ..was popular in the 80s - DATED.
Apache OpenOffice cannot save DOCX files and lacks advanced features.

**Comment by NoneRain** [comment]
I don't think it's a big deal at all.
Look, most users won't even notice the difference if Bing become the default search engine. Other than that, you can simply remove the extension, or change the default search engine on your own.
As this version of the 365 is aimed for enterprises, adms can simply block the installation from GPO. 
No one is going to "jump-ship" Office 365 Pro Plus....

**Comment by ninken** [comment]
@legitosaurus legitosaurus
You are correct I can copy and paste the free stuff. However you made it sound like you have no options at all.  You are right Microsoft will fight to the death when it comes to it's office products. Hence why would they do something sooo entirely stupid, and think that they have the right to change our PC settings to Bing.  Yahoo/Ask did this, and no one still uses them, this ploy did not benefit them, or its users. 

As far a my fast copy and paste, I've used WPS Premium at Home, it works very well with no ads. 
Never have a issue with it. 

As far as paid commercial office here are real alternatives. Granted It lacks on the outlook side of things. 
WPS Office Premium
OnlyOffice
Softmaker Office Pro 

If you love Bing good for you, but think of someone came in and changed your Bing to something else. It does not take a genius to say I would not want that behavior.

**Comment by Xeyk** [comment]
@legitosaurus 

> OnlyOffice appears to have a lack of documentation and support.

Ok, I think you pulled that one out of your rear. It's actually one of the best alternatives listed, and with proper Nextcloud integration, can even mimic some features such as collaborative document editing. Documentation is extensive and there are paid versions where you get support from the company.

I get what you were trying to do, but you grasped at non-existent straws in regards to OnlyOffice, which is not fair to that company.

**Comment by concerned-users** [comment]
many people successfully use Google Docs as an alternative to MS Office in an enterprise environment
