### ISSUE TITLE
I've reported the author to Github

### ISSUE THREAD

**Issue by ninken** [MicrosoftDocs/OfficeDocs-DeployOffice#643]
Daniel H. Brown, 

Has posted this article, then comments from: 
https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing

Daniel has embed Office 365 to auto install a Chrome Extension "Bing" into Office 365 Pro Plus users without consent. This is considered malware when you buy a product and it download other unwanted software. This is a major high crime, criminal offence, against all public opinions and is very much illegal act.
I'm highly considering calling legal professionals and criminal investigators on this topic immediately!

**Comment by RAJU2529** [comment]
Author is said clearly 

If you don't want the extension installed, follow these steps. Also, if Bing is already the default search engine, the extension doesn't get installed.

Even after the extension is installed, your users can easily stop using Bing as the default search engine on their own by using a simple On/Off toggle or you can remove the extension.

**Comment by Xeyk** [comment]
@RAJU2529 nothing you just said exempts this from being considered malware, because it is malware.

**Comment by 4oo4** [comment]
> If you don't want the extension installed, follow these steps. Also, if Bing is already the default search engine, the extension doesn't get installed.

So, resistance is futile, essentially?
