### ISSUE TITLE
This is the worst possible way to deploy "software", and the best way to lose customer trust,

### ISSUE THREAD

**Issue by cwmoriarty** [MicrosoftDocs/OfficeDocs-DeployOffice#644]
We're wasting our time chasing/blocking this.

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
