### ISSUE TITLE
Clarify targeted OS

### ISSUE THREAD

**Issue by hambranch** [MicrosoftDocs/OfficeDocs-DeployOffice#645]
Please clarify if this will only apply to Windows or if this extension will also be installed by Office 365 ProPlus for macOS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by ddussell** [comment]
This needs to be answered. What steps do I need to take to avoid this for our Mac Users!

**Comment by DHB-MSFT** [comment]
There are no plans at this time to include Office for Mac. We'll update the article to make that clearer.
