### ISSUE TITLE
Horrible idea

### ISSUE THREAD

**Issue by seagull** [MicrosoftDocs/OfficeDocs-DeployOffice#646]
Do not try to mess with people's default search engines. Bing is failing because it's terrible, not because you haven't been sneaky enough.
If you want Bing to stand a chance against Google, make it a better product -- how about fixing it to accept quotation marks in search queries, for example -- instead of being underhanded about it.

Whoever thought this up should be fired.

**Comment by Zorlin** [comment]
Absolutely agreed. This is a ridiculous change.

**Comment by seanvandermolen** [comment]
Yup, just wrote this same message on their FB wall.
