### ISSUE TITLE
Adware

### ISSUE THREAD

**Issue by cedwards-telis** [MicrosoftDocs/OfficeDocs-DeployOffice#647]
So basically what you are saying is that now O365 is adware?  I don't want my users (or any users) to open a web browser and see a story about Harry and Meghan (as it is at the moment) or bloody Kim Kardashian.

WTAF are you thinking?  I can see the antitrust lawyers rubbing their hands.  Bonkers decision.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by technaustin** [comment]
I can't believe this? Someone told me about this, and I was like no, that would be the definition of malware. NO way Microsoft is going through with this? So many customers I push to Microsoft because I thought they weren't tyrants. We will have some major issues with MS if they go through with this.

**Comment by jozefizso** [comment]
Yes, it’s a paid for adware. What a great marketing strategy.

**Comment by scqless** [comment]
LOL @ Microsoft shill @ItzLevvie downvoting all the issues.

**Comment by scqless** [comment]
@ItzLevvie that felt good. One more time?

**Comment by scqless** [comment]
@ItzLevvie Thanks! :heart_eyes:

**Comment by Thor-HoG** [comment]
What's sad is that the internal employee @ItzLevvie, in his effort to shamelessly defend Microsoft, had simply turned GitHub into his own personal YouTube channel by going through and spamming every single comment with a downvote.  The irony, clearly, is that Microsoft and their employees - even while trying to defend Microsoft - simply turn everything into another Google product.  So @ItzLevvie, rather than wasting your time downvoting what the CUSTOMER says in your capacity as a MSFT employee, how about concentrating on making the product better on its own so that you don't have to turn Office into a malware engine?  That would be a far better use of your time, AND would actually benefit the customer and not make Microsoft look even more immature than you already do.

**Comment by 4oo4** [comment]
@Thor-HoG I'm reporting them for abuse. These were just the ones I saw from 5 minutes of searching.

https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/647
https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/660
https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/658
https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/521
https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/655
https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/652
https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/650
https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/646
https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/649
https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/648
https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/647
https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/646
https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/644
https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/641
https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/640

**Comment by scqless** [comment]
What's even more sad is I was under the impression that the folks at Microsoft took pride in their work and that things like this were just pushed down from the top. But him going through and taking the time to downvote everything speaks to the contrary, that at least certain employees legitimately think they're somehow doing the world a favor here.

Oh, and on another note, I thought it would be fun to take a page out of ItzLevvie's book and just downvote all his comments on GitHub issues... So I went to Google (not Bing :smiley:), typed in `site:github.com inurl:issues "ItzLevvie"`, and downvoted issues from 20 pages worth of Google search results.

Worth it? Not at all. Petty? Absolutely. But I thought I'd have some fun giving him a taste of his own medicine. :smiley:

**Comment by technaustin** [comment]
Lol. Honestly though, we can’t be like them. We need people who will reason, without getting emotional. It’s ok that he disagrees, even if he’s being cultish. Hopefully those who prefer freedom will show their support. There’s nothing wrong with liking bing more, the problem comes with it being forced upon users. I’ve already enabled GPOs on one client to block the upcoming feature. We shouldn’t have to do this.

**Comment by Thor-HoG** [comment]
It's not just that it is being "forced" onto users.  It is the method by which MSFT chooses to do so.  If they want to make Bing the default (and only) service for in-app "intelligence" services, that is their prerogative.  But downloading a separate app written for a 3rd party application (both Chrome and Firefox), installing that plugin, and then changing the default options for those completely separate, 3rd party applications isn't just "wrong," it's a violation of federal law.  

What really makes this particularly insidious is that MSFT **knows what they are doing is wrong.**  They just don't care.  Our marketing department uses specific, dedicated Google tools as part of their job.  Not only will this break those tools, it could (and will) have direct financial repercussions for my team.  Sure, I've also added the GPO setting with the updated ADMX files.  But I've already notified the MSFT emergency response team about this, and I can tell you in utter seriousness that if MSFT implements this change, the moment it happens I will be calling the FBI and reporting them for violating federal law, irrespective of how they've managed to sneak it into the EULA.  

For MSFT to know this is wrong, and illegal, but to proceed with this action anyway shows a MUCH MUCH bigger problem than the act in itself.  It shows that any future mention of what "the customer wants" is nothing but a willful, purposeful, and premeditated lie.  There will be dire consequences for this action.

**Comment by ninken** [comment]
ItzLevvie is Deranged and wearing his Windows XP t-shirt on his twitter page. He probably the one who spammed Microsoft to adding the Bing by default.

**Comment by scqless** [comment]
I wouldn't mind an XP shirt... it's the second to last good release of Windows before MS turned it into a mobile app store data mining OS filled with dark patterns trying to get you to sign into a MS account.

**Comment by dfinnema** [comment]
Looks like this might the Chrome Extension they will install:
https://chrome.google.com/webstore/detail/bing-search-engine/aangdklamdiddalhpaidkchnpifidmhl

**Comment by Thor-HoG** [comment]
What makes this fiasco even worse is that MSFT customers are forced to uncover alternatives on their own, and every single one of the posts here have gone completely ignored, other than ItzLevvie trolling downvotes (who is still at it).  They'll answer questions about GPO vs ODT precedence immediately, but not a single response has been made giving any indication of disposition or if our voices here even make a difference.  No feedback, no guidance, nothing whatsoever other than an employee trolling responses. What's worse is that they don't have the presence of mind to even consider providing resources supporting the decision.  Not so much as a single link for "How this benefits you" or a FAQ addressing all the concerns customers have.  It makes the entire Office team look incompetent, and even the moderators and MSFT employee-contributors look amateur.  The best MSFT has been able to do is have ItzLevvie as their mascot.

**Comment by cedwards-telis** [comment]
Perhaps they use the down vote from ItzLevvie to mark the issue as "will not be addressed"?

**Comment by Thor-HoG** [comment]
Perhaps.  If the team considers the use of the Office 365 customer update process a mechanism by which to distribute browser-hijacking malware, I wouldn't be entirely surprised that they consider an employee's personal GitHub downvote to be the preferred method of communicating further design changes.

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.

**Comment by scqless** [comment]
@ItzLevvie looks like you misclicked when giving someone an upvote earlier. Just thought you'd like to know. :)
