### ISSUE TITLE
SCCM support for RemoveMSI

### ISSUE THREAD

**Issue by rasldasl** [MicrosoftDocs/OfficeDocs-DeployOffice#65]
I'm creating O365 installs directly in SCCM, not using Office Deployment Tool. Is this functionality supported? Can I edit an existing xml or will the bits needed for RemoveMSI to function not be there? (assuming the other two requirements are met)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d5595cb-3513-fca5-be7c-ec7652c73115
* Version Independent ID: 6f6f02e0-10a9-dbac-7747-a5dc5f395a35
* Content: [Remove existing MSI versions of Office when upgrading to Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/upgrade-from-msi-version)
* Content Source: [DeployOffice/upgrade-from-msi-version.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/upgrade-from-msi-version.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by chhopkin** [comment]
Currently SCCM does not expose this new option but we are working on an update that will allow this.  In the meantime you can edit the XML manually once you have created the Application, adding the necessary XML to enable the new Remove MSI behavior.  As long as you have the latest version of the ODT and you are installing from the Monthly or Semi-Annual (Targeted) channels as referenced in the RemoveMSI requirements section this will work.

**Comment by rasldasl** [comment]
This did work pretty well (edited XML after application was created in SCCM). One thing I noticed is that the prompt to save your work says the open apps will be closed but they are not actually closed. After reboot they are gone but until reboot they stay open. 

I also have a dilemma with Project Pro - some users have multiple versions. I want to remove all but 2013. If I add the line  <IgnoreProduct ID="PrjPro" /> I'm assuming it will leave multiple MSI versions. If I use <RemoveMSI All="True" /> I can then reinstall Project Pro 2013 MSI but I'm concerned the next upgrade will remove it.

**Comment by rasldasl** [comment]
Never mind the bit about Project Pro. I let our MSI install of Pro 2013 be skipped but the MSI cleanup removed a SOAP component. I had to run a repair on 2013 MSI and restart. Given that, I'm going to try replacing with 2016 volume license and let RemoveMSI do all.

**Comment by MarkGig** [comment]
<RemoveMSI All="True" /> uninstall anything and prompt me the error Couldn't install Error Code 0-1008 (0)
here is my xml

<Configuration>
  <Add OfficeClientEdition="64" Channel="Monthly">
    <Product ID="O365ProPlusRetail">
      <Language ID="fr-fr" />
      <Language ID="MatchPreviousMSI" />
    </Product>
    <Product ID="VisioProRetail">
      <Language ID="fr-fr" />
    </Product>
  </Add>
  <RemoveMSI All="True" />

  

  

  

  

</Configuration>

**Comment by RAJU2529** [comment]
use office 2016 , it's good.
2016 does not have msi,  Latest version have Click 2 Run  edition.
