### ISSUE TITLE
Add redirect from SharePoint to Google drive

### ISSUE THREAD

**Issue by jasonnerothin** [MicrosoftDocs/OfficeDocs-DeployOffice#651]
This is a really great tool you are providing! 

It would be great if we had the ability to push user traffic from user's chosen software to the software that we want them to use, instead!

Just think of the possibilities!

**Comment by jasonnerothin** [comment]
Teams -> Slack
Word -> Sheets
Edge -> Firefox
Worpad -> SublimeText

**Comment by scqless** [comment]
My favorite part is this:

> You don’t need to wait for the extension to be installed along with Office 365 ProPlus to make Bing the default search engine on devices in your organization

Microsoft are so full of themselves if they think that is a question anybody is asking.

(Impending downvote from ItzLevvie in three... two... one...)

**Comment by scqless** [comment]
@ItzLevvie you're running late... are you OK?

**Comment by scqless** [comment]
@ItzLevvie thank God you're alright! I was starting to get worried...
