### ISSUE TITLE
Now playing: "Nine Inch Nails - I Do Not Want This"

### ISSUE THREAD

**Issue by jfcantu** [MicrosoftDocs/OfficeDocs-DeployOffice#652]
Using an existing near-monopoly to force people into using another MS product.

Isn't this exactly what led to the antitrust case in 1998?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by ninken** [comment]
I bet Microsoft is play Nine Inch Nails "Down it in"

Kinda like a cloud, I was up, way up in the sky
And I was feeling some feelings you wouldn't believe
Sometimes I don't believe them myself
And I decided I was never coming down
Just then, a tiny little dot caught my eye
It was just about too small to see.
It was **Bing** in Office you see!
