### ISSUE TITLE
This is beyond absurd, completely narcissistic, and an unwanted invasive change no one asked for.

### ISSUE THREAD

**Issue by ItsBildo** [MicrosoftDocs/OfficeDocs-DeployOffice#654]
I specifically created an account just to highlight how insanely narcissistic this is, and how Microsoft gives ZERO FUCKS about the consumer. Fuck you Microsoft for thinking this is what people want. There are REASONS people dont use your shitty Bing service - it fucking sucks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by ItsBildo** [comment]
If I see this change happen on my users, know I WILL submit legal action as this is effectively browser hi-jacking.

18 U.S. Code § 1030. Fraud and related activity in connection with computers.

(5)
(A) knowingly causes the transmission of a program, information, code, or command, and as a result of such conduct, intentionally causes damage without authorization, to a protected computer;
(B) intentionally accesses a protected computer without authorization, and as a result of such conduct, recklessly causes damage; or
(C) intentionally accesses a protected computer without authorization, and as a result of such conduct, causes damage and loss.

The term “exceeds authorized access” means to access a computer with authorization and to use such access to obtain or alter information in the computer that the accesser is not entitled so to obtain or alter.

I will get lawyers involved.

**Comment by DHB-MSFT** [comment]
Comments are subject to the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). Locking this conversation because of inappropriate language.
