### ISSUE TITLE
BrowserModifier Malware Classification

### ISSUE THREAD

**Issue by seangibbz** [MicrosoftDocs/OfficeDocs-DeployOffice#658]
This behaviour would constitute Malware/Adware of the *BrowserModifier* variety.

This is emphasized by [Microsoft's own security documentation](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/criteria).

> You must be able to start, stop, or otherwise revoke authorization given to software. Software should obtain your consent before installing, and it must provide a clear and straightforward way for you to install, uninstall, or disable it.

This browser behaviour should, if implemented at all, be explicitly presented as an **option** (i.e. checkbox) during the Office 365 installation / update procedure.

To not do so would not only go against Microsoft's own Malware guidelines, but could also trigger a response by security protocols implemented by either Google, or by third-party anti-malware tools.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by caspChristian** [comment]
@itzLevvie downvote? why? This is the truth, and no one in their right mind would think that what Microsoft is doing is any thing other than a browser hijack, also everyone knows that is a bad thing!

**Comment by Thor-HoG** [comment]
@ItzLevvie has been consistently downvoting any negative feedback with troll-like persistence.  The user clearly has no concept of security, and should be ignored; particularly in the absence of any actual justification for downvoting.

**Comment by caspChristian** [comment]
@Thor-HoG indeed, seems to be a troll, he did downvote everything at first, then removed the downvotes, and now started again, and are also responding to PRs etc, which raised the possibility of being an MS employee. And if that is the case I would like to know ;)

**Comment by Thor-HoG** [comment]
Seems like internal MSFT for sure, particularly given these references to MS-Internal and MSFT's "dogwood" site (an internal dev testing resource for MSFT employees):

https://gitmemory.com/ItzLevvie/dogfood-msinternal

https://webcache.googleusercontent.com/search?q=cache:aXPcvorGtUgJ:https://raw.githubusercontent.com/ItzLevvie/Office16/master/defconfig+&cd=21&hl=en&ct=clnk&gl=us&client=safari

**Comment by scqless** [comment]
And he has a Twitter that does an awful lot of retweeting Microsoft posts... 😃 Definitely someone internal or close to MS.

**Comment by 4oo4** [comment]
If they keep doing this, maybe we can report them according to Microsoft's Open Source Code of Conduct? I know some of the issues filed here go against it too, but I think their conduct also clearly goes against the "Understand differences" point here. That is, automatically downvoting people critical of MSFT instead of trying to discuss in issues like this one where people are actually trying to be constructively critical in explaining why this is a bad idea. Normally someone doing this isn't a big deal, but it becomes one since Microsoft owns Github now this reeks of them abusing this ownership and shutting down legitimate community discussion.

https://opensource.microsoft.com/codeofconduct/
