### ISSUE TITLE
New option

### ISSUE THREAD

**Issue by iDolmatov** [MicrosoftDocs/OfficeDocs-DeployOffice#66]
/customize in 16.0.10321.33602

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66127c02-c2dc-f6d1-6e83-a6d2b1166731
* Version Independent ID: 27635315-22db-d136-f07e-5169f6207b50
* Content: [Overview of the Office Deployment Tool](https://docs.microsoft.com/en-us/deployoffice/overview-of-the-office-2016-deployment-tool)
* Content Source: [DeployOffice/overview-of-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by DHB-MSFT** [comment]
Information about /customize has been added to the article. See the [Apply application settings to an existing installation of Office 365 ProPlus
](https://docs.microsoft.com/deployoffice/overview-of-the-office-2016-deployment-tool#apply-application-settings-to-an-existing-installation-of-office-365-proplus) section.
