### ISSUE TITLE
Google access (gmail Via outlook) 

### ISSUE THREAD

**Issue by HeartbliT** [MicrosoftDocs/OfficeDocs-DeployOffice#662]
Hi my Google account is connected with my outlook and is available  only thru outlook (email)
Google Password I'm don't have access Any attempt recover pass. Via Google not Working
My Q is:
Existing any way to restore present account Via outlook futures

**Comment by DHB-MSFT** [comment]
@HeartbliT -- We recommend that you contact [Microsoft Support](https://support.microsoft.com/contactus) or post your question to the [Answers forum](https://answers.microsoft.com/).
