### ISSUE TITLE
 Registry file to exclude the extension for Microsoft Search in Bing from being installed on Google Chrome 

### ISSUE THREAD

**Issue by Underdoge** [MicrosoftDocs/OfficeDocs-DeployOffice#663]
You can get it [here](https://gist.github.com/Underdoge/e9341b3efd87e9929e405df20294cbe1). Enjoy!

**Comment by caspChristian** [comment]
```regf
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\office\16.0\common\officeupdate]
"preventbinginstall"=dword:00000001
```
Same as documented in #563

or as simple command: `reg add HKLM\SOFTWARE\Policies\Microsoft\office\16.0\common\officeupdate /v preventbinginstall /t REG_DWORD /d 1 /f`

**Comment by Underdoge** [comment]
Duplicate
