### ISSUE TITLE
Changing users from one channel to another via SCCM?

### ISSUE THREAD

**Issue by rejohnson76** [MicrosoftDocs/OfficeDocs-DeployOffice#666]
I'm not clear from reading the documentation on how we move a user to and from the targeted channel after they have O365 installed.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed5f04ea-0285-19f0-6c28-ed2b53ce83de
* Version Independent ID: a4630f18-7c9d-6a66-58b7-67f074001a79
* Content: [Deploy Office 365 ProPlus with Microsoft Endpoint Configuration Manager](https://docs.microsoft.com/en-us/deployoffice/deploy-office-365-proplus-with-configuration-manager?source=docs#feedback)
* Content Source: [DeployOffice/deploy-office-365-proplus-with-configuration-manager.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-office-365-proplus-with-configuration-manager.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by davguent** [comment]
@rejohnson76 Office is a machine based installation so you can only change channel of Office for the machine...  can't change channel per User only for the machine itself.  Couple of references which may help:

Change the Office 365 ProPlus update channel for devices in your organization
https://docs.microsoft.com/en-us/deployoffice/change-update-channels

How to manage Office 365 ProPlus Channels for IT Pros
https://techcommunity.microsoft.com/t5/office-365-blog/how-to-manage-office-365-proplus-channels-for-it-pros/ba-p/795813
