### ISSUE TITLE
Subscription and Volume licensing

### ISSUE THREAD

**Issue by Upendra365** [MicrosoftDocs/OfficeDocs-DeployOffice#667]
We are using O365 Click-to-Run version for Office deployment and activating it based on the subscription in O365 Portal. However, we also have to deploy Project and Visio Pro 2019 Click-to-Run (Volume Licensed). Please guide on how to configure XML while packaging O365 and Project/Visio. Also, what would be the PIDKEY and how to get it.
Activation of previous version of Office, Project & Visio 2013 are done via KMS. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f83d98-4309-f494-9ce3-ce3d818edd50
* Version Independent ID: c7fede47-c25e-5ca9-5ad5-55f602ed2b2c
* Content: [Activate volume licensed versions of Office by using KMS](https://docs.microsoft.com/en-us/deployoffice/vlactivation/activate-office-by-using-kms?toc=%2Fdeployoffice%2Foffice2019%2Ftoc.json#feedback)
* Content Source: [DeployOffice/vlactivation/activate-office-by-using-kms.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/vlactivation/activate-office-by-using-kms.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@Upendra365 -- We recommend that you use the [Office Customization Tool](https://docs.microsoft.com/DeployOffice/overview-of-the-office-customization-tool-for-click-to-run) to build your xml file. It will allow you to combine a subscription version of Office with volume licensed versions of Project & Visio 2019. 

If you're going to use KMS to activate your volume licensed versions of Project & Visio 2019, you don't need a PIDKEY. The PIDKEY is only needed if you're doing MAK activation.

**Comment by Upendra365** [comment]
@DHB-MSFT Thank you for the prompt response Daniel.
We have the requirement to deploy Office (to all computers), Visio and Project (to selected users) separately. So, we need to create 3 different packages.
We have already created the Office 365 CTR package for subscription version using ODT.
Is there a different way of creating Project and Visio Pro 2019 CTR packages to work with existing KMS without needing to mention PIDKEY or MAK in xml file.

**Comment by DHB-MSFT** [comment]
@Upendra365 -- for volume licensed versions of 2019, there's no need to specify a PIDKEY in the xml. (You can remove it, if the Office Customization Tool adds it.) PIDKEY is only needed for MAK activation. Just deploy Visio or Project using your xml file, and if KMS is correctly configured, the Project/Visio install should get activated automatically.  

Also, in your xml file, don't include the channel name. The Project/Visio install will then match the channel for your existing Office 365 install.

**Comment by Upendra365** [comment]
@DHB-MSFT Thank you so much for the clarification. Will configure accordingly and keep you posted :)
