### ISSUE TITLE
Office Customization Tool

### ISSUE THREAD

**Issue by danbu** [MicrosoftDocs/OfficeDocs-DeployOffice#672]
Can these settings be set in the using the Office Customization Tool when deploying Office 365?  There is the setting "Turn on privacy settings in Office Telemetry Agent" in application preferences but this appears to be an out dated setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef4debee-6a1e-53c7-7bec-2dbd208f4f2d
* Version Independent ID: b93ad6a2-0976-6f5f-7aae-1756079bdc1d
* Content: [Use policy settings to manage privacy controls for Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/privacy/manage-privacy-controls)
* Content Source: [DeployOffice/privacy/manage-privacy-controls.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/manage-privacy-controls.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@danbu -- Those settings aren't available in the [Office Customization Tool](https://docs.microsoft.com/DeployOffice/overview-of-the-office-customization-tool-for-click-to-run) but they are available in the [Office cloud policy service](https://docs.microsoft.com/DeployOffice/overview-office-cloud-policy-service).

As for _Turn on privacy settings in Office Telemetry Agent_, that setting is related to a [feature of Office Telemetry Dashboard](https://docs.microsoft.com/en-us/deployoffice/compat/manage-the-privacy-of-data-monitored-by-telemetry-in-office) and is not related to these privacy settings.
