### ISSUE TITLE
Conflicting info in linked documents. 

### ISSUE THREAD

**Issue by hibble** [MicrosoftDocs/OfficeDocs-DeployOffice#673]
Page should clarify if home users’ personal computers in our Tennent will be affected? 
This page states the change affects Office 365 ProPlus which implies all installs of Office 365 ProPlus 2002 which would include users who install proplus on personal non domain joined devices. However, in the Microsoft search for Bing adoption kit link on this page https://go.microsoft.com/fwlink/p/?LinkID=2114710 it states "This change will only impact computers that are managed by the company and connected to the company domain, &lt;DOMAIN/&gt;.  It won't affect your personal computers or any mobile devices you use."
So, the question is dose this affect all installs of office 365 ProPlus or just Office 365 ProPlus on domain joined computers?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
