### ISSUE TITLE
Does disabling Microsoft Search stop the deployment of the browser add in?

### ISSUE THREAD

**Issue by DaveClarkey** [MicrosoftDocs/OfficeDocs-DeployOffice#676]
If Microsoft Search is disabled at https://admin.microsoft.com/Adminportal/Home#/MicrosoftSearch -&gt; Set up, does the add in still deploy as part of the Office 365 Pro Plus install. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by lawtonj404** [comment]
Nope - Microsoft = greedy piglets with no respect for people’s choice

**Comment by Thor-HoG** [comment]
Yes, @DHB-MSFT is happy to lock threads and answer other questions unrelated to this "feature," but does nothing about a MSFT employee spamming the entire tree with downvotes, nor do they bother even addressing the concerns voiced by so many people.  Not even a "we hear you, and he's  a contact to discuss this" response.

**Comment by DHB-MSFT** [comment]
Based on customer feedback, we're making some changes to the plan to roll out the extension for Microsoft Search in Bing. For information about the changes, [read this announcement](https://techcommunity.microsoft.com/t5/office-365-blog/update-to-microsoft-search-in-bing-through-office-365-proplus/ba-p/1161030). This article will be updated when more details are available.
