### ISSUE TITLE
Product Brand should be translate to Loc String

### ISSUE THREAD

**Issue by qgvc4** [MicrosoftDocs/OfficeDocs-DeployOffice#678]
Microsoft Search in Bing is a product name, and it shouldn't be translated to "Micorosft 必应搜索" in Chinese. We should keep the brand name in English before there is a brand name in other languages.

Repro URL: https://docs.microsoft.com/zh-cn/deployoffice/microsoft-search-bing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Taking offline with our content localization team.

**Comment by TinaMcN** [comment]
This is caused by an issue with the machine translation which "overtranslates" product names sometimes.   I uplifted the topic to human translation, it should take 2-3 days to complete translation.
