### ISSUE TITLE
Action Pack Licensing - Which Mode? O356 or VLK

### ISSUE THREAD

**Issue by jansenbro** [MicrosoftDocs/OfficeDocs-DeployOffice#679]
I seems impossible to get this information out of Microsoft. When using the ODT to deploy on premise O2019 with Action Pack Licensing, do we use the VLK configuration in the ODT config or O365. There is ZERO documentation ANYWHERE on the internet on this, which from a reseller, and training perspective simply frustrating. Dont get me started on just how idiotic the entire ODT is, but microsoft should learn that there should be 1 Media, and the KEY unlocks the entitlements.. this convoluted way to deploy office is a huge pain the ass, and has me looking at alternatives for ALL my clients.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [Deploy Office 2019 (for IT Pros)](https://docs.microsoft.com/en-us/deployoffice/office2019/deploy)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@jansenbro -- If by "on premise O2019" you mean Office Professional Plus 2019, then you should follow the steps in this article.
