### ISSUE TITLE
Server 2019

### ISSUE THREAD

**Issue by miked1313** [MicrosoftDocs/OfficeDocs-DeployOffice#682]
Should Server 2019 be added to the supported RDS versions on this page?  Per this announcement:  https://docs.microsoft.com/en-us/DeployOffice/deploy-office-365-proplus-by-using-remote-desktop-services

Thank you,
Mike

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6da18a8b-9e96-0155-7b30-9c211070d793
* Version Independent ID: 5a7e610a-bfcb-d9cc-03f7-589d970128d9
* Content: [Deploy Office 365 ProPlus by using Remote Desktop Services](https://docs.microsoft.com/en-us/DeployOffice/deploy-office-365-proplus-by-using-remote-desktop-services)
* Content Source: [DeployOffice/deploy-office-365-proplus-by-using-remote-desktop-services.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-office-365-proplus-by-using-remote-desktop-services.md)
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by rawtaz** [comment]
@DHB-MSFT  The article is still not updated to include Windows Serve 2019. Please fix this ASAP, Microsoft licensing is confusing enough as it is, without this lack of information!

**Comment by manoth-msft** [comment]
Thanks for bringing this up. We will clarify and update our documentation accordingly.

**Comment by manoth-msft** [comment]
I've got word back, Microsoft 365 Apps for enterprise is supported on Windows Server 2019 running RDS since September 2019, so any build newer than version 1909 is supported. I will work it into the documentation soon.

**Comment by rawtaz** [comment]
Thanks a lot for getting back to us with that information!

**Comment by manoth-msft** [comment]
I've incorporated this feedback into PR#811...
