### ISSUE TITLE
Why are posts that don’t violate policy being deleted?

### ISSUE THREAD

**Issue by lawtonj404** [MicrosoftDocs/OfficeDocs-DeployOffice#683]
Please tell me why github posts are disappearing that don’t violate any policy? Freedom of speech = gone freedom of search = gone 

Freedom of partners = gone to google

**Comment by DHB-MSFT** [comment]
To the best of our knowledge, only 2 issues have been deleted by our admins and those were for "code of conduct" violations.

**Comment by 4oo4** [comment]
@DHB-MSFT If you want to talk about Code of Conduct violations, look at @ItzLevvie's downvoting behavior, they are not respecting the "Understand differences" part of that at all. I'm in the process of reporting them now, Microsoft employees/affiliates are bound to this too.
