### ISSUE TITLE
Personal Opinion

### ISSUE THREAD

**Issue by AsaIt32** [MicrosoftDocs/OfficeDocs-DeployOffice#688]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd465474-5237-e58f-c3a8-a52f0c6f0afa
* Version Independent ID: fa4d9d36-c115-4044-0ede-90629e193b83
* Content: [Required service data for Office](https://docs.microsoft.com/en-us/deployoffice/privacy/required-service-data)
* Content Source: [DeployOffice/privacy/required-service-data.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/required-service-data.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by scqless** [comment]
[Enter comment here]

**Comment by scqless** [comment]
lul @ItzLevvie

**Comment by 4oo4** [comment]
Thanks @ItzLevvie! Your downvotes here are helping me build my code of conduct case against you. Please, keep up the pettiness.

**Comment by scqless** [comment]
@ItzLevvie Mr. Sajeey, it's very unprofessional to use your personal account to weigh in on matters you aren't impartial to while employed by MSFT. :smiley:
