### ISSUE TITLE
Discrepancy in end of mainstream support for OneNote 2016

### ISSUE THREAD

**Issue by mtlgirl** [MicrosoftDocs/OfficeDocs-DeployOffice#689]
The blue box at the top says: "We're continuing mainstream support for OneNote 2016 until October 2023, which aligns with mainstream support for Office 2019". About 1/3 of the way down under "Choose the Version..." heading, below the purple box, it says: "Mainstream support for OneNote 2016 ends in October 2020"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2319f44f-09fc-2649-2667-58fa159e3151
* Version Independent ID: 0b6c5c52-edaa-436d-95dd-0943d0b0c303
* Content: [Deployment guide for OneNote](https://docs.microsoft.com/en-us/deployoffice/deployment-guide-onenote#feedback)
* Content Source: [DeployOffice/deployment-guide-onenote.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deployment-guide-onenote.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@mtlgirl  -- Thanks for bringing that to our attention. We've removed that info from the "Choose the version...." section to avoid any confusion.
