### ISSUE TITLE
Link to "Quickly set up Office Telemetry Dashboard on a workgroup or domain-joined computer." does not work

### ISSUE THREAD

**Issue by MSFTEfeedback** [MicrosoftDocs/OfficeDocs-DeployOffice#690]
I am trying to install the processor using the link, but the link "Quickly set up Office Telemetry Dashboard on a workgroup or domain-joined computer" link sends me to an archive that doesn't contain the blog.  The reason I am trying to do this is that even though my device is domain joined, but I am still getting an error that says my device must be domain joined. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f14f242-749c-2ac1-2cae-9cdeadee5c3c
* Version Independent ID: e1239b9a-792c-aa63-7981-70d952d913cc
* Content: [Deploy Office Telemetry Dashboard](https://docs.microsoft.com/en-us/deployoffice/compat/deploy-telemetry-dashboard#feedback)
* Content Source: [DeployOffice/compat/deploy-telemetry-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/compat/deploy-telemetry-dashboard.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@MSFTEfeedback -- Thanks for bringing this to our attention. We've updated the link and it should send you to the new location of the blog post, which is https://docs.microsoft.com/archive/blogs/office_resource_kit/quickly-set-up-office-telemetry-dashboard-on-a-workgroup-or-domain-joined-computer.
