### ISSUE TITLE
add a list of error codes

### ISSUE THREAD

**Issue by marypcbuk** [MicrosoftDocs/OfficeDocs-DeployOffice#692]
running the ODT will sometimes result in an Office install error; it would be useful to list or link to the set of codes and what they mean (some are related to the state of Office client on the device, others to network issues)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66127c02-c2dc-f6d1-6e83-a6d2b1166731
* Version Independent ID: 27635315-22db-d136-f07e-5169f6207b50
* Content: [Overview of the Office Deployment Tool](https://docs.microsoft.com/en-us/deployoffice/overview-of-the-office-2016-deployment-tool?source=docs#feedback)
* Content Source: [DeployOffice/overview-of-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by jwhit-MSFT** [comment]
Thanks for this input--I agree that we could capture these in a Office deployment guide. I've added the request to our backlog. In the meantime, some of the error codes are documented [here](https://docs.microsoft.com/en-us/mem/intune/apps/apps-add-office365#errors-during-installation-of-the-app-suite).
