### ISSUE TITLE
ForceAppShutdown and display level

### ISSUE THREAD

**Issue by sebassem** [MicrosoftDocs/OfficeDocs-DeployOffice#699]
FroceAppShutdown only works when the display level is None  , can the docs reflect this relation between the two options ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a0b1ff-0498-505a-6024-b813980d310f
* Version Independent ID: b8057930-b4bd-1304-17ce-5561f837e901
* Content: [Configuration options for the Office Deployment Tool](https://docs.microsoft.com/en-us/deployoffice/configuration-options-for-the-office-2016-deployment-tool#feedback)
* Content Source: [DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by manoth-msft** [comment]
I can repro the issue, but it is inconsistent across different configs. I will work with engineering on RCA. I suggest to close this issue for now, I can file an update once we have a clear view on the actual issue.

**Comment by manoth-msft** [comment]
RCA completed, will be fixed in ODT, no doc change required. @jwhit-MSFT or @sebassem, can you close this issue?
