### ISSUE TITLE
No information on how update channels effect Click-to-Run installation of Volume Activated Visio and Project

### ISSUE THREAD

**Issue by CCDFischer** [MicrosoftDocs/OfficeDocs-DeployOffice#70]
We must use the ODT to install a Click-to-Run version of Visio and Project that are Volume licensed per https://docs.microsoft.com/en-us/DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer and https://docs.microsoft.com/en-us/deployoffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016

However there is no guidance on how to set the configuration xml file in terms of the update element, the OfficeMgmtCOM element for management with SCCM, nor for the channel element for volume licensed installations of Visio and Project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cd85e3b-e780-457e-9502-856bc6315bca
* Version Independent ID: 416e351f-13c5-e951-ea81-1650910a7c25
* Content: [Overview of update channels for Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/overview-of-update-channels-for-office-365-proplus?redirectSourcePath=%252fen-us%252farticle%252f9ccf0f13-28ff-4975-9bd2-7e4ea2fefef4)
* Content Source: [DeployOffice/overview-of-update-channels-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-update-channels-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
There is no difference between how those settings are used, whether you're installing Office 365/subscription versions of Project & Visio or you're installing volume licensed editions of Visio 2016 & Project 2016 using the Office Deployment Tool. We'll try to make that clearer in the documentation. Thanks for your feedback.
