### ISSUE TITLE
Project/Visio Professional 2019 downgrading O365 version

### ISSUE THREAD

**Issue by Upendra365** [MicrosoftDocs/OfficeDocs-DeployOffice#700]
Hello,
We have installed O365 ProPlus CTR version 16.0.12325.20298. Then, when we deploy Project or Visio Professional 2019 16.0.10352.20042 the O365 ProPlus version is also getting downgraded to 16.0.10352.20042. The build version still shows 16.0.12325.20298 but Add/Remove programs shows 16.0.10352.20042.
Will it be an issue?
Also, we are planning to have monthly channel updates for O365 and semi-annual updates (via application packaging) for Project/Visio.

Please let me know if there are any special action to be taken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d40c96f3-1c97-b538-ef82-ffbf0eef204d
* Version Independent ID: 2d6883b5-1b5c-dc16-9999-17d0652bfa48
* Content: [Supported scenarios for installing different versions of Office, Project, and Visio on the same computer](https://docs.microsoft.com/en-us/deployoffice/install-different-office-visio-and-project-versions-on-the-same-computer)
* Content Source: [DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by RAJU2529** [comment]
Normally office 365 does not compatible with office 2019. You must install any one version completely either office 365 or office 2019.
I would recommend you use 2019 all products

**Comment by Upendra365** [comment]
This link  https://docs.microsoft.com/en-us/deployoffice/install-different-office-visio-and-project-versions-on-the-same-computer  says it is supported not sure if we need to take any additional steps to achive this. Anyways, we already have O365 on all computers. Can we use Visio and Project online or desktop client instead of changing the office version to 2019. We have volume license for Visio professional and Project Standard, how do we reuse them for Visio and project online/desktop versions?

**Comment by jeffwmiles** [comment]
I am also experiencing this issue. I had Office 365 ProPlus CTR Build 2003 installed on Monthly Channel. I installed Visio Professional 2019 volume license with a "Monthly" channel flag, as per the documentation on this page. 

Now both products are at 1808 build. Is there not a way to keep Office 365 ProPlus on Monthly channel?

**Comment by manoth-msft** [comment]
I can't repro the behavior. Could it be that you used a sourcepath and downloaded the 1808 bits before (running /download with a config files having channel=perpetual)? We recommend to configure Visio installs in a lean, dynamic and universal way as described here: https://docs.microsoft.com/en-us/deployoffice/fieldnotes/build-dynamic-lean-universal-packages

**Comment by jeffwmiles** [comment]
Thats very interesting @manoth-msft; I was able to get it to successfully work. 

Attempting to use the /download switch for Visio based off your link (with matching versions and 
languages) when I'm using O365ProPlusRetail and VisioPro2019Volume only produces this error:

![image](https://user-images.githubusercontent.com/40004712/80498255-bcf39a80-8928-11ea-962c-7eda9ce33cc5.png)

However if I went direct to /configure using the following XML, I ended up with both products at 2003 build but Visio installed with a volume key.
```
<Configuration ID="6659a04f-037d-4f23-b8a2-64c851090a5e">
  <Add Version="MatchInstalled" >
    <Product ID="VisioPro2019Volume" PIDKEY="insert key">
      <Language ID="MatchInstalled" TargetProduct="O365ProPlusRetail" />
    </Product>
  </Add>
</Configuration>
```

Is there a good way to work this information into this doc page, as a reference?

**Comment by RAJU2529** [comment]
From three days. Downloading of office using configuration file  gives same problem as check you interney connection even though I have high speed connection.
I took alternate way I downloaded the  office pro plus 2019 2004. 12730.20236 iso file,. Using that updated to latest.

**Comment by RAJU2529** [comment]
@manoth-msft.  Also we try to download using configuration file, office tries to download from latest version only from CDN server.

**Comment by manoth-msft** [comment]
@jeffwmiles Thanks for the feedback. I will see how I can work the two nuggets into the doc: 1. /download does not work with the lean install xml (this is expected, btw) and 2. this approach also works for VL versions. Thanks!

**Comment by manoth-msft** [comment]
#767

**Comment by RAJU2529** [comment]
@manoth-msft . please solve the office server issues, while downloading the update using C2R by suing winword2019.

**Comment by manoth-msft** [comment]
@RAJU2529 This issue is not related to any office server issues, nor updates or Word 2019.

**Comment by simonburbery** [comment]
Just confirming when you install a 'non 365' version of visio or project (in my case my Visual Studio copy of Project that I get with the companies MSDN / Visual Studio subscription being a Gold partner), the O365 apps are downgraded.  Appreciate why but a bit of a pain!  My Outlook has gone back to the 'less enjoyable' search experience.

**Comment by manoth-msft** [comment]
The M365Apps get downgraded when at least one of the two is true:

- When adding Visio/Project 2016/2019/2021, you specified a version in the XML. Remove the "Version=16.0.12345.67890" portion your XML, do prevent forcing a downgrade.
- When adding Visio/Project 2016/2019/2021, you specified a different channel in the XML. Remove the Channel=Something portion from your XML and setup will carry the existing channel forward. In this scenario (adding Visio/Project perpetual to an existing M365Apps install), the ProductID being set to a perpetual product is sufficient.
