### ISSUE TITLE
MECM deployment of Visio or Office/Visio

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/OfficeDocs-DeployOffice#703]
this section - last word "office" 
- "If you already use other tools to deploy software to your users, such as Microsoft Endpoint Configuration Manager, you can use the Office Deployment Tool along with those tools to deploy the subscription version of Office."
Yes I want to use MECM.  We already have "Office" on all computers, now I want to install Visio Plan 2 on some computers, however the install is failing with an error code of 30088-4 after preparing just Visio with the MECM office deployment tool. (no office included) Based on the way the sentence is worded above, can I assume that if I want to install Visio Plan 2, I need to now include office with my Visio Plan 2 deployment and replace my current office install with an office / visio deployment for anybody that needs Visio Plan 2?

OR should this sentence read

"If you already use other tools to deploy software to your users, such as Microsoft Endpoint Configuration Manager, you can use the Office Deployment Tool along with those tools to deploy the subscription version of Visio."

meaning visio can be deployed as a separate install and my error message is unrelated.  

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3fc30fd-858c-d1cd-0729-6eb72ef7975a
* Version Independent ID: aa690d1d-8e25-6de1-9a83-7acd851fed7a
* Content: [Deployment guide for Visio](https://docs.microsoft.com/en-gb/deployoffice/deployment-guide-for-visio#feedback)
* Content Source: [DeployOffice/deployment-guide-for-visio.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deployment-guide-for-visio.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
I suspect that the detection method of your Visio SCCM app is looking for Office and thus can't install Visio as the detection method returns "already installed" immediately. I suggest to look at the Detection Method of your VIsio SCCM app and make sure that this is unique, e.g. by checking for the visio.exe or another regkey unique to Visio.

**Comment by MJP-MSFT** [comment]
@PaulKlerkx Did the recommendation from @manoth-msft  address your issue?

**Comment by manoth-msft** [comment]
I will go forward and close this issue for now. If you are still facing an issue which is not related to the documentation itself, feel free to ping us on https://techcommunity.microsoft.com/t5/microsoft-365-apps-for/bd-p/Microsoft365Apps

**Comment by PaulKlerkx** [comment]
yes, OK to close, sorry for not responding, I never got the visio install working but other priorities didn't allow me to spend too much time on it.  not sure when I'll get to it.
