### ISSUE TITLE
Requirements - Security Groups

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-DeployOffice#704]
The requirements state that Security groups must be created in Azure AD, but makes no mention of Office 365 Groups. Can this service be used with both types of groups? if so, please state this explicitly, and if not please state this to remove any potential ambiguity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa63a94-daaa-9491-213e-f0329f6299b1
* Version Independent ID: 47fe5a3a-ee7c-a7f7-b913-ca0ac3c063e0
* Content: [Overview of the Office cloud policy service for Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/overview-office-cloud-policy-service?WT.mc_id=twitter)
* Content Source: [DeployOffice/overview-office-cloud-policy-service.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-office-cloud-policy-service.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by chhopkin** [comment]
Thank you for the feedback.  At this time Office 365 Groups is not supported.

**Comment by jwhit-MSFT** [comment]
Docs will be updated soon--thanks for the catch.
