### ISSUE TITLE
Prevent Users from Installing Clients Outside Scope

### ISSUE THREAD

**Issue by rzavalik** [MicrosoftDocs/OfficeDocs-DeployOffice#705]
We're facing a problem: we want to prevent corporate users to install corporate licenses (such as Office ProPlus) in their personal devices. Our users are using their work license (which has a 5 machines limit) to install on their personal computers at home, or mobile, totally out of our control. How can we better control that?

**Comment by RAJU2529** [comment]
@rzavalik . i am not an Office system administrator, i have an idea. Use app locker under secpol.msc , you can avoid  the installation of  office professional plus setup file .
and apply this rule to all corporate users via  group policy.  Make a group policy editor should be restricted by changing this. prevent the users from changes keys in the windows registry editor.

i hope above idea might help to you.

**Comment by manoth-msft** [comment]
@rzavalik You can't prevent the installation of Office on personal devices, but you can prevent the activation using a corporate license by preventing the user to sign in using your corporate credentials. Have a look at Azure Conditional Access for that: https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/overview It allows you to e.g. prevent any sign-in attempt from outside your corp network or from un-managed devices.
