### ISSUE TITLE
Exceed number of installs change in deactivation process

### ISSUE THREAD

**Issue by gasperj** [MicrosoftDocs/OfficeDocs-DeployOffice#707]
Please update this text: "If the user decides to install Office 365 ProPlus on a sixth computer, she will need to deactivate one of the first five."

Office 365 license activation changes
https://www.microsoft.com/en-us/microsoft-365/roadmap?featureid=53698
"Going forward, Office will automatically sign the user out of the user’s least recently used device when the user exceeds the limit, eliminating unnecessary friction."

This is a really important and useful new method of roll off the oldest activation, but it seems to be hidden only in the roadmap.

(And it does work great.)   Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3c236da-c63a-f789-f1b6-7aeb41f16c1f
* Version Independent ID: 35319bac-d94f-832c-ce79-41bffe5c8d25
* Content: [Overview of licensing and activation in Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/overview-of-licensing-and-activation-in-office-365-proplus#feedback)
* Content Source: [DeployOffice/overview-of-licensing-and-activation-in-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-licensing-and-activation-in-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by MJP-MSFT** [comment]
Hello @gasperj 

Which version of the Office client are you using. The improvements for licensing were shipped in versions post 1909. Please test with Monthly Channel, Semi Annual - Targeted and let me know if you see better results. Both of the above versions on on 2002 which has the licensing improvements.

We are updating our documentation with the new licensing improvements within the next week. Thank you for reaching out!

Thank You,

Matt

**Comment by gasperj** [comment]
Thanks, Matt. We're on monthly and the new licensing method is working great. It's has helped us transition off device-based activation, with its troubles when you get duplicate AAD entries, until we have device-based licensing operational (middle of that getting enabled). We have automatic sign in to OneDrive enabled; Office seems to be picking that up and our users don't even get prompted to sign in on first start of an Office desktop application. Works so well we could get by without device-based licensing. Just thought the docs could call out the new user-based method as it's really helpful - thanks for getting them updated.

**Comment by MJP-MSFT** [comment]
@jwhit-MSFT  to close as we have updated the Overview of licensing and activation article with licensing improvements.

**Comment by gasperj** [comment]
I guess I would state that this line is not accurate:
"If the user decides to install Office 365 ProPlus on a sixth computer, she will need to deactivate one of the first five."
That now happens automatically for the user - the oldest used activation is automatically deactivated for the user. See my comment that started this thread.

**Comment by gasperj** [comment]
Hmmm... opportunity to mention better experience with 1910+ :-)    I understand. Thanks for these opportunities to help with our docs. Done here.
