### ISSUE TITLE
machine wide teams installer and O365 teams

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/OfficeDocs-DeployOffice#708]
I see these are both mentioned here, but it's still a bit vague - if you had machine wide installer, then office updated to include Teams.  Do you then need to deploy an uninstall of the teams wide installer or are these both part of the office install now or are they both separate from each other as well as being separate to office? in applications and features, I have Microsoft Office 365 ProPlus v18.2002.1101.0, Microsoft Teams v1.3 and Teams Machine-wide installer v1.2, but if Teams is now part of office, shouldn't I only see Microsoft Office, not either of the teams entries?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7936ca5e-c658-4956-b174-99eaf1eb67d4
* Version Independent ID: 9ecc0b61-a941-f5e1-96c3-d32fae59eacd
* Content: [Deploy Microsoft Teams with Office 365 ProPlus](https://docs.microsoft.com/en-gb/deployoffice/teams-install)
* Content Source: [DeployOffice/teams-install.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/teams-install.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by acmatthews** [comment]
This article states: 
"If you're letting your users install Office 365 ProPlus for themselves from the Office 365 portal, you can't exclude Teams from being included as part of the installation, unless you use Group Policy."
But that information is incorrect. The Office 365 Portal still includes Skype for Business instead of Teams in the self-install page of My Account: https://techcommunity.microsoft.com/t5/office-365-proplus/office-proplus-self-install-does-not-include-teams/td-p/1292177

**Comment by DHB-MSFT** [comment]
@acmatthews  -- Does "Teams Machine-Wide Installer" appear when you go to Add/Remove Programs?  Also, Teams doesn't actually get installed until after the user logs out and back in to Windows.

**Comment by DHB-MSFT** [comment]
@PaulKlerkx -- As part of an Office 365 ProPlus install/update, the Teams Machine-Wide Installer gets installed. That then installs Teams the next time the user logs into Windows. So it's expected for you to see those separate entries for Teams Machine-Wide Installer and for Teams, along with the entry for Office 365 ProPlus. Hope that explanation helps.

**Comment by acmatthews** [comment]
Thanks for the explanation @DHB-MSFT . What a terrible end-user experience though! The Office 365 Portal where the user goes to self-install still shows a Skype logo and makes no mention of Teams.

**Comment by DHB-MSFT** [comment]
@acmatthews -- thanks for the feedback on the Teams icon not appearing on the self-install page and it causing user confusion. We've sent this feedback on to the product team and someone has been assigned to add the Teams icon to that UI surface.
