### ISSUE TITLE
DeviceBasedLicensing Property

### ISSUE THREAD

**Issue by NeverEnoughCoffeeMan** [MicrosoftDocs/OfficeDocs-DeployOffice#709]
Another observation. If you use the Office Customization Tool (config.office.com), your collection of deployment settings might contain this Property element:

&lt;Property Name="DeviceBasedLicensing" Value="0" /&gt;

There's no mention of this Name attribute value on this page. You'll find this value discussed in a separate Docs article titled "Device-based licensing for Office 365 ProPlus" that you won't find in the Reference section. Here's the link:

https://docs.microsoft.com/en-us/deployoffice/device-based-licensing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a0b1ff-0498-505a-6024-b813980d310f
* Version Independent ID: b8057930-b4bd-1304-17ce-5561f837e901
* Content: [Configuration options for the Office Deployment Tool](https://docs.microsoft.com/en-us/DeployOffice/configuration-options-for-the-office-2016-deployment-tool)
* Content Source: [DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/configuration-options-for-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by RAJU2529** [comment]
I also configured the office configutaion file i mentioned config.office.com 
i conformed  **<Property Name="DeviceBasedLicensing" Value="0" />**
is  added to .xml file

**Comment by MJP-MSFT** [comment]
I have submitted a pull request to update the Property Section with Device based subscription details. @jwhit-MSFT  to close this issue request.
