### ISSUE TITLE
Permissions Required

### ISSUE THREAD

**Issue by IsaacHayward** [MicrosoftDocs/OfficeDocs-DeployOffice#711]
What permissions are needed to set Office Download Settings?
The Tip of where to find them is useful, but I have fairly high level access to our tenant, and it seems Global Administrator is required. Please clarify

**Comment by IsaacHayward** [comment]
I have found Office Apps Admin in other documentation:
https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide

**Comment by manoth-msft** [comment]
@jwhit-MSFT / @DHB-MSFT Can be closed
