### ISSUE TITLE
Revise suggestion

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/OfficeDocs-DeployOffice#712]
Reading through the whole doc, I cannot tell whether it's doable to install Office 365 with RDS when SCA is not enabled. For example, deploy Office 365 on an Azure windows VM. The fact is you cannot do that according to this [KB](https://docs.microsoft.com/en-us/office/troubleshoot/error-messages/click-to-run-office-on-terminal-server). Suggest make a note explicitly about this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ab31873-7ad3-afde-3c72-8a7fb4f2e551
* Version Independent ID: 19f7f483-9f53-f577-1cd4-d360c0b234fc
* Content: [Overview of shared computer activation for Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus)
* Content Source: [DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
Thanks for the feedback. I submitted changed to both our SCA documentation as well as the KB, making it more clear that SCA is a hard requirement for any Windows instance used by more than one user. Thanks for flagging.
@DHB-MSFT : Can be closed once pull requests are merged.
