### ISSUE TITLE
Need to uninstall OneNote 2016

### ISSUE THREAD

**Issue by Upendra365** [MicrosoftDocs/OfficeDocs-DeployOffice#718]
Hello,

We have many clients that have OneNote 2016 installed along with O365 suite. However, our customer wants to use OneNote for Windows 10 and do not want OneNote 2016.

We can configure xml file to exclude OneNote from installing on new clients. However, how to uninstall OneNote 2016 on the clients that have already installed it along with O365 suite.

Thanks,
Upendra

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2319f44f-09fc-2649-2667-58fa159e3151
* Version Independent ID: 0b6c5c52-edaa-436d-95dd-0943d0b0c303
* Content: [Deployment guide for OneNote](https://docs.microsoft.com/en-us/deployoffice/deployment-guide-onenote)
* Content Source: [DeployOffice/deployment-guide-onenote.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deployment-guide-onenote.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
@Upendra365 Scheck out this blog post for an explanation how to achieve that: https://techcommunity.microsoft.com/t5/office-365-blog/excluding-and-re-including-applications-within-the-office-365/ba-p/1250367. We will backport some information into the article you mentioned, thanks for flagging.
@DHB-MSFT Can be closed then
