### ISSUE TITLE
Wrong Screenshot

### ISSUE THREAD

**Issue by sargeanthatred** [MicrosoftDocs/OfficeDocs-DeployOffice#72]
Under Solution Detail Worksheet the screenshot is for the Document Details Worksheet not for Solution Details - 26/07/2018

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 621d3141-346d-0f15-c850-db51cfbc32b9
* Version Independent ID: 00686abe-6714-7736-e3f1-06c4b317cdff
* Content: [Telemetry Dashboard worksheet reference](https://docs.microsoft.com/en-us/deployoffice/compat/telemetry-dashboard-worksheet-reference#feedback)
* Content Source: [DeployOffice/compat/telemetry-dashboard-worksheet-reference.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/compat/telemetry-dashboard-worksheet-reference.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Thanks for bringing this to our attention. The correct screenshot for "Solution details" is now appearing in the article.
