### ISSUE TITLE
change the wording about how to avoid getting TEAMS installed when updating Office

### ISSUE THREAD

**Issue by TheBaban** [MicrosoftDocs/OfficeDocs-DeployOffice#721]
To avoid getting TEAMS installed when updating Office the article state you need to deploy a GPO or use the Office Deployment toolkit. This is misleading.
In fact you need to deploy a GPO OR to have define &lt;ExcludeApp ID="Teams" /&gt;.
This means if you have already deploy OPP with that exclusion, you don't need to do anything.
The current wording is not explicit and makes people think they need to deploy the GPO or rerun the ODT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7936ca5e-c658-4956-b174-99eaf1eb67d4
* Version Independent ID: 9ecc0b61-a941-f5e1-96c3-d32fae59eacd
* Content: [Deploy Microsoft Teams with Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/teams-install#feedback)
* Content Source: [DeployOffice/teams-install.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/teams-install.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by RAJU2529** [comment]
@illfated. Please review PR #726 . Thanks

**Comment by illfated** [comment]
@RAJU2529 : I notice that there is no need to update the Administrative Template files (ADMX/ADML), because the required minimum version is already mentioned in that article.
Anyway, the OP is pointing to a different problem (unless I have misread or misunderstood the main post here).

@TheBaban : Do you have a suggestion for what the paragraph or section could look like, in your opinion?

**Comment by RAJU2529** [comment]
@illfated Sorry i will delete my comment.

**Comment by manoth-msft** [comment]
@TheBaban Thanks for the feedback. We've submitted a pull request to update the documentation accordingly.
@DHB-MSFT can be closed

**Comment by illfated** [comment]
#sign-off 
#please-close
