### ISSUE TITLE
admx adml templates version number not updated

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#725]
Already Microsoft released v4993.1000 admx adml templates, so this article needs to be updated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7936ca5e-c658-4956-b174-99eaf1eb67d4
* Version Independent ID: 9ecc0b61-a941-f5e1-96c3-d32fae59eacd
* Content: [Deploy Microsoft Teams with Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/teams-install#feedback)
* Content Source: [DeployOffice/teams-install.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/teams-install.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by illfated** [comment]
See https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/pull/726#issuecomment-607159359 :
> The article mentioned "**at least** version 48xx.xxx", so there is no need to update the article.

**Comment by illfated** [comment]
#please-close

**Comment by RAJU2529** [comment]
closed

**Comment by RAJU2529** [comment]
@illfated . ok I will close  now, i need a solution from windows defender application.
Please go through below query site, i  already a question on Microsoft forum , but no user is answered 

here is  the link
**https://answers.microsoft.com/en-us/windows/forum/all/i-received-error-code-0xc00ce225-when-i-entered/9503a0b4-1143-4578-a563-a83649bfed10**

**Comment by illfated** [comment]
See answers you received today on this page:
https://www.windowsphoneinfo.com/threads/i-received-error-code-0xc00ce225-when-i-entered-configsecuritypolicy-exe-in-command-with.323375/

**Comment by RAJU2529** [comment]
@removing  account and recreating it does solve. Please you using windows 10 pro 64bit means , i am sure you also get the same error, please try once.

please enter below commands, in cmd what gets 
**cd "C:\Program Files\Windows Defender"**

**ConfigSecurityPolicy.exe  /?**

**Comment by illfated** [comment]
That being said, please note that I am not currently working in an enterprise environment, it is 6 years or more since I had the opportunity to be in contact with a nationwide multi-server Microsoft network. I recommend asking someone in the technet forum pages or somewhere else where it is likely that you can get recommendations from active primary server admins who know about the topics you run into when you are testing those enterprise software packages. (My everyday support does not extend much beyond creating new users in a Windows Server 2016 Standard and deploy them manually on one of the 20 available computers. I don't even create roaming profiles, so my workplace experience is not in line with Enterprise environments.

**Comment by illfated** [comment]
@RAJU2529 : it looks like the command you are trying to run does not have a **` /? `** option to use. I can only assume that you need to either provide a policy template file as one of its parameters, or supply a name for a new policy file, in case it is able to create policy files from scratch.

Please, please note that I do not work in an Enterprise environment. The most advanced policies I have managed or used so far, are the policies to manage how Windows Update is allowed to run on one of the users' computers. That experience does not extend easily to any advanced policy configuration scenario, nor any of the policies for Windows Defender or other security policies.

**Comment by RAJU2529** [comment]
@illfated . Now you understood the real problem,  i did not get any policy in .xml file, thats the problem, i  want to create new policy .xml , and i need to apply to my own machine.

**Comment by illfated** [comment]
Fair enough. You may want to look up what the correct procedure is to create the policy you need. Unfortunately, I don't know what that procedure is.

**Comment by RAJU2529** [comment]
@illfated . Searching
