### ISSUE TITLE
64 to 32? 

### ISSUE THREAD

**Issue by Pitel81** [MicrosoftDocs/OfficeDocs-DeployOffice#728]
Article talks about going from 32 to 64, but can it go the other way? We are pushing all our users to x64, but have a few that need x32 for legacy apps/macros.  It would be nice see this feature offered both ways. Other than that, this is excellent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3eacd91-ad3e-79a3-d946-0fa33785b7ee
* Version Independent ID: 0e5a2663-78b8-6068-2e80-cd472a72d7b1
* Content: [Change an Office 365 ProPlus installation from 32-bit to 64-bit](https://docs.microsoft.com/en-us/deployoffice/change-bitness#feedback)
* Content Source: [DeployOffice/change-bitness.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/change-bitness.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
@Pitel81 : The information you're looking for is a bit hidden in the article, but your scenario is supported. By setting MigrateArch=TRUE and OfficeClientEdition=32 it will move from x64 to x86.

**Comment by Pitel81** [comment]
Thanks, I thought that it might work that way, but I wasn't sure and all my test boxes are tied up in delivery optimization testing.  Thanks for the quick response!
