### ISSUE TITLE
Installs Visio 2019

### ISSUE THREAD

**Issue by bprettyman1** [MicrosoftDocs/OfficeDocs-DeployOffice#742]
The current Deployment Tool installs Visio 2019 when using the example XML. How do you tell it to install 2016 specifically? Through the Version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e6c0641-503d-7959-2afb-839821cc792f
* Version Independent ID: 046c52d9-4fbe-4fe7-0778-5c1d4138f69e
* Content: [Use the Office Deployment Tool to install volume licensed versions of Project 2016 and Visio 2016](https://docs.microsoft.com/en-us/deployoffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016#feedback)
* Content Source: [DeployOffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
The provided XML should install the 2016 versions of Visio/Project as the 2019 version have different Product IDs, e.g. VisioPro2019Volume and ProjectStd2019Volume. Check also out https://docs.microsoft.com/en-us/office365/troubleshoot/installation/product-ids-supported-office-deployment-click-to-run
