### ISSUE TITLE
Syncing computers from local AD to Azure AD via security group fails

### ISSUE THREAD

**Issue by HP1974** [MicrosoftDocs/OfficeDocs-DeployOffice#748]
Is this option valid: Create using these tools + On-premises Active Directory and sync to Azure AD with Azure AD Connect
What are the prerequisites for this to actually work? There seems to be very little documentation of this option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e52eb9c1-1755-bec5-4ad8-6df59779e041
* Version Independent ID: 10e4cf5d-ea61-806e-f226-1e14265eabe1
* Content: [Device-based licensing for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/device-based-licensing#feedback)
* Content Source: [DeployOffice/device-based-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/device-based-licensing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by manoth-msft** [comment]
The scenario your describing is called "hybrid Azure AD Join", your device is joined into your local AD and will by synced by Azure AD Connect and the device will than join the Azure AD in parallel to the existing local AD join. Check out these docs: https://docs.microsoft.com/en-us/azure/active-directory/devices/concept-azure-ad-join-hybrid and https://docs.microsoft.com/en-us/azure/active-directory/devices/hybrid-azuread-join-plan#select-your-scenario-based-on-your-identity-infrastructure.

I will submit and update to the article to link off to these docs.

**Comment by HP1974** [comment]
The actual problem is that in 2 different tenants this does not work. Both have Hybrid Azure AD join working. Local ad group can be created (Global security group) and filled with computer accounts that exist in the local AD. AADConnect will sync the group itself but AzureAD shows that group does not have computers as members. The exact phrase is that the group has no "devices" as members. I have tested this with computer account that existed in local ad and in azure AD as "Joined" or "Registered" status and also with an computer account that was not synced to Azure AD at all. All the documentation I have read about AADsync talks about users synced to Azure groups but I have not found any reference to how computer accounts can be synced to group members in Azure AD from local AD.
