### ISSUE TITLE
Needs to be updated

### ISSUE THREAD

**Issue by wongcarter** [MicrosoftDocs/OfficeDocs-DeployOffice#749]
I see slightly different pop ups now. Recently received one like this:
Office will update in 22 minutes
We need to close your office apps to install...
[Postpone][Update Now]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67822bd8-e17c-5e0b-2ad8-f51325dcb30d
* Version Independent ID: 2a10d821-4fa6-9e06-232c-7d6cba683615
* Content: [End-user update notifications for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/end-user-update-notifications-for-office-365-proplus#feedback)
* Content Source: [DeployOffice/end-user-update-notifications-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/end-user-update-notifications-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by jwhit-MSFT** [comment]
Thanks for the input on this. We agree that this article needs some updating--it's in our backlog and should be addressed in the next couple months.
