### ISSUE TITLE
Licensing requirement clarification

### ISSUE THREAD

**Issue by Jared-Harrington-Gibbs** [MicrosoftDocs/OfficeDocs-DeployOffice#751]
This page and [some of the comments](https://techcommunity.microsoft.com/t5/office-365-blog/the-new-cloud-based-policy-management-service-for-office-365/bc-p/870587/highlight/true#M1748) on the original blog comment seem to indicate that this only works with ProPlus.
The [service description page](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-applications-service-description/office-applications-service-description?redirectedfrom=MSDN) however indicates that the office cloud policy features are available for e3/e5 users.
Could additional clarification be provided?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa63a94-daaa-9491-213e-f0329f6299b1
* Version Independent ID: 47fe5a3a-ee7c-a7f7-b913-ca0ac3c063e0
* Content: [Overview of the Office cloud policy service for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/overview-office-cloud-policy-service)
* Content Source: [DeployOffice/overview-office-cloud-policy-service.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-office-cloud-policy-service.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by DHB-MSFT** [comment]
@Jared-Harrington-Gibbs  -- Office 365 ProPlus is the version of Office that comes with E3 and E5 plans.  That version of Office is also available in a standalone plan (named Office 365 ProPlus). As long as you have a plan that includes Office 365 ProPlus, you should be able to use Office cloud policy service (as long as the other requirements for using Office cloud policy service are met).

We hope that explanation helps.

**Comment by Jared-Harrington-Gibbs** [comment]
Hey @DHB-MSFT, That absolutely answers my question. Thanks for the clarification.
