### ISSUE TITLE
GPO error

### ISSUE THREAD

**Issue by jwatt130** [MicrosoftDocs/OfficeDocs-DeployOffice#758]
I added the GPO as suggested from this page under 'Use Group Policy to control the installation of Microsoft Teams' in our environment and now we receive an error "The processing of Group Policy failed. Windows attempted to read the file \\xxxxx.net\SysVol\xxxxx.net\Policies\{456B5A1A-BFF7-4370-965C-AD50A0549696}\gpt.ini from a domain controller and was not successful. "  Powershell inquiry shows the newly added Teams - Excluded GPO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7936ca5e-c658-4956-b174-99eaf1eb67d4
* Version Independent ID: 9ecc0b61-a941-f5e1-96c3-d32fae59eacd
* Content: [Deploy Microsoft Teams with Microsoft 365 Apps](https://docs.microsoft.com/en-us/deployoffice/teams-install#feedback)
* Content Source: [DeployOffice/teams-install.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/teams-install.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by RAJU2529** [comment]
@jwatt130 . Did you updated  latest admx adml templates in your  domain computer.
Which policy settings did you enabled in GPO
