### ISSUE TITLE
Please update to cover OneNote 2016 and Office 2019

### ISSUE THREAD

**Issue by marypcbuk** [MicrosoftDocs/OfficeDocs-DeployOffice#76]
As OneNote will not be update with Office 2019 and Office 2019 will be CTR only, please add the support matrix for OneNote 2016 and Office 2019.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d40c96f3-1c97-b538-ef82-ffbf0eef204d
* Version Independent ID: 2d6883b5-1b5c-dc16-9999-17d0652bfa48
* Content: [Supported scenarios for installing different versions of Office, Visio, and Project on the same computer](https://docs.microsoft.com/en-gb/DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer)
* Content Source: [DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Thanks for your feedback. We plan to update this article with Office 2019 relevant information when Office 2019 is released later this year.

**Comment by hypercube33** [comment]
Documentation is still horrible - does not cover how to deploy Office 365 (current branch) with missing OneNote and Office 365/OneNote properly. There is a page on this found here: https://support.office.com/en-us/article/onenote-2016-is-missing-after-installing-office-2019-or-office-365-1844ba87-7248-4bd8-a735-66a52f98e6e5 but it appears to have some type of click to run with embedded XML so we cant deploy it silently. Are we supposed to just deploy a version-locked Separate copy of 365 with just OneNote? Needs Clarification

**Comment by marypcbuk** [comment]
the page should note that the 'upgrade' to 2019 from 2016 is actually an uninstall and reinstall that will remove OneNote 2016 if you're moving from 32 to 64-bit, and it should note that even a 32-bit to 32-bit upgrade removes OneNote 2016 then re-installs it and does a new backup without removing the old backup in a new folder structure under 16 rather than 15, so old backup files can amount to gigabytes in size and have to be removed manually. 
Solutions for handling the OneNote installation are to individually install the 32 or 64-bit version, to install the beta Centennial 32-bit version from the Microsoft Store (which doesn't support plugins or add-ons like Onetastic) or to add OneNote to the Office deployment tool. I summarise the steps here https://www.techrepublic.com/article/is-the-desktop-version-of-onenote-dead/ but it would be great if the official documentation included all of this ;)

**Comment by DHB-MSFT** [comment]
@hypercube33  -- This might be the article you're looking for to answer your OneNote deployment questions -- [Deployment guide for OneNote](https://docs.microsoft.com/en-us/DeployOffice/deployment-guide-onenote).  Most of the pertinent info should be there, but we have a few updates we need to make to it. For example, this new install behavior is now in all update channel (as of the Version 1808 release to Semi-Annual Channel in January 2019).  Hope that helps.
