### ISSUE TITLE
After updating to 2004 certain third-party apps can't attach to Outlook messages

### ISSUE THREAD

**Issue by elscorcho3** [MicrosoftDocs/OfficeDocs-DeployOffice#761]
Some of our clients automatically updated to Office v2004 and this broke the ability for a couple of apps (Computer Ease, HP Scan) to launch a new Outlook message with an attachment created from those apps. Had to revert all of them to a previous version, 2002 for this to work again.

**Comment by manoth-msft** [comment]
Hi, the 2004 release is the Monthly Targeted channel. We recommend to use the in-app support functionality to raise this bug to the right team within Microsoft. Thank you.

**Comment by manoth-msft** [comment]
In case you are eligible for FastTrack App Assurance, we would appreciate if you open a case with them and they will ttriage the issue. If you are eligible, there are no additional costs.

[Link](https://www.microsoft.com/en-us/fasttrack/microsoft-365/app-assure)

**Comment by matjue85** [comment]
https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/761#issue-608741643
