### ISSUE TITLE
Office Automatic Update 2.0

### ISSUE THREAD

**Issue by lexios** [MicrosoftDocs/OfficeDocs-DeployOffice#763]
You report the following:

"After the Office Automatic Update 2.0 task runs and updates the assigned channel, the new build is installed the next time the Configuration Manager client runs a Software Updates Deployment Evaluation Cycle."

My 1803 build task is not version 2.0, it reads "Office Automatic Update"

Is there any change in functionality?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d23ac821-9cb8-8855-598f-d1327df04fac
* Version Independent ID: 78f2127a-0c6b-d236-a415-6215c582ce8b
* Content: [Change the Microsoft 365 Apps update channel for devices in your organization](https://docs.microsoft.com/en-us/deployoffice/change-update-channels?source=docs)
* Content Source: [DeployOffice/change-update-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/change-update-channels.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by RAJU2529** [comment]
in 19xx series  office automatics update 2.0 app is included, i have the latest version office 2019
2004 build 12730.20236 c2r

**Comment by manoth-msft** [comment]
No major changes, but you should really update your Office installation as it is pretty outdated and not supported any more.
