### ISSUE TITLE
Awful page, outdated, incomplete, lack of information, misleading

### ISSUE THREAD

**Issue by itsChris** [MicrosoftDocs/OfficeDocs-DeployOffice#766]
Please, we pay a lot of money for Office and Windows licenses and this is what we get in return? This page is somewhat misleading when it comes to 'how to install Office 365 E3' on a RDS Session Host running on Windows Server 2019. I mean, if you look for an instruction 'how to install Libre Office on Ubuntu' -&gt; you don't pay a cent but you get 100 times better documentation. 

So please, update an correct this page and remove the misleading infomation!!

thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6da18a8b-9e96-0155-7b30-9c211070d793
* Version Independent ID: 5a7e610a-bfcb-d9cc-03f7-589d970128d9
* Content: [Deploy Microsoft 365 Apps by using Remote Desktop Services](https://docs.microsoft.com/en-us/deployoffice/deploy-microsoft-365-apps-remote-desktop-services#feedback)
* Content Source: [DeployOffice/deploy-microsoft-365-apps-remote-desktop-services.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-microsoft-365-apps-remote-desktop-services.md)
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
Can you elaborate what portion of the documentation is misleading?
