### ISSUE TITLE
Where can i download Teams machine wide MSI installer file? 

### ISSUE THREAD

**Issue by Sri-Boddupalli** [MicrosoftDocs/OfficeDocs-DeployOffice#768]
I am not able to find MSI machine wide installer for newest version. Where can i download machine wide MSI installer file?

**Comment by DHB-MSFT** [comment]
@Sri-Boddupalli  -- links to the 32-bit and 64-bit MSI installers available here -- [Install Microsoft Teams using Microsoft Endpoint Configuration Manager](https://docs.microsoft.com/MicrosoftTeams/msi-deployment)
