### ISSUE TITLE
Support deadline is incorrect

### ISSUE THREAD

**Issue by TomoharuMisawa** [MicrosoftDocs/OfficeDocs-DeployOffice#77]
日本語訳のOffice 365 ProPlus の半期の機能リリースのサポート期間、Version1803の期間が2019/3までとなっている。
原文
2018 年 7 月まで 半期チャネル で利用可能となる予定で、半期チャネル で 2019 年 3 月までサポートされます。
正しくは以下
2018 年 7 月まで 半期チャネル で利用可能となる予定で、半期チャネル で 2019 年 9 月までサポートされます。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 0cd85e3b-e780-457e-9502-856bc6315bca
* Version Independent ID: 416e351f-13c5-e951-ea81-1650910a7c25
* Content: [Office 365 ProPlus 更新プログラムのチャネルの概要](https://docs.microsoft.com/ja-jp/DeployOffice/overview-of-update-channels-for-office-365-proplus#feedback)
* Content Source: [DeployOffice/overview-of-update-channels-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice-pr.ja-JP/blob/live-sxs/DeployOffice/overview-of-update-channels-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Thank you for your feedback. The support duration information in the article was only intended to be an example. But I should update the information to a more current example and make it clearer it's only an example. Information about the most current versions for each update channel is available here:  [Release information for updates to Office 365 ProPlus](https://docs.microsoft.com/officeupdates/release-notes-office365-proplus).
