### ISSUE TITLE
domain accounts with single sign on combined with 1 shared local student account for offline work

### ISSUE THREAD

**Issue by cvermeir** [MicrosoftDocs/OfficeDocs-DeployOffice#770]
In normal circumstances our studens sign on different schoolcomputers whitin the domain and get registred at the office365 with their account and can fully work with office thanks to the shared computer activation installation of office365 apps. Sometimes there's an outage of the internet/wifi, or laptops are being used outside the school on projects without wifi. For those situations we have made a single student account that every student can access, but within this general student account we would like to register the office365 to the device. Is there a way so we deploy our schoolcomputers with both options, or are there other sollutions to get a fully operational office on an offline computer with office365 installed with shared computer activation? The only ugly hack we are looking at now is to copy the token at %localappdata%\Microsoft\Office\16.0\Licensing from the domain account to the local computer student account, but then accounts are probably comprimised when the lokal computer student account is used when there is internet available and not only in the backup situation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ab31873-7ad3-afde-3c72-8a7fb4f2e551
* Version Independent ID: 19f7f483-9f53-f577-1cd4-d360c0b234fc
* Content: [Overview of shared computer activation for Microsoft 365 Apps](https://docs.microsoft.com/en-us/deployoffice/overview-shared-computer-activation#feedback)
* Content Source: [DeployOffice/overview-shared-computer-activation.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-shared-computer-activation.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by MJP-MSFT** [comment]
> In normal circumstances our studens sign on different schoolcomputers whitin the domain and get registred at the office365 with their account and can fully work with office thanks to the shared computer activation installation of office365 apps. Sometimes there's an outage of the internet/wifi, or laptops are being used outside the school on projects without wifi. For those situations we have made a single student account that every student can access, but within this general student account we would like to register the office365 to the device. Is there a way so we deploy our schoolcomputers with both options, or are there other sollutions to get a fully operational office on an offline computer with office365 installed with shared computer activation? The only ugly hack we are looking at now is to copy the token at %localappdata%\Microsoft\Office\16.0\Licensing from the domain account to the local computer student account, but then accounts are probably comprimised when the lokal computer student account is used when there is internet available and not only in the backup situation.
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 8ab31873-7ad3-afde-3c72-8a7fb4f2e551
> * Version Independent ID: 19f7f483-9f53-f577-1cd4-d360c0b234fc
> * Content: [Overview of shared computer activation for Microsoft 365 Apps](https://docs.microsoft.com/en-us/deployoffice/overview-shared-computer-activation#feedback)
> * Content Source: [DeployOffice/overview-shared-computer-activation.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-shared-computer-activation.md)
> * Service: **o365-proplus-itpro**
> * GitHub Login: @jwhit-MSFT
> * Microsoft Alias: **jwhit**

First off, thank you for reaching out. SCA is designed for shared devices that well connected. The issue here is that when these devices go offline for more than 30 days SCA will be forced to activate again. Your method of copying the token over may not work due to validation of the accounts in the token and on the device.  For the roaming devices that leave the network I would suggest using Device Based Subscriptions this would activate the device and then allow the end user to sign in with their Office 365 credentials to get access to documents and content. 

We also made licensing improvements in 1910+ of Office that will rollover the leat used device and allow the use of subscription activation.  In either scenario you should be able to use Office for the lifetime of the token or remaining grace.
