### ISSUE TITLE
token based licence?

### ISSUE THREAD

**Issue by cvermeir** [MicrosoftDocs/OfficeDocs-DeployOffice#772]
Is the licence token based (same way as user-based licensing) and can the office be fully used on an offline computer for as long as 30 days? Or can the device operate offline with full office as long it is once verified?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: e52eb9c1-1755-bec5-4ad8-6df59779e041
* Version Independent ID: 10e4cf5d-ea61-806e-f226-1e14265eabe1
* Content: [Device-based licensing for Microsoft 365 Apps for enterprise](https://docs.microsoft.com/nl-nl/deployoffice/device-based-licensing)
* Content Source: [DeployOffice/device-based-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/device-based-licensing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by MJP-MSFT** [comment]
> Is the licence token based (same way as user-based licensing) and can the office be fully used on an offline computer for as long as 30 days? Or can the device operate offline with full office as long it is once verified?
> 
> #### Documentdetails
> ⚠ _Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub._
> 
> * ID: e52eb9c1-1755-bec5-4ad8-6df59779e041
> * Version Independent ID: 10e4cf5d-ea61-806e-f226-1e14265eabe1
> * Content: [Device-based licensing for Microsoft 365 Apps for enterprise](https://docs.microsoft.com/nl-nl/deployoffice/device-based-licensing)
> * Content Source: [DeployOffice/device-based-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/device-based-licensing.md)
> * Service: **o365-proplus-itpro**
> * GitHub Login: @jwhit-MSFT
> * Microsoft Alias: **jwhit**

The license with Device Based Licensing will activate the device itself and does not tie to the user. If a Users chooses to sign in to gain access to their documents they can but it's not required. The device will need connectivity to validate at least once every 30 days similar to User based licensing.   If you want long term offline state I would suggest Office 2019.
