### ISSUE TITLE
Tip

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/OfficeDocs-DeployOffice#775]
Microsoft 365 admin center with your admin account, and then go to Show all &gt; Settings &gt; Settings &gt; Services.
I think right now it's Settings &gt; Org settings &gt; Services &gt; ‎Office‎ software download settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ae73873-0e39-3fab-4d9d-3129f7f32345
* Version Independent ID: 3b5ba9ae-756a-149d-81e6-5eda13bf15e6
* Content: [Manage software download settings in Office 365](https://docs.microsoft.com/en-us/deployoffice/manage-software-download-settings-office-365)
* Content Source: [DeployOffice/manage-software-download-settings-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/manage-software-download-settings-office-365.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
Thanks, I've created PR #776 to address this issue.

**Comment by DHB-MSFT** [comment]
@hwkwicre -- Yes, the UI in the Microsoft 365 admin center was updated yesterday afternoon (Tuesday 12 May), and we are planning to update all references in our documentation today.
