### ISSUE TITLE
Azure AD nested security group

### ISSUE THREAD

**Issue by iaasazure** [MicrosoftDocs/OfficeDocs-DeployOffice#777]
Please could you explain if a nested Azure AD security group is supported for applying policy, the article does not cover this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa63a94-daaa-9491-213e-f0329f6299b1
* Version Independent ID: 47fe5a3a-ee7c-a7f7-b913-ca0ac3c063e0
* Content: [Overview of the Office cloud policy service for Microsoft 365 Apps for enterprise](https://docs.microsoft.com/en-us/deployoffice/overview-office-cloud-policy-service#feedback)
* Content Source: [DeployOffice/overview-office-cloud-policy-service.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-office-cloud-policy-service.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by chhopkin** [comment]
OCPS supports Security groups, Mail Enabled Security groups and Distribution groups created in Azure AD.  The membership type can be either Dynamic or Assigned.

If users are located in nested groups and the parent group is targeted for policies in OCPS, the users in the nested groups will receive the policies.

**Comment by jwhit-MSFT** [comment]
Worked with Chris to update the article--thanks for catching this, iaasazure. Note that we've revised the above comment to:

Office cloud policy service supports security groups and mail-enabled security groups created. [Distribution groups are not supported.]
