### ISSUE TITLE
Copy policy is limited

### ISSUE THREAD

**Issue by iaasazure** [MicrosoftDocs/OfficeDocs-DeployOffice#778]
Please note that when using the copy policy feature many configured items to not copy between the policy. For example I can copy a policy with 20 configured settings, only 5 are copied to the new policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa63a94-daaa-9491-213e-f0329f6299b1
* Version Independent ID: 47fe5a3a-ee7c-a7f7-b913-ca0ac3c063e0
* Content: [Overview of the Office cloud policy service for Microsoft 365 Apps for enterprise](https://docs.microsoft.com/en-us/deployoffice/overview-office-cloud-policy-service#feedback)
* Content Source: [DeployOffice/overview-office-cloud-policy-service.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-office-cloud-policy-service.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by manoth-msft** [comment]
This is a known issue that is already being worked on. Should be resolved soon.

**Comment by chhopkin** [comment]
This issue is now resolved.
