### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by umairaziz112221** [MicrosoftDocs/OfficeDocs-DeployOffice#781]
Data protection 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e7b617d-911f-ca64-1ce2-08f0c8414cac
* Version Independent ID: 1e5fe5fa-7ae7-da70-0883-03146eef9a6b
* Content: [Use policy settings to manage privacy controls for Office on Android devices](https://docs.microsoft.com/en-us/deployoffice/privacy/android-privacy-controls#feedback)
* Content Source: [DeployOffice/privacy/android-privacy-controls.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/android-privacy-controls.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@umairaziz112221 -- Which link in this article is broken?

**Comment by RAJU2529** [comment]
@umairaziz112221 . From my testing, all links are working fine.

**Comment by DHB-MSFT** [comment]
@RAJU2529  -- Thanks for checking. We checked as well and links are working for us.
