### ISSUE TITLE
Undocumented use of TargetProduct attribute (part of Language element)

### ISSUE THREAD

**Issue by bmkaiser** [MicrosoftDocs/OfficeDocs-DeployOffice#783]
This document makes use of the `TargetProduct` attribute in the section **How to build and benefit from building dynamic, lean, and universal packages**. It seems useful, but is not documented as part of the [Configuration options for the Office Deployment Tool](https://docs.microsoft.com/en-us/DeployOffice/office-deployment-tool-configuration-options#language-element) document. It's unclear if this attribute is deprecated or just missing from the ODT Configuration Options document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b29550a-6478-1a72-8189-182fc3fa28dd
* Version Independent ID: 2133ba3d-a9e4-5618-40f0-d7d4ccc3496c
* Content: [Build dynamic, lean, universal packages for Microsoft 365 Apps for enterprise](https://docs.microsoft.com/en-us/DeployOffice/fieldnotes/build-dynamic-lean-universal-packages)
* Content Source: [DeployOffice/fieldnotes/build-dynamic-lean-universal-packages.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/fieldnotes/build-dynamic-lean-universal-packages.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @manoth-msft
* Microsoft Alias: **manoth**

**Comment by manoth-msft** [comment]
Point taken. It is documented in https://docs.microsoft.com/en-us/DeployOffice/overview-deploying-languages-microsoft-365-apps, but I will update the ODT options article to also include the MatchInstalled+TargetProduct functionality.

**Comment by manoth-msft** [comment]
Submitted #785 and #786 with updates to the description

**Comment by bmkaiser** [comment]
Thank you, @manoth-msft! I didn't realize this was documented elsewhere. Your submitted commits look like they do a good job of connecting the dots between existing docs and adding clarification for how best to use this attribute.
