### ISSUE TITLE
Minimum version needed to use Monthly Enterprise Channel?

### ISSUE THREAD

**Issue by sdxfuj** [MicrosoftDocs/OfficeDocs-DeployOffice#787]
It's unclear in the docs if you require a specific minimum version of existing 365 apps deployed on the clients if you intend to switch the client channel via GPO to the new enterprise monthly channel. So is there a minimum version required for the updater engine to recognize this new channel? If yes, from what version in each channel will the new monthly enterpirse channel be recognized and honored?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cd85e3b-e780-457e-9502-856bc6315bca
* Version Independent ID: 416e351f-13c5-e951-ea81-1650910a7c25
* Content: [Overview of update channels for Microsoft 365 Apps](https://docs.microsoft.com/en-us/deployoffice/overview-update-channels)
* Content Source: [DeployOffice/overview-update-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-update-channels.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
I suggest to also check out https://docs.microsoft.com/en-us/deployoffice/update-channels-changes#new-names-for-the-existing-update-channels. The latest release of the ODT is sufficient: "You can start using the MonthlyEnterprise attribute value on May 12, 2020. The most current version of the Office Deployment Tool available on the Microsoft Download Center supports using that new value."

Hope this helps.

**Comment by sdxfuj** [comment]
The question asks for existing installations, not new deployments. The existing deployment is never touched by ODT again, they're only managed by GPO. Which means that the answer isn't applicable in this scenario. But it might answer someone elses question though. :)

**Comment by sdxfuj** [comment]
To answer my own question at least partially: Lab tests show that a client that was running a build of version 1910 was unable to update at all when the GPO was set to the Monthly Enterprise Channel. However, the client could auto-update again once the GPO was set to the Current channel. Conclusion: There is a minimum software version requirement, but which version?

**Comment by DHB-MSFT** [comment]
@sdxfuj -- We'll check with the product team on this.  What channel are you using with Version 1910?  Because Version 1910 isn't a supported version for any of the update channels based on the information in the table in this article --  [Update history for Microsoft 365 Apps (listed by date)](https://docs.microsoft.com/en-us/officeupdates/update-history-microsoft365-apps-by-date)

**Comment by stdin82** [comment]
Monthly Enterprise Channel exist since January 14, 2020
that's Version 1912 (Build 12325.20298) for Monthly channel

**Comment by DHB-MSFT** [comment]
@stdin82 -- the first generally available version of Monthly Enterprise Channel is Version 2003, which was released on 12 May 2020.

**Comment by manoth-msft** [comment]
When using GPO, any version newer than 1912 will understand the new channel name.
