### ISSUE TITLE
Step 2 where does service settings exist?

### ISSUE THREAD

**Issue by Typhoon87** [MicrosoftDocs/OfficeDocs-DeployOffice#79]
2.Go to the Office 365 admin center, and then choose Service Settings &gt; User software. 

In the Admin console I do not see anything called "service settings" is it possible the name has changed but this document has not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e681974-a3d2-8052-347c-a7ca4a3016ab
* Version Independent ID: 03874918-ff15-099a-a688-6a4969b7c691
* Content: [What's new for admins in Office 2016 for Mac](https://docs.microsoft.com/en-us/deployoffice/mac/what-s-new-for-admins-in-office-for-mac)
* Content Source: [DeployOffice/mac/what-s-new-for-admins-in-office-for-mac.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/mac/what-s-new-for-admins-in-office-for-mac.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
There isn't a Step 2 in this article. Did you intend to leave this comment on a different article? If so, which one?  Thanks.

**Comment by Typhoon87** [comment]
Oops yes should be for this page  
https://docs.microsoft.com/en-us/deployoffice/mac/deployment-options-for-office-for-mac



I poked around the O365 console some more and still do not see it. Even using the search do it appears to no longer exist or have been renamed.

**Comment by DHB-MSFT** [comment]
Ah yes, they've moved some pages around and renamed some things. Sorry about that. I think this is what you're looking for:

On Home page of the Office 365 admin center, in the "Office software" section, choose "Software download settings." Near the top of that page, click on the "Manually deploy user software" link. On that page, expand the "Install Office 2016 for Mac" section and click on the Install button. You should get a pop up to Open/Save/Cancel. Choose Save.

You can always download the latest version from the [Updated history for Office for Mac](https://docs.microsoft.com/officeupdates/update-history-office-for-mac) page.

Hope that helps.

**Comment by Typhoon87** [comment]
That seems to be what im looking for. Thanks

May want to update that doc for anyone else looking for the same.

**Comment by DHB-MSFT** [comment]
Glad I could be of assistance. Thanks for bringing this to our attention. We'll get the content updated.
