### ISSUE TITLE
OneDrive still get installed when excluded

### ISSUE THREAD

**Issue by kpropell** [MicrosoftDocs/OfficeDocs-DeployOffice#794]
Even if we exclude everything OneDrive related, it get's installed:

&lt;ExcludeApp ID="Groove" /&gt;
&lt;ExcludeApp ID="OneDrive" /&gt;

Can this be fixed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a0b1ff-0498-505a-6024-b813980d310f
* Version Independent ID: b8057930-b4bd-1304-17ce-5561f837e901
* Content: [Configuration options for the Office Deployment Tool](https://docs.microsoft.com/en-us/deployoffice/office-deployment-tool-configuration-options)
* Content Source: [DeployOffice/office-deployment-tool-configuration-options.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office-deployment-tool-configuration-options.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by manoth-msft** [comment]
Please note that OneDrive is already embedded in Windows 10, so maybe the OneDrive instance you see isn't coming through Microsoft 365 Apps. Is the icon shown on the splash screen during install?

**Comment by kpropell** [comment]
The OneDrive icon is not shown on the splash screen during install. I observe Apps & Features during the installation, and see that OneDrive does get installed. On the image I deploy Windows 10 from, I can confirm that OneDrive is not present in Apps & Features and under AppData for any user, so OneDrive do get installed from Office Deployment-tool even if it is Excluded.

**Comment by manoth-msft** [comment]
As this issue is not related to the documentation itself, I would recommend to post to https://techcommunity.microsoft.com/t5/microsoft-365-apps-for/bd-p/Microsoft365Apps w/ the config.xml used and the actual build of Microsoft 365 Apps.
