### ISSUE TITLE
Typo for Enabled attribute (part of Updates element)

### ISSUE THREAD

**Issue by AneurinHsu** [MicrosoftDocs/OfficeDocs-DeployOffice#795]
As bold line below:

Enabled attribute (part of Updates element)
Optional. The default value is TRUE if not specified.

If set to TRUE, Office will check for updates. If set to FALSE, Office won't check for updates, but the user can check for updates by going to File > Account > Update Options > Update Now.

Allowed values:

Enabled="TRUE"
**Enabled="FALSE"**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a0b1ff-0498-505a-6024-b813980d310f
* Version Independent ID: b8057930-b4bd-1304-17ce-5561f837e901
* Content: [Configuration options for the Office Deployment Tool](https://docs.microsoft.com/en-us/deployoffice/office-deployment-tool-configuration-options)
* Content Source: [DeployOffice/office-deployment-tool-configuration-options.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office-deployment-tool-configuration-options.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by RAJU2529** [comment]
@AneurinHsu . I could not able to find  any typo error in the following paragraphs

Enabled attribute (part of Updates element)
Optional. The default value is TRUE if not specified.

If set to TRUE, Office will check for updates. If set to FALSE, Office won't check for updates, but the user can check for updates by going to File > Account > Update Options > Update Now.

Allowed values:

Enabled="TRUE"
Enabled="FALSE"

**Comment by AneurinHsu** [comment]
Ah, I think I misunderstood it. Thanks!

VARADHARAJAN K <notifications@github.com> 於 2020年5月26日 週二 12:33 寫道：
