### ISSUE TITLE
What about consumer "Monthly Channel"

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/OfficeDocs-DeployOffice#796]
I understand this documentation is intended primarily for Business license users, but many consumers find their way here.  This page does not mention the consumer "Monthly Channel". I assume it is equivalent to the "Current Channel" documented, but it would be nice to make the difference explicitly clearn. 
.
Don't forget, many SMBs still use Windows Home and try to sneak in using 365 Home. 
[Enter feedback here]

PS: forcing us to sign into github sucks. Why aren't you using the standard Feedback Hub / UserVoice? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cd85e3b-e780-457e-9502-856bc6315bca
* Version Independent ID: 416e351f-13c5-e951-ea81-1650910a7c25
* Content: [Overview of update channels for Microsoft 365 Apps](https://docs.microsoft.com/en-us/deployoffice/overview-update-channels)
* Content Source: [DeployOffice/overview-update-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-update-channels.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
We are about to rename the "Monthly Channel" to "Current Channel", so both channels are basically the same. There is also no distinction between "consumer" and "business" user, the channels are the same for both audiences. Check out https://docs.microsoft.com/en-us/deployoffice/update-channels-changes

**Comment by Ronsss** [comment]
You are missing the point. That documentation is corporate only. There is
no mention of consumer channels, specifically "Monthly Channel" being
changed into anything.  The closest they mention is "
"monthly Enterprise Channel"  which is NOT the same! You make buckets of
money from consumer products, how about documenting them!

**Comment by DHB-MSFT** [comment]
@Ronsss -- The only update channels that apply to versions of Office that come with consumer Microsoft 365 plans (such as Microsoft 365 Personal) are the following (using the new names): Current Channel, Current Channel (Preview), and Beta Channel. Consumer versions of Office are set to Current Channel by default. To choose the other 2 update channels, you can go to File > Account and select the Office Insider tile.  We'll add a note to this article to make it clear which update channels apply to consumer versions of Office.

**Comment by Ronsss** [comment]
Thank you I appreciate that.
So consumer "Monthly Channel" which I have. will become "Current Channel"?

**Comment by DHB-MSFT** [comment]
@Ronsss -- Yes, Monthly Channel is changing its name to Current Channel. For both consumer and commercial customers, since it's the exact same channel for both groups of customers.

**Comment by DHB-MSFT** [comment]
@Ronsss -- we've added a mention of the consumer SKUs to the "channel overview" article:

![image](https://user-images.githubusercontent.com/32883970/84165765-ea079280-aa28-11ea-9afa-06b00572859c.png)

https://docs.microsoft.com/en-us/deployoffice/overview-update-channels#additional-information-about-update-channels-for-microsoft-365-apps
