### ISSUE TITLE
Group Policies to enable shared computer activation | supported: Yes/No ? 

### ISSUE THREAD

**Issue by CKITNLD** [MicrosoftDocs/OfficeDocs-DeployOffice#798]
Hi, 

First, thanks for publishing this article. 

However, there was something about Group Policies which was not clear. Between the first note and second note:

Note #1:
_- The Microsoft 365 Business Premium plan is the only business plan that includes support for shared computer activation. There are other business plans, such as Microsoft 365 Business Standard, that include Microsoft 365 Apps for business, But, those business plans don't include support for shared computer activation.
**- Microsoft 365 Apps for business doesn't doesn't support the use of Group Policy, so you'll need to use another method to enable shared computer activation.**
- Shared computer activation isn't available for Office for Mac._

and Note #2:
_Here are some other ways that you can **enable shared computer activation**:

- Download and run the Microsoft Support and Recovery Assistant.
**- **Use Group Policy** by downloading the most current Administrative Template files (ADMX/ADML) for Office and enabling the "Use shared computer activation" policy setting. This policy setting is found under Computer Configuration\Policies\Administrative Templates\Microsoft Office 2016 (Machine)\Licensing Settings.**
- Use Registry Editor to add a string value (Reg_SZ) of SharedComputerLicensing with a setting of 1 under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration._

In the **first note** you mentioned that Group Policy is **not supported** to enable shared computer activation. Then in the **second note** you mentioned that the use of Group Policy is a way **enable shared computer activation**. 
This is confusing. 

Could you please elaborate? 
Thank you

Regards, 
Chi-Kit Tse - CKIT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ab31873-7ad3-afde-3c72-8a7fb4f2e551
* Version Independent ID: 19f7f483-9f53-f577-1cd4-d360c0b234fc
* Content: [Overview of shared computer activation for Microsoft 365 Apps](https://docs.microsoft.com/en-us/deployoffice/overview-shared-computer-activation)
* Content Source: [DeployOffice/overview-shared-computer-activation.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-shared-computer-activation.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by manoth-msft** [comment]
Group Policies are a supported method to enable Shared Computer Activation **as long as** the Office license supports group policies. So if your are running Microsoft 365 Apps for business premium or Microsoft 365 Apps for enterprise you can use group policies, that's why these are listed. For other licenses it doesn't work, as those do not support group policies.

**Comment by manoth-msft** [comment]
I've created PR #805 to incorporate your feedback into the deck.
