### ISSUE TITLE
No link or info about OCT

### ISSUE THREAD

**Issue by ciphernemo** [MicrosoftDocs/OfficeDocs-DeployOffice#80]
Where is the additional links or information on the Office Customization Tool? Nothing here in this article. Very weak.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3fc30fd-858c-d1cd-0729-6eb72ef7975a
* Version Independent ID: aa690d1d-8e25-6de1-9a83-7acd851fed7a
* Content: [Deployment guide for Visio 2016](https://docs.microsoft.com/en-us/deployoffice/deployment-guide-for-visio)
* Content Source: [DeployOffice/deployment-guide-for-visio.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deployment-guide-for-visio.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
You can find some info about the OCT here -- [Office Customization Tool (OCT) 2016 Help: Overview](https://docs.microsoft.com/en-us/deployoffice/oct/oct-2016-help-overview). I'll add a link to that in this article. Thanks for the feedback.
