### ISSUE TITLE
AllowCdnFallback Not Working

### ISSUE THREAD

**Issue by rimetree** [MicrosoftDocs/OfficeDocs-DeployOffice#807]
I'm finding that with the CDN fallback set, and my existing Office installation has English and Finnish languages, that the installation fails because a required file is missing. The log points to the CAB files associated with the Finnish language. The article suggests the ODT will get what it needs from the CDN, but that isn't happening.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3eacd91-ad3e-79a3-d946-0fa33785b7ee
* Version Independent ID: 0e5a2663-78b8-6068-2e80-cd472a72d7b1
* Content: [Change a Microsoft 365 Apps installation from 32-bit to 64-bit](https://docs.microsoft.com/en-us/deployoffice/change-bitness)
* Content Source: [DeployOffice/change-bitness.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/change-bitness.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
Please post the description, your XML and a screenshot of the folder holding your setup.exe and config file to https://techcommunity.microsoft.com/t5/microsoft-365-apps-for/bd-p/Microsoft365Apps. We can help you better over there than here on GitHub. Thanks.

**Comment by rimetree** [comment]
Will do, and thanks for the quick response

**Comment by DHB-MSFT** [comment]
Discussion moved to TechCommunity -- https://techcommunity.microsoft.com/t5/microsoft-365-apps-for/migratearch-allowcdnfallback-not-getting-missing-content-from/m-p/1457303
