### ISSUE TITLE
Business Premium RDS clarification

### ISSUE THREAD

**Issue by WoutVergauwen** [MicrosoftDocs/OfficeDocs-DeployOffice#808]
Hi,
I believe the note about Business Premium should have some additional info about RDS installs for that version. As far as I'm aware, Business Premium does not include the right to install on an RDS server (https://docs.microsoft.com/en-us/DeployOffice/deploy-microsoft-365-apps-remote-desktop-services), I feel that's something that should be pointed out in that note as well, as the most common scenario for shared computer licensing is RDS.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ab31873-7ad3-afde-3c72-8a7fb4f2e551
* Version Independent ID: 19f7f483-9f53-f577-1cd4-d360c0b234fc
* Content: [Overview of shared computer activation for Microsoft 365 Apps](https://docs.microsoft.com/en-us/DeployOffice/overview-shared-computer-activation)
* Content Source: [DeployOffice/overview-shared-computer-activation.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-shared-computer-activation.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by manoth-msft** [comment]
Thanks for the feedback. We submitted PR #8051 to clarify that piece. Thanks for highlighting!
