### ISSUE TITLE
M365 Business Premium RDS

### ISSUE THREAD

**Issue by WoutVergauwen** [MicrosoftDocs/OfficeDocs-DeployOffice#809]
Hi,
According to this post: https://techcommunity.microsoft.com/t5/small-and-medium-business-blog/shared-computer-activation-for-office-in-microsoft-365-business/ba-p/472994
M365 Business premium is allowed to be installed on RDS, so it's not just M365 apps for Enterprise that's allowed?

thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6da18a8b-9e96-0155-7b30-9c211070d793
* Version Independent ID: 5a7e610a-bfcb-d9cc-03f7-589d970128d9
* Content: [Deploy Microsoft 365 Apps by using Remote Desktop Services](https://docs.microsoft.com/en-us/deployoffice/deploy-microsoft-365-apps-remote-desktop-services)
* Content Source: [DeployOffice/deploy-microsoft-365-apps-remote-desktop-services.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-microsoft-365-apps-remote-desktop-services.md)
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
Thanks for the feedback. We submitted PR #811 to clarify that Microsoft 365 Apps for Business is supported on RDS if a Microsoft 365 Business plan is in place. We also reviewed the whole article and updated references to Microsoft 365 Apps instead of Microsoft 365 Apps for enterprise.
