### ISSUE TITLE
Poor wording - HyperV requirement

### ISSUE THREAD

**Issue by jantoney** [MicrosoftDocs/OfficeDocs-DeployOffice#810]
Hey,

The following line shouldn't be included on the page, or should be re-worded.
**A server that supports Hyper-V if you're deploying Microsoft 365 Apps for enterprise on a shared virtual machine.**

The line implies that you're only licensed to run *Microsoft 365 Apps for Enterprise* on Hyper-V and can't use ESXi. I've just had a discussion with Microsoft Licensing and their reply is below.

> Typically, when a customer navigates to a Microsoft technical/product website, it is going to promote/encourage you to use Microsoft components, not a 3rd party product. If the licensing says that you need to use Hyper-V, then you are required to use Hyper-V. If it says nothing about Hyper-V, then you are free to use a 3rd party technology. Microsoft typically stays out of saying what technology you should use in legal documentation. **There is no reference in the OST stating that a specific Hyper Visor is needed, just that it can be installed and used with shared computer activation on a Network Server (yellow).**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6da18a8b-9e96-0155-7b30-9c211070d793
* Version Independent ID: 5a7e610a-bfcb-d9cc-03f7-589d970128d9
* Content: [Deploy Microsoft 365 Apps by using Remote Desktop Services - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/deploy-microsoft-365-apps-remote-desktop-services)
* Content Source: [DeployOffice/deploy-microsoft-365-apps-remote-desktop-services.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-microsoft-365-apps-remote-desktop-services.md)
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
Thanks for your feedback. I've incorporated it into PR #811, clarifying that Microsoft supports Hyper-V as a hypervisor only, but Office will not refuse from running on other hypervisors (but being unsupported in these cases).
