### ISSUE TITLE
Question about policy priority (non-configured)

### ISSUE THREAD

**Issue by Michai901** [MicrosoftDocs/OfficeDocs-DeployOffice#816]
I got 2 groups each with its own policy.
If a user is member of both groups will he basically have the policy settings of the "higher" group exclusively or is it a mix of the 2 groups hes a member of. The question is specifically targeted at non-configured policies.

Like lets say Group with Prio 0 has: Connected experiences: non-configured
Group with prio 1 (lower) has: Deactivated

Would the user have it deactivated or activated ?

**Comment by manoth-msft** [comment]
Hi, https://techcommunity.microsoft.com/t5/microsoft-365-apps-for/bd-p/Microsoft365Apps is the best place to drop this kind of questions. Anyway, the priority is calculated per setting for enabled/disabled settings. So in your example, the net result for the user would be "deactivated". It would be "activated", when the setting in Group 0 would be "activated".
