### ISSUE TITLE
New attribute value vs. Previous attribute value

### ISSUE THREAD

**Issue by brucesp1** [MicrosoftDocs/OfficeDocs-DeployOffice#817]
[Enter feedback here]
I strongly suspect the values listed in the table concerning "New attribute value and Previous attribute value" for the channel is backwards.  I just built a new deployment, and the channel is listed as Broad, where the configuration.xml I had from a few months ago says SemiAnnual.  Your chart here says the NEW attributes include SemiAnnual etc. and the PREVIOUS lists Broad.  Isn't this backwards?

Bruce

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65a95a12-d57e-291b-3042-3012ebd7e4a2
* Version Independent ID: 3f096623-9336-3cf5-f6ef-5c63b888e8fc
* Content: [Changes to update channels for Microsoft 365 Apps - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/update-channels-changes)
* Content Source: [DeployOffice/update-channels-changes.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/update-channels-changes.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@brucesp1 -- the values in the table are correct. What tool are using to build your new deployment?

**Comment by brucesp1** [comment]
I am using ConfigManager. You know what though I think I made a mistake here, if I compare xml files it looks like the package I made in May says Channel="Broad" and the new one I just made this morning says Channel="SemiAnnual" 

so disregard that I guess. My mistake.

**Comment by DHB-MSFT** [comment]
@brucesp1 -- Thanks for double-checking. Keep in mind that the previous values will still work, so you don't have to go back and update older xml files.
