### ISSUE TITLE
office 2019 download link is not working

### ISSUE THREAD

**Issue by kishoreg1980** [MicrosoftDocs/OfficeDocs-DeployOffice#826]
[Enter feedback here]
Seems same download link is given for both office 365 and office 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33efc383-9a47-6dea-b81e-898246773b23
* Version Independent ID: 3237227f-5c43-8fc9-4ca4-0e8c02bf496d
* Content: [Deployment options for admins for Office for Mac - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/mac/deployment-options-for-office-for-mac)
* Content Source: [DeployOffice/mac/deployment-options-for-office-for-mac.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/mac/deployment-options-for-office-for-mac.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@kishoreg1980 -- Office for Mac (the Office 365 version) and Office 2019 use the same download.  In the Note section right below the download links, we mention that:

_The same installer package is used for Office for Mac and Office 2019 for Mac. How you activate the product determines whether you get the features for Office for Mac or the features for Office 2019 for Mac._

Does that help?

**Comment by kishoreg1980** [comment]
Could you plz let me know the activation procedures to get office 2019.
    On Wednesday, 8 July, 2020, 10:21:19 pm IST, Daniel H. Brown <notifications@github.com> wrote:  
 
 


@kishoreg1980 -- Office for Mac (the Office 365 version) and Office 2019 use the same download. In the Note section right below the download links, we mention that:

The same installer package is used for Office for Mac and Office 2019 for Mac. How you activate the product determines whether you get the features for Office for Mac or the features for Office 2019 for Mac.

Does that help?

**Comment by DHB-MSFT** [comment]
@kishoreg1980 -- 

- For a business, use this information -- [Activate volume licensed versions of Office for Mac](https://docs.microsoft.com/deployoffice/mac/overview-of-activation-for-office-for-mac#activate-volume-licensed-versions-of-office-for-mac).  

- For a home/personal version, use this information -- [Activate Office for Mac](https://support.microsoft.com/office/activate-office-for-mac-7f6646b1-bb14-422a-9ad4-a53410fcefb2).
