### ISSUE TITLE
Misleading Licence Requirements

### ISSUE THREAD

**Issue by Tularis1** [MicrosoftDocs/OfficeDocs-DeployOffice#835]
The Line "A Microsoft 365 Business plan that includes Microsoft 365 Apps for Business." Is Misleading!!
Shared Activation This will only work with "A Microsoft 365 Business Premium" Plan. 

If you have a  "Microsoft 365 business standard" Plan which includes "Microsoft 365 Apps for Business" this will not activate Office Apps in Shared Activation Mode

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6da18a8b-9e96-0155-7b30-9c211070d793
* Version Independent ID: 5a7e610a-bfcb-d9cc-03f7-589d970128d9
* Content: [Deploy Microsoft 365 Apps by using Remote Desktop Services - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/deploy-microsoft-365-apps-remote-desktop-services)
* Content Source: [DeployOffice/deploy-microsoft-365-apps-remote-desktop-services.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-microsoft-365-apps-remote-desktop-services.md)
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
Thanks for highlighting this. We've submitted a fix to the doc in #851
