### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by clamb123** [MicrosoftDocs/OfficeDocs-DeployOffice#839]
[Enter feedback here]
Web page says:

You must be running at least version 15.0.4605.1003 of Microsoft 365 Apps, which was released in April 2014, to use the following policy settings: Hide update notifications, Target version, Update deadline, and Update path. To determine which version of Microsoft 365 Apps is installed on a user's computer, go to File > Account in any Office program. **The version is listed under the Office Updates section.**

The major version is not listed in the office updates section, only under "About Word" (or other app I'd guess).

Next page I read has it right!

To determine which version of Microsoft 365 Apps is installed on a user's computer, go to File > Account in any Office program. The version is listed under the About section. For example, in Excel, under the About Excel section.
https://docs.microsoft.com/en-us/deployoffice/overview-update-process-microsoft-365-apps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 601039de-64e0-6f70-a5c6-f569f7d0cf87
* Version Independent ID: 861e9906-f260-fdcd-9bba-eb86056e51bd
* Content: [Configure update settings for Microsoft 365 Apps - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/configure-update-settings-microsoft-365-apps)
* Content Source: [DeployOffice/configure-update-settings-microsoft-365-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/configure-update-settings-microsoft-365-apps.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by DHB-MSFT** [comment]
@clamb123 -- Thanks for pointing that out. We've gone ahead and removed that section from the article. The minimum version information isn't really relevant anymore since all versions of Microsoft 365 Apps that are currently supported can make use of those of policy settings.
