### ISSUE TITLE
Registry path is not correct

### ISSUE THREAD

**Issue by FullStackEngN** [MicrosoftDocs/OfficeDocs-DeployOffice#840]
[
At the page end, it mentioned registry path, but it seems like it missed "Cloud" in the path.
For example, the document use "HKEY_CURRENT_USER\Software\Policies\Microsoft\office\16.0\common\privacy".
But when I did test, I found the registry is "HKEY_CURRENT_USER\Software\Policies\Microsoft\Cloud\office\16.0\common\privacy"

Please help double confirm.
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef4debee-6a1e-53c7-7bec-2dbd208f4f2d
* Version Independent ID: b93ad6a2-0976-6f5f-7aae-1756079bdc1d
* Content: [Use policy settings to manage privacy controls for Microsoft 365 Apps for enterprise - Deploy Office](https://docs.microsoft.com/en-us/DeployOffice/privacy/manage-privacy-controls)
* Content Source: [DeployOffice/privacy/manage-privacy-controls.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/manage-privacy-controls.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@FullStackEngN -- Did you use [Office cloud policy service](https://docs.microsoft.com/DeployOffice/overview-office-cloud-policy-service) to configure & apply the policy setting? The Office cloud policy service writes settings to the \Cloud\ location in the registry, whereas Group Policy writes settings to the other location listed in the article.

**Comment by FullStackEngN** [comment]
You are right, I test local GPO and it's in the path mentioned in the document.
Thanks. We can close this question.
