### ISSUE TITLE
Please remove Office Feedback from Other Connected Experiences

### ISSUE THREAD

**Issue by HarryEmil** [MicrosoftDocs/OfficeDocs-DeployOffice#841]
Please remove **Office Feedback** from the list under **Other Connected Experiences**. It is not managed by this policy. 

This list is for Data Controller services. Microsoft operates as a Data Processor for feedback and provides separate policies in the Office 365 Client Configuration Service for IT Admins to control availability of feedback and surveys. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9f215c4-d995-2d6c-0693-bca19f66fe2f
* Version Independent ID: a9aa816b-f30d-3bbe-8fdc-204777b25dfe
* Content: [Connected experiences in Office - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/privacy/connected-experiences)
* Content Source: [DeployOffice/privacy/connected-experiences.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/connected-experiences.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
Taking offline with Harry.
