### ISSUE TITLE
Grammatical error in "Activate volume licensed versions of Office by using Active Directory"

### ISSUE THREAD

**Issue by writh** [MicrosoftDocs/OfficeDocs-DeployOffice#842]
Under the heading, "Additional information about Active-Directory based activation," there is a grammatical error. It reads: 

> Active-Directory based activation uses the same keys that are used by Key Management Service (KMS). But Active Directory-based activation doesn't require a dedicated host computer, because the activation object is replicated across all the domain controllers in the Active Directory forest.

When it should read:

> Active-Directory based activation uses the same keys that are used by Key Management Service (KMS), but Active Directory-based activation doesn't require a dedicated host computer, because the activation object is replicated across all the domain controllers in the Active Directory forest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88987141-eb61-186f-ada4-6b8765764737
* Version Independent ID: 9264a57c-554a-c69e-b408-4c3196788ec5
* Content: [Activate volume licensed versions of Office by using Active Directory - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/vlactivation/activate-office-by-using-active-directory)
* Content Source: [DeployOffice/vlactivation/activate-office-by-using-active-directory.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/vlactivation/activate-office-by-using-active-directory.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by writh** [comment]
I created a pull request that resolves this issue.

**Comment by kristyyaeger** [comment]
BWARE76
