### ISSUE TITLE
Include other macro security options for Mac

### ISSUE THREAD

**Issue by primarytyler** [MicrosoftDocs/OfficeDocs-DeployOffice#846]
The docs currently only outline `VisualBasicMacroExecutionState`, but per the Jamf documentation there are a few other settings available as well, such as `VisualBasicEntirelyDisabled` or `DisableVisualBasicExternalDylibs` that don't seem to be documented anywhere in the Microsoft Docs. 

https://docs.jamf.com/technical-papers/jamf-pro/microsoft-office/10.18.0/Appendix_D__Microsoft_Office_Default_Preference_Keys.html

Would be useful to have some official documentation on all the security settings available and details about what the setting values enforce.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49b973ef-56e1-163a-ae00-e0f1ccd0453f
* Version Independent ID: 441f7560-8fe6-e9ac-8754-5b3076d97176
* Content: [Set a preference for macro security in Office for Mac - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/mac/set-preference-macro-security-office-for-mac)
* Content Source: [DeployOffice/mac/set-preference-macro-security-office-for-mac.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/mac/set-preference-macro-security-office-for-mac.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by pbowden-msft** [comment]
@primarytyler - thanks for the feedback! We've now listed the other security related preferences in this article.

**Comment by pbowden-msft** [comment]
@primarytyler - thanks for the feedback! We've now listed the other security related preferences in this article.
