### ISSUE TITLE
Contradict Statement

### ISSUE THREAD

**Issue by chmish95** [MicrosoftDocs/OfficeDocs-DeployOffice#850]
What you need to get started

The following is a list of prerequisites that you need to deploy Microsoft 365 Apps or the Project and Visio desktop apps with RDS:

One of the following plans:
An Office 365 (or Microsoft 365) plan that includes Microsoft 365 Apps for enterprise, purchased through a Volume Licensing Program.
**A Microsoft 365 Business plan that includes Microsoft 365 Apps for Business. // incorrect information** 
For the Project and Visio desktop apps, a subscription plan that includes those products.

**Comment by manoth-msft** [comment]
Thanks for highlighting this. We've submitted a fix to the doc in #851
