### ISSUE TITLE
STOP "Learn More" yellow banner on every page 

### ISSUE THREAD

**Issue by fmutlu** [MicrosoftDocs/OfficeDocs-DeployOffice#853]
This issue has already been reported in November 2019 and despite this it is still not corrected in the last version of OneNote 2016 for the Windows version of Office 365. 
![image](https://user-images.githubusercontent.com/36670071/91773744-a9fb1a80-ebe7-11ea-8084-70498c18eb23.png)

This banner is very annoying. I'm not the only one who complains about it. It coerces the users to change their privacy preferences and that is unacceptable. You have to pay respect to each user's preferences. Please remove it or replace it with a notification that we can hide.  

#485

**Comment by DHB-MSFT** [comment]
@fmutlu -- We have sent this to the OneNote product team for them to investigate.

**Comment by DHB-MSFT** [comment]
Here's a reply back from the OneNote product team:

We have a fix that’s currently rolled out to approximately 50% of customers in Beta Channel (sometimes referred to as Insiders Fast). This fix is bundled with other updates in the client that we’re carefully vetting, so while we expect the fix to eventually reach production channels (starting with Current Channel), we don’t have a committed timeline.
