### ISSUE TITLE
Why!

### ISSUE THREAD

**Issue by wt29** [MicrosoftDocs/OfficeDocs-DeployOffice#855]
Why is there a line - 

"It will look as if nothing is happening, but the download is happening in the background. Once the download is complete, you are returned to a command prompt."

How hard would it be to but a basic progress bar in - these things have been around since 1982 (in DOS at least). Incredulous that you need a dumb line "just wait because we couldn't be bothered putting in any user feedback"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [Deploy Office 2019 (for IT Pros) - Deploy Office](https://docs.microsoft.com/en-us/DeployOffice/office2019/deploy)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
If you have thoughts on how to improve deploying and managing Office, submit your suggestions to the [UserVoice site for Office Deployment Insiders](https://odinsiders.uservoice.com/).
