### ISSUE TITLE
Links are incorrect?

### ISSUE THREAD

**Issue by Skatterbrainz** [MicrosoftDocs/OfficeDocs-DeployOffice#86]
The links on the side bar and within the main content to "Deploy with Configuration Manager (Current Branch)" are actually linked to "https://docs.microsoft.com/sccm/sum/deploy-use/manage-office-365-proplus-updates" which doesn't look correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67f2a4fb-0249-516c-cf08-bcf659d0a529
* Version Independent ID: d3e73e31-7db9-4698-9fa0-ba4ef84d4d94
* Content: [Deploy Office 365 ProPlus with System Center Configuration Manager](https://docs.microsoft.com/en-us/deployoffice/deploy-office-365-proplus-with-system-center-configuration-manager)
* Content Source: [DeployOffice/deploy-office-365-proplus-with-system-center-configuration-manager.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-office-365-proplus-with-system-center-configuration-manager.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by DHB-MSFT** [comment]
Those links are correct as that article does cover how to deploy Office 365 ProPlus by using Configuration Manager (Current Branch). But we are working on consolidating/revising/updating the content for this deployment scenario and we'll have an article for it that will be published in with the other Office 365 ProPlus deployment content on [https://docs.microsoft.com/deployoffice](https://docs.microsoft.com/deployoffice).  Thanks for the comment/feedback.

**Comment by Skatterbrainz** [comment]
You are correct.  I was seeing the "update" string in the URL and it threw me off.  Thank you!
