### ISSUE TITLE
Outdated/Incorrect Office 2016 Support Extended End date.

### ISSUE THREAD

**Issue by lcorduke** [MicrosoftDocs/OfficeDocs-DeployOffice#861]
Hi there,

This page says that Versions of Office 2019 and Office 2016 are supported until October **2023**. However, support dates report an extended date of 14-OCT-2025. 

See here: https://docs.microsoft.com/en-us/lifecycle/products/microsoft-office-2016

Hope this helps,

Laurence

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e86f8d4f-3eb1-6763-0f10-a0b637f3035c
* Version Independent ID: a6642647-dc4d-30a9-e962-76f7cd1f5089
* Content: [Office versions and connectivity to Office 365 services - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/endofsupport/office-365-services-connectivity)
* Content Source: [DeployOffice/endofsupport/office-365-services-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/endofsupport/office-365-services-connectivity.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@lcorduke -- Thanks for the feedback. While both Office 2016 and Office 2019 are supported until October 2025, they are only supported for connectivity to Office 365 services until October 2023.  We'll update the article to make that clearer. 

Our [Office configuration support matrix](https://go.microsoft.com/fwlink/p/?linkid=2111390) is a handy downloadable/printable resource for all this info. And there's a section on the right side of the page specifically about connectivity to Office 365 services.

Hope that explanation helps. Thanks for bringing this to our attention.

**Comment by DHB-MSFT** [comment]
@lcorduke -- We've updated that sentence to read as follows:

Versions of Office 2019 and Office 2016 will be supported for connecting to Office 365 (and Microsoft 365) services until October 2023.


Thanks again for bringing this to our attention so that we could make it clearer.
