### ISSUE TITLE
Duplicate wording in article "Overview of shared computer activation for Microsoft 365 Apps"

### ISSUE THREAD

**Issue by CWellardMaidenhill** [MicrosoftDocs/OfficeDocs-DeployOffice#863]
In the article "Overview of shared computer activation for Microsoft 365 Apps", there is duplicate spelling of the word "doesn't".
https://docs.microsoft.com/en-gb/deployoffice/overview-shared-computer-activation 

This can be found under the header "How to enable shared computer activation for Microsoft 365 Apps" and embedded in the second note.

"Microsoft 365 Apps for business **_doesn't doesn't_** support the use of Group Policy, so you'll need to use another method to enable shared computer activation. If a user already activated the Microsoft 365 Apps before shared computer activation was enabled, you have to reset the activation to allow shared computer activation to work."

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ab31873-7ad3-afde-3c72-8a7fb4f2e551
* Version Independent ID: 19f7f483-9f53-f577-1cd4-d360c0b234fc
* Content: [Overview of shared computer activation for Microsoft 365 Apps - Deploy Office](https://docs.microsoft.com/en-gb/deployoffice/overview-shared-computer-activation)
* Content Source: [DeployOffice/overview-shared-computer-activation.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-shared-computer-activation.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by manoth-msft** [comment]
Thanks for highlighting, I've submitted #864 to get this fixed.
