### ISSUE TITLE
GCC / GCC High / DOD Availability

### ISSUE THREAD

**Issue by Marweis** [MicrosoftDocs/OfficeDocs-DeployOffice#865]
[Enter feedback here]
Please update the article to clarify the use of this feature in GCC/ GCC HIGH/ DOD O365 tenants.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Microsoft 365 Apps for enterprise - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing?source=docs#what-is-microsoft-search-in-bing)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@Marweis --We're checking with the product team about this and will update the article accordingly based on what they tell us. Thanks for your feedback.

**Comment by DHB-MSFT** [comment]
@Marweis -- Thanks again for your feedback. We've updated the article to make that clearer.

![image](https://user-images.githubusercontent.com/32883970/95907702-ce9ef200-0d50-11eb-81ad-b5e83303d061.png)
