### ISSUE TITLE
Error log?

### ISSUE THREAD

**Issue by andykn** [MicrosoftDocs/OfficeDocs-DeployOffice#87]
Where does it log errors? On my first download attempt it created an Office\Data folder in the share but nothing else.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66127c02-c2dc-f6d1-6e83-a6d2b1166731
* Version Independent ID: 27635315-22db-d136-f07e-5169f6207b50
* Content: [Overview of the Office Deployment Tool](https://docs.microsoft.com/en-us/deployoffice/overview-of-the-office-2016-deployment-tool#get-started-with-the-office-deployment-tool)
* Content Source: [DeployOffice/overview-of-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by DHB-MSFT** [comment]
Default location is the %temp% folder, but that can be configured by using the [Logging element](https://docs.microsoft.com/en-us/deployoffice/configuration-options-for-the-office-2016-deployment-tool#logging-element) in the configuration.xml file. Hope that helps. Thanks for your question.
