### ISSUE TITLE
Having issue with Office Telemetry Dashboard running on Office 365 Click-to-Run on Windows 10

### ISSUE THREAD

**Issue by riya3005** [MicrosoftDocs/OfficeDocs-DeployOffice#873]
One of my customer is having an issue with Office Telemetry Dashboard running on Office 365 Click-to-Run on Windows 10, whilst the Telemetry Processor is running with Office 2016 on a Windows Server 2016 server. They get a pop-up (Telemetry Dashboard couldn’t create worksheets.) when attempting to connect to the database. 

As per document - https://docs.microsoft.com/en-us/deployoffice/compat/deploy-telemetry-dashboard

"Office Telemetry Dashboard is an Excel workbook that is configured to connect to a database. Office Telemetry Dashboard is installed together with Microsoft 365 Apps for enterprise, Office Professional Plus 2019, Office Professional Plus 2016, and Office Standard 2016. **To view Office Telemetry Dashboard, you must have Excel 2019 or Excel 2016 installed.**"

I have some follow up questions on this -

1. Office Telemetry Dashboard is part of Office 365, 2016 and 2019. Why include it in Office 365 if it only works with Excel 2016 and 2019?
2. Is there a way to make it work with Excel 365 at some point? Or am I missing something?

**Comment by DHB-MSFT** [comment]
Issue covered offline. Suspected cause is that the user doesn't have permission to the database.

Also, Excel that comes with Microsoft 365 Apps for enterprise is supported, so we'll get that updated in the article.
