### ISSUE TITLE
How to assign licenses to devices

### ISSUE THREAD

**Issue by jasonfritts** [MicrosoftDocs/OfficeDocs-DeployOffice#874]
Section "Configure Microsoft 365 Apps for enterprise to use device-based licensing"  is misleading, you have to use the M365 Admin Center to assign device-based licenses to the AAD group containing those devices as per another document https://docs.microsoft.com/en-us/microsoft-365/commerce/licenses/manage-licenses-for-devices?view=o365-worldwide#assign-licenses-to-devices  this section makes it sound like you do that in the Azure AD portal

This document should be updated to reflect you have to do this from M365 Admin -> Billing -> Licenses portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e52eb9c1-1755-bec5-4ad8-6df59779e041
* Version Independent ID: 10e4cf5d-ea61-806e-f226-1e14265eabe1
* Content: [Device-based licensing for Microsoft 365 Apps for enterprise - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/device-based-licensing#steps-to-configure-device-based-licensing-for-office-365-proplus)
* Content Source: [DeployOffice/device-based-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/device-based-licensing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by MJP-MSFT** [comment]
@jasonfritts   Thanks for calling this out!  I will submit a change! You're correct the assignment ha done in the M365 Admin portal.
