### ISSUE TITLE
Inconsistent requirements

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-DeployOffice#879]
[Enter feedback here]

This page states that 1908 is required, but https://docs.microsoft.com/en-us/DeployOffice/overview-office-cloud-policy-service states 1808. Please resolve this discrepancy
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a75b46cd-b999-9c6b-3b4b-7a53c9a1a7b3
* Version Independent ID: 92b5b3c9-37fa-9bed-3ff5-e832f664bed7
* Content: [Overview of Security Policy Advisor for Microsoft 365 Apps for enterprise - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/overview-of-security-policy-advisor)
* Content Source: [DeployOffice/overview-of-security-policy-advisor.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-security-policy-advisor.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by manoth-msft** [comment]
@DeanGross thanks for filing an issue. Both pages are correct stating different versions. Version 1808 is required to use the Office Cloud Policy Service, but 1908 is the min version for the Security Policy Advisor which builds on Office Cloud Policy Service, but is a separate feature. Hope this clarification helps.
