### ISSUE TITLE
AdminCenter - Inventory

### ISSUE THREAD

**Issue by xpre-s** [MicrosoftDocs/OfficeDocs-DeployOffice#887]
Hi there,

could you please provide more information about the requirements for the Inventory?
We fulfil the current listed requirements: 
- Microsoft 365 Apps for enterprise, Version 2007 or later
- A version of Windows 10 supported by Microsoft 365 Apps for enterprise
- Microsoft 365 (or Office 365) A3, A5, E3, or E5 subscription plan

But we only see Clients from Monthly Enterprise Channel and Current Channel (Build 2007 & 2008)
We have already about 100 Clients in Preview Channel (Build 2008)

We changed our Diagnostic Settings to "Optional" and restarted also manually on some Clients the [Click2RunSvc ](https://techcommunity.microsoft.com/t5/office-365-blog/introducing-new-cloud-based-admin-capabilities-to-help-you/ba-p/1675401)Service but without success...Is there something else we can check/try? 

Ps: not sure if this issue is correct here but i´ll try anyway 👍

**Comment by manoth-msft** [comment]
@xpre-s  Please reach out to me directly, we can then check a) if CC Preview is actually enabled to register into inventory already and b) if your tenant is enabled for Apps health. martin.nothnagel   AT   microsoft.com

**Comment by manoth-msft** [comment]
@xpre-s  and I synced offline, closing issue now
