### ISSUE TITLE
download dosen´t start, download startet nicht

### ISSUE THREAD

**Issue by 20MSOfficeSB** [MicrosoftDocs/OfficeDocs-DeployOffice#89]
I´m using the officedeploymenttool, my XML looks like this
&lt;Configuration&gt;
&lt;Add SourcePath="E:\Office\" OfficeClientEdition="64" &gt;
&lt;Product ID="ProPlusRetail"&gt;
&lt;Language ID="de-de" /&gt;
&lt;/Add&gt;
&lt;/Configuration&gt;

so i just want to change the folder where office shoulb be installed.

When i start the download, there comes this Message:
Office couldnt install
Error code:30029-1007 (0)

I should check the internetconnection an the free disc space. Both ist O.K. 
MS create also an Office an Office folder. But the download dosent start.
Is it my mistake? 
When i use the Standard installation exe c2r everything works fine, just Programs where installed at the wrong hard disk (for me the wrong).
Sorry for my english.
Please help me.
Markus

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 66127c02-c2dc-f6d1-6e83-a6d2b1166731
* Version Independent ID: 27635315-22db-d136-f07e-5169f6207b50
* Content: [Übersicht über das Office-Bereitstellungstool](https://docs.microsoft.com/de-de/DeployOffice/overview-of-the-office-2016-deployment-tool?redirectSourcePath=%252fde-de%252farticle%252fbb5b62d9-1168-47e9-9d54-15a958acfcca)
* Content Source: [DeployOffice/overview-of-the-office-2016-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice-pr.de-DE/blob/live-sxs/DeployOffice/overview-of-the-office-2016-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by DHB-MSFT** [comment]
ProPlusRetail isn't a valid Product ID. If you're trying to install Office 365 ProPlus, the correct Product ID is O365ProPlusRetail.

**Comment by 20MSOfficeSB** [comment]
I´ve got this Product: Office Professional Plus 2016 do you know the correct Product ID?

**Comment by DHB-MSFT** [comment]
How did you purchase Office Professional Plus 2016? I don't think you can install it using the Office Deployment Tool.

**Comment by DHB-MSFT** [comment]
Also, with Click-to-Run and the Office Deployment Tool, Office will always install on the system drive, which is the drive where Windows is installed, which is usually C:\.  You can't change the drive and you can't specify a different folder for the apps to be installed in.

**Comment by 20MSOfficeSB** [comment]
Oh that´s sad. I hoped it would work. So thank you for your answer. 
Markus

**Comment by RAJU2529** [comment]
i am downloading the setup files after configured .xml file,  downloading files are not in c drive .

**Comment by RAJU2529** [comment]
Create new folder  C:\officesetup\  and  E:\Office\
copy  three  files  "setup.exe"  "EULA" "configuration.xml"   to  C:\officesetup\

now open cmd run as administartor  
type   cd /d C:\officesetup
type  setup.exe /download C:\officesetup\configuration.xml
downloading started  , wait for  few hours 

all  data folders and all required files are  downbloaded  in E:\Office\office

**Comment by DHB-MSFT** [comment]
@RAJU2529 -- is there a SourcePath specified in your configuration.xml? If there is, that's where the installation files will be downloaded. If you don't specify a SourcePath, then the files will automatically be downloaded into an Office folder in the same location that you're running the Office Deployment Tool (setup.exe) from.  In your case, it would create C:\officesetup\office.  Hope that helps.

**Comment by RAJU2529** [comment]
source path is nothing downloading files are saved to particular location

**Comment by RAJU2529** [comment]
here is my configuration file
<Configuration>

  <Add SourcePath="K:\Office2016Setup\C2R\" OfficeClientEdition="32" Channel="Monthly">
    <Product ID="ProPlusRetail">
      <Language ID="en-us" />
    </Product>
    <Product ID="VisioProRetail">
      <Language ID="en-us" />
    </Product>
    <Product ID="ProjectProRetail">
      <Language ID="en-us" />
    </Product>
  </Add>
     <AppSettings>
     <User Key="software\microsoft\office\16.0\excel\security"
          Name="vbawarnings" 
          Value="3" 
          Type="REG_DWORD" 
          App="excel16" 
          Id="L_VBAWarningsPolicy" />
     </AppSettings>

  

  

  

  

  

</Configuration>

**Comment by RAJU2529** [comment]
files will be dpwnloaded in K:\Office2016Setup\C2R\

**Comment by RAJU2529** [comment]
files are downloaded correctly in my sources path

**Comment by DHB-MSFT** [comment]
OK, thanks for clarifying. I'll close the issue.
