### ISSUE TITLE
The -t and -m commands added in msupdate 4.24 aren't documented

### ISSUE THREAD

**Issue by sdagley** [MicrosoftDocs/OfficeDocs-DeployOffice#895]
Bug number 4180152 has the Description "msupdate needs to support timer-based termination with custom messages (-t secs -m 'text')" and according to [https://macadmins.software/mau/](https://macadmins.software/mau/) that was Fixed/Added in version 4.24. Those options are not documented on this page, or in the msupdate tool's usage page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59e840a0-92ac-3ba4-75b3-01a154d67899
* Version Independent ID: 8f7fd243-8f3a-7d32-8433-03b8167aee6f
* Content: [Update Microsoft applications for Mac by using msupdate - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/mac/update-office-for-mac-using-msupdate)
* Content Source: [DeployOffice/mac/update-office-for-mac-using-msupdate.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/mac/update-office-for-mac-using-msupdate.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @pbowden-msft
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@sdagley Thanks for the feedback/suggestion. We have an email out to the PM to get the relevant info to update the article.

**Comment by DHB-MSFT** [comment]
@sdagley Thanks for bringing this to our attention. We've added info about the -t and -m modifiers to the article. This info has also been added to the "help" for the msupdate tool and will be available in an upcoming update/release.
