### ISSUE TITLE
the .exe is not called "setup" but "setupODT" and this guide needs to be updated

### ISSUE THREAD

**Issue by hot-ham-water** [MicrosoftDocs/OfficeDocs-DeployOffice#899]
Using _setupODT_ in the command line worked as expected. any worthwhile IT pro would see this and correct it but most people would not, and would generate an error in the console.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [Deploy Office 2019 (for IT Pros) - Deploy Office](https://docs.microsoft.com/en-us/DeployOffice/office2019/deploy)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@hot-ham-water  Thanks for catching that and letting us know. We missed updating those two command line examples when we were updating the other references in this article and in other articles. This article is now updated.
