### ISSUE TITLE
Conflicting documentation

### ISSUE THREAD

**Issue by Inesicen** [MicrosoftDocs/OfficeDocs-DeployOffice#901]
The article (11/06/2020) states: "If you disable or don’t configure [the policy setting for diagnostic data], both optional and required diagnostic data are sent to Microsoft." Whereas `ADMX!H740` in [this spreadsheet](https://www.microsoft.com/download/details.aspx?id=49030) (11/20/2020) states that the default setting is `Neither`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef4debee-6a1e-53c7-7bec-2dbd208f4f2d
* Version Independent ID: b93ad6a2-0976-6f5f-7aae-1756079bdc1d
* Content: [Use policy settings to manage privacy controls for Microsoft 365 Apps for enterprise - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/privacy/manage-privacy-controls#feedback)
* Content Source: [DeployOffice/privacy/manage-privacy-controls.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/manage-privacy-controls.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@Inesicen -- It seems this just refers to what the default setting is when you select Enable when configuring the policy setting. For example, if you're using the Group Policy management console or Office cloud policy service, and choose Enable, "Neither" is automatically selected for you from the drop-down list. But you can still choose either Required or Optional from the drop-down list. If the policy setting is set to Disabled or Not Configured, the associated registry entry for this policy setting is not created.

Hope that explanation helps.
