### ISSUE TITLE
Wrong script name

### ISSUE THREAD

**Issue by JoeBrunsTR** [MicrosoftDocs/OfficeDocs-DeployOffice#905]
Paragraph that starts with "To configure KMS host caching, you can use the opss.vbs script"

Then in examples below, the script is called ospp.vbs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f83d98-4309-f494-9ce3-ce3d818edd50
* Version Independent ID: c7fede47-c25e-5ca9-5ad5-55f602ed2b2c
* Content: [Activate volume licensed versions of Office by using KMS - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/vlactivation/activate-office-by-using-kms)
* Content Source: [DeployOffice/vlactivation/activate-office-by-using-kms.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/vlactivation/activate-office-by-using-kms.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@JoeBrunsTR  -- Thanks for letting us know about that. We've fixed that article (and 2 other articles that had the same typo).
