### ISSUE TITLE
Missing an important detail

### ISSUE THREAD

**Issue by walvis79** [MicrosoftDocs/OfficeDocs-DeployOffice#906]
Hello team, 

Please review this article sine in my opinion needs to be more specific with "what will happen" when use the MigrateArch attribute on the configuration.xml. I mean, the article need to say very clear and also on the top of the article, when MigrateArch attribute is used, the existing installed apps will get uninstalled. 

Thanks, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3eacd91-ad3e-79a3-d946-0fa33785b7ee
* Version Independent ID: 0e5a2663-78b8-6068-2e80-cd472a72d7b1
* Content: [Change a Microsoft 365 Apps installation from 32-bit to 64-bit - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/change-bitness)
* Content Source: [DeployOffice/change-bitness.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/change-bitness.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@walvis79 -- Thanks for your feedback. There are 2 mentions in the article that a uninstall/reinstall happens, but admittedly they are buried deep in the article and could easily be overlooked. So we've gone ahead and added a note about this at the end of the introduction section of the article (as seen in the screenshot below)

Thanks again for your feedback to help make our documentation better.

![add_note](https://user-images.githubusercontent.com/32883970/100903323-9d9e8c00-347a-11eb-8f03-db5b01637137.PNG)
