### ISSUE TITLE
Regitry key is it REG_SZ or REG_DWORD

### ISSUE THREAD

**Issue by loveall27** [MicrosoftDocs/OfficeDocs-DeployOffice#909]
[Enter feedback here]
 As per the Microsoft  document, we have to create REG_DWORD value whereas in one of the articles I came across to troubleshoot the issue it advises to create REG-SZ value and it worked but  REG_DWORD did not work. Which one is correct?

The following is suggested by the Micorosft 

Use Registry Editor to add a **DWORD value (Reg_DWORD)** of SharedComputerLicensing with a setting of 1 under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration.

whereas in my case following key worked.

https://www.urtech.ca/2019/03/solved-video-how-to-set-office-365-pro-plus-to-run-on-a-kiosk-with-shared-activation/
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ab31873-7ad3-afde-3c72-8a7fb4f2e551
* Version Independent ID: 19f7f483-9f53-f577-1cd4-d360c0b234fc
* Content: [Overview of shared computer activation for Microsoft 365 Apps - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/overview-shared-computer-activation)
* Content Source: [DeployOffice/overview-shared-computer-activation.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-shared-computer-activation.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by MJP-MSFT** [comment]
@loveall27 

Thank you for your post.  I submitted a PR to change this. The Reg_SZ is correct. 

Not is you are moving from subscription(User) mode over to SharedComupterLicensing you will need ro rest the licensing via the Sara tool or following the article here: https://docs.microsoft.com/en-us/office/troubleshoot/activation/reset-office-365-proplus-activation-state

**Comment by RAJU2529** [comment]
@jwhit-MSFT , I think this issue is solved, please check and close it.Thanks
