### ISSUE TITLE
Is there any way to stop this overriding Group Policy?

### ISSUE THREAD

**Issue by mtwelve** [MicrosoftDocs/OfficeDocs-DeployOffice#916]
We need to be able to control the Office installs on MEM managed devices differently from Office installs on traditional AD DS Joined Group Policy managed devices.

Is this possible? I see no configuration options or documentation (other than saying it overrides Group Policy).

We'll have to step away from this otherwise fantastic functionality if there is no way to do the above. We'd have to go back to using manually authored MEM Custom Profiles to manage the Office install on said MEM devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa63a94-daaa-9491-213e-f0329f6299b1
* Version Independent ID: 47fe5a3a-ee7c-a7f7-b913-ca0ac3c063e0
* Content: [Overview of the Office cloud policy service for Microsoft 365 Apps for enterprise - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/overview-office-cloud-policy-service)
* Content Source: [DeployOffice/overview-office-cloud-policy-service.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-office-cloud-policy-service.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by chhopkin** [comment]
There is not an option in the product to configure the override behavior.  If you have the same policy set in GPM and OCPS with different values, the value set in OCPS will always win.  I would like to learn more about your scenario if you can email me at chhopkin@microsoft.com with additional information.
