### ISSUE TITLE
Update to Microsoft 365 and Outlook for Windows connectivity

### ISSUE THREAD

**Issue by tcfinney** [MicrosoftDocs/OfficeDocs-DeployOffice#917]
Hello - there was a recent Message Center notification (MC229143) in the M365 Admin Center with the details below.

Wondering if this could be added to [this page](https://docs.microsoft.com/en-us/deployoffice/endofsupport/resources)?

> To ensure that we meet performance expectations, we are updating the supported versions of Outlook for Windows that can connect to Microsoft 365 services. 
> 
> Effective November 1, 2021, the following versions of Outlook for Windows, as part of Office and Microsoft 365 Apps, will not be able to connect with Office 365 and Microsoft 365 services. 
> 
> Office and Microsoft 365 Apps  |  Outlook   for Windows Version
> Office 2013 > 15.0.4970.9999   and older
> Office 2016 > 16.0.4599.9999 and older
> Microsoft 365 Apps for enterprise (formerly Office 365 ProPlus) > 1705   and older
> Microsoft 365 Apps for business (formerly Office   365 Business) > 1705 and older
> 
> Versions that are newer than minimum version requirements listed above, but are not the currently supported version, may experience connectivity issues.

Thank you,
TC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e6edce-5c6a-5792-8a17-ee581414e190
* Version Independent ID: a91cd251-f9cb-9c1c-311c-6720c738a063
* Content: [End of support resources for Office - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/endofsupport/resources)
* Content Source: [DeployOffice/endofsupport/resources.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/endofsupport/resources.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@tcfinney -- Thanks for the suggestion. We already have plans to add it to this article -- [Office versions and connectivity to Office 365 services](https://docs.microsoft.com/deployoffice/endofsupport/office-365-services-connectivity). We're just following up with the Outlook team about some of the details.

**Comment by tcfinney** [comment]
Many thanks, @DHB-MSFT!  Any estimate on when it will be published?  Thanks again!

**Comment by DHB-MSFT** [comment]
@tcfinney -- We're hoping to have it added by the end of January, at the latest. Just waiting to hear back from the Outlook team. Thanks.

**Comment by DHB-MSFT** [comment]
@tcfinney We've added this information to the article:  https://docs.microsoft.com/deployoffice/endofsupport/office-365-services-connectivity#minimum-version-requirements-for-outlook-for-windows.  Apologies for the delay.
