### ISSUE TITLE
Device based licensing setting with proxy 

### ISSUE THREAD

**Issue by forester123** [MicrosoftDocs/OfficeDocs-DeployOffice#918]
Hi Team,

Please add instruction about device based licensing with proxy settings.

We have received cases from customer that Office cannot be activated with device based licensing when they have proxy.

The cause is device based licensing uses System account to call OLS and fetch license. They must set proxy for System account to make the activation work.

Usually user only set proxy for user account in Windows, thus device based licensing won't work.

This is very important because lots of customer don't have direct access to internet, they use proxy a lot. 

Please point this out for customers clearly to avoid miss understandings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e52eb9c1-1755-bec5-4ad8-6df59779e041
* Version Independent ID: 10e4cf5d-ea61-806e-f226-1e14265eabe1
* Content: [Device-based licensing for Microsoft 365 Apps for enterprise - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/device-based-licensing)
* Content Source: [DeployOffice/device-based-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/device-based-licensing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by forester123** [comment]
Hi Team, may I know if there's any update?

**Comment by MJP-MSFT** [comment]
@forester123   I am investigating this. I will respond once I have an update.

**Comment by forester123** [comment]
@MJP-MSFT kindly ping again

**Comment by MJP-MSFT** [comment]
@forester123  Thanks for checking back in. We confirmed this was by design and I filed a DCR with engineering to find a solution here.  The best work-around i have is what you've done already -  bypass the System account through Proxy for this scenario. I will monitor and once they work through the DCR I will update content.

**Comment by forester123** [comment]
@MJP-MSFT thank you so much for the update.
