### ISSUE TITLE
MS Partners do not have access to C2R-P keys

### ISSUE THREAD

**Issue by simon-baer** [MicrosoftDocs/OfficeDocs-DeployOffice#92]
We have 5 Visio licenses because we are Microsoft Partner, but we do not have access to VLSC. I already spent hours on the phone with different MS support departments. Conclusion:
Partner support is unable to generate these C2R-P keys and unwilling to help on this subject.
VLSC support is able to generate the keys, but requires a volume license contract number. (which we don't have, because as MS Partner we did not bought a volume license)
This really sucks!

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 1e6c0641-503d-7959-2afb-839821cc792f
* Version Independent ID: 046c52d9-4fbe-4fe7-0778-5c1d4138f69e
* Content: [Verwenden des Office-Bereitstellungstools zum Installieren von Volumenlizenzeditionen von Visio 2016 und Project 2016](https://docs.microsoft.com/de-de/DeployOffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016)
* Content Source: [DeployOffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice-pr.de-DE/blob/live-sxs/DeployOffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
I'm trying to get clarification/confirmation about what partners should be able to get for this scenario.

**Comment by MatthiasLaechele** [comment]
Thanks simon-baer, we have the same question and problem. Rolling out Office 365 to all employees and therefor have the need for Visio ODT installation but can not use our MPN benefits. Very annoying situation...

**Comment by DHB-MSFT** [comment]
Sorry for the delay in responding. I've been able to confirm that C2R-P keys are only available from the VLSC. I have forwarded on your comments/feedback to the appropriate team. I recognize this situation is a source of frustration for you. Please know that our product and program teams take this feedback seriously, and it has been added as evidence for potential future improvements to the program.  Thank you again for your comments/feedback.

**Comment by gkienhuis** [comment]
@DHB-MSFT, we 10 months further, is there already an option for an MS partner to get C2R-P keys based on IUR benefits?

**Comment by MatthiasLaechele** [comment]
@gkienhuis  / @simon-baer 
We cloud activate Visio Professional 2016 with our partner keys by creating our own c2r installation media with office deployment tool, see: https://docs.microsoft.com/de-de/deployoffice/use-the-office-deployment-tool-to-install-volume-licensed-editions-of-visio-2016 using ID "VisioProXVolume"

**Comment by gkienhuis** [comment]
@MatthiasLaechele thanks for sharing your experience, gone try to do the same.
