### ISSUE TITLE
updates to "Tips for safer shopping" page: 

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/OfficeDocs-DeployOffice#922]
https://www.microsoft.com/en-us/howtotell/Shop.aspx  

This article is missing the "Did this help" Yes/No option to provide suggestions

"MAKE SURE YOU ARE GETTING WHAT YOU’VE PAID FOR"
When buying onetime payment Office online, check the offer closely.  Many online pages illegally resell Office Professional Plus volume license product keys.  Sometimes they say they are selling Office Professional.  
Look at the list of applications in the bundle Office 2019 Pro Plus includes Skype

"GET THE RIGHT SOFTWARE FOR YOU"
Should also make the point to buy the software version for the right OS.  Although it is becoming more liberal, One-time payment Office licenses before 2019 were specific for Windows or MAC.  Many people have been caught by this trap.
.
Make the point to pay for software as a single item on a credit card transaction. Many credit card companies won't provide a refund for just one part of a multi-item transaction.

**Comment by Ronsss** [comment]
Missed a couple of points
ADDITIONAL TIP WHEN BUYING SOFTWARE
Why would you need this advice. The specific situation that has occurred multiple times is when scratching the protective cover off of an Office Product Key Card, some people have also damaged the text of the actual product key. The key is unusable. MS refuses to help, they send you back to the store. The store has a “no return, no exchange, no refund” policy for software, they send you to MS. 
You have 2 options that I know have worked.
One is to appeal to the store manager. In exactly 2 cases, the store managers (at Best Buy) have overridden the polity to exchange the key cards. In the name of “customer service”. Walmart is another store that has a fairly liberal return policy, but I have no independent confirmation that it applies to software.
The other option is call your credit card company and ask them for a refund. The reason is “defective product”
PAY WITH A CREDIT CARD. 
It gives you another option for refunds if the store has a “no return, no exchange, no refund” policy
SINGLE ITEM TRANSACTION
When paying for software with a credit card, it is to your advantage to make the software the single item in the transaction.
If there is more than one item in the transaction, some credit card companies won’t give you a refund. 
MAKE SURE YOU GET WHAT YOU ARE PAYING FOR
Pro: Access (Windows only), Excel, Outlook, PowerPoint, and (Windows only) Publisher, Word, 
Pro Plus: Access (Windows only), Excel, Outlook, PowerPoint, (Windows only) Publisher, Word, and Skype for Business.

**Comment by DHB-MSFT** [comment]
@Ronsss -- Thanks for the feedback. We're trying to track down the owner of that page so that we can provide them with your feedback.
