### ISSUE TITLE
Wrong link for footnote 4

### ISSUE THREAD

**Issue by shadenMSFT** [MicrosoftDocs/OfficeDocs-DeployOffice#928]
The link for footonote {4] is wrong. It goes to an internal Microsoft Excel document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 871fcfaa-3fc9-0c46-3700-ce7dda6416e5
* Version Independent ID: b5e600b9-349f-4e3e-7f32-93a3b14c8538
* Content: [Microsoft 365 change guide - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/fieldnotes/microsoft-365-change-guide?source=docs#footnote-4)
* Content Source: [DeployOffice/fieldnotes/microsoft-365-change-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/fieldnotes/microsoft-365-change-guide.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @tabriggs
* Microsoft Alias: **tabriggs**

**Comment by DHB-MSFT** [comment]
@shadenMSFT -- Thanks for catching that and letting us know. Link has been fixed and now points to the correct location.
