### ISSUE TITLE
Office 2019 on Server 2019

### ISSUE THREAD

**Issue by FredVH** [MicrosoftDocs/OfficeDocs-DeployOffice#929]
Hi

According to this article you can't use Active Directory-based activation for Office 2019 (with GVLK) that's installed on Server 2019?

Kind regards
Frederik.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88987141-eb61-186f-ada4-6b8765764737
* Version Independent ID: 9264a57c-554a-c69e-b408-4c3196788ec5
* Content: [Activate volume licensed versions of Office by using Active Directory - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/vlactivation/activate-office-by-using-active-directory)
* Content Source: [DeployOffice/vlactivation/activate-office-by-using-active-directory.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/vlactivation/activate-office-by-using-active-directory.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@FredVH That might just be an oversight on our part. We'll check with the product team responsible for activation to see if Windows Server 2019 is supported.

**Comment by DHB-MSFT** [comment]
@FredVH - According to the product team, no changes were made to Active Directory activation for Windows Server 2019. Based on that info, it should work. So we've added Windows Server 2019 to the list in the requirements section in this article. Thanks for bringing this to our attention.
