### ISSUE TITLE
I tried this but there is no msupdate in that directory nor in any other one.

### ISSUE THREAD

**Issue by hvdkooij** [MicrosoftDocs/OfficeDocs-DeployOffice#93]
Mini-van-Hugo:MacOS hugo$ pwd
/Library/Application Support/Microsoft/MAU2.0/Microsoft AutoUpdate.app/Contents/MacOS
Mini-van-Hugo:MacOS hugo$ ./msupdate 
-bash: ./msupdate: No such file or directory
Mini-van-Hugo:MacOS hugo$ ls -l
total 1360
drwxr-xr-x  3 root  wheel      96 Jan 18  2018 Microsoft AU Daemon.app
-rwxrwxr-x  1 root  wheel  695136 Dec 16  2017 Microsoft AutoUpdate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59e840a0-92ac-3ba4-75b3-01a154d67899
* Version Independent ID: 8f7fd243-8f3a-7d32-8433-03b8167aee6f
* Content: [Update Office 2016 for Mac by using msupdate](https://docs.microsoft.com/en-us/deployoffice/mac/update-office-for-mac-using-msupdate)
* Content Source: [DeployOffice/mac/update-office-for-mac-using-msupdate.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/mac/update-office-for-mac-using-msupdate.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @pbowden-msft
* Microsoft Alias: **danbrown**

**Comment by AndreaBarr** [comment]
@hvdkooij  Thank you for submitting this Feedback.

From my understanding this msupdate issue  has been resolved. If the issue is not resolved please re-open this issue.

**Comment by hvdkooij** [comment]
Steps taken:
 1. Download the pkg file
 2. Install the pkg file from cli
 3. Run the msupdate tool to update Office365 components
Status:
Works as documented with addition of the minimal version of the update software.
