### ISSUE TITLE
Required Diagnostic Data

### ISSUE THREAD

**Issue by p3t3r88** [MicrosoftDocs/OfficeDocs-DeployOffice#931]
Hi  @DHB-MSFT,

I used Diagnostic Data Viewer to monitor possible issues with my Excel that has connection with several Add-Ons and some macros calling other files. Tried to decipher all the data I collected and not getting any wiser. Read your [docs](https://docs.microsoft.com/en-us/deployoffice/privacy/required-diagnostic-data) and just cannot figure out those info under "Activity". Is the Activity.Duration showing in milliseconds (see attached snapshot)? Some numbers are way too high with 9 char length. And what are the explanation for each of the Activity.AggMode values?

Where can I find details info/docs on Event.Name that relates to Office.Excel.xxx.xxx.xxx?

Really appreciate your help and prompt reply. Thanks in advance!

Regards... Peter

![image](https://user-images.githubusercontent.com/45168698/108383657-45219400-720a-11eb-96e6-56da1572a263.png)

**Comment by DHB-MSFT** [comment]
@p3t3r88 We're checking to see if we can get this additional information from the product team.

**Comment by p3t3r88** [comment]
Much appreciated @DHB-MSFT. Looking forward to the info and have a good weekend.

**Comment by p3t3r88** [comment]
Hello @DHB-MSFT , sorry to bother, did you get any info yet from the product team? My manager and customer are expecting on the analysis and findings soon. Really appreciate your help. Thanks!

**Comment by DHB-MSFT** [comment]
@p3t3r88  Are you trying to troubleshoot an Excel-specific issue or do you have privacy-related questions? If an Excel-specific question, your best course of action is to contact support. The required diagnostic data article isn't really intended to provide troubleshooting assistance. The purpose of the article is provide transparency to the type of data that is being sent to Microsoft.

**Comment by p3t3r88** [comment]
@DHB-MSFT I'm trying to troubleshoot Excel-specific issue. The diagnostic data has so much info available, just thought of using it as the base for my analysis. I understand that its mainly for Microsoft use purpose but would have been great if we can also understand the data... Do you have any alternative "diagnostic tool" specific for Excel you can recommend?

**Comment by DHB-MSFT** [comment]
@p3t3r88 -- Suggest you try posting on the Excel section of the Microsoft Tech Community.  https://techcommunity.microsoft.com/t5/excel/ct-p/Excel_Cat.   Seems likely you'll find some Excel experts there that can provide some suggestions of troubleshooting tools/tips that might help.

**Comment by p3t3r88** [comment]
Contacted MS for help but to no avail...
