### ISSUE TITLE
Invalid link?

### ISSUE THREAD

**Issue by FC-EricWeller** [MicrosoftDocs/OfficeDocs-DeployOffice#939]
The link for the diagnostic tool appears invalid.
It resolves to https://home.diagnostics.support.microsoft.com/SelfHelp?knowledgebaseArticleFilter=2870357

No DNS for home.diagnostics.support.microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d5eff63-106d-9679-a548-6f68b30d712b
* Version Independent ID: b8c1d0db-a564-48b7-3d2b-c5aec5ab0d46
* Content: [Troubleshoot volume activation of Office - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/vlactivation/troubleshoot-volume-activation-of-office)
* Content Source: [DeployOffice/vlactivation/troubleshoot-volume-activation-of-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/vlactivation/troubleshoot-volume-activation-of-office.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@FC-EricWeller  Thanks for contacting us about this. We are aware of the issue with this link and are investigating. We'll update the article once we determine whether the tool has been moved or has been retired.

**Comment by DHB-MSFT** [comment]
@FC-EricWeller   Those diagnostic tools are no longer available for download, so we have removed that information from the article.
