### ISSUE TITLE
Visio Macros are stored in more extensions than those listed above

### ISSUE THREAD

**Issue by davidjpp** [MicrosoftDocs/OfficeDocs-DeployOffice#94]
Please add .vst, .vstx, .vstm, .vss, .vssx and .vsdm to the list of Visio files that need to be scanned for VBA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2843afe2-a11d-7d88-8b56-24f131782d01
* Version Independent ID: f8bc6a27-b9f5-a729-b5e3-fdd9ac6642ed
* Content: [Use the Readiness Toolkit to assess application compatibility for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro#BKMK_FileExt)
* Content Source: [DeployOffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/use-the-readiness-toolkit-to-assess-application-compatibility-for-office-365-pro.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
I'm checking with the Readiness Toolkit team. I'll get back to you.  Thanks.

**Comment by DHB-MSFT** [comment]
Those file extensions aren't currently supported/scanned by the tool, but the team is investigating about possibly adding them in the future.  Thanks for your comment/feedback.
