### ISSUE TITLE
Small Typo - Replace "OneNote" with "OneDrive"

### ISSUE THREAD

**Issue by rterakedis** [MicrosoftDocs/OfficeDocs-DeployOffice#940]
The note towards the bottom states:

> OneNote does use a different bundle ID, and different management controls are available depending on how you obtain the app. For more information, see Deploy and configure the new OneDrive sync client for Mac.

The linked article only references OneDrive, not OneNote.   It appears the mention of "OneNote" in the note is a typo and should read OneDrive. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bca0ba76-cbbf-563b-6baa-7a09cd742e87
* Version Independent ID: 578cb671-6328-b85f-3b07-813b073e810f
* Content: [Deploy Office for Mac from the Mac App Store - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/mac/deploy-mac-app-store)
* Content Source: [DeployOffice/mac/deploy-mac-app-store.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/mac/deploy-mac-app-store.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @pbowden-msft
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@rterakedis  Thanks for catching that and letting us know. We've submitted a fix for that and the update should be live later today.
