### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by LindaCicero** [MicrosoftDocs/OfficeDocs-DeployOffice#941]
[On this sentence, I think it should be _safe_ instead of save: "so it is _save_ to assign updates from multiple channels to a device."]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d23ac821-9cb8-8855-598f-d1327df04fac
* Version Independent ID: 78f2127a-0c6b-d236-a415-6215c582ce8b
* Content: [Change the Microsoft 365 Apps update channel for devices in your organization - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/change-update-channels)
* Content Source: [DeployOffice/change-update-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/change-update-channels.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@LindaCicero Thanks for catching that and letting us know. We've fixed the issue and it should be published live later this afternoon.
