### ISSUE TITLE
Links to Diagnostic Tools Don't Work

### ISSUE THREAD

**Issue by mattlenco** [MicrosoftDocs/OfficeDocs-DeployOffice#945]
[The link to the client and KMS host diagnostic tools don't work. Please update the links so I can download the tools. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d5eff63-106d-9679-a548-6f68b30d712b
* Version Independent ID: b8c1d0db-a564-48b7-3d2b-c5aec5ab0d46
* Content: [Troubleshoot volume activation of Office - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/vlactivation/troubleshoot-volume-activation-of-office)
* Content Source: [DeployOffice/vlactivation/troubleshoot-volume-activation-of-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/vlactivation/troubleshoot-volume-activation-of-office.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@mattlenco  Those diagnostic tools are no longer available for download, so we have removed that information from the article.
