### ISSUE TITLE
Unable to check O365 subscription license status with "ospp.vbs /dstatus"

### ISSUE THREAD

**Issue by Bolt10000** [MicrosoftDocs/OfficeDocs-DeployOffice#946]
Here's the situation,

- Clean install Windows 10 20H2 X64
- Downloaded and installed office setup.exe from https://www.office.com/
- Activated it by logging-in my outlook ID which has the personnel license for O365

It showed me this on office apps,

![77561-image](https://user-images.githubusercontent.com/56072429/112677718-185b3f00-8e90-11eb-8273-34eb3915dfd8.png)

- But when I checked my office license through ospp.vbs /dstatus, it only showed the default grace period license and didn't show any info about my O365 license.

![77458-image](https://user-images.githubusercontent.com/56072429/112677791-2ad57880-8e90-11eb-96f8-26938ea31565.png)

I've seen O365 license info in ospp.vbs /dstatus with other user licenses in **other's** systems.
For example,

``` 
---------------------------------------
 PRODUCT ID: 00265-80198-35232-AA551
 SKU ID: 6337137e-7c07-4197-8986-bece6a76fc33
 LICENSE NAME: Office 16, Office16O365BusinessR_Subscription edition
 LICENSE DESCRIPTION: Office 16, TIMEBASED_SUB channel
 BETA EXPIRATION: 01.01.1601
 LICENSE STATUS:  ---LICENSED---
 ERROR CODE: 0x4004FC04 (for information purposes only as the status is licensed)
 ERROR DESCRIPTION: The Software Licensing Service reported that the application is running within the timebased validity period.
 REMAINING GRACE: 31 days  (45379 minute(s) before expiring)
 Last 5 characters of installed product key: XTMGD
 ---------------------------------------
```

**My question is**, why I'm not able to view such O365 subscription info through in ospp.vbs /dstatus in my system with my license?
p.s. I've tested this in two different Windows 10 clean installs with the same result.

**Comment by MJP-MSFT** [comment]
@Bolt10000  Thank you for reaching out. The reason you're not seeing anything in the ospp.vbs response is because our latest versions of Office use a new licensing process. I am working on getting documentation created to walk through the changes and the process to check legacy ospp or the new process.  

Until the docs get created you need to download the Office Licensing Diagnostic - https://www.microsoft.com/en-us/download/details.aspx?id=55948

After downloaded and extracted there is a PS1 script titled vnextdiag.ps1  you need to run this in PowerShell and it will return an output similar to ospp.vbs with entitlements status and activation status of the applications.

**Comment by infohost** [comment]
@MJP-MSFT @DHB-MSFT 
What is the official Microsoft term for this new kind of license?
Is it **vNext** license or **Subscription** license?

If we are calling it a **Subscription** license then wouldn't it contradict the **lifetime** license of Office 2021 which is also being transferred to the vNext format?

I've checked the documentation but couldn't find docs explaining what is vNext. Hence the question, what the is official term for it.

**Comment by MJP-MSFT** [comment]
It is called subscription vNext is mostly an internal term.

Matt Philipenko
Microsoft 365 Apps Ranger
<Deployment/Servicing/Activation/Accessibility>
Direct:(813) 868-8108| E-mail: ***@***.******@***.***>
Office Hours: M-F  9AM-6PM EST
10 Habits to create accessible content<https://blogs.microsoft.com/accessibility/10-habits-to-create-accessible-content/>
Are you using the Accessibility Reminder App?<https://techcommunity.microsoft.com/t5/microsoft-365-blog/accessibility-reminder-app-for-microsoft-365-now-generally/ba-p/3053021>
Follow the Ranger team on YouTube<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fchannel%2FUCtGE6W1kFbokk_aFVyN1KmA%2F&data=05%7C01%7Cmattphil%40microsoft.com%7C837e3f4e840e4322eb1608da63fcd2c4%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637932234789028242%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LmmsQ7stL%2BNBxSJJDgwJtQOtKAtPEHiWLBE3kgcNrS8%3D&reserved=0>.

**Comment by SteffenH89** [comment]
Hi Matt,
i tried that and got the following output:

========== Mode per ProductReleaseId ==========
o365proplusretail = NUL

========== NUL licenses found ==========
{
    "Version":  "5",
    "Type":  "User|Subscription",
    "Product":  "O365ProPlusRetail",
    "Email":  "XXXXXXXXXXXXXXXX",
    "LicenseState":  "Licensed",
    "EntitlementStatus":  "Provisioned",
    "ReasonCode":  null,
    "NotBefore":  "2022-11-02T07:16:15.4587377Z",
    "NotAfter":  "2023-02-01T07:16:15.4587377Z",
    "ExpiresOn":  null,
    "TenantId":  "XXXXXXXXXXXXXXXX"
}

========== Device licenses found ==========
No licenses found.

There is no entry about the "REMAINING GRACE" which is shown by the old ospp.vbs or is that the "ExpiresOn" entry now?
But it is also empty?!

Another question is if there is a way to renew the grace period?
Maybe i will use Office for a month without network but my remaining grace is 20 days left?

Thanks
Steffen
