### ISSUE TITLE
on how many devices can a user activate MS 365 Apps?

### ISSUE THREAD

**Issue by tlcarpenter** [MicrosoftDocs/OfficeDocs-DeployOffice#950]
[Enter feedback here]

There are what appear to be contradictory statements on this page - wondering if someone could clarify a few points.

It's stated in the introduction

"Each license allows a user to install Microsoft 365 Apps on up to five desktops, five tablets, and five mobile devices."

and under "Licensing Modes | Subscription User Based Licensing"

"With a single license, users can install and activate Microsoft 365 Apps on up to 5 desktops/laptops, 5 tablets, and 5 mobile devices."

However, "Activating Microsoft 365 Apps | Managing activated installations" states

"If a user installs Microsoft 365 Apps on more than 10 devices, then the device that hasn't been used for the longest amount of time is automatically deactivated."

So, are users able to install and simultaneously activate Microsoft 365 Apps on

"5 desktops/laptops, 5 tablets, and 5 mobile devices"

or

"10 devices"

or some other quantity?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3c236da-c63a-f789-f1b6-7aeb41f16c1f
* Version Independent ID: 35319bac-d94f-832c-ce79-41bffe5c8d25
* Content: [Overview of licensing and activation in Microsoft 365 Apps - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/overview-licensing-activation-microsoft-365-apps)
* Content Source: [DeployOffice/overview-licensing-activation-microsoft-365-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-licensing-activation-microsoft-365-apps.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @MJP-MSFT
* Microsoft Alias: **mattphil**

**Comment by MJP-MSFT** [comment]
@tlcarpenter 

I apologize for any confusion. The process is 5 desktop/laptop ~ 5 tablet ~ 5 mobile devices.  The desktop/laptop/tablet is rolled into one group totaling 10 devices. The new functionality  automatically rolls the least used device off the user account so that the user does not receive the and activation prompts.
