### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by cclifton7** [MicrosoftDocs/OfficeDocs-DeployOffice#952]
Last sentence is missing a period.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3c138ab-9f4e-6e4a-8d2d-d9734b2d5a9f
* Version Independent ID: efc2ae80-4618-250e-b46c-a214c1ddbc3e
* Content: [Microsoft 365 Apps health - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/admincenter/microsoft-365-apps-health)
* Content Source: [DeployOffice/admincenter/microsoft-365-apps-health.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/admincenter/microsoft-365-apps-health.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @javiercarrillo
* Microsoft Alias: **jacarril**

**Comment by DHB-MSFT** [comment]
@cclifton7  Thanks for letting us know. We've made the change and submitted it for publishing. Should appear later today.
