### ISSUE TITLE
Full list of new features compared to Office 2019

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/OfficeDocs-DeployOffice#954]
You have added a trivially short list of new features.  MS never documents all of the new features in one place.

It would be really nice if you included a full list, by application of ALL of the new features in 2021, or a link to a general page with ALL of that information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8f67f86-10d5-8dd2-3d29-c2112522b11b
* Version Independent ID: 14036bbd-22f5-6528-97c9-00c5d0f2fe9f
* Content: [Overview of Office LTSC Preview - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/office2021/overview-ltsc-preview)
* Content Source: [DeployOffice/office2021/overview-ltsc-preview.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2021/overview-ltsc-preview.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@Ronsss Thanks for your feedback. We've passed your feedback on to the teams that are compiling the final list of features and will be publishing this type of information closer to when the products are released later this year. 

Their current plan is to do something similar to what was done for the Office 2019 release. For example, this article: [What's New in Office 2019](https://support.microsoft.com/office/5077cbbe-0d94-44cc-b30e-654e37629b0c). If you scroll down, there are links to articles for the individual apps, such as [What's new in Excel 2019 for Windows](https://support.microsoft.com/office/5a201203-1155-4055-82a5-82bf0994631f).

**Comment by Ronsss** [comment]
NO! the issue is NOT closed for me. Your "answer" does not fix the issue I
raised.
.
The 2019 link you provided is typical MS Mickey Mouse **it.
It is INCOMPLETE!
It is ANNOYING!

Just one example from it:
<snip>

*New functions*

TEXTJOIN, CONCAT, IFS, and more. Let Excel do the work so you don't have to.
</snip>

The "and more" is the problem!  MS is promoting this page as "What's new in
Office 2019", but then they DON'T TELL US everything that is new.   Where
do we go to find the details of the "and more"?  Other subsections on the
page you provided at list have links to "more information". But even those
linked pages are incomplete.
.
If MS doesn't know exactly what is new in their own products, how are we
supposed to find out!?!
.
That link you provided is exactly why I made the suggestion! Your PAYING
CUSTOMERS. Your USERS need ONE place to find EVERYTHING that is new in an
application. A SINGLE LIST that is constantly updated when monthly new 365
features are released to the general public.  We should not have to filter
through 3 dozen monthly "what's new" updates to compile a list we can pass
on to people asking us this question.
.
Does my frustration come through?

**Comment by DHB-MSFT** [comment]
@Ronsss .... We'll provide your feedback to the teams that are responsible for publishing documentation about new features.

Are you using the subscription version of Office, such as Microsoft 365 Apps?  It sounds that way from your feedback on the documentation for new monthly features. If so, then the Office LTSC Preview probably isn't relevant to you. This preview is for customers who aren't using the subscription version of Office.

Office LTSC Preview has just started the preview stage and there are still some decisions being made on which features will be available when it is released later this year. That is why there isn't currently a more complete list of "new features" available. When that information is available and published, we'll link to it. After Office LTSC is released, it won't receive any new features. So the "What's New" documentation for Office LTSC won't change after that.

**Comment by Ronsss** [comment]
The comment was intended for all 3 "versions" of Office:

   - 365
   - LTSC
   - 2021

Yes, the previous comment was largely based on 365, but the overall idea
still remains. It is impossible to find a single location where all new
2019, or 2016 etc. features are listed. They list a few highlights and
leave the rest for the user to play "hide and seek" web searches.  What we
need is a single home page that says Office 2021 applications (or LTSC)
(and a single page for 365 would be really nice too so it would require
monthly updates) have the following new features that are not part of
Office 2019. The list has to be complete and for each new feature have one
or more links to detail pages describing how to use the feature.

It would be even better if this new LTSC/2021 list of new features extended
to multiple earlier versions of Office ie: 2010, 2013, 2016.  Lots of
people are coming from versions older than 2019 so it would be really great
for them to be able to look at a single site/page to find out what ALL of
the new features they are getting compared to their current version.  This
site would also work for people using older versions. It would be a single
place to go to look for a "Comprehensive What's New" list in multiple
versions of Office. Thinking about it, it could also include 365 at the
"top" of the list

This unified source of information is needed since MS no longer provides
printed documentation.

Thanks for passing on my comments.
