### ISSUE TITLE
A Question re WebView2 Runtime Rollout

### ISSUE THREAD

**Issue by neu-milenko** [MicrosoftDocs/OfficeDocs-DeployOffice#955]
Will WebView2 Runtime rollout be an ongoing campaign, e.g. if WebView2 is to be installed for the users having Microsoft 365 apps already installed, when it will be installed for the users installing Microsoft 365 apps at a future time?
Is there a more specific time estimate when will WebView2 Runtime rollout will begin, after April 1, 2021?
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8ac95be-d5b8-b295-3003-fa5ce70dfb55
* Version Independent ID: d2acedb5-834c-8fa6-d917-7316e9bcda3d
* Content: [Microsoft Edge WebView2 and Microsoft 365 Apps - Deploy Office](https://docs.microsoft.com/en-us/DeployOffice/webview2-install)
* Content Source: [DeployOffice/webview2-install.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/webview2-install.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@neu-milenko  Thanks for your questions. For WebView2 Runtime, there aren't separate rollout "campaigns" based on whether it's an existing install or a new install. For example, if you perform a new install of Version 2103 from Current Channel next week, you'll likely get WebView2 Runtime installed within a few days. After Office is installed, there's a process that checks to see if WebView2 Runtime is installed on the device, and if not, will install it.

The rollout (for both existing and new installs) has been happening throughout April. We've been rolling out in phases, so if you haven't seen WebView2 Runtime installed yet on devices in your organization (and you're running at least Version 2101 of Microsoft 365 Apps), you'll probably see WebView2 Runtime installed fairly soon.

We hope this information answers your questions.
