### ISSUE TITLE
Insights add-in is analyze-your-content category

### ISSUE THREAD

**Issue by mike-g-msft** [MicrosoftDocs/OfficeDocs-DeployOffice#962]
Can we add "MyAnalytics Insights add-in for Outlook" to "Connected experiences that analyze your content"? It already has correct error handling in it to inform the user "Your organization's admin has turned off the service required to use this experience." when the UserContentDisabled value/policy = 2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9f215c4-d995-2d6c-0693-bca19f66fe2f
* Version Independent ID: a9aa816b-f30d-3bbe-8fdc-204777b25dfe
* Content: [Connected experiences in Office - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/privacy/connected-experiences?source=docs#feedback)
* Content Source: [DeployOffice/privacy/connected-experiences.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/connected-experiences.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@mike-g-msft   Ping me offline (I'm in the address book) and we can discuss. Thanks.
