### ISSUE TITLE
Command to remove the background service for Microsoft Search in Bing

### ISSUE THREAD

**Issue by racret** [MicrosoftDocs/OfficeDocs-DeployOffice#964]
Hello,

It seems like there is an issue in the documentation with the command to remove the background service for Microsoft Search in Bing.

The article lists it as "**%ProgramFiles(x86)%**\Microsoft\DefaultPackMSI\MainBootStrap.exe" uninstallAll"  but this should be
"**%ProgramData%**\Microsoft\DefaultPackMSI\MainBootStrap.exe" uninstallAll as the MainBootStrap.exe only exists in the second location.

Thanks,
Radu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Microsoft 365 Apps for enterprise - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@racret  We're checking with the product team and will update the content based on what they tell us.

**Comment by DHB-MSFT** [comment]
@racret We've received confirmation from the product team that the correct location is under %programdata% as noted in your comment. We've updated the article to reflect that. Thanks for bringing this to our attention.

**Comment by racret** [comment]
@DHB-MSFT thanks for looking into this and for the quick fix. looks good now :)
