### ISSUE TITLE
Configuration.xml

### ISSUE THREAD

**Issue by stinkydiver** [MicrosoftDocs/OfficeDocs-DeployOffice#98]
The configuration xml file that is included with the Office Deployment Tool already includes the line:

&lt;Display Level="None" AcceptEULA="True" /&gt;

So there is no need to modify it to prevent Office from auto activating during the installation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a003f6a-2edb-3303-01c1-41a63ce82260
* Version Independent ID: 203d6b80-acd5-566a-3f6c-be1852ae8909
* Content: [Deploy Office 365 ProPlus as part of an operating system image](https://docs.microsoft.com/en-us/deployoffice/deploy-office-365-proplus-as-part-of-an-operating-system-image)
* Content Source: [DeployOffice/deploy-office-365-proplus-as-part-of-an-operating-system-image.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-office-365-proplus-as-part-of-an-operating-system-image.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
The line in the sample configuration.xml file that comes with the ODT download is commented out by default. Also, not everyone uses the sample xml file. They might have re-used an xml file from a different installation. So best to remind them to include that line.  Thanks.
