### ISSUE TITLE
Outlook 2016 Support

### ISSUE THREAD

**Issue by aakash-shah** [MicrosoftDocs/OfficeDocs-DeployOffice#980]
Hello! I see that this page indicates that Outlook 2016 is supported until October 2023. However, this page also links to the Office configuration support matrix at https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2OqRI, which indicates that:

"As of October 13, 2020, connectivity support to Office 365 services (e.g. Exchange 
Online, SharePoint Online, OneDrive) now requires Microsoft 365 Apps, Office 365, 
or non-subscription versions of Office in mainstream support."

And per https://docs.microsoft.com/en-us/lifecycle/products/microsoft-office-2016, my understanding is that Outlook 2016 passed mainstream support in October 2020.

These links also appear to indicate that Outlook 2016 is no longer officially supported for connecting to Exchange Online:

From https://www.microsoft.com/en-us/microsoft-365/blog/2017/04/20/office-365-proplus-updates:
"Office 365 ProPlus or Office perpetual in mainstream support required to connect to Office 365 services. Starting October 13, 2020, it will be necessary to have Office 365 ProPlus or Office perpetual in mainstream support to connect to Office 365 services. Office 365 ProPlus will deliver the best experience, but for customers who aren’t ready to move to the cloud by 2020, we will also support connections from Office perpetual in mainstream support at that time (Office 2016 and Office 2019)."

From https://techcommunity.microsoft.com/t5/office-365-blog/office-365-system-requirements-changes-for-office-client/ba-p/62327: 
"Effective October 13th, 2020, Office 365 will only support client connectivity from subscription clients (Office 365 ProPlus) or Office perpetual clients within mainstream support (Office 2016 and Office 2019). (Please refer to the Microsoft support lifecycle site for Office mainstream support dates.)"

Can you please clarify the discrepancy and whether Outlook 2016 is still officially supported to connect to Exchange Online/O365?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e86f8d4f-3eb1-6763-0f10-a0b637f3035c
* Version Independent ID: a6642647-dc4d-30a9-e962-76f7cd1f5089
* Content: [Office versions and connectivity to Office 365 services - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/endofsupport/office-365-services-connectivity)
* Content Source: [DeployOffice/endofsupport/office-365-services-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/endofsupport/office-365-services-connectivity.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@aakash-shah   Connecting to Office 365/Microsoft 365 services using Office 2016 (including Outlook) is supported until October 2023, even though mainstream support has ended for Office 2016. The information in the [Office versions and connectivity to Office 365 services](https://docs.microsoft.com/deployoffice/endofsupport/office-365-services-connectivity) and in the [Office configuration support matrix](https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2OqRI) is up-to-date and accurate.

The 2 blog posts you reference have older information. Both older blog posts have links at the top that point customers to this newer blog post:

https://www.microsoft.com/en-us/microsoft-365/blog/2018/09/06/helping-customers-shift-to-a-modern-desktop/

In the newer blog post (near the end), there is a section specifically about Office 2016:

_To give you more time to transition fully to the cloud, we are now modifying that policy and will continue to support Office 2016 connections with the Office 365 services through October 2023._

Also, there is a footnote at the bottom of the [Office configuration support matrix](https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2OqRI) that says the following (and has a link to the newer blog post we mention above):

_Although mainstream support for Office 2016 ended on October 13, 2020, Office 365 services will continue to be supported with Office 2016 until October 2023._

We hope that clarifies the supportability info for you. We're planning some updates to the [Office configuration support matrix](https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2OqRI) in the near future and we'll try to make this clearer when we make those other updates.

**Comment by aakash-shah** [comment]
@DHB-MSFT Thanks for your prompt response and for the clarifying information!
