### ISSUE TITLE
Failure in "Example of MSICondition attribute"

### ISSUE THREAD

**Issue by AlyaKoni** [MicrosoftDocs/OfficeDocs-DeployOffice#983]
In the example in the section "Example of MSICondition attribute" is a failure. The sesond Language element is not closed which makes the xml corrupt. Please close the second Language element correctly.

Actual:
`         <Language ID="MatchPreviousMSI">
`
Correct:
`         <Language ID="MatchPreviousMSI" />
`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a0b1ff-0498-505a-6024-b813980d310f
* Version Independent ID: b8057930-b4bd-1304-17ce-5561f837e901
* Content: [Configuration options for the Office Deployment Tool - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/office-deployment-tool-configuration-options)
* Content Source: [DeployOffice/office-deployment-tool-configuration-options.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office-deployment-tool-configuration-options.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@AlyaKoni  Thank you for bringing this error to our attention. We have fixed the error.
