### ISSUE TITLE
I need to say thanks admx  adml  templates developers team

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#984]
On  23rd July 2021, i downloaded office 2019 admx and adml templates version 5191.1000.
This build solves the arrangement of adml language files.

In old previous versions, users need to find the correct adml file for their installed language in windows.
In the new build version has no issues.

So please convey my **Best Wishes** to **Administrative templates developers team**

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f5cfe20-90ad-3f7e-8ae8-ff99bd1e1b55
* Version Independent ID: 97b2760a-50a2-f7c0-32ab-20b0420838d1
* Content: [Update Office 2019 (for IT Pros) - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/office2019/update)
* Content Source: [DeployOffice/office2019/update.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/update.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@RAJU2529  Thanks for your feedback.
