### ISSUE TITLE
Office Deployment Tool is not updated with August Updates

### ISSUE THREAD

**Issue by sysadmin84** [MicrosoftDocs/OfficeDocs-DeployOffice#991]
There has not been a new release for August 2021 of the Microsoft Office Deployment Tool. It states the download is from July 12th at this link https://www.microsoft.com/en-us/download/details.aspx?id=49117

 When can the release for the download of the August 2021 version be expected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66127c02-c2dc-f6d1-6e83-a6d2b1166731
* Version Independent ID: 27635315-22db-d136-f07e-5169f6207b50
* Content: [Overview of the Office Deployment Tool - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/overview-office-deployment-tool)
* Content Source: [DeployOffice/overview-office-deployment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-office-deployment-tool.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
The release of the ODT does not follow a fixed schedule, e.g. a monthly cycle. We publish a new version when we added features to ODT or fixed some issues. So, there might not be an August release for the ODT, at least we have none scheduled at the moment. But this can change quickly when we e.g. fix an urgent issue.

I hope this answers your question.

**Comment by sysadmin84** [comment]
If we use the July 12th ODT, will it pull down the August updates?

**Comment by DHB-MSFT** [comment]
@sysadmin84   Yes, you can use the July ODT to pull down the August updates.

**Comment by msft-bcorob** [comment]
The earlier commenters are both correct.  We did not publish a new ODT earlier this week as there were no pending changes.  The existing release of ODT (version 16.0.14131.20278 / setup.exe version 16.0.14131.20278, released July 12, 2021) can continue to be used for all deployment scenarios.
