### ISSUE TITLE
Update Office 365 Client Configuration Service to Microsoft 365 Apps admin center

### ISSUE THREAD

**Issue by DavidTaig** [MicrosoftDocs/OfficeDocs-DeployOffice#994]
On all pages in MicrosoftDocs, please update _Office 365 Client Configuration Service_ to [Microsoft 365 Apps admin center](https://config.office.com/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67f2376c-177b-110f-9c88-f83d53bd6bc7
* Version Independent ID: a98d74e5-f7dc-c073-4cb9-a8901895a89a
* Content: [Overview of the Office Customization Tool - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/overview-of-the-office-customization-tool-for-click-to-run)
* Content Source: [DeployOffice/overview-of-the-office-customization-tool-for-click-to-run.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-the-office-customization-tool-for-click-to-run.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@DavidTaig  Thanks for pointing that out. We've fixed the 2 references in this article. And we didn't find any other references to "Office 365 Client Configuration Service"
