### ISSUE TITLE
Clarification on "...purchased through a Volume Licensing Program."

### ISSUE THREAD

**Issue by Viajaz** [MicrosoftDocs/OfficeDocs-DeployOffice#997]
In the [What you need to get started](https://docs.microsoft.com/en-us/deployoffice/deploy-microsoft-365-apps-remote-desktop-services#what-you-need-to-get-started), it has the statement:
```
An Office 365 (or Microsoft 365) plan that includes Microsoft 365 Apps for
enterprise, purchased through a Volume Licensing Program.
```
Is this actually correct? Does the rights for Microsoft 365 Apps for enterprise change depending on where the license originates from? This is not mentioned in [Licensing Microsoft 365 Apps in Commercial Licensing](https://download.microsoft.com/download/3/D/4/3D42BDC2-6725-4B29-B75A-A5B04179958B/Licensing_brief_PLT_M365_Apps_in_Commercial_Licensing.pdf), section "Microsoft 365 Apps activation options"

From that same document, "Appendix: Microsoft Office software vs. Microsoft 365 Apps" under "Microsoft 365 Apps as a subscription service" and "Remote Use"
```
Remote Use Rights permitted including via Virtual Desktop Infrastructure (VDI) or
Remote Desktop Services with shared computer activation enabled for Licensed
Users, or remote use from the Licensed Device for per device licenses
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6da18a8b-9e96-0155-7b30-9c211070d793
* Version Independent ID: 5a7e610a-bfcb-d9cc-03f7-589d970128d9
* Content: [Deploy Microsoft 365 Apps by using Remote Desktop Services - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/deploy-microsoft-365-apps-remote-desktop-services)
* Content Source: [DeployOffice/deploy-microsoft-365-apps-remote-desktop-services.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-microsoft-365-apps-remote-desktop-services.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by alrebh** [comment]
https://github.com/alrebh/Alidhneem2-gmail.com.git

**Comment by rojedai** [comment]
Could you please confirm if it is necessary to purchase Microsoft 365 Apps for Enterprise through Volume Licensing Program to use it on a RDS server? I believe this requirement is only for other Office versiones (2016/2019/...) and not for Microsoft 365/Office 365 because they include Shared Computer Activation. This is creating a lot of confusion and needs to be clarified ASAP. Thank you so much.

**Comment by DHB-MSFT** [comment]
We've checked and you're correct. Purchase through a volume license program isn't required. We've removed that from the article. Thanks for pointing that out to us.
